### PR TITLE
feat: add shared checks for casks and formulae

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----
This should make sure that the issues in the linux-fonts tap are fixed in the casks as well. It just doesn't work yet.

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
Makes sense to me (once 🟢)! Thanks @SMillerDev.

**Comment by SMillerDev** [comment]
For some reason after this the checks don't actually run anymore:
```console
/o/homebrew (feat/cops/shared_homepage_cop|✔) $ brew style --fix homebrew/core --debug --verbose
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/bin/bundle clean
```

No idea how to debug that problem though.

**Comment by MikeMcQuaid** [comment]
> For some reason after this the checks don't actually run anymore:

I don't know why, sorry. Perhaps @issyl0 can help?



> No idea how to debug that problem though.

Stick `puts` and `raise` all over the place and/or run rubocop in debug mode.

**Comment by samford** [comment]
> For some reason after this the checks don't actually run anymore

This looks to be fixed by https://github.com/Homebrew/brew/pull/17482. I checked out this branch locally, rebased it, and your `brew style` command above works as expected.

**Comment by SMillerDev** [comment]
Should be fine once those PRs are merged and we re-run the check. Thanks for the help @samford !

**Pull request merged**
