### PR TITLE
dev-cmd/vendor-gems: run bundle clean

### PR DESCRIPTION
**Pull request by Bo98**
Fixes install inconsistencies between standalone and all other bundle operations.

Should work as is but will test properly in a bit

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> Fixes install inconsistencies between standalone and all other bundle operations.

This resolves inconsistencies but in the wrong direction for `base64` if we care about handling that.

Removing https://github.com/Homebrew/brew/blob/49609ecf68b59a1585edf8a0da02695d8fc7fcb6/Library/Homebrew/.bundle/config#L3 (or making it `false`) and making `bundle clean` always require an explicit call feels like it might be nicer?

**Comment by Bo98** [comment]
I wouldn't necessarily say wrong. Standalone mode is the mode that's much less used than regular mode. So using the base64 that ships with Ruby is fine.

What breaks things is when if flip flops between the two, but this should fix that as it undos the unique standalone mode behaviour.

**Review by MikeMcQuaid — APPROVED** [review]
I don't understand why this works when I tried this approach before and it didn't seem to work before but: it's working and that's great, nice work @Bo98!

**Comment by Bo98** [comment]
> I don't understand why this works when I tried this approach before and it didn't seem to work before but: it's working and that's great, nice work @Bo98!

If you were trying locally, it's possible the Bootstrap cache is already corrupt. But in CI that's fine because we don't carry that cache over and for other end users it's also OK as we never shipped the bad state.

**Comment by MikeMcQuaid** [comment]
> If you were trying locally, it's possible the Bootsnap cache already got corrupt and would have required manually deleting. But in CI that's fine because we don't carry that cache over and for other end users it's also OK as we never shipped the bad state.

Yeh, Bootsnap was definitely messing some stuff up here. Thanks for explaining @Bo98!

**Pull request merged**
