### PR TITLE
bintray: don't output raw JSON

### PR DESCRIPTION
**Pull request by dawidd6**
Current situation:
https://github.com/Homebrew/homebrew-core/runs/1018446727?check_suite_focus=true#step:5:46

Situation after this PR:
https://github.com/dawidd6/homebrew-tap/runs/1018549880#step:5:44

With this PR, we no longer see the JSON received from Bintray.
It's redundant to see it, it lacks final newline and messes the whole output a bit.
We already parse and check this JSON, no need to output it too.

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by reitermarkus** [comment]
We have `curl_output` which does exactly that.

**Comment by dawidd6** [comment]
`def curl_output` calls `curl` command via `system_command` without exclamation mark, while `def curl` does. This is essential, we need it to throw an exception if something goes wrong.

**Comment by reitermarkus** [comment]
Ah, okay. However, I'm not quite sure it makes sense that `show_output` depends on `verbose?`, since this also controls passing the `--fail` flag, so we might get different behaviour depending on the verbosity.

**Comment by MikeMcQuaid** [comment]
> Ah, okay. However, I'm not quite sure it makes sense that `show_output` depends on `verbose?`, since this also controls passing the `--fail` flag, so we might get different behaviour depending on the verbosity.

Agreed 👍🏻

**Comment by dawidd6** [comment]
Rebased on latest master. Any ideas on how to resolve this `verbose?` concern?

**Comment by MikeMcQuaid** [comment]
@dawidd6 I'm not sure, @reitermarkus?

**Comment by reitermarkus** [comment]
I'd say just remove `show_output:  verbose?` altogether.

**Comment by dawidd6** [comment]
@jonchang what do you think?

**Comment by jonchang** [comment]
> Ah, okay. However, I'm not quite sure it makes sense that `show_output` depends on `verbose?`, since this also controls passing the `--fail` flag, so we might get different behaviour depending on the verbosity.

At some point we're going to have to clean up how we use `curl` in Homebrew since the `--fail` stuff has bit us before. 

> I'd say just remove `show_output: verbose?` altogether.

I think this is an acceptable solution for now.

**Pull request merged**
