### PR TITLE
allow uses_from_macos "ruby@2.7"

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----
Since this is `keg_only :versioned_formula` it normally isn't allowed. But 2.7 is definitely more accurate then 3.0 (which is allowed).

CC @Bo98

### CODE REVIEW

**Review by Bo98 — APPROVED** [review]
Out of interest, which formula do you plan using this in?

**Comment by SMillerDev** [comment]
[test-kitchen](https://github.com/SMillerDev/homebrew-tap/blob/main/Formula/test-kitchen.rb) in my personal tap.

**Comment by Bo98** [comment]
At some point, it might be reasonable to make a general case that all versioned formulae of `provided_by_macos` formulae are allowed here.

**Comment by SMillerDev** [comment]
I'm not sure. In the end I'd say that you want Linux to have the same versions as macOS so ruby would have to be disallow in favor of @2.7

**Comment by iMichka** [comment]
I think we already had this discussion somewhere else. There are a lot of other formulae in the uses_from_macos list that have a different version than the macOS one. You would have to update the whole list. And the our Linux users would still like to use the latest version, not the old version pinned on macOS.

I would recommend using:

```
on_linux do
  depends_on "ruby@2.7"
end
```

This is what we did in linuxbrew-core.

**Comment by Bo98** [comment]
> I'd say that you want Linux to have the same versions as macOS so ruby would have to be disallow in favor of @2.7

In that case, this would be `ruby@2.6` and not `ruby@2.7`.

It's a bit tricky - there's a few things here that aren't actually supplied by macOS, such as `openssl@1.1`, but are nevertheless on this list. We've never really shown the desire for matching versions in the past.

**Review by MikeMcQuaid — CHANGES_REQUESTED** [review]
I'm 👎🏻 on this PR, sorry. As mentioned by @Bo98: 2.7 does not ship with macOS. I'd see an argument for `ruby@2.6` but even that feels a bit weird; why would Linux specifically want the older version?

**Comment by Bo98** [comment]
> why would Linux specifically want the older version

Typically because of compatibility concerns with newer versions. I imagine `openssl@1.1` will remain on this list even when 3.0 is out, despite neither version actually being included with macOS.

**Comment by iMichka** [comment]
I also think that the method name (`uses_from_macos`) is confusing here, but it's hard to find anything better. Unless you rename it to `depends_on_linux ""` and/or provide versioned formulae pinned at the specific macOS version (which might vary between the 3 last supported OSes).

**Pull request closed without merging**
