### PR TITLE
docs: fix broken link

### PR DESCRIPTION
**Pull request by vidusheeamoli**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

`brew-test-bot.rb` was renamed to `test-bot.rb`. This PR fixes the broken link.

### CODE REVIEW

**Comment by issyl0** [comment]
Thanks! You need to run `brew man` and commit the changes for the build to go green.

**Comment by issyl0** [comment]
Oh, sorry! This isn't your fault. This is because there were changes to the [`bundle` subcommand](https://github.com/Homebrew/homebrew-bundle). I pushed a fix, so if you rebase this branch on the latest master it'll go green.

**Comment by vidusheeamoli** [comment]
@issyl0 On it! Will report once all tests pass. 😄

**Comment by issyl0** [comment]
I think you forgot to `brew update`? 😄You shouldn't need either of the `docs/Manpage.md` or `manpages/brew.1` changes here now.

**Comment by vidusheeamoli** [comment]
Sorry! Correcting it. Thank you for the heads up 😄

**Comment by vidusheeamoli** [comment]
@issyl0 Tests pass now :)

**Comment by issyl0** [comment]
We got there! 😅 Thanks again Vidushee!

**Comment by MikeMcQuaid** [comment]
Thanks again @vidusheeamoli!

**Pull request merged**
