### PR TITLE
cmd/pull: add retry to curl bottle download

### PR DESCRIPTION
**Pull request by apjanke**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [X] Have you successfully run `brew tests` with your changes locally?

-----

Adds retry logic to the "download bottle file with curl" step in the bottle verification method. 

Works around issue with GET and HEAD apparently acting differently, and bottle downloads failing even after successful polling completion. This is something @UniqMartin has been seeing.

I went with this implementation because it sticks with doing the main polling (which is expected to happen several times in the normal caes) using the lightweight HEAD and reused server connection, which is polite to Bintray's server, and produces concise "Waiting on Bintray....." progress output.

Uses exponential backoff instead of constant backoff for this step because it's using `curl` so it gets a new connection every time.

I also tried switching the polling to use a GET with byte ranges instead of HEAD, but it appears that Bintray's web server does not support them.

### CODE REVIEW

**Comment by UniqMartin** [comment]
Re 745a1312dce936ddd519c2e151e889459243c543: I'm pretty sure this line can be just dropped (and should be to avoid future confusion). It is probably unlikely to ever matter, but I'd use the same opportunity to bump `max_curl_retries` to 2 or 3.

I guess the morale of the story could be to run `brew readall --syntax` (and `tests`!) locally if the bot is particularly busy and you're inclined to pull before the `test-bot` run finishes successfully.

**Comment by apjanke** [comment]
Yeah, it was a dumb bug on my part after I moved the `retry_count += 1` down into the `rescue` block. Removed in 2044294a865a85c4c3144a3000bd9a48427e12c6. Sorry about that.

I had run `brew tests` locally, but I never do `brew readall --syntax`. Maybe `brew tests` should incorporate `brew readall --syntax` as a test, for convenience, and so our PR template steps include it?

**Comment by UniqMartin** [comment]
> I had run `brew tests` locally, but I never do `brew readall --syntax`. Maybe `brew tests` should incorporate `brew readall --syntax` as a test, for convenience, and so our PR template steps include it?

If you want to poke this code a bit, I think nowadays (after the split) `readall` is making even less sense than it did a while ago, because it performs two completely orthogonal tasks:

- Check the Ruby syntax of Homebrew (the package manager) files.
- Validate aliases and try to load all formula files, either from a specified tap or all installed taps.

The former only makes sense for the Homebrew/brew repository and the latter only makes sense in the various Homebrew/homebrew-* repositories, thus some rearrangement would make sense. I don't think `tests` is the right place for it, but maybe it would be convenient to have a developer command that can be run locally without too much thought and does something similar to `test-bot` for Homebrew/brew.

That said, if you really wanted to dive into the code, I think `test-bot` could benefit from some refactoring around `readall` and `tests`. Not all of it makes sense in both the Homebrew/brew repository and the Homebrew/homebrew-* repositories now that we have separated them.

**Comment by mikemcquaid** [comment]
> The former only makes sense for the Homebrew/brew repository and the latter only makes sense in the various Homebrew/homebrew-* repositories, thus some rearrangement would make sense.

👍

**Comment by DomT4** [comment]
Was some discussion on this line from https://github.com/Homebrew/homebrew-core/pull/999#issuecomment-218608832 and below, if anyone wonders historically why my hack seemingly came out of the blue 😄.

Agree with @UniqMartin's comment above here.

**Pull request merged**
