### PR TITLE
Add test.xls for testing libxls

### PR DESCRIPTION
**Pull request by wkoszek**
I want to improve existing `sc-im` brew. It supports exporting spreadsheets to Excel, but not reading them. I'd like to add reading support. To do this, we will need `libxls` which I'd be pushing:

https://github.com/Homebrew/homebrew-core/compare/master...wkoszek:adding_libxls?expand=1

Problem: I don't know how to reference libxls's own test case. The package has `test/files/test2.xls` file upon unzipping. I'm not sure how to reference it from there. Instead, I'm adding a test Excel file here. I think more packages would benefit from having Excel file for testing (frankly we already have GPL-licensed `xlslib` that oddly isn't required by any other package).

Once this is committed, I'd like my `libxls` to have `test` block that uses this `test.xls` to make the test pass.

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by wkoszek** [comment]
Hm. I got a failure from CI, but it seems like it's coming from other parts of the code.

**Comment by EricFromCanada** [comment]
> Problem: I don't know how to reference libxls's own test case. The package has `test/files/test2.xls` file upon unzipping. I'm not sure how to reference it from there. 

Some formulae put example files in `pkgshare`, e.g. [`alembic`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/alembic.rb).

**Comment by wkoszek** [comment]
Exactly. I didn't find a way to do it either. That's why I'm suggesting we put this file in. It's a file from libxls package, in fact.

**Comment by wkoszek** [comment]
Closing as we've found an alternate solution

**Pull request closed without merging**
