### PR TITLE
list.sh: fix arg parsing always failing

### PR DESCRIPTION
**Pull request by Bo98**
Turns out this script has never worked.

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
Thanks! Completion is now indeed much faster. Could this work for `brew ls` too? That's [an internal alias](https://github.com/Homebrew/brew/blob/33f53ddb36a77a49de63b78568ed72dfd2727ed7/Library/Homebrew/brew.sh#L816) but it's still routed to `cmd/list.rb`.

**Review by carlocab — COMMENTED** [review]
Why not just do `shift` in the `case` block above?

**Comment by Bo98** [comment]
> Could this work for `brew ls` too?

Yeah, will do this later today (separate PR probably).

> Why not just do `shift` in the `case` block above?

This logic is borrowed from other files like command_path.sh.

I guess the initial idea was to avoid tampering the args as we conditionally fallback to *.rb but that probably doesn't happen since this is in a function.

**Review by carlocab — APPROVED** [review]

**Review by ZhongRuoyu — APPROVED** [review]

**Review by MikeMcQuaid — APPROVED** [review]
Thanks @Bo98!

**Comment by MikeMcQuaid** [comment]
> Turns out this script has never worked.

@Bo98 Could you elaborate a bit more here (and on future PRs): what specifically has never worked and why? This pull request message does not reveal this information 😁

**Comment by Bo98** [comment]
> what specifically has never worked and why?

The whole thing. Because `$1 == list` it will always hit the `return 1` case of the argument parsing loop.

**Pull request merged**
