### PR TITLE
brew list 'filtered_list': pass explicit sort to handle APFS

### PR DESCRIPTION
**Pull request by commitay**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----
https://github.com/Homebrew/brew/issues/3311

Follow up to https://github.com/Homebrew/brew/pull/3316 

Not sure if the sort needs to be applied to `--pinned`?

### CODE REVIEW

**Comment by DomT4** [comment]
Damn, thought we'd caught the last of this fun.

> Not sure if the sort needs to be applied to --pinned?

Yeah, it does 😓. Pinned a few things locally to check and:
```
qt
libressl
openssl
gnutls
```

**Comment by commitay** [comment]
Thanks @DomT4!

**Comment by MikeMcQuaid** [comment]
Thanks again for your contribution to Homebrew, @commitay! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by DomT4** [comment]
> Thanks @DomT4!

Thank you for catching this! ❤️

**Pull request merged**
