### PR TITLE
cask: add `cpu` stanza to cask DSL

### PR DESCRIPTION
**Pull request by SeekingMeaning**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?
- [x] Have you successfully run `brew man` locally and committed any changes?

-----

This PR adds a new DSL for casks to specify supported CPUs (Intel, ARM, PowerPC), which is useful for `brew bump-cask-pr` in determining new SHA-256 checksums for not just the user's CPU but _all CPUs_

Question: Which term is more accurate (or preferable) for this? "CPU" or "architecture"?

Todo:
- Add audit for valid CPU symbols (`:intel`, `:arm`, `:ppc`)
- Add list of CPUs supported by cask to `brew info` text

(Let me know if I should include any or all of these todos in this PR)

[`macintoshjs`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/macintoshjs.rb) cask converted to use new DSL:

```rb
cask "macintoshjs" do
  version "1.1.0"

  cpu :intel do
    sha256 "4ca41517f15c594e718da622074a2160754cb8f1293cb1fad908f6d0ae585384"
    "x64"
  end

  cpu :arm do
    sha256 "0af95bbcc075f939d6c3e1fdcdab0d8da2760e5546aecfbc82767e326640740c"
    "arm64"
  end

  url "https://github.com/felixrieseberg/macintosh.js/releases/download/v#{version}/macintosh.js-darwin-#{cpu}-#{version}.zip"
  # ...
end
```

[`dosbox-x`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/dosbox-x.rb) converted to use new DSL:

```rb
cask "dosbox-x" do
  cpu :intel do
    version "0.83.9,20201231203002"
    sha256 "af55d06fb9277c62708b1b8f22bba3d3555744eab759700d0e5e4cd0d439abe5"
    "x86_64"
  end

  cpu :arm do
    version "0.83.9,20201231202930"
    sha256 "cd56080debf70543b030bbe8131fd009caf37c970624be35da76c0ad4d7fca99"
    "arm64"
  end

  url "https://github.com/joncampbell123/dosbox-x/releases/download/dosbox-x-v#{version.before_comma}/dosbox-x-macosx-#{cpu}-#{version.after_comma}.zip",
      verified: "github.com/joncampbell123/dosbox-x/"
  # ...
end
```

Related:
- https://github.com/Homebrew/homebrew-cask-versions/pull/10205#issuecomment-761610485
- https://github.com/Homebrew/discussions/discussions/561

### CODE REVIEW

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/discussions/discussions/561#discussioncomment-288085

**Comment by SeekingMeaning** [comment]
Updated to support setting `version` inside `cpu` block, for example:

```rb
cask "visual-studio-code-insiders" do
  cpu :intel do
    version "1.53.0,6dc779565e1e4a26104002fde340b68c157c3bc5"
    sha256 "ea08cd72f7501223d1c888b300bd961df27e80558e4e51c868740f651f3912ce"
    ""
  end

  cpu :arm do
    version "1.53.0,e17aea136d32fdb06d9b32184b04ccd36bb51e9c"
    sha256 "3f9bdb6867636cc9116d96a09aef53a927e1636609df33bfe23a1275107a04b6"
    "-arm64"
  end

  url "https://az764295.vo.msecnd.net/insider/#{version.after_comma}/VSCode-darwin#{cpu}.zip",
      verified: "az764295.vo.msecnd.net/insider/"
  appcast "https://update.code.visualstudio.com/api/update/darwin#{cpu}/insider/VERSION"
  # ...
end
```

**Comment by vitorgalvao** [comment]
I still don’t see how that would solve the problem of having to provide both versions in `brew bump-cask-pr`. What command would you run?

**Comment by SeekingMeaning** [comment]
It would require a bit of refactoring, but I think a semicolon-separated list for `--version` would work:

```bash
brew bump-cask-pr visual-studio-code-insiders --version='1.53.0,6dc779565e1e4a26104002fde340b68c157c3bc5;1.53.0,e17aea136d32fdb06d9b32184b04ccd36bb51e9c'
```

The version strings should be in the same order they appear in the cask

**Comment by vitorgalvao** [comment]
In truth, I can’t bring myself to see this as an improvement. Yes, it will allow for `brew bump-cask-pr`, but it will need to be a somewhat obtuse command. Plus, the readability of the cask suffers.

In sum, I think the extra effort of not being able to `brew bump-cask-pr` certain casks doesn’t justify adding the extra complexity to the casks themselves.

Can’t we find another way to help `brew bump-cask-pr` do it with the `if`s? Example: assuming `brew bump-cask-pr` updates whatever architecture the user is on, perhaps there’s an environment flag we can manipulate to make Homebrew behave like in the other architecture. For example, there used to be a flag that allows us to fake the macOS version Homebrew saw, which I did use to great effect in `cask-repair`, by making it always download what was appropriate for the latest macOS version, not the one the user was on.

**Comment by domoritz** [comment]
I don't think it's a good UX to require people to manually change the cpu environment. Someone will forget (as happened in the past) and casks will have the wrong hash.

**Comment by vitorgalvao** [comment]
> I don't think it's a good UX to require people to manually change the cpu environment.

That’s not the suggestion. The point of the flag is that the command could automatically set it and use *both*, making it impossible to forget. Like I mentioned, that’s the approach I used in `cask-repair` and it never failed (and that tool was used for the majority of cask PRs).

**Comment by domoritz** [comment]
> That’s not the suggestion. The point of the flag is that the command could automatically set it and use both, making it impossible to forget.

Ahh, perfect. Thanks for the clarification.

**Comment by SeekingMeaning** [comment]
Opened PR https://github.com/Homebrew/brew/pull/10683

**Pull request closed without merging**
