### PR TITLE
Allow custom default remote base for brew tap

### PR DESCRIPTION
**Pull request by elquimista**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Related to the PR https://github.com/Homebrew/install/pull/254 so that core tap can be tapped from custom remote repo.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> Related to the PR [Homebrew/install#254](https://github.com/Homebrew/install/pull/254) so that core tap can be tapped from custom remote repo.

This is already possible. See the (documented) variable `HOMEBREW_CORE_GIT_REMOTE`

**Comment by elquimista** [comment]
@MikeMcQuaid I already tried setting that variable `HOMEBREW_CORE_GIT_REMOTE` before opening the PR and it didn't work - sorry I forgot to mention it on my PR opener description.

So I managed to install homebrew binary itself following your suggestion. When I tried to run `brew info vim`, it attempted to tap the core repo as expected, but from the official Github repo. It obviously complained with errors since I turned off the internet.

```
$ brew info vim
==> Tapping homebrew/core
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': Could not resolve host: github.com
...
```
This is the line that says "Tapping", I started debugging from here:
https://github.com/Homebrew/brew/blob/4bdce4701fa4490a415c04fd8d0030cde24fbe44/Library/Homebrew/tap.rb#L275
And `git clone` line: https://github.com/Homebrew/brew/blob/4bdce4701fa4490a415c04fd8d0030cde24fbe44/Library/Homebrew/tap.rb#L276
`requested remote` setter:
https://github.com/Homebrew/brew/blob/4bdce4701fa4490a415c04fd8d0030cde24fbe44/Library/Homebrew/tap.rb#L238
Finally, it resolves to `default_remote` method, which is hard-coded:
https://github.com/Homebrew/brew/blob/4bdce4701fa4490a415c04fd8d0030cde24fbe44/Library/Homebrew/tap.rb#L117-L119

Can we reopen this PR and get it merged?

**Comment by MikeMcQuaid** [comment]
> I already tried setting that variable `HOMEBREW_CORE_GIT_REMOTE` before opening the PR and it didn't work - sorry I forgot to mention it on my PR opener description.

You'll need to elaborate a bit on "didn't work" with step-by-step reproduction instructions and your `brew config` output.



> It obviously complained with errors since I turned off the internet.

This is not a supported configuration.



> Finally, it resolves to `default_remote` method, which is hard-coded:

It should be. Individual taps can have their locations changed either by using `git` or by using the `brew tap user/repo URL` form.

**Comment by elquimista** [comment]
```sh
$ export HOMEBREW_CORE_GIT_REMOTE="http://gitlab.local:4000/Homebrew/homebrew-core"
$ brew info vim
==> Tapping homebrew/core
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': Could not resolve host: github.com
...
```
Do you mean this is not sufficient to show what I tried? According to the documentation and your suggestion, this should work i.e. brew should've tried to clone the core tap from my local url.
I will try another way this time using `brew tap Homebrew/core http://gitlab.local:4000/Homebrew/homebrew-core` and see if it works, but even though it worked, then HOMEBREW_CORE_GIT_REMOTE is misleading as it's not used the way as it's supposed to be. Better remove it from docs I guess.

**Comment by MikeMcQuaid** [comment]
There's some missing code to handle that case (the auto-tapping) it seems. Added in https://github.com/Homebrew/brew/pull/6929.

**Comment by elquimista** [comment]
FTR, `brew tap Homebrew/core http://gitlab.local:4000/Homebrew/homebrew-core` did work, however, I'd much prefer `HOMEBREW_CORE_GIT_REMOTE` variable working and looks like it's working on `master` branch. What's the release ETA for v2.2.3?

**Comment by MikeMcQuaid** [comment]
> What's the release ETA for v2.2.3?

There is no ETA. Some time this month, probably.

**Pull request closed without merging**
