### PR TITLE
fix_dynamic_linkage: Check HOMEBREW_RELOCATE_METAVARS

### PR DESCRIPTION
**Pull request by sjackman**
Only remove RPATH when HOMEBREW_RELOCATE_METAVARS is set.

See PR https://github.com/Homebrew/brew/pull/5413

### CODE REVIEW

**Comment by woodruffw** [comment]
I think the problematic line is this one:

https://github.com/Homebrew/brew/blob/f67fad1e6e4f10d1c02cf85d3069c283648564b9/Library/Homebrew/extend/os/mac/keg_relocate.rb#L123

Since we're no longer filtering `@rpath`-prefixed install names, they end up getting passed through `fixed_name` and falling through to the `bad_name` case. We should either revert that regexp back to `/^@(loader_|executable_|r)path/` or add an additional environment check there like:

```ruby
dylibs.reject! { |fn| fn =~ /^@rpath/ } unless ENV["HOMEBREW_RELOCATE_METAVARS"]
```

**Comment by MikeMcQuaid** [comment]
> We should either revert that regexp back to `/^@(loader_|executable_|r)path/` or add an additional environment check there like:
> 
> ```ruby
> dylibs.reject! { |fn| fn =~ /^@rpath/ } unless ENV["HOMEBREW_RELOCATE_METAVARS"]
> ```

👍

**Comment by sjackman** [comment]
I've added…
```ruby
dylibs.reject! { |fn| fn =~ /^@rpath/ } unless ENV["HOMEBREW_RELOCATE_METAVARS"]
```

**Comment by jonchang** [comment]
https://github.com/Homebrew/brew/pull/5894 might have fixed it. Can you open a pull request to bump the revision of `swiftgen`?

**Pull request merged**
