### PR TITLE
Fixing link to CODE_OF_CONDUCT.md within CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by pseudocody**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [X] Have you added an explanation of what your changes do and why you'd like us to include them?

-----

On https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md the link to the Code of Conduct page leads to a 404 page.

Updating the link allows a user to navigate to the correct page to view the resource.

### CODE REVIEW

**Comment by JCount** [comment]
@pseudocody Could you squash these two commits together and then force push? Thanks.

**Comment by pseudocody** [comment]
@JCount updated

**Comment by JCount** [comment]
@pseudocody One last request, I promise. 🤞
Could you switch it to using `https://github.com/Homebrew/brew/blob/master/CODE_OF_CONDUCT.md#code-of-conduct` as the url. The `#code-of-conduct` href nicely points directly to the beginning of the actual text of the Code of Conduct. 😄

**Comment by pseudocody** [comment]
@JCount updated 😃

**Comment by JCount** [comment]
Thanks! 💯 😄

**Comment by MikeMcQuaid** [comment]
Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request merged**
