### PR TITLE
Add Python 3 path in brew config

### PR DESCRIPTION
**Pull request by iMichka**
This is useful when debugging user issues for
formulae using Python 3.

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by tdsmith** [comment]
This won't work for system Python since Apple doesn't ship a `python2` executable. It does ship a `python2.7`. Understanding where the naked `python` executable is pointing is also interesting, though.

**Comment by MikeMcQuaid** [comment]
I think we could end up adding a bunch of stuff in here. I'd rather see a more generic solution so am 👎 on this I'm afraid.

**Comment by ilovezfs** [comment]
Can we print the path to COBOL?

**Comment by MikeMcQuaid** [comment]
Sorry, passing on this for now.

**Comment by iMichka** [comment]
No problem. My ruby skills / knowledge of homebrew's internals are not yet good enough to provide a more generic solution here. And I understand that that list could grow, which may or may not be a good idea. So I'm OK on passing on this :).

Still, there is a mix between system specific stuff and other things that seem unrelated: Python2 , java, x11? So I thought: why not add Python3. @tdsmith is right that this output's only a part of the picture at the moment, at least for Python.

Maybe `brew doctor` is better at warning us when weird stuff is going on with the user's setup, so extending the `brew config` list is not the best idea.

**Comment by MikeMcQuaid** [comment]
> Still, there is a mix between system specific stuff and other things that seem unrelated: Python2 , java, x11?

All that stuff was at one time provided by macOS FWIW 😁

**Pull request closed without merging**
