### PR TITLE
dependency: cleanup unused code

### PR DESCRIPTION
**Pull request by Bo98**
Most of this wasn't used since the removal of default_formula from Requirements.

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
Good catch, thanks @Bo98!

**Comment by ernie** [comment]
@MikeMcQuaid FWIW, it looks like this breaks neovim `HEAD` install, failing with:

```
  NoMethodError: undefined method `modify_build_environment' for #<Dependency: "lpeg" []>
```

**Comment by timsutton** [comment]
^ seeing the same on a few other formula updates I have been testing: `freerdp` (cmake) and `minio` (go) for example

**Comment by Bo98** [comment]
Sorry, this is already fixed and I will look into improving where CI missed this for the future.

**Pull request merged**
