### PR TITLE
cmd/formulae.sh: columnate output, fix spaces

### PR DESCRIPTION
**Pull request by maxim-belkin**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?
- [ ] Have you successfully run `brew man` locally and committed any changes?

-----

columnate output of `brew formulae` when the `column` command is available and the output is going to a terminal.
Also, remove spaces around `\n` so that formulae names are properly aligned.

### CODE REVIEW

**Review by MikeMcQuaid — CHANGES_REQUESTED** [review]
I'd rather we didn't do this. It adds complexity and edge-cases to a script that benefits from simplicity.

**Comment by maxim-belkin** [comment]
From the perspective of a user of this command, I see benefit in using columns: I don't have to scroll two and a half years to get to the top of the list.  Plus, it makes the behavior of `brew formulae` consistent with that of `brew list`. And performance is not affected in any way.

**Comment by MikeMcQuaid** [comment]
> From the perspective of a user of this command, I see benefit in using columns

You could do so with `brew formulae | columns`, no? We've passed on (many) PRs before for less than this.

> Plus, it makes the behavior of `brew formulae` consistent with that of `brew list`.

I don't think that's necessary (or a desirable goal given one is written in Ruby and another in Bash).

> And performance is not affected in any way.

It's adding more checks. That may mean it's affected so minimally to be unnoticeable but: that is still affected.

**Comment by maxim-belkin** [comment]
> It's adding more checks. That may mean it's affected so minimally to be unnoticeable but: that is still affected.

The most time-consuming part is the one that obtains the list of formulae. Processing time by `column` is overshadowed by it by a factor of ~50 (tested locally) and we're talking about tenths of a second -- so even a minor fluke in the first one obscures the time it takes to columnise the output.

> I don't think that's necessary (or a desirable goal given one is written in Ruby and another in Bash).

I thought this is a user-facing command (because it's in `cmd` folder) and, as such, we should prettify it a little bit. If we don't want to encourage its use by the end-users, we could probably move it to `dev-cmd`.

I'll repurpose this PR to fix the spacing issue.

**Comment by maxim-belkin** [comment]
Actually, let me close this one and create a new one 👍

**Pull request closed without merging**
