### PR TITLE
tests: Use Parser to parse args

### PR DESCRIPTION
**Pull request by GauthamGoli**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
#1860 

This is a backwards incompatible change for `--seed`

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> This is a backwards incompatible change for --seed

@GauthamGoli We'll need to support the `--key=value` format for some other commands. Why is it not posssible for `--seed` but is for `--only`?

**Comment by GauthamGoli** [comment]
@MikeMcQuaid `--seed` was of `--key value` format, now it is of `--key=value` format

**Comment by MikeMcQuaid** [comment]
@GauthamGoli Ah, gotcha, yes, misread! Thanks again!

**Comment by ilovezfs** [comment]
It would be nice if, in general, `--key val` and `--key=val` both worked for Homebrew commands. I think it's a common error for people to
```
brew bump-formula-pr --url https://github.com/macvim-dev/macvim/archive/snapshot-146.tar.gz --version=8.0-146 macvim
```
when they mean
```
brew bump-formula-pr --url=https://github.com/macvim-dev/macvim/archive/snapshot-146.tar.gz --version=8.0-146 macvim
```
and the error message is about as strange as you could imagine
```
Josephs-MacBook-Pro:Formula joe$ brew bump-formula-pr --url https://github.com/macvim-dev/macvim/archive/snapshot-146.tar.gz --version=8.0-146 macvim
##################################################################################################################################################################################################### 100.0%
Error: snapshot-146.tar.gz: /Users/joe/Library/Caches/Homebrew/Formula/snapshot-146.tar.gz:1: Invalid char `\x1F' in expression
/Users/joe/Library/Caches/Homebrew/Formula/snapshot-146.tar.gz:1: invalid multibyte char (UTF-8)
Josephs-MacBook-Pro:Formula joe$ 
```

**Comment by GauthamGoli** [comment]
@ilovezfs Actually, `OptionParser` supports both, so both ways would work for Homebrew and I was wrong in saying this is a backwards incompatible change

**Comment by GauthamGoli** [comment]
And no more weird errors once I add Parser support in `bump-formula-pr` 👍

**Pull request merged**
