### PR TITLE
formula_auditor: add cairomm@1.14 to allowlist

### PR DESCRIPTION
**Pull request by tschoonj**
Required for https://github.com/Homebrew/homebrew-core/pull/65531

Cairomm 1.16 and 1.14.x can be installed alongside each other without conflicts

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?
- [x] Have you successfully run `brew man` locally and committed any changes?

-----

### CODE REVIEW

**Comment by tschoonj** [comment]
Interesting catch-22: I can't add cairomm@1.14 to the allow list because the formula doesn't exist in core, and I can't add the formula to core until it's added here to the allow list 😄

**Comment by reitermarkus** [comment]
You add a `skip` to the test and open a follow-up PR removing it again.

**Review by reitermarkus — APPROVED** [review]

**Comment by tschoonj** [comment]
@reitermarkus can you merge this one in?

Thanks!

**Comment by MikeMcQuaid** [comment]
@tschoonj Done, thanks!

**Pull request merged**
