### PR TITLE
tests: fix problems in 'log with formula' test

### PR DESCRIPTION
**Pull request by UniqMartin**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

PR #333 was merged a bit too soon. Sorry I failed to notice the issues there. Problems fixed:

- Broken and leaking test if run as part of `brew tests --coverage` due to the `cmd` call being nested in the `Pathname#cd` block (see 2nd transcript below).
- Output during `git clone` operation because of a missing `shutup do` (see 1st transcript below).
- Still incomplete coverage for `cmd/log.rb` because `brew log` is invoked on the formula in the origin instead of the shallow clone.
- Minor stylistic fixes:
  - Superfluous parentheses around `core_tap.path.dirname`.
  - Overly long lines.

cc @eirinikos

----

```
$ /usr/bin/time brew tests --no-compat
Run options: --seed 9768

# Running:

................................................................................
................................................................................
.............................................................S.......S.S........
.............................................Cloning into 'homebrew-core-clone'...
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 4 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (4/4), done.
Checking connectivity... done.
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
...........

Finished in 59.391283s, 14.4129 runs/s, 35.1230 assertions/s.

856 runs, 2086 assertions, 0 failures, 0 errors, 3 skips

You have skipped tests. Run with --verbose for details.
       61.08 real        50.35 user        12.39 sys
```

----

```
$ /usr/bin/time brew tests --no-compat --coverage
Run options: --seed 64083

# Running:

................................................................................
................................................................................
................................................................................
..............................S..S............S...................Cloning into 'homebrew-core-clone'...
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 4 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (4/4), done.
Checking connectivity... done.
....................................F...........................................
................................................................................
................................................................................
................................F...............................................
................................................................................
................................................................................
......................................................................

Finished in 256.890035s, 3.3322 runs/s, 8.0190 assertions/s.

  1) Failure:
IntegrationCommandTests#test_tap [HOMEBREW_PREFIX/Library/Homebrew/test/test_integration_cmds.rb:245]:
Expected /2\ taps/
 to match "3 taps, 0 pinned, 0 formulae, 0 commands, 22 files, 18.6K"
.


  2) Failure:
TapTest#test_names [HOMEBREW_PREFIX/Library/Homebrew/test/test_tap.rb:71]:
--- expected
+++ actual
@@ -1 +1 @@
-["homebrew/core", "homebrew/foo"]
+["homebrew/coverage", "homebrew/core", "homebrew/foo"]


856 runs, 2060 assertions, 2 failures, 0 errors, 3 skips

You have skipped tests. Run with --verbose for details.
Coverage report generated for Unit Tests, […snip…]
HOME/.gem/ruby/2.0.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
HOME/.gem/ruby/2.0.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
HOME/.gem/ruby/2.0.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
HOME/.gem/ruby/2.0.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
HOME/.gem/ruby/2.0.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
HOME/.gem/ruby/2.0.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
HOME/.gem/ruby/2.0.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
HOME/.gem/ruby/2.0.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
HOME/.gem/ruby/2.0.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
HOME/.gem/ruby/2.0.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
HOME/.gem/ruby/2.0.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
HOME/.gem/ruby/2.0.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
HOME/.gem/ruby/2.0.0/bin/bundle:23:in `load'
HOME/.gem/ruby/2.0.0/bin/bundle:23:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
Warning: File leak is detected
IntegrationCommandTests#test_log_formula
--- expected
+++ actual
@@ -8,5 +8,6 @@
  "/prefix/Library",
  "/prefix/Library/Taps",
  "/prefix/Library/Taps/homebrew",
+ "/prefix/Library/Taps/homebrew/coverage",
  "/prefix/Library/Taps/homebrew/homebrew-core",
  "/prefix/Library/Taps/homebrew/homebrew-core/Formula"]
      275.89 real       248.69 user        47.51 sys
```

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> PR #333 was merged a bit too soon. Sorry I failed to notice the issues there.

Apologies.

> Broken and leaking test if run as part of brew tests --coverage due to the cmd call being nested in the Pathname#cd block (see 2nd transcript below).

Maybe worth making `brew test-bot` always run `--coverage` to catch these cases in future (rather than leaning on Travis after the fact)?

**Comment by UniqMartin** [comment]
> Maybe worth making `brew test-bot` always run `--coverage` to catch these cases in future (rather than leaning on Travis after the fact)?

Makes sense, but would considerably impact throughput on our test bot. Compare 275 seconds (with `--coverage`) with 61 seconds (without `--coverage`) from my two transcripts above.

That's mostly an inefficiency in SimpleCov (and the somewhat non-standard way we're using it in our integration tests). I have a somewhat working fix for that locally, but it will take a few more days to get this cleaned up and submitted to SimpleCov upstream.

**Comment by MikeMcQuaid** [comment]
@UniqMartin Fair point 👍

**Comment by UniqMartin** [comment]
This slowness of generating a complete coverage report is also a major annoyance when working on this stuff, so I hope to have a decent fix that we can use in our `simplecov` fork soon. (Upstream seems to be moving fairly slowly these days and some of the fixes we rely on still haven't made it into a release.)

**Comment by eirinikos** [comment]
Argh, I missed a lot of things. Hindsight is 20/20. 👓  Thanks @UniqMartin for the fixes and improvements.

I was thinking (hoping) that the long lines weren't *too* long (even though they surpass 80 characters in length), but I see that it was easy to shorten them, anyway.

How is [this line](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/log.rb#L23) being tested? I would have thought that there needed to be an explicit assertion for this output.

**Comment by UniqMartin** [comment]
> Argh, I missed a lot of things.

I'm sure I also missed something. Maybe I'm missing less nowadays than six months ago. Maybe I'm just missing different things. There's always something to be added to one's mental checklist …

> I was thinking (hoping) that the long lines weren't *too* long (even though they surpass 80 characters in length), but I see that it was easy to shorten them, anyway.

We don't have a hard and fast rule for that, but it helps with seeing all of the relevant code at a glance without horizontal scrolling. I would probably would have left the lines unwrapped if I didn't have to change them anyway. In this case it was fairly simple to make the code both narrow enough and readable, but sometimes that's quite a challenge …

> How is [this line](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/log.rb#L23) being tested? I would have thought that there needed to be an explicit assertion for this output.

It's only tested in the sense that the output is triggered due to the presence of the `.git/shallow` file, thus all lines of the file are executed at least once. To actually test for that one would have to add an assertion on the output of that command and check for the presence of (part of) that message in the output.

**Pull request merged**
