### PR TITLE
XCode 8.2 is stable

### PR DESCRIPTION
**Pull request by dersvenhesse**
Updated `latest_version` and `prerelease`.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by dersvenhesse** [comment]
Please try `brew update`.

**Comment by kellyjandrews** [comment]
It was a new homebrew install.  Not sure what happened - but I see it's been updated, so I ignored it.

**Comment by dersvenhesse** [comment]
Maybe we can figure it out. ;)
Does `brew --version` show `Homebrew 1.1.2-82-g755be9a2`?

**Comment by kellyjandrews** [comment]
Homebrew 1.1.2
Homebrew/homebrew-core (git revision 8366; last commit 2016-12-13)

**Comment by kellyjandrews** [comment]
I run a script that first installs from master, and runs `brew doctor`, then updates, so hard telling. I don't get the error now - so no worries. Sorry for the trouble, and thanks for keeping the repo up-to-date.  Appreciate all you do!

**Comment by MikeMcQuaid** [comment]
It's not in the latest tag yet. @kellyjandrews Don't need you to report this multiple times in multiple places, thanks.

**Comment by kellyjandrews** [comment]
Sorry for the duplication :)

**Comment by MikeMcQuaid** [comment]
`brew update`, fixed in the `1.1.3` release/tag.

**Comment by amicming** [comment]
```brew update``` fixed the issue 👍

**Pull request merged**
