### PR TITLE
Revert "Revert "github_runner_matrix: enable usage of `macos-15` runners""

### PR DESCRIPTION
**Pull request by carlocab**
This has been fixed, so we only need to wait for the fix to be deployed: https://github.com/actions/runner-images/issues/10686#issuecomment-2377183831

Reverts Homebrew/brew#18418

### CODE REVIEW

**Comment by carlocab** [comment]
We should probably also run tests on the GitHub-hosted runners just like in `doctor.yml`.

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
> We should probably also run tests on the GitHub-hosted runners just like in `doctor.yml`.

Good idea 👍🏻

**Comment by carlocab** [comment]
Fix has shipped, we just need to wait a little bit longer for runners to pick up the update: https://github.com/actions/runner-images/commit/8726158fca5622d4bf6cbff3cc58e244c4fda687

**Comment by carlocab** [comment]
Should be good now. Will look into tests soon.

**Pull request merged**
