### PR TITLE
setup-analytics: Handle missing /proc/.../uuid

### PR DESCRIPTION
**Pull request by sjackman**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
When is this missing?

**Comment by sjackman** [comment]
On [Windows Subsystem for Linux](https://msdn.microsoft.com/en-us/commandline/wsl/about), for example.

**Comment by MikeMcQuaid** [comment]
And does it have `/usr/bin/uuidgen` present? If so, can we reverse the ordering so `/proc` is only checked if `uuidgen` isn't present?

**Comment by sjackman** [comment]
Yes, it does have `/usr/bin/uuidgen`, at least with the default Ubuntu file system image.

**Comment by sjackman** [comment]
> If so, can we reverse the ordering so /proc is only checked if uuidgen isn't present?

:+1: Done.

**Comment by MikeMcQuaid** [comment]
Thanks again @sjackman!

**Comment by sjackman** [comment]
Thanks again for merging, Mike!

**Pull request merged**
