### PR TITLE
[Advice needed] search: show checkmark next to installed casks

### PR DESCRIPTION
**Pull request by alyssais**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

I'm trying to implement #1764.

To do that, I've changed <kbd>brew search</kbd> to search local casks as well as formulae. However, for this to work I needed to use some cask code, which wasn't possible.

@MikeMcQuaid suggested I refactor whatever Cask I needed into Homebrew, but I'm not sure how to do that. Really what I need is something like `Hbc.all_tokens`, but there's no sensible place to put it. One option would be to add a `Cask` class to Homebrew that had some very basic metadata like `name` and `tap`, but that seems like repeating ourselves when the code's already there in Cask.

So, I'm looking for advice on how to refactor the Cask functionality I need to use here into Homebrew.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
I think it's probably worth punting on showing checkmarks for Casks for now. When we do do so I think it's probably worth refactoring some of the logic to detect if a Cask is installed into shared code in `Library/Homebrew` rather than having Homebrew call into the Homebrew Cask code/modules. Another option would be to call out to `brew cask search`.

CC @reitermarkus and @jawshooah for thoughts.

**Comment by reitermarkus** [comment]
> One option would be to add a `Cask` class to Homebrew that had some very basic metadata like name and tap, but that seems like repeating ourselves when the code's already there in Cask.

I thought about refactoring the whole `Hbc::Cask` class before to behave more like the `Formula` class, i. e. being `Enumerable` and letting you call `Cask["token"]` instead of `Hbc.load("token")`.

**Comment by MikeMcQuaid** [comment]
We could also have a mixin or proxy to abstract formulae and casks in a case like this.

**Review by dolfly — APPROVED** [review]

**Comment by vitorgalvao** [comment]
Looks like this has already been implemented. I seem to distinctly recall a PR to do it, but I’m not finding it. Either way, just tested it and it works.

**Pull request closed without merging**
