### PR TITLE
Revert "shims/scm/git: Fix the search for brewed git"

### PR DESCRIPTION
**Pull request by ilovezfs**
Reverts Homebrew/brew#3589

### CODE REVIEW

**Comment by ilovezfs** [comment]
CC @sjackman now I'm getting
```
Josephs-MacBook-Pro:~ joe$ brew update
git: 'credential-osxkeychain' is not a git command. See 'git --help'.
fatal: could not read Username for 'https://github.com': terminal prompts disabled
Error: Fetching /usr/local/Homebrew/Library/Taps/ilovezfs/homebrew-whitelist failed!
Updated Homebrew from 5c7d2d0 to bd471d6.
No changes to formulae.
```

**Comment by sjackman** [comment]
The intention of `shims/scm/git` is to prefer brewed `git` over `/usr/bin/git`.
Due to a bug, it was preferring `/usr/bin/git` over brewed `git`.
I can't say exactly why it broke for you. Perhaps your brewed `git` isn't happy? Doe the following succeed?
```sh
cd /usr/local/Homebrew/Library/Taps/ilovezfs/homebrew-whitelist
/usr/local/bin/git fetch
```

**Comment by sjackman** [comment]
```
git: 'credential-osxkeychain' is not a git command. See 'git --help'.
```
Can you please report…
```sh
grep credential-osxkeychain ~/.gitconfig /usr/local/Homebrew/Library/Taps/ilovezfs/homebrew-whitelist/.gitconfig
which -a credential-osxkeychain
```

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:~ joe$ cd /usr/local/Homebrew/Library/Taps/ilovezfs/homebrew-whitelist
Josephs-MacBook-Pro:homebrew-whitelist joe$ /usr/local/bin/git fetch
Josephs-MacBook-Pro:homebrew-whitelist joe$ 
```

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:~ joe$ grep credential-osxkeychain ~/.gitconfig /usr/local/Homebrew/Library/Taps/ilovezfs/homebrew-whitelist/.gitconfig
grep: /usr/local/Homebrew/Library/Taps/ilovezfs/homebrew-whitelist/.gitconfig: No such file or directory
Josephs-MacBook-Pro:~ joe$ 
```

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:~ joe$ which -a git-credential-osxkeychain
/usr/local/bin/git-credential-osxkeychain
/usr/local/bin/git-credential-osxkeychain
/usr/local/bin/git-credential-osxkeychain
Josephs-MacBook-Pro:~ joe$ 
```

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:~ joe$ brew list git | grep git-credential-osxkeychain
/usr/local/Cellar/git/2.15.0/bin/git-credential-osxkeychain
/usr/local/Cellar/git/2.15.0/share/git-core/contrib/credential/osxkeychain/git-credential-osxkeychain.c
Josephs-MacBook-Pro:~ joe$ 
```

**Comment by sjackman** [comment]
I have an idea…
```sh
brew update
HOMEBREW_NO_ENV_FILTERING=1 brew update
```

**Comment by sjackman** [comment]
I bet `git` is not finding `git-credential-osxkeychain` in your `PATH` with `ENV_FILTERING` enabled.

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:Homebrew joe$ brew update
git: 'credential-osxkeychain' is not a git command. See 'git --help'.
fatal: could not read Username for 'https://github.com': terminal prompts disabled
Error: Fetching /usr/local/Homebrew/Library/Taps/ilovezfs/homebrew-whitelist failed!
Josephs-MacBook-Pro:Homebrew joe$ HOMEBREW_NO_ENV_FILTERING=1 brew update
Already up-to-date.
Josephs-MacBook-Pro:Homebrew joe$ 
```
Since env filtering is on for everyone, that is a problem.

**Comment by sjackman** [comment]
This breaks for people who have set `git config credential.helper osxkeychain`, which is definitely a problem, but doesn't affect everyone. Mostly affects developers.

**Comment by ilovezfs** [comment]
In any case, I'm merging this until we have a version that doesn't break things for anyone.

**Comment by sjackman** [comment]
Okay.

**Comment by sjackman** [comment]
I'm taking a Christmas break for a week, so I may not get back to this issue until the new year.

**Comment by sjackman** [comment]
Does this work for you?
```
cd /usr/local/Homebrew/Library/Taps/ilovezfs/homebrew-whitelist
PATH=/usr/bin:/bin /usr/local/bin/git fetch
```

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:Homebrew joe$ cd /usr/local/Homebrew/Library/Taps/ilovezfs/homebrew-whitelist
Josephs-MacBook-Pro:homebrew-whitelist joe$ PATH=/usr/bin:/bin /usr/local/bin/git fetch
git: 'credential-osxkeychain' is not a git command. See 'git --help'.
Username for 'https://github.com':
```

**Comment by sjackman** [comment]
I'm fine with reverting it.

**Comment by sjackman** [comment]
It's odd that `/usr/bin/git` is able to find `/usr/local/bin/git-credential-osxkeychain` but the brewed `/usr/local/bin/git` is not able to find it. Quite strange.

**Comment by ilovezfs** [comment]
It's probably finding `/usr/libexec/git-core/git-credential-osxkeychain` via magic.

**Comment by sjackman** [comment]
I was thinking something like that too. I don't have `/usr/libexec/git-core/git-credential-osxkeychain` on my machine. Do you? I wonder where else it could be hiding.

**Comment by ilovezfs** [comment]
I do, yeah. Yours is
```
iMac-TMP:~ joe$ ls /Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git-credential-osxkeychain 
```
and/or
```
/Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git-credential-osxkeychain
iMac-TMP:~ joe$ ls /Library/Developer/CommandLineTools/usr/libexec/git-core/git-credential-osxkeychain 
/Library/Developer/CommandLineTools/usr/libexec/git-core/git-credential-osxkeychain
iMac-TMP:~ joe$ 
```

**Comment by ilovezfs** [comment]
I guess you'd probably need to add the parent directory of the realpath of git to the PATH or at least HOMEBREW_PREFIX/opt/git/bin for it to work with ENV_FILTERING and Homebrew git.

**Comment by sjackman** [comment]
That's what I was thinking too. Should be pretty straight forward.

**Comment by sjackman** [comment]
Yep, I have both of those files that you listed above.

**Comment by sjackman** [comment]
And yes, I agree, `/usr/bin/git` is probably finding it via magics. 🐰🎩

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:~ joe$ strings /usr/bin/git|grep libexec
libexec/git-core
```
hehe

**Comment by JCount** [comment]
🌈 and 🦄 s

**Pull request merged**
