### PR TITLE
spec:  Pathname#rpath, Pathname#interpreter and Pathname#patch!

### PR DESCRIPTION
**Pull request by rmNULL**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

**Open for discussion**

The PIE elfs were generated by `gcc`, `g++`, `go`, `rustc` compilers.
The go elf is heavy around 1.9M it prolly aint worth it.
Anyway, these elf-fixtures were used as dummies to write tests,
If you wish to use different elf fixtures it's totally fine.

cc @sjackman @woodruffw

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Yeh, I'd pass on `rust` and `go` for size but 👍🏻 to the others.

**Comment by woodruffw** [comment]
I agree with @MikeMcQuaid here -- let's drop those bins, and then this LGTM!

**Comment by MikeMcQuaid** [comment]
@rmNULL Any news here?

**Comment by rmNULL** [comment]
@MikeMcQuaid sorry about the delay, removed those ELFs, including cpp it shouldn't differ much from gcc produced binary.

@sjackman iirc there was some request from you to include a puts call in `libforty.so`. can u verify whether these ELFs are enough

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks @rmNULL!

**Pull request merged**
