### PR TITLE
Automate updation of maintainers in README

### PR DESCRIPTION
**Pull request by nandahkrishna**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?
- [x] Have you successfully run `brew man` locally and committed any changes?

-----

This PR automates the updation of maintainers in Homebrew/brew's README and manpages. Rather than having this be a separate workflow, I've modified `update-manpage.yml` to update maintainers if it's the first day of the month (for efficiency).

**Important:** This requires the `read:org` scope to be available to the `HOMEBREW_GITHUB_API_TOKEN` secret.

### CODE REVIEW

**Comment by Rylan12** [comment]
I wonder if this should also run if the workflow is manually triggered (i.e. `workflow_dispatch`). Or, maybe a setting could be added to `workflow_dispatch` to indicate whether or not to update the maintainers. Otherwise, there's no way to test it out or manually update the maintainers unless you get lucky and it's the first of the month.

---

Separately, I wonder if it's even necessary to only run once a month. This workflow is only running once a day on a schedule, and I don't think this operation is so time-intensive that it will slow things down. I think we may as well update everything at once.

Maybe instead restrict updating maintainers to `schedule` or `workflow_dispatch` and not have it run on `push` events.

**Comment by nandahkrishna** [comment]
> Maybe instead restrict updating maintainers to `schedule` or `workflow_dispatch` and not have it run on `push` events.

I've updated it to run on events other than `push`, which would be `schedule` and `workflow_dispatch`.

**Review by Rylan12 — APPROVED** [review]
Looks good to me! 🎉

**Comment by nandahkrishna** [comment]
Thanks Rylan! We just need to ensure the token has the required scope before merging this. (CC @MikeMcQuaid)

**Review by MikeMcQuaid — APPROVED** [review]
LGTM. Will setup token when I get the chance (or another @Homebrew/plc or @Homebrew/tsc member can beat me to it).

**Comment by MikeMcQuaid** [comment]
@nandahkrishna I think `HOMEBREW_GITHUB_API_TOKEN` already has `read:org`. Is there any way to trigger this to test it before it's merged?

**Comment by nandahkrishna** [comment]
I think if the PR is created from a branch of `Homebrew/brew`, we could run it manually (`workflow_dispatch`).

**Comment by MikeMcQuaid** [comment]
Let's merge and try it out!

**Comment by nandahkrishna** [comment]
It seems the workflow run failed:
```
Error: GitHub API Error: This endpoint requires you to be authenticated.
Try again in 59 minutes 59 seconds, or:
Create a GitHub personal access token:
    https://github.com/settings/tokens/new?scopes=gist,public_repo,workflow&description=Homebrew
  echo 'export HOMEBREW_GITHUB_API_TOKEN=your_token_here' >> /home/runner/.bash_profile
```

**Pull request merged**
