### PR TITLE
fix: allow running bin/brew with SHELLOPTS=nounset

### PR DESCRIPTION
**Pull request by kaihowl**
A similar fix is already present on line 6.

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Review by MikeMcQuaid — CHANGES_REQUESTED** [review]
Sorry, I don't think this is the right fix. Can `SHELLOPTS=nounset` either be unset here or detected and fail?

**Comment by kaihowl** [comment]
> Sorry, I don't think this is the right fix. Can `SHELLOPTS=nounset` either be unset here or detected and fail?

@MikeMcQuaid what is wrong with the fix? Detecting and temporarily unsetting “nounset” is more complex for no apparent benefit. Please help me understand your concerns.

**Comment by MikeMcQuaid** [comment]
> what is wrong with the fix?

It's likely to regress again. There's nothing in our CI requiring that this script work with `SHELLOPTS=nounset`.

Similarly, it's a fix for a user issue that could be fixed by you in your environment instead.

**Comment by kaihowl** [comment]
> > what is wrong with the fix?
> 
> It's likely to regress again. There's nothing in our CI requiring that this script work with `SHELLOPTS=nounset`.
> 
> Similarly, it's a fix for a user issue that could be fixed by you in your environment instead.

@MikeMcQuaid thank you that clears it up for me. 

If you think there is value in going the full way by making this script work with “set -euo pipefail” or similar, I am happy to take a look at that. 

From my experience, bash scripts should fail for expanding unset variables. Otherwise, the risk of dormant faults rises. 

But, yes, this is an issue I detected downstream in my dotfiles: I globally enabled strict SHELLOPTS to weed out errors in my shell scripts. I could just as well disable the strict shellopts before invoking brew. 

Let me know if I should expand this fix by including a strict “set -euo pipefail” preamble/line or rather decline the PR and fix it in my environment.

**Comment by MikeMcQuaid** [comment]
> If you think there is value in going the full way by making this script work with “set -euo pipefail” or similar, I am happy to take a look at that.

I don't think `set -e` makes sense given we handle all the errors manually and that would override that.

`set -u` or similar would do, though. If it's set in this file I'd be 👍🏻 on this change.

**Comment by kaihowl** [comment]
> `set -u` or similar would do, though. If it's set in this file I'd be 👍🏻 on this change.

I added this now. Yet, there were (of course) more undefined variables. I am no longer confident about this change. Please make a judgement call if this if really improving the state.

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @kaihowl!

**Pull request merged**
