### PR TITLE
audit: Check for invocations of cctools.

### PR DESCRIPTION
**Pull request by woodruffw**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Now that ruby-macho is available, cctools should be invoked as little
as possible.

### CODE REVIEW

**Comment by woodruffw** [comment]
This shouldn't be merged until I revendor ruby-macho at least one more time, since the changes that add `lipo(1)`-like functionality aren't in the currently vendored version.

**Comment by MikeMcQuaid** [comment]
> This shouldn't be merged until I revendor ruby-macho at least one more time, since the changes that add lipo(1)-like functionality aren't in the currently vendored version.

@woodruffw Any news on this?

**Comment by woodruffw** [comment]
Yeah, I implemented the necessary features in ruby-macho a few months ago - I just haven't done a 1.1 release, which when revendored would include the changes.

I'm currently in the mountains with limited internet, but I can do one next week :smile:

**Comment by MikeMcQuaid** [comment]
@woodruffw Cool, thanks!

**Comment by woodruffw** [comment]
Just bumped ruby-macho to 1.1.0, I'll have a revendor PR ready soon and then this'll be good to go :tada:

**Comment by woodruffw** [comment]
This should now be good to go. I'll merge it tonight, unless someone else feels like doing it first :smile:

**Comment by ilovezfs** [comment]
:confetti_ball:

**Comment by ilovezfs** [comment]
@woodruffw looks like this needs some kind of exception for `cctools` itself:
```
iMac-TMP:~ joe$ brew audit --strict --online cctools
cctools:
  * Use ruby-macho instead of calling 
Error: 1 problem in 1 formula
iMac-TMP:~ joe$ 
```

**Comment by ilovezfs** [comment]
@woodruffw also the tool name not being printed isn't specific to cctools:
```
chicken:
  * Use ruby-macho instead of calling 
Error: 1 problem in 1 formula
iMac-TMP:~ joe$
```

**Comment by woodruffw** [comment]
Yeah, the check should be something like :

```ruby
if line =~ /system\s+['"](otool|install_name_tool|lipo)/ && formula.name != "cctools"
```

to keep to capture all in `$1` and exclude `cctools`. Should I revert-and-fix or just update it in another PR?

**Comment by ilovezfs** [comment]
No need for revert.

**Comment by fxcoudert** [comment]
`wine` calls `lipo` like this:

```
        system "lipo", "-create", "#{dirs.first}/openssl",
                                  "#{dirs.last}/openssl",
                       "-output", "#{libexec}/bin/openssl"
```

What would be the ruby-macho equivalent?

**Comment by ilovezfs** [comment]
I think you want
```
          MachO::Tools.merge_machos("#{libexec}/bin/openssl",
                                    "#{dirs.first}/openssl", 
                                    "#{dirs.last}/openssl")
```

**Comment by woodruffw** [comment]
Yep, `merge_machos` is what you want. The docs are here: http://www.rubydoc.info/gems/ruby-macho/MachO/Tools#merge_machos-class_method, although I just realized there's an error: the `files` are strings like @ilovezfs showed, not `MachOFile`/`FatFile` instances like the doc says.

**Comment by fxcoudert** [comment]
@woodruffw can you confirm that it will work the same way for dylibs and executables?

**Comment by woodruffw** [comment]
@fxcoudert Yes. All `merge_machos` does is take *N* Mach-O binaries, flatten them down to single architectures, and then smush all of those together with a fat Mach-O header. It doesn't care about what kind of Mach-O they are (dylib, executable, object file, etc).

**Comment by fxcoudert** [comment]
@woodruffw thanks!

**Comment by woodruffw** [comment]
No problem :+1:

**Comment by MikeMcQuaid** [comment]
@woodruffw Feature request: a `lipo` drop-in written in Ruby 😉

**Comment by woodruffw** [comment]
@MikeMcQuaid That would actually be pretty easy to do, although having Homebrew use it would probably be a pretty ugly hack onto `$PATH` when the real `lipo` isn't available. We also benefit a fair bit in terms of performance from not having to `exec` in the current form :smile:

**Comment by ilovezfs** [comment]
I'm not sure you two are on the same page. @MikeMcQuaid could you be more explicit about what you're asking for please.

**Comment by MikeMcQuaid** [comment]
This isn't a feature request for Homebrew but just in general for Ruby MachO having command-line tools that can be used instead of e.g. `lipo`, `install_name_tool`, `otool` but produce identical output could make the tool more widely useful.

**Comment by woodruffw** [comment]
Yeah, that's something I can do. I recently broke https://github.com/woodruffw/ruby-macho-utils off from the main repo to experiment with command-line tools (since I wanted to add extra dependencies that ruby-macho itself doesn't require), so I can implement `lipo`, etc over there.

**Pull request merged**
