### PR TITLE
Installing casks is supported only on macOS

### PR DESCRIPTION
**Pull request by sjackman**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by sjackman** [comment]
See the discussions of the related closed and unmerged PR at https://github.com/Homebrew/brew/pull/3325.

**Comment by sjackman** [comment]
Dang. That was fast, Mike. 🏁

**Comment by MikeMcQuaid** [comment]
Thanks again @sjackman!

**Comment by sjackman** [comment]
My pleasure. Thanks for merging, Mike!

**Pull request merged**
