### PR TITLE
cask: Don’t remove login items on upgrade.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

---

Don't remove login items when upgrading an application.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> Don't remove login items when upgrading an application.

Why not? What if the current login items are outdated/no longer needed? What’s the harm in removing them and letting the application add them again?

**Comment by commitay** [comment]
> What if the current login items are outdated/no longer needed?

Good point.

> Don't remove login items when upgrading an application.

Is this intended to help with the `login_item` problems on mojave?

**Comment by reitermarkus** [comment]
The reason for this is that every time I run `upgrade --greedy`, my Dropbox login item gets removed. You could argue that `login_item` should be in `zap` because it isn't added as part of the installation process.

**Comment by vitorgalvao** [comment]
> You could argue that `login_item` should be in `zap` because it isn't added as part of the installation process.

If I uninstall an app, I may want to keep their settings, but I’ll never want to keep a broken login item. That justifies having `login_item` in `uninstall`.

I don‘t particularly agree with the change, but since you have a real need for it, I also don’t particularly oppose it.

Out of curiosity, when you upgrade Dropbox what do you need to do to readd the login item?

**Comment by reitermarkus** [comment]
I prefer a broken login item to a broken setup. A login item changing is an exception and not the norm.

> Out of curiosity, when you upgrade Dropbox what do you need to do to readd the login item?

I have to start Dropbox manually, which I shouldn't have to. And of course I only realise this once I actually *need* documents which haven't synced yet.

**Pull request merged**
