### PR TITLE
Add Git diff driver for `.drawio.svg` files

### PR DESCRIPTION
**Pull request by claui**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

## Summary

Originally part of #8627 but spun off as @SMillerDev [suggested](https://github.com/Homebrew/brew/pull/8627#issuecomment-687711397).

The diff driver helps with `git diff` on [diagrams](https://github.com/Homebrew/brew/blob/master/docs/Diagram-Guidelines.md) in the draw.io format.
The driver requires an XSLT file, which is included in this PR. The XSLT code enforces a defined order for XML attributes, which removes noise from diffs.

## Setting up and using the driver

This PR adds the necessary information to the Diagram Guidelines.

### Without a diff driver

```diff
--- a/managing-pull-requests.drawio.svg
+++ b/managing-pull-requests.drawio.svg
@@ -1,4 +1,4 @@
-<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="759px" height="936px" viewBox="-0.5 -0.5 759 936" content="&lt;mxfile host=&quot;&quot; modified=&quot;2020-07-16T21:15:00.400Z&quot; agent=&quot;5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.46.1 Chrome/78.0.3904.130 Electron/7.3.1 Safari/537.36&quot; etag=&quot;pmHBLrtnrX4nNGyRVqOD&quot; version=&quot;13.1.3&quot;&gt;&lt;diagram id=&quot;6hGFLwfOUW9BJ-s0fimq&quot; name=&quot;Page-1&quot;&gt;7Vzbkps4EP0aP3oKxM1+nOsmVcnWVGUr2TylsJFtdjFyhJix8/UrgWSQBLbHCHuozcsMSKIR6u7TRy3JI+d+vf0Dh5vVZxTBZASsaDtyHkYA2Baw6T9WsitLJrZXFixxHPFGVcGX+BcUT/LSPI5gJjUkCCUk3siFc5SmcE
[…] (184 lines omitted)
```

### With a diff driver:

```diff
--- a/managing-pull-requests.drawio.svg
+++ b/managing-pull-requests.drawio.svg
@@ -188,5 +188,8 @@
     <mxCell id="54" parent="1" style="verticalLabelPosition=bottom;verticalAlign=top;html=1;shape=trapezoid;perimeter=trapezoidPerimeter;whiteSpace=wrap;size=0.23;arcSize=10;flipV=1;" vertex="1" value="Push the button">
       <mxGeometry x="560" y="550" width="100" height="60" as="geometry"/>
     </mxCell>
+    <mxCell id="70" parent="1" style="" vertex="1" value="Cheers!">
+      <mxGeometry x="92" y="900" width="120" height="60" as="geometry"/>
+    </mxCell>
   </root>
 </mxGraphModel>
```

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
This seems pretty heavy for a single file that could be compressed better anyway (see https://github.com/Homebrew/brew/pull/8656), doesn't seem like it'll be changing much and is easily diffed through the GitHub rich diff?

**Comment by claui** [comment]
@MikeMcQuaid Even though it’s only one drawing today, a couple of places in the docs still are complex and need illustrations.

The GitHub diff only shows the generated SVG, not the original source. While compression is fine, it makes the SVG diff even less legible.

YMMV but I can’t work that way, and thought the driver might be useful to other maintainers. It’s not going to affect you unless you add it to your Git config.

Having said all that: I’m fine with putting it into my own tap. For me, that would work just the same.
Let’s wait for one or two more opinions from fellow @homebrew/core maintainers, then I’m 👍.

**Comment by claui** [comment]
@MikeMcQuaid What’s that rich diff you mentioned?

**Comment by reitermarkus** [comment]
> the driver might be useful to other maintainers

Maybe this could be a formula which you install and can set globally in your config so it would be useful for more even more people in other repos as well?

> What’s that rich diff you mentioned?

The right button (in the “Files” tab):

Bildschirmfoto 2020-09-14 um 13 18 24

**Comment by MikeMcQuaid** [comment]
> @MikeMcQuaid Even though it’s only one drawing today, a couple of places in the docs still are complex and need illustrations.

Is anyone currently working on these?

> The GitHub diff only shows the generated SVG, not the original source. While compression is fine, it makes the SVG diff even less legible.

I think we should aim to have these compressed for the folks reading the docs. Ideally this would be tested in the CI process?

**Comment by claui** [comment]
> Is anyone currently working on these?

I’d prefer to fix the remaining issues on the existing diagram first, e. g. add the `depends_on :linux` case.

> I think we should aim to have these compressed for the folks reading the docs. Ideally this would be tested in the CI process?

No strong opinion but I think minification should happen at page generation time, not in the source.
Minifying the source at CI or merge time creates needless conflicts, makes the source less readable, and makes the review/feedback process more awkward.

**Comment by claui** [comment]
Taking into account the feedback and lack of interest, closing this PR in favour of a dedicated formula.

**Comment by claui** [comment]
Thanks for the feedback @MikeMcQuaid and @reitermarkus!

**Comment by MikeMcQuaid** [comment]
> No strong opinion but I think minification should happen at page generation time, not in the source.

This is not possible with GitHub Pages and I don't think it's a strong enough argument to move elsewhere.

**Comment by claui** [comment]
@MikeMcQuaid Fair enough. Let’s have CI enforce minification, then.

**Pull request closed without merging**
