### PR TITLE
remove /usr/bin/xattr unsupported -s option in macOS 10.15

### PR DESCRIPTION
**Pull request by ytqh**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
Related Issue: https://github.com/Homebrew/homebrew-cask/issues/70603

### CODE REVIEW

**Comment by reitermarkus** [comment]
What does the `-s` option do?

**Comment by ytqh** [comment]
> What does the `-s` option do?

According to the manual of xattr 0.9.4

```
     -s  If a file argument is a symbolic link, act on the symbolic link
         itself, rather than the file that the symbolic link points at.
```

**Comment by amyspark** [comment]
I can confirm Casks installed in Mojave with this patch still work.

**Comment by ytqh** [comment]
> Do Casks still pass Gatekeeper in Catalina after this change? Please run `spctl --assess --verbose <app>` and `codesign -dvv --deep <app>` on an app with symbolic links.

```
ln -s /Applications/XcodeClangFormat.app ~/Desktop/test.app

$ spctl --assess --verbose ~/Desktop/test.app                     
/Users/yutian/Desktop/test.app: accepted
source=Developer ID

$ codesign -dvv --deep ~/Desktop/test.app                           
Executable=/Applications/XcodeClangFormat.app/Contents/MacOS/XcodeClangFormat
Identifier=com.mapbox.XcodeClangFormat
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=443 flags=0x0(none) hashes=6+5 location=embedded
Signature size=8911
Authority=Developer ID Application: Mapbox, Inc. (GJZR2MEM28)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Sep 16, 2016 at 03:07:02
Info.plist entries=22
TeamIdentifier=GJZR2MEM28
Sealed Resources version=2 rules=13 files=3
Nested=PlugIns/clang-format.appex
Internal requirements count=1 size=220
```

**Comment by amyspark** [comment]
cc @MikeMcQuaid for merging

**Comment by MikeMcQuaid** [comment]
Thanks @ytqh!

@amyspark 👍🏻. Would love if you’d accept maintainer invitation purely to be able to review and merge Cask changes on Homebrew/brew; don’t need to do anything else.

**Pull request merged**
