### PR TITLE
resource_auditor: restore curl HTTP mirror auditing

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

We need brewed curl for functional HTTPS support, but can't currently install curl from source because there's HTTPS everywhere.

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
Makes sense to me, nice work restoring this.

**Review by Rylan12 — APPROVED** [review]

**Comment by Bo98** [comment]
The Linux dep tree seems very large.

**Comment by Bo98** [comment]
```
curl
├── pkg-config
├── brotli
│   └── cmake
│       ├── sphinx-doc
│       │   └── python@3.9
│       │       ├── pkg-config
│       │       ├── gdbm
│       │       ├── mpdecimal
│       │       ├── openssl@1.1
│       │       ├── readline
│       │       │   └── ncurses
│       │       │       ├── pkg-config
│       │       │       └── gpatch
│       │       ├── sqlite
│       │       │   ├── readline
│       │       │   │   └── ncurses
│       │       │   │       ├── pkg-config
│       │       │   │       └── gpatch
│       │       │   └── zlib
│       │       ├── xz
│       │       ├── bzip2
│       │       ├── expat
│       │       ├── libffi
│       │       ├── ncurses
│       │       │   ├── pkg-config
│       │       │   └── gpatch
│       │       ├── unzip
│       │       │   └── bzip2
│       │       └── zlib
│       ├── ncurses
│       │   ├── pkg-config
│       │   └── gpatch
│       └── openssl@1.1
├── libidn2
│   ├── pkg-config
│   ├── gettext
│   │   ├── libxml2
│   │   │   ├── python@3.9
│   │   │   │   ├── pkg-config
│   │   │   │   ├── gdbm
│   │   │   │   ├── mpdecimal
│   │   │   │   ├── openssl@1.1
│   │   │   │   ├── readline
│   │   │   │   │   └── ncurses
│   │   │   │   │       ├── pkg-config
│   │   │   │   │       └── gpatch
│   │   │   │   ├── sqlite
│   │   │   │   │   ├── readline
│   │   │   │   │   │   └── ncurses
│   │   │   │   │   │       ├── pkg-config
│   │   │   │   │   │       └── gpatch
│   │   │   │   │   └── zlib
│   │   │   │   ├── xz
│   │   │   │   ├── bzip2
│   │   │   │   ├── expat
│   │   │   │   ├── libffi
│   │   │   │   ├── ncurses
│   │   │   │   │   ├── pkg-config
│   │   │   │   │   └── gpatch
│   │   │   │   ├── unzip
│   │   │   │   │   └── bzip2
│   │   │   │   └── zlib
│   │   │   ├── readline
│   │   │   │   └── ncurses
│   │   │   │       ├── pkg-config
│   │   │   │       └── gpatch
│   │   │   └── zlib
│   │   └── ncurses
│   │       ├── pkg-config
│   │       └── gpatch
│   └── libunistring
├── libssh2
│   ├── openssl@1.1
│   └── zlib
├── nghttp2
│   ├── pkg-config
│   ├── c-ares
│   │   └── cmake
│   │       ├── sphinx-doc
│   │       │   └── python@3.9
│   │       │       ├── pkg-config
│   │       │       ├── gdbm
│   │       │       ├── mpdecimal
│   │       │       ├── openssl@1.1
│   │       │       ├── readline
│   │       │       │   └── ncurses
│   │       │       │       ├── pkg-config
│   │       │       │       └── gpatch
│   │       │       ├── sqlite
│   │       │       │   ├── readline
│   │       │       │   │   └── ncurses
│   │       │       │   │       ├── pkg-config
│   │       │       │   │       └── gpatch
│   │       │       │   └── zlib
│   │       │       ├── xz
│   │       │       ├── bzip2
│   │       │       ├── expat
│   │       │       ├── libffi
│   │       │       ├── ncurses
│   │       │       │   ├── pkg-config
│   │       │       │   └── gpatch
│   │       │       ├── unzip
│   │       │       │   └── bzip2
│   │       │       └── zlib
│   │       ├── ncurses
│   │       │   ├── pkg-config
│   │       │   └── gpatch
│   │       └── openssl@1.1
│   ├── jemalloc
│   ├── libev
│   ├── openssl@1.1
│   ├── libxml2
│   │   ├── python@3.9
│   │   │   ├── pkg-config
│   │   │   ├── gdbm
│   │   │   ├── mpdecimal
│   │   │   ├── openssl@1.1
│   │   │   ├── readline
│   │   │   │   └── ncurses
│   │   │   │       ├── pkg-config
│   │   │   │       └── gpatch
│   │   │   ├── sqlite
│   │   │   │   ├── readline
│   │   │   │   │   └── ncurses
│   │   │   │   │       ├── pkg-config
│   │   │   │   │       └── gpatch
│   │   │   │   └── zlib
│   │   │   ├── xz
│   │   │   ├── bzip2
│   │   │   ├── expat
│   │   │   ├── libffi
│   │   │   ├── ncurses
│   │   │   │   ├── pkg-config
│   │   │   │   └── gpatch
│   │   │   ├── unzip
│   │   │   │   └── bzip2
│   │   │   └── zlib
│   │   ├── readline
│   │   │   └── ncurses
│   │   │       ├── pkg-config
│   │   │       └── gpatch
│   │   └── zlib
│   └── zlib
├── openldap
│   ├── openssl@1.1
│   └── util-linux
│       ├── asciidoctor
│       │   └── ruby
│       │       ├── pkg-config
│       │       ├── libyaml
│       │       │   ├── autoconf
│       │       │   │   ├── m4
│       │       │   │   └── perl
│       │       │   │       ├── berkeley-db
│       │       │   │       │   └── openssl@1.1
│       │       │   │       ├── gdbm
│       │       │   │       └── expat
│       │       │   ├── automake
│       │       │   │   └── autoconf
│       │       │   │       ├── m4
│       │       │   │       └── perl
│       │       │   │           ├── berkeley-db
│       │       │   │           │   └── openssl@1.1
│       │       │   │           ├── gdbm
│       │       │   │           └── expat
│       │       │   └── libtool
│       │       │       └── m4
│       │       ├── openssl@1.1
│       │       ├── readline
│       │       │   └── ncurses
│       │       │       ├── pkg-config
│       │       │       └── gpatch
│       │       ├── libffi
│       │       └── zlib
│       ├── gettext
│       │   ├── libxml2
│       │   │   ├── python@3.9
│       │   │   │   ├── pkg-config
│       │   │   │   ├── gdbm
│       │   │   │   ├── mpdecimal
│       │   │   │   ├── openssl@1.1
│       │   │   │   ├── readline
│       │   │   │   │   └── ncurses
│       │   │   │   │       ├── pkg-config
│       │   │   │   │       └── gpatch
│       │   │   │   ├── sqlite
│       │   │   │   │   ├── readline
│       │   │   │   │   │   └── ncurses
│       │   │   │   │   │       ├── pkg-config
│       │   │   │   │   │       └── gpatch
│       │   │   │   │   └── zlib
│       │   │   │   ├── xz
│       │   │   │   ├── bzip2
│       │   │   │   ├── expat
│       │   │   │   ├── libffi
│       │   │   │   ├── ncurses
│       │   │   │   │   ├── pkg-config
│       │   │   │   │   └── gpatch
│       │   │   │   ├── unzip
│       │   │   │   │   └── bzip2
│       │   │   │   └── zlib
│       │   │   ├── readline
│       │   │   │   └── ncurses
│       │   │   │       ├── pkg-config
│       │   │   │       └── gpatch
│       │   │   └── zlib
│       │   └── ncurses
│       │       ├── pkg-config
│       │       └── gpatch
│       ├── ncurses
│       │   ├── pkg-config
│       │   └── gpatch
│       └── zlib
├── openssl@1.1
├── rtmpdump
│   ├── openssl@1.1
│   └── zlib
├── zstd
│   ├── cmake
│   │   ├── sphinx-doc
│   │   │   └── python@3.9
│   │   │       ├── pkg-config
│   │   │       ├── gdbm
│   │   │       ├── mpdecimal
│   │   │       ├── openssl@1.1
│   │   │       ├── readline
│   │   │       │   └── ncurses
│   │   │       │       ├── pkg-config
│   │   │       │       └── gpatch
│   │   │       ├── sqlite
│   │   │       │   ├── readline
│   │   │       │   │   └── ncurses
│   │   │       │   │       ├── pkg-config
│   │   │       │   │       └── gpatch
│   │   │       │   └── zlib
│   │   │       ├── xz
│   │   │       ├── bzip2
│   │   │       ├── expat
│   │   │       ├── libffi
│   │   │       ├── ncurses
│   │   │       │   ├── pkg-config
│   │   │       │   └── gpatch
│   │   │       ├── unzip
│   │   │       │   └── bzip2
│   │   │       └── zlib
│   │   ├── ncurses
│   │   │   ├── pkg-config
│   │   │   └── gpatch
│   │   └── openssl@1.1
│   └── zlib
├── krb5
│   ├── openssl@1.1
│   ├── bison
│   │   └── m4
│   └── gettext
│       ├── libxml2
│       │   ├── python@3.9
│       │   │   ├── pkg-config
│       │   │   ├── gdbm
│       │   │   ├── mpdecimal
│       │   │   ├── openssl@1.1
│       │   │   ├── readline
│       │   │   │   └── ncurses
│       │   │   │       ├── pkg-config
│       │   │   │       └── gpatch
│       │   │   ├── sqlite
│       │   │   │   ├── readline
│       │   │   │   │   └── ncurses
│       │   │   │   │       ├── pkg-config
│       │   │   │   │       └── gpatch
│       │   │   │   └── zlib
│       │   │   ├── xz
│       │   │   ├── bzip2
│       │   │   ├── expat
│       │   │   ├── libffi
│       │   │   ├── ncurses
│       │   │   │   ├── pkg-config
│       │   │   │   └── gpatch
│       │   │   ├── unzip
│       │   │   │   └── bzip2
│       │   │   └── zlib
│       │   ├── readline
│       │   │   └── ncurses
│       │   │       ├── pkg-config
│       │   │       └── gpatch
│       │   └── zlib
│       └── ncurses
│           ├── pkg-config
│           └── gpatch
└── zlib
```

**Comment by Rylan12** [comment]
The current issue only affects macOS, though, right? Do we need the `http` mirrors for Linux too?

**Comment by Bo98** [comment]
It's something that we'd ideally have, but won't be a blocker for now.

**Review by Rylan12 — APPROVED** [review]

**Review by MikeMcQuaid — APPROVED** [review]
Makes sense to me. Would be good to document why e.g. `ca-certificates` doesn't need this.

**Comment by Bo98** [comment]
> Would be good to document why e.g. `ca-certificates` doesn't need this.

It kinda does except we have not found a HTTP mirror.

Though if we go the `--insecure` route then that'll be enough, which I'll document here.

**Comment by MikeMcQuaid** [comment]
> Though if we go the `--insecure` route then that'll be enough for now (only breaking things for those with a _really_ old curl without modern TLS support), which I'll document here.

Gotcha 👍🏻

**Pull request merged**
