### PR TITLE
Format identifiers in oh1

### PR DESCRIPTION
**Pull request by yous**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

I noticed a small inconsistency between `install` and `upgrade` commands. Note that `vim` is green while `gdb` is white.

screenshot 2018-02-09 11 18 06

### CODE REVIEW

**Comment by yous** [comment]
The following test has failed:

```
Failures:

  1) Hbc::Pkg#uninstall removes files and dirs referenced by the pkg
     Failure/Error: pkg.uninstall

     Hbc::CaskCommandFailedError:
       Command failed to execute!

       ==> Failed command:
       /usr/bin/xargs -0 -- /bin/rm --

       ==> Standard Output of failed command:


       ==> Standard Error of failed command:
       rm: /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/plain_file20180209-5238-11t38yz: No such file or directory
       rm: /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/plain_file20180209-5238-1ao8iqt: No such file or directory
       rm: /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/plain_file20180209-5238-1ijvpga: No such file or directory


       ==> Exit status of failed command:
       #<Process::Status: pid 8669 exit 1>
     # ./cask/lib/hbc/system_command.rb:70:in `assert_success'
     # ./cask/lib/hbc/system_command.rb:36:in `run!'
     # ./cask/lib/hbc/system_command.rb:14:in `run'
     # ./test/support/helper/cask/never_sudo_system_command.rb:6:in `run'
     # ./cask/lib/hbc/system_command.rb:18:in `run!'
     # ./cask/lib/hbc/pkg.rb:19:in `uninstall'
     # ./test/cask/pkg_spec.rb:22:in `block (3 levels) in <top (required)>'
     # ./test/support/helper/spec/shared_context/homebrew_cask.rb:40:in `block (2 levels) in <top (required)>'
     # ./test/spec_helper.rb:101:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'

Finished in 5 minutes 50 seconds (files took 3.61 seconds to load)
1129 examples, 1 failure

Failed examples:

rspec ./test/cask/pkg_spec.rb:7 # Hbc::Pkg#uninstall removes files and dirs referenced by the pkg

{"uploaded": true, "queued": true, "message": "Coverage reports upload successfully", "id": "81d6458a-dcf9-453b-9c84-598723f5ff8e", "url": "https://codecov.io/github/Homebrew/brew/commit/02744e506be5a19108c381e1d0407316abb6ae98", "meta": {"status": 200}}
Tests Failed

2243 examples, 1 failure
```

Is this test relevant to the changes? Please let me know if there is something to change.

**Comment by MikeMcQuaid** [comment]
Nice work! That test failure should be unrelated so rereran it. There's a few other uses of `oh1` in `formula_installer.rb` and elsewhere (search for `oh1 "In`) that may not be consistent. Mind taking a look at them too and seeing what you think? After that: we'll merge this. Thanks again!

**Comment by yous** [comment]
I think these cases are intentionally not using `Formatter.identifier` to `formula.full_name`, so I left them.

``` ruby
oh1 "Installing dependencies for #{formula.full_name}: #{deps.map(&:first).map(&Formatter.method(:identifier)).join(", ")}",
  truncate: false
oh1 "Installing #{formula.full_name} dependency: #{Formatter.identifier(dep.name)}"
```

I found few instances in `unpack`, `cask` commands, so I updated them. There are much more `ohai` calls, but no `Formatter.identifier` call inside.

**Comment by MikeMcQuaid** [comment]
Thanks so much for your contribution! Without people like you submitting PRs we couldn't run this project. You rock, @yous!

**Pull request merged**
