### PR TITLE
FAQ: Remove reference to `--enable-bar` that does not exist

### PR DESCRIPTION
**Pull request by heavywatal**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by EricFromCanada** [comment]
`--enable-bar` is a placeholder for a [formula `option`](https://docs.brew.sh/Formula-Cookbook#adding-optional-steps). Instead of removing the line, it should be updated to say `--with-bar` to match the recommended `option` format.

**Comment by heavywatal** [comment]
Thank you for the quick reply. I see, here are my misunderstanding:

- "Bar" is a special term/function in Homebrew system like tap, bottle, and so on. And `--enable-bar` enables it.
- Homebrew stopped supporting formula options long time ago.

Assuming that other users can get confused in a similar way, I would suggest several changes:

- Change "bar" to "foo" because it is much less confusing as a placeholder in the Homebrew context.
- Explicitly say "formula options" not just "options".
- Change "i.e." to "for example" so that users can see it is just an example of giving a formula option.
- Move this item to the bottom of the list. Formula options are not so common now even though they are still supported technically.

**Comment by Bo98** [comment]
> Assuming that other users can get confused in a similar way, I would suggest several changes:
> 
>   * Change "bar" to "foo" because it is much less confusing as a placeholder in the Homebrew context.
> 
>   * Explicitly say "formula options" not just "options".
> 
>   * Change "i.e." to "for example" so that users can see it is just an example of giving a formula option.
> 
>   * Move this item to the bottom of the list. Formula options are not so common now even though they are still supported technically.

Strongly agree with all this. 👍

**Review by Rylan12 — APPROVED** [review]
Thanks, this is definitely a nice clarification!

**Pull request merged**
