### PR TITLE
brew: add `GITHUB_STEP_SUMMARY` to allowlist

### PR DESCRIPTION
**Pull request by woodruffw**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

This just adds another GitHub Actions specific environment variable to the allowlist in `bin/brew`; we hit this one while trying to get `GITHUB_STEP_SUMMARY` generation working in a `brew ruby` invoked script (for `brew-pip-audit`).

### CODE REVIEW

**Comment by woodruffw** [comment]
(cc @alex since he's the one who debugged this)

**Review by alex — APPROVED** [review]

**Comment by woodruffw** [comment]
More generally this could be rewritten to allow all `GITHUB_` variables in the same way that all `HOMEBREW_` variables are allowed, but I figured I'd avoid that more invasive change unless others think it's reasonable.

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks @woodruffw and for review @alex!

> More generally this could be rewritten to allow all `GITHUB_` variables in the same way that all `HOMEBREW_` variables are allowed, but I figured I'd avoid that more invasive change unless others think it's reasonable.

@woodruffw if you have to add more than say 1-2 more after this PR: I'm coming around to that idea, at least when `CI` or `GITHUB_ACTIONS` are set.

**Comment by carlocab** [comment]
> at least when `CI` or `GITHUB_ACTIONS` are set.

I think this is a good idea, though I'd err on wanting them both set, and we should probably also clear `GITHUB_TOKEN`.

**Pull request merged**
