### PR TITLE
Fix installer deleting artifacts if they already exist.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Fixes https://github.com/Homebrew/brew/issues/1785#issuecomment-271378674.

@jeremy, thank you for providing the diff in https://github.com/Homebrew/brew/issues/1785#issuecomment-274380422.

### CODE REVIEW

**Comment by joewiz** [comment]
I can confirm this fixes the bug I reported in https://github.com/caskroom/homebrew-cask/issues/28789 (same as https://github.com/Homebrew/brew/issues/1785). Thanks so much @jeremy and @reitermarkus!

**Comment by monfresh** [comment]
Thanks for fixing this. I started working on this, but I wanted to make sure there was a test for it first since the PR that introduced the bug didn't include tests. I'm curious as to your stance on merging PRs without tests. Is that not something you generally enforce, or did you want to get this out the door first, and then follow up with tests?

I had a very hard time getting the Cask tests to run locally. The only documentation I could find about running tests locally when contributing code was to run `brew tests`, but that command does not run any of the RSpec Cask tests. After digging around some more, I found `brew cask-tests`, but that only runs the tests in `/usr/local/Homebrew`, not in my local forked repo. I tried to figure out how to get `brew tests` to run the RSpec tests but I couldn't get it to work. I stopped there out of frustration last night, and was going to continue today by writing tests in `/usr/local/Homebrew`, making sure they failed, then making them pass, then copy and paste the tests into my local repo so that I could submit a PR.

I also noticed that Travis runs `brew test-bot`, but I couldn't find the file that describes what that runs. Both of these docs link to a nonexistent `test-bot.rb` file:
https://github.com/Homebrew/brew/blob/f8ea328ffdcbc3d0de89187df85f6ee379543a7f/docs/Brew-Test-Bot.md

https://github.com/Homebrew/brew/blob/f8ea328ffdcbc3d0de89187df85f6ee379543a7f/docs/Brew-Test-Bot-For-Core-Contributors.md

I was trying to figure out if Travis runs the RSpec tests or not.

**Comment by alyssais** [comment]
@monfresh to use `brew` commands on your forked repo, you need to use the `bin/brew` executable in that repo.

So you can run the cask tests by `cd`-ing into the `brew` repository you want to use, then running `bin/brew cask-tests`.

**Comment by alyssais** [comment]
@monfresh as a side note: if you want to, you can develop in your `/usr/local/Homebrew` repo. Just add your fork as a remote alongside `Homebrew/brew` and push your changes to it (make sure `Homebrew/brew` stays as `origin` though!).

Let me know if you need any more help. :)

**Comment by monfresh** [comment]
Thanks for the tips!

**Comment by reitermarkus** [comment]
> I'm curious as to your stance on merging PRs without tests. Is that not something you generally enforce, or did you want to get this out the door first, and then follow up with tests?

In this case I think merging this without a test was better than waiting until I have time to write one.

It would be greatly appreciated if you could add a test. 😉

**Pull request merged**
