### PR TITLE
macos_version: add `KERNEL_MAJOR_VERSIONS` map

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

This will be used by `llvm` (and, presumably, in the future, versioned
LLVM formulae). The idea is that we will write a config file for each OS
version pointing to the correct SDKROOT so that `llvm` does not require
rebuilding/reinstalling when a user upgrades to a new major version of
macOS.

See Homebrew/homebrew-core#196094.

### CODE REVIEW

**Comment by Bo98** [comment]
Looks good but maybe we probably expose the API as a function wrapping this constant as it's easier to deprecate etc.

We can probably make it calculated to be honest:

```rb
if version.major == 10
  version.minor + 4
else
  version.major + 9
end
```

**Review by MikeMcQuaid — APPROVED** [review]
Good idea, thanks @carlocab!

**Comment by carlocab** [comment]
> Looks good but maybe we probably should expose the API as a function wrapping this constant as it's easier to deprecate etc.
> 
> We can probably make it calculated to be honest:
> 
> ```ruby
> if version.major == 10
>   version.minor + 4
> else
>   version.major + 9
> end
> ```

Cool, done in 42dd0acdc9ea6f9149b53fe1028e67bb68f653bc.

**Review by MikeMcQuaid — COMMENTED** [review]
Thanks @carlocab!

**Pull request merged**
