### PR TITLE
bump-formula-pr: run audit by default

### PR DESCRIPTION
**Pull request by commitay**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----
Have `bump-formula-pr` run `brew audit` by default with an option to skip the audit.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@commitay Do you think we need the option at all or can it be 💀?

**Comment by commitay** [comment]
It's probably not needed for us with `core` PRs but without it we might break `bump-formula-pr` for people using it in external taps.

**Comment by MikeMcQuaid** [comment]
@commitay What do you think about removing and adding on request? Would rather only keep around options we know we or others are definitely using (and their workflow will need to change with this new option anyway).

**Comment by commitay** [comment]
Their workflow will need to change but I think people should be able to use this without having to make their formulae audit compliant.

**Pull request merged**
