### PR TITLE
Zsh/completion cache for 'brew search' / formulae name

### PR DESCRIPTION
**Pull request by bosr**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Hi, in #5388 @MikeMcQuaid mentioned caching the names of formulae: here is an implementation.

## Cache invalidation for names of formulae
As formulae may be updated anytime, I think it is appropriate to declare the cache file for formulae names as invalid as soon as new commits have been made to the Homebrew working dir. This is what the implementation below does, it simply compares epoch times of the cache file and the latest commit on HEAD in Homebrew working dir. In order to access the working dir, I use `HOMEBREW_PREFIX` and fallback onto `/usr/local` and use this as `--git-dir` option to `git`. Also, I chose to check for commits on HEAD, which normally corresponds to the branch 'stable' for most people (including me). What's your opinion on this?

I conducted the following tests:

- with no existing cache file at ~/.zcompcache/brew_formulae: the cache gets created
- with an invalid cache file (older than latest commit): the cache gets recreated.
- with a valid cache file (newer than latest commit): the cache is simply used and should age indefinitely until new commits.

In the end, it looks like the same cache invalidation semantics can be used for `brew_all_commands()`. If you feel like so, just tell me, I'll merge both cache policies.

## Note
I took the liberty in `__brew_all_commands` to simplify a bit the code that sets the `cache-policy` zstyle circa line 140. In practice the `cache-policy` zstyle must anyway always be set to  `__brew_commands_cache_policy` for the "semantics" to be correct, so I think there is no actual need for the little dance about the zstyle existence. I simply set its value to `__brew_commands_cache_policy` every time, it is more straightforward. 

Are you ok with this? Should this go to a separate PR?

Thanks in advance for your review, cheers!

### CODE REVIEW

**Comment by igas** [comment]
I think cache invalidation should go through multiple repos, as the implementation we have now checks this repo, while formula updates come from https://github.com/Homebrew/homebrew-core and could be from other taps.

**Comment by bosr** [comment]
Thanks @igas, I'll try to think about it. Ideas are welcome!

**Comment by bosr** [comment]
Hmm, I just had a couple of ideas. I really don't know what you think of them.

1. I can get the date of the latest modified formula ('*.rb' file) in all taps with a glob qualifier on a path (this is a list of file, and `(om[1])` simply takes the latest modified):

```shell
local latest_file=$(echo ${HOMEBREW_PREFIX}/Homebrew/Library/Taps/**/*.rb(om[1]))
local latest_date=$(date -r ${latest_file} +%s)
```
but even on my home SSD this takes ~90ms, so I fear it can only get worse for people with many taps or slower systems like mine at work.

2. I can get the date of the latest modified git index *file* in each tap with a glob qualifier:

```shell
local latest_file=$(echo ${HOMEBREW_PREFIX}/Homebrew/Library/Taps/*/*/.git/index(om[1]))
local latest_date=$(date -r ${latest_file} +%s)
```

and this one is fast (8ms on my SSD at home, I'll check at work). To illustrate further, these are the git index files listed on my system:

```
l Homebrew/Library/Taps/*/*/.git/index
-rw-r--r-- 1 bosr admin    257 Jul 20 23:46 Homebrew/Library/Taps/bosr/homebrew-heapusage/.git/index
-rw-r--r-- 1 bosr admin    289 Nov  2 10:03 Homebrew/Library/Taps/go-swagger/homebrew-go-swagger/.git/index
-rw-r--r-- 1 bosr admin  20242 Dec 11 06:54 Homebrew/Library/Taps/homebrew/homebrew-cask-versions/.git/index
-rw-r--r-- 1 bosr admin 356931 Dec 11 06:54 Homebrew/Library/Taps/homebrew/homebrew-cask/.git/index
-rw-r--r-- 1 bosr admin 415804 Dec 11 06:54 Homebrew/Library/Taps/homebrew/homebrew-core/.git/index
-rw-r--r-- 1 bosr admin    401 Jul 21 00:10 Homebrew/Library/Taps/jmespath/homebrew-jmespath/.git/index
-rw-r--r-- 1 bosr admin    497 Jul 21 00:10 Homebrew/Library/Taps/kylef/homebrew-formulae/.git/index
-rw-r--r-- 1 bosr admin    457 Jul 20 23:43 Homebrew/Library/Taps/universal-ctags/homebrew-universal-ctags/.git/index
```

This is clearly a hack, but it could be satisfactory for a completion caching mechanism. An alternative is to invoke git on each repo, but I hardly imagine using 15ms per repo to get the latest HEAD.

Ideas are welcome! Have a great day.

**Comment by MikeMcQuaid** [comment]
> and this one is fast (8ms on my SSD at home, I'll check at work). To illustrate further, these are the git index files listed on my system:

Something like this seems like a good idea 👍

**Comment by bosr** [comment]
Thanks Mike, I’ll update the PR with this later today for anyone to try it. 

Is it ok to rely on HOMEBREW_PREFIX (and fallback on /usr/local)?

Romain

**Comment by MikeMcQuaid** [comment]
@bosr `HOMEBREW_REPOSITORY` and `/usr/local/Homebrew` but: yes.

**Comment by bosr** [comment]
code is updated as discussed, I agree it looks better now. I tested it again as described initially. Thanks for the insights. Tell me if you want me to squash. Cheers.

**Comment by bosr** [comment]
Thanks. If you don't mind, I'd rather replace the 24h completion caching on brew_all_commands (#5388) to this git-index caching.

**Comment by bosr** [comment]
Ok, I fixed some comments. I'm good now. Have a great day!

**Comment by MikeMcQuaid** [comment]
Makes sense to me. Thanks again for another great contribution @bosr!

**Pull request merged**
