### PR TITLE
Livecheck::SkipConditions: Skip versioned casks

### PR DESCRIPTION
**Pull request by samford**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

While working on a versioned cask, I realized that livecheck doesn't automatically skip versioned casks without a `livecheck` block. This is the case for formulae but we don't have a similar `SkipCondition` for casks.

This adds a `Cask#versioned_cask?` method with a similar approach as `Formula#versioned_formula?` and uses it in a new `SkipConditions#cask_versioned` method.

-----

One wrinkle is that casks use a broader type of versioning than formulae. All existing versioned formulae have a numeric @ suffix format like `example@1` or `example@1.2`. Some casks have a similar numeric @ suffix but there are also various others like `@beta`, `@nightly`, etc.

This implementation of `#versioned_cask?` will return `true` for any cask with a `@` in the name, which may or may not make sense for non-numeric suffixes like `@beta`. If it should only return `true` for versioned casks with a numeric @ suffix, I can update how we identify versioned casks.

To be clear, the automatic skip can easily be overridden by adding a `livecheck` block. Of the ~202 `versioned` casks, only four don't have a `livecheck` block and each of those should have one anyway, so this shouldn't be a problem. Edit: I updated these casks to have a `livecheck` block in https://github.com/Homebrew/homebrew-cask/pull/181322, so there aren't any versioned casks without a `livecheck` block now.

### CODE REVIEW

**Comment by bevanjkay** [comment]
In practice, having Casks without a `livecheck` fail audit because the `livecheck` doesn't match causes us to add a skip block or add a functional `livecheck` block.
Does this change still result in there being an audit failure when there is no functional `livecheck`?

**Comment by samford** [comment]
> Does this change still result in there being an audit failure when there is no functional `livecheck`?

Casks that have a skip condition (whether that's one of the detected ones (deprecated, disabled, latest, unversioned) or a `livecheck` block using `#skip`) don't have the livecheck version audited but I could add a special case in the audit for this. The other automatic skip conditions shouldn't be checked but I agree that continuing to make sure that versioned casks are checkable makes sense. Thanks for the reminder.

**Comment by bevanjkay** [comment]
Only tangentially related to this PR.
It's very much likely an edge case, but are there times that a `deprecated` Cask may still receive a security release despite being "discontinued"?
This is probably more likely for "versioned" Casks, which may backport critical fixes.

**Comment by samford** [comment]
> It's very much likely an edge case, but are there times that a `deprecated` Cask may still receive a security release despite being "discontinued"?

It happens sometimes for deprecated formulae/casks but it's a rarity for anything that's deprecated upstream. Usually if there's a possibility of a new version in the future I'll try to wait to remove a `livecheck` block from a deprecated/disabled formula/casks (I periodically review ones that still have a `livecheck` block).

For example, there are a few formulae with a `livecheck` block that have been deprecated/disabled for a reason like `:does_not_build`, so I tend to leave those because there may be a new version in the future that fixes the build issues. [`:unsupported` can also sometimes be a bit subjective, as I've seen it applied to projects that haven't had any activity in a long time but haven't been deprecated upstream. In that scenario there's maybe a non-zero chance of the project becoming active again, unlike something more concrete like `:repo_archived`.]

That said, I think I've seen at least one project where a major version was discontinued, the EOL date passed, and they _still_ pushed out a new version, so anything is possible 🤷

**Review by p-linnane — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
> Generally if there's a possibility of a new version in the future I'll try to wait to remove a `livecheck` block from a deprecated/disabled formula/cask (I periodically review ones that still have a `livecheck` block).

I think we should always avoid removing working livecheck blocks and instead improve tooling to not push updates if that's what we wants. Feels like that's more for `disabled` than `deprecated`, though.

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by samford** [comment]
> I think we should always avoid removing working livecheck blocks and instead improve tooling to not push updates if that's what we wants.

At least for me, removing `livecheck` blocks from deprecated/disabled formulae/casks isn't about avoiding updates if a new version appears, as I'm typically modifying formulae/casks where that isn't a concern. It's just an efficiency thing to avoid unnecessarily checking for new versions in situations where there shouldn't be any.

Similar to my previous comment, I leave the `livecheck` block if there's a reasonable chance that there may be a new version in the future. The ones that are straightforward removals are typically `:repo_archived`/`:repo_removed`, `:deprecated_upstream`, `:discontinued`, `:no_longer_available`, etc.

I'm happy to discuss it further if we need to establish clear guidelines, though.

**Comment by MikeMcQuaid** [comment]
> It's just an efficiency thing to avoid unnecessarily checking for new versions in situations where there shouldn't be any.

I think it'd be better to push that into the `brew livecheck` tool default behaviours rather than removing correct metadata from formulae.



> The ones that are straightforward removals are typically `:repo_archived`/`:repo_removed`, `:deprecated_upstream`, `:discontinued`, `:no_longer_available`, etc.

All but `repo_removed`/`no_longer_available` to me feel like they may change in future.

**Pull request closed without merging**
