### PR TITLE
Cask: rename appcast configuration to must_contain

### PR DESCRIPTION
**Pull request by vitorgalvao**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

`configuration` feels a bit like we can do complicated things in here. `match` is closer to what we’re doing and fits the operation’s name in ruby.

This will require updates to a considerable number of casks, but nothing that can’t be done with a fast script.

Tests *are* failing, but they were already failing before these changes. I’ll have to check if something is wrong with my setup. There were no new failures after these changes, so presuming this is working.

### CODE REVIEW

**Comment by core-code** [comment]
looks good to me. i agree that 'configuration' doesn't nail it, i was never happy with that word. i'm not sure 'match' is perfect either, but it is perhaps closer.

what about "look_for"? :)

**Comment by vitorgalvao** [comment]
> i'm not sure 'match' is perfect either, but it is perhaps closer.

I chose that one because it’s already used in ruby:

```ruby
'this is an example string'.match('example')
```

But we could also go with `includes` (`include`, singular, doesn’t work because it looks like we’re *telling* it to include something). Better?

> <unserious_suggestion>what about "look_for"? :)</unserious_suggestion>

No joke, when I was thinking about this today that was the first alternative that popped into my head.

**Comment by core-code** [comment]
i don't have any good ideas here. basically it should make sense for our contributors (which are probably not Ruby developers). maybe time for a poll? :)

**Comment by vitorgalvao** [comment]
Renamed to `includes`.

@MikeMcQuaid Is the next HB release scheduled for tomorrow? At what time does it usually happen?

**Comment by MikeMcQuaid** [comment]
@vitorgalvao It depends. The next release will be 2.3.0 so need things to stabilise a bit for that.

**Comment by reitermarkus** [comment]
Maybe it should be named `must_include`?

**Comment by vitorgalvao** [comment]
Anyone objects to `lookup`? Short, unambiguous, not used anywhere else.

**Comment by core-code** [comment]
i am fine with all proposals.

**Comment by reitermarkus** [comment]
> Any objections to `lookup`?

Now, obviously I am biased towards my suggestions, but from just looking at `lookup` I am not sure it would be clear to me what this parameter does. 

You can read

```ruby
appcast "https://example.org",
        must_contain: version
```

like a sentence.

**Comment by vitorgalvao** [comment]
Switched to `must_contain`.

**Comment by vitorgalvao** [comment]
I’ll update all casks on the next Homebrew release.

I’ve already tested and this change doesn’t seem to break anything (some CI `appcast` checks will fail for a few moments until the update is done, but that is all). Since this should only be in use in official taps, we’re also not breaking anything for third-parties.

**Pull request merged**
