### PR TITLE
formula_installer: add check for HOMEBREW_RELOCATE_BUILD_PREFIX

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
This should fix the issue reported in https://github.com/Homebrew/brew/issues/13209.  I had not considered that, by design, `--force-bottle` bypasses `compatible_location`, meaning it bypasses the check for `HOMEBREW_RELOCATE_BUILD_PREFIX` being set.  The solution here is simply to check again for `HOMEBREW_RELOCATE_BUILD_PREFIX` in `def pour` before calling `keg.relocate_build_prefix` - this restores the behavior of `--force-bottle` to what it was before.

**Review by carlocab — APPROVED** [review]
I had thought something like this was missing. But now I think some `HOMEBREW_RELOCATE_BUILD_PREFIX` checks are now redundant.

**Comment by danielnachun** [comment]
> I had thought something like this was missing. But now I think some `HOMEBREW_RELOCATE_BUILD_PREFIX` checks are now redundant.

The only other check is in `compatible_locations` in `software_spec`, and it is used to enforce the requirement that the user must set `HOMEBREW_RELOCATE_BUILD_PREFIX` even if their prefix is short enough for patching to work.  If not, bottle pouring is skipped altogether.

I suppose we could have implemented this such that you could only get binary patching if you used `--force-bottle` and had a short enough prefix, but I think that is less convenient for the user.

**Comment by carlocab** [comment]
Marking as critical since this is a bug fix.

**Comment by MikeMcQuaid** [comment]
Tanks @danielnachun!

**Pull request merged**
