### PR TITLE
Revert "Remove usages of HOMEBREW_INSTALL_BUNDLER_GEMS_FIRST"

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Reverts Homebrew/brew#8442 as @rmNULL was running into issues with this.

CC @dawidd6

### CODE REVIEW

**Comment by dawidd6** [comment]
Any details on those issues?

**Comment by sjackman** [comment]
> Any details on those issues?

@rmNULL Can you please provide instructions to reproduce the issue?

**Comment by dawidd6** [comment]
I would really recommend not reverting this as before running `brew audit -h` or `brew audit --skip-style` caused bundler gems installation which is a bad UX in my opinion (also annoying). Instead maybe try to squeeze `install_bundler_gems!` method calls where really needed, as I suppose there are some problems with `patchelf.rb`?

**Comment by rmNULL** [comment]
# steps to reproduce
```
docker run -it --rm homebrew/brew
cd /home/linuxbrew/.linuxbrew/Homebrew
git fetch origin pull/7213/merge:pr7213
git switch pr7213
export HOMEBREW_DEVELOPER=1 HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_PATCHELF_RB_WRITE=1
brew install hello
```


# crash log 
```
rror: You have already activated json 2.1.0, but your Gemfile requires json 2.3.1. Since json is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports json as a default gem.
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/bundler/runtime.rb:319:in `check_for_activated_spec!'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/bundler/runtime.rb:31:in `block in setup'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/bundler/runtime.rb:26:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/bundler/runtime.rb:26:in `setup'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/bundler.rb:107:in `setup'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:186:in `patchelf_patcher'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:114:in `dynamic_elf?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:53:in `block in detect_cxx_stdlibs'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:52:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:52:in `detect_cxx_stdlibs'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cxxstdlib.rb:29:in `check_compatibility'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:1064:in `pour'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:338:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:665:in `install_dependency'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:602:in `block in install_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:602:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:602:in `install_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:309:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:343:in `install_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:262:in `block in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:260:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:260:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:113:in `<main>'
root@2a41bcaff6cb:/home/linuxbrew/.linuxbrew/Homebrew#
```

**Comment by rmNULL** [comment]
@dawidd6 
> install_bundler_gems! method calls where really needed
the issue is despite this being done.

https://github.com/rmNULL/brew/blob/05fd281e38df6b2d56a9866c4876e1f871f1fd9a/Library/Homebrew/os/linux/elf.rb#L187

**Comment by rmNULL** [comment]
> I would really recommend not reverting this cause before, running brew audit -h or brew audit --skip-style caused bundler gems installation which is a bad UX and simply wrong behavior in my opinion (also annoying).

strongly agree.

**Comment by dawidd6** [comment]
Looks a bit unrelated for me. This env var is exported only if audit or style commands are run. There are no more occurrencies in the code. You are simply installing a formula here. Am I missing something?

**Comment by rmNULL** [comment]
> Looks a bit unrelated to me. This env var is exported only if audit or style commands are run. There are no more occurrencies in the code. You are simply installing a formula here. Am I missing something?

It's likely the issue is not related to the commit in question.

quoting @sjackman  
```
I also tried
git fetch origin pull/7213/merge:pr7213
git switch pr7213
git fetch origin pull/8498/head
git cherry-pick 968580dc9419a206805ad03efc05a2af2a07ba3b
export HOMEBREW_DEVELOPER=1 HOMEBREW_PATCHELF_RB_WRITE=1 HOMEBREW_NO_AUTO_UPDATE=1
brew install hello
but it gave the same error Error: You have already activated json 2.1.0, but your Gemfile requires json 2.3.1.
```

**Comment by rmNULL** [comment]
@dawidd6 confirmed, issue is unrelated to this PR.
it is caused by the vendored ruby gem having `json 2.1.0` as its default gem.

`/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/gem update json`
fixes the issue.

**Pull request closed without merging**
