### PR TITLE
Fix analytics_spec.rb test to pass when run from M1

### PR DESCRIPTION
**Pull request by nipunn1313**
On M1 running from a rosetta terminal - the code puts a ", Rosetta" in the analytics string.
Can repro by running from a rosetta emulated terminal (eg alacritty). This fixes it!

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by Rylan12** [comment]
Thanks for the PR!

I think a better way to handle this is to just control for whether or not we're running under Rosetta and test all cases. That way, we're still testing the output to `Utils::Analytics::os_arch_prefix_ci` and not just testing the modifications that we made to the output. Does that make sense?

I made some changes to reflect what I think is best and pushed them as a second commit to this PR. Do they fix your problem? If so, I think something along those lines (even if it's not exactly my changes) is the way we want to go.

If you disagree with the changes, feel free to revert and we can discuss.

**Comment by nipunn1313** [comment]
Yep this looks good to me. Pushed another commit to fix the test in CI (CI includes a ", CI" at the end of the analytics string). That's why the old test used to use "include" instead of "eq" - but this seems even better.

**Review by Rylan12 — APPROVED** [review]
I made one more small modification to fix the test. Can you double-check that `brew tests --only=utils/analytics:9` and `brew tests --only=utils/analytics:9 --generic` work on your machine?

**Comment by nipunn1313** [comment]
yep looks good - works on my machine.
Appreciated!

**Comment by Rylan12** [comment]
Awesome, thanks so much for your first contribution to Homebrew, @nipunn1313!

**Pull request merged**
