### PR TITLE
Set user to linuxbrew in Dockerfile

### PR DESCRIPTION
**Pull request by blankenberg**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
A linuxbrew user is created, so use it.

### CODE REVIEW

**Comment by blankenberg** [comment]
xref https://github.com/Homebrew/brew/pull/5913 https://github.com/Homebrew/brew/pull/5865

**Comment by MikeMcQuaid** [comment]
Thanks @blankenberg but we're making this intentionally `root` because it's more standard in `Dockerfile`s.

**Comment by blankenberg** [comment]
Awesome, following standards is almost always best. 

A sincere thank you for the explanation, and sorry about the extra noise.

**Comment by MikeMcQuaid** [comment]
No apology needed, we appreciate the PR to try and fix the issue ❤️

**Pull request closed without merging**
