### PR TITLE
resource: add reference method for PatchResource

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----
The idea is that comments like "can be removed after X is merged" can be a `reference`, where an audit can check if X is merged/closed/whatever.

### CODE REVIEW

**Comment by Bo98** [comment]
Can you give an example of how you envision this would be used in a formula?

**Comment by SMillerDev** [comment]
It'll allow this version, which we can audit.
```
patch do
  url "https://brew.sh"
  sha256 "something"
  reference "https://github.com/Homebrew/brew/pull/12228"
```
Instead of the current 
```
# remove if https://github.com/Homebrew/brew/pull/12228 is merged
patch do
  url "https://brew.sh"
  sha256 "something"
```

**Comment by SMillerDev** [comment]
Do you see this having value for `formula-patches` patches still? Or do you think I'm just overthinking this?

**Comment by MikeMcQuaid** [comment]
@SMillerDev This DSL specifically? Probably not. Something that solves this problem but for formula-patches and `__END__` patches: yes. Combination of additional metadata in the formula-patches repo with CI and attempts to eliminate `__END__` patches would be worthwhile, I think.

**Pull request closed without merging**
