### PR TITLE
utils/gems: handle mismatching EUID and UID for bundle installs

### PR DESCRIPTION
**Pull request by Bo98**
https://github.com/Homebrew/brew/pull/17178#discussion_r1584341300

### CODE REVIEW

**Comment by Bo98** [comment]
CI failure looks like a Sorbet bug

**Review by carlocab — APPROVED** [review]
Error looks like a sorbet bug.

**Review by MikeMcQuaid — APPROVED** [review]
Looks good when 🟢

**Comment by MikeMcQuaid** [comment]
@Bo98 Nudge on this when you get a bit.

**Comment by Bo98** [comment]
The fix was merged upstream already - just waiting on a release now.

**Pull request merged**
