### PR TITLE
audit: allowlist some formulae homepage cert issues

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----
relates to https://github.com/Homebrew/homebrew-core/pull/60591

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Do these all work in e.g. Safari?

**Comment by chenrui333** [comment]
yeah, it works on safari:
image

allowlist these formula would prevent this PR (https://github.com/Homebrew/homebrew-core/pull/60720), the installation from source still failed for dashing and etc.

**Comment by chenrui333** [comment]
actually this is the url, 
image


we might need to bypass the check for rubydocs as well.

**Comment by chenrui333** [comment]
libpqxx also suffered the issue as well (https://github.com/Homebrew/homebrew-core/pull/61385)

**Pull request merged**
