### PR TITLE
add ALL_PROXY for brew

### LINKED ISSUE #3752: whitelist variable ALL_PROXY
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Tried to install package behind SOCKS proxy using `ALL_PROXY='socks5://proxy:port'` variable
- What happened (include command output)
Curl ignored proxy setting.
- What you expected to happen
Curl respected proxy setting.
- Step-by-step reproduction instructions (by running `brew` commands)
ALL_PROXY='socks5://host:port' brew install 

# Features
Please replace this section with:
- a detailed description of your proposed feature
I propose to add `all_proxy` and `ALL_PROXY` variables to `FILTERED_ENV`.
- the motivation for the feature
so brew can be used behind SOCKS proxy
- how the feature would be relevant to at least 90% of Homebrew users
- what alternatives to the feature you have considered

We will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

### PR DESCRIPTION
**Pull request by xiehuc**
Signed-off-by: xiehuc <xiehuc@gmail.com>

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

i don't know why there just lack ALL_PROXY . 

there a so many tutorial say ALL_PROXY to set socks5 proxy

https://github.com/Homebrew/legacy-homebrew/issues/11114
https://stackoverflow.com/questions/37231204/osx-proxy-issue-with-homebrew-install
https://apple.stackexchange.com/questions/228865/how-to-install-an-homebrew-package-behind-a-proxy

Fixes #3752

### CODE REVIEW

**Comment by scpeters** [comment]
#3752 mentions `all_proxy` as well

**Comment by MikeMcQuaid** [comment]
@xiehuc Please add this to https://github.com/Homebrew/brew/blob/master/Library/Homebrew/manpages/brew.1.md.erb#L242-L256 and run `brew man` and commit the changes.

**Comment by xiehuc** [comment]
no problem at all. i would update later. thank you.

**Comment by xiehuc** [comment]
@MikeMcQuaid done, @scpeters add all_proxy

**Comment by MikeMcQuaid** [comment]
Thanks so much for your contribution! Without people like you submitting PRs we couldn't run this project. You rock, @xiehuc!

**Pull request merged**
