### PR TITLE
dev-cmd/bottle: correct `all` rebuild matching logic

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Fix a small error in the rebuild logic for `all` bottle selection.

### CODE REVIEW

**Comment by carlocab** [comment]
Still broken: Homebrew/homebrew-core@1fabff4e8ec4d72ddda95431511ac4cbfb2b9fb1

**Comment by Bo98** [comment]
Looks like we've exposed a bug that actually also affected the "no bottle changes" logic. I think I know how to fix it.

**Comment by Bo98** [comment]
I've opened a PR to fix, but rebottling should already work to fix the affected formulae.

**Comment by carlocab** [comment]
Ok. I'll retrigger one rebottle to test the `rebuild` logic and then try another when your PR is merged.

**Comment by carlocab** [comment]
Rebottling doesn't work because the checksum didn't change: https://github.com/Homebrew/homebrew-core/runs/4134613251?check_suite_focus=true

**Comment by Bo98** [comment]
Hmm the only real fix for that is to dodge that logic in the test-bot environment - it only really makes sense to do at the upload stage when all bottles are together.

Avoiding `--write` would do that, but someone or something somewhere probably relies on that so maybe we'll need to create a new flag or something to do that.

**Comment by MikeMcQuaid** [comment]
I think we can probably avoid the `all:` behaviour when `--keep-old` is passed, right?

**Pull request merged**
