### PR TITLE
formula: runtime deps of build deps aren't runtime

### LINKED ISSUE #1554: some build-time dependencies recorded as run-time dependencies
CC @alyssais @MikeMcQuaid 

Situation:
A depends on B (and C) at build time.
B depends on C at run time.
Problem:
C is recorded in A's install receipt as a run-time dependency.

Example:
`influxdb` depends on `gdm` at build time and `go` at build time.
`gdm` depends on `go` at run time.
`influxdb`'s install receipt shows `go` as a run time dependency.

```
iMac-TMP:~ joe$ brew install go
==> Downloading https://homebrew.bintray.com/bottles/go-1.7.3.el_capitan.bottle.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/go-1.7.3.el_capitan.bottle.tar.gz
==> Pouring go-1.7.3.el_capitan.bottle.tar.gz
==> Caveats
As of go 1.2, a valid GOPATH is required to use the `go get` command:
  https://golang.org/doc/code.html#GOPATH

You may wish to add the GOROOT-based install location to your PATH:
  export PATH=$PATH:/usr/local/opt/go/libexec/bin
==> Summary
🍺  /usr/local/Cellar/go/1.7.3: 6,438 files, 250.6M
iMac-TMP:~ joe$ brew install --build-bottle gdm
==> Using the sandbox
==> Downloading https://github.com/sparrc/gdm/archive/1.4.tar.gz
==> Downloading from https://codeload.github.com/sparrc/gdm/tar.gz/1.4
######################################################################## 100.0%
==> Cloning https://go.googlesource.com/tools.git
Cloning into '/Users/joe/Library/Caches/Homebrew/gdm--golang.org-x-tools--git'...
remote: Sending approximately 13.02 MiB ...
remote: Total 17266 (delta 11318), reused 17266 (delta 11318)
Receiving objects: 100% (17266/17266), 13.01 MiB | 9.34 MiB/s, done.
Resolving deltas: 100% (11318/11318), done.
==> Checking out revision 6f233b96dfbc53e33b302e31b88814cf74697ff6
==> go build -o /usr/local/Cellar/gdm/1.4/bin/gdm -ldflags -X main.Version=1.4
🍺  /usr/local/Cellar/gdm/1.4: 4 files, 7.4M, built in 6 seconds
iMac-TMP:~ joe$ cat /usr/local/Cellar/gdm/1.4/INSTALL_RECEIPT.json 
{"used_options":[],"unused_options":[],"built_as_bottle":true,"poured_from_bottle":false,"changed_files":null,"time":1479928826,"source_modified_time":1473431244,"HEAD":"c7267b123d38d1c96c2ca786c942255d2417cd86","stdlib":null,"compiler":"clang","runtime_dependencies":[{"full_name":"go","version":"1.7.3"}],"source":{"path":"/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gdm.rb","tap":"homebrew/core","spec":"stable","versions":{"stable":"1.4","devel":null,"head":"HEAD","version_scheme":0}}}iMac-TMP:~ joe$ brew install --build-bottle influxdb
Warning: influxdb-1.1.0 already installed
iMac-TMP:~ joe$ brew uninstall -f influxdb
Uninstalling influxdb... (7 files, 41.3M)
iMac-TMP:~ joe$ brew install --build-bottle influxdb
==> Using the sandbox
==> Cloning https://github.com/influxdata/influxdb.git
Cloning into '/Users/joe/Library/Caches/Homebrew/influxdb--git'...
remote: Counting objects: 541, done.
remote: Compressing objects: 100% (507/507), done.
remote: Total 541 (delta 34), reused 178 (delta 6), pack-reused 0
Receiving objects: 100% (541/541), 1.44 MiB | 0 bytes/s, done.
Resolving deltas: 100% (34/34), done.
Note: checking out '800da5732b91c816b0a097acf8887fa2af1efa1a'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

==> Checking out tag v1.1.0
==> gdm restore
==> go install -ldflags -X main.version=v1.1.0 -X main.commit=800da5732b91c816b0a097acf8887fa2af1efa1
==> Caveats
To have launchd start influxdb now and restart at login:
  brew services start influxdb
Or, if you don't want/need a background service you can just run:
  influxd -config /usr/local/etc/influxdb.conf
==> Summary
🍺  /usr/local/Cellar/influxdb/1.1.0: 7 files, 41.3M, built in 16 seconds
iMac-TMP:~ joe$ cat /usr/local/Cellar/influxdb/1.1.0/INSTALL_RECEIPT.json 
{"used_options":[],"unused_options":[],"built_as_bottle":true,"poured_from_bottle":false,"changed_files":null,"time":1479928981,"source_modified_time":1478906722,"HEAD":"c7267b123d38d1c96c2ca786c942255d2417cd86","stdlib":null,"compiler":"clang","runtime_dependencies":[{"full_name":"go","version":"1.7.3"}],"source":{"path":"/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/influxdb.rb","tap":"homebrew/core","spec":"stable","versions":{"stable":"1.1.0","devel":null,"head":"HEAD","version_scheme":0}}}iMac-TMP:~ joe$ ls /usr/local/Cellar/influxdb/
1.1.0
iMac-TMP:~ joe$ brew uninstall go
Warning: /usr/local/Cellar/go/1.7.3 is required by gdm 1.4, godep 75, govendor 1.0.8, influxdb 1.1.0, packer 0.11.0, packer 0.12.0, syncthing-inotify 0.8.4, the_platinum_searcher 2.1.4, vultr 1.10, which are currently installed.
You can silence this warning with:
  brew uninstall --ignore-dependencies go
Uninstalling /usr/local/Cellar/go/1.7.3... (6,438 files, 250.6M)
iMac-TMP:~ joe$
```

### PR DESCRIPTION
**Pull request by alyssais**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Fixes #1554 (but only for new installations).

@ilovezfs I am fairly sure this will fix the issue you reported, but would be great if you could verify.

### CODE REVIEW

**Comment by ilovezfs** [comment]
I'm AFK so cannot test right now. But if this only works for new installs, I think we may need to use the fallback for everything that already exists and use a new field going forward.

**Comment by MikeMcQuaid** [comment]
> I'm AFK so cannot test right now. But if this only works for new installs, I think we may need to use the fallback for everything that already exists and use a new field going forward.

Yeh, I think we'll need to figure something out for old installs too.

**Comment by alyssais** [comment]
I think we should store in install receipts what version of Homebrew generated them. That way we can just correct behaviour (without introducing a new attribute) and detect whether an install receipt was generated with a buggy version when accessing the data.

**Comment by MikeMcQuaid** [comment]
@alyssais Sounds like a good idea.

**Comment by MikeMcQuaid** [comment]
Thanks again @alyssais!

**Comment by ilovezfs** [comment]
Looks like this PR has caused a bug where it attempts to resolve optional dependencies (with the option not in use for the current build) from other taps that aren't tapped.

Specifically https://github.com/Homebrew/brew/pull/1592/files#diff-b4a6fcb9de3a9163fd8cdac432ad8270R1470.

See https://github.com/Homebrew/homebrew-core/issues/7826.

`brew install -dvs libgroove` reproduces the bug.

@MikeMcQuaid This may need to be reverted and a new tag created to prevent a flood of issues.

**Pull request merged**
