### PR TITLE
Properly fix Git error in tests.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

### CODE REVIEW

**Comment by reitermarkus** [comment]
@MikeMcQuaid, I think I found the right fix. We also need to clear the cache after each `Git` spec, not just before each one.

**Comment by MikeMcQuaid** [comment]
@reitermarkus Thanks, sounds good. Can you also remove the `HOMEBREW_TEST_GENERIC_OS` addition?

**Comment by MikeMcQuaid** [comment]
(or raise an exception in that case instead of unsetting)

**Review by MikeMcQuaid — APPROVED** [review]
Thanks for the change 👏🏻

**Pull request merged**
