### PR TITLE
dev-cmd/contributions: Show only the CSV output for `--csv`

### PR DESCRIPTION
**Pull request by issyl0**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

- This was overly noisy when using `--csv` as it would print both the text output and the CSV output.

### CODE REVIEW

**Review by apainintheneck — APPROVED** [review]
I saw this a few weeks ago too but I assumed it was on purpose. I agree that it's an improvement.

**Comment by issyl0** [comment]
I think I originally did it this way to make it not seem like an eternity gathering the data waiting for the CSV to output.

**Comment by MikeMcQuaid** [comment]
> I think I originally did it this way to make it not seem like an eternity gathering the data waiting for the CSV to output.

personally I preferred the pre-this-PR behaviour for this reason. doing this query for all maintainers produces no output for too long, in my opinion. 

would be nice for a tool heavily used for evaluating maintainer contribution levels by the project leader to wait more than ~2 hours at a weekend before being merged 😉

**Comment by issyl0** [comment]
Sorry! Maybe we could do `.`s instead of the full text, then at least there's _something_ happening? Or just revert this, which I've done in https://github.com/Homebrew/brew/pull/17889.

**Pull request merged**
