### PR TITLE
English language minor corrections in diagnostic.rb

### PR DESCRIPTION
**Pull request by Rezonansowy**
Minor natural language fixes; sticking with US English convention that is predominantly present in the code.

- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
- [X] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [X] Have you successfully run `brew style` with your changes locally?
- [X] Have you successfully run `brew typecheck` with your changes locally?
- [X] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Sorry, passing on this, we intentionally use en_GB as documented in our Prose Guidelines on docs.brew.sh.

**Comment by Rezonansowy** [comment]
@MikeMcQuaid I do not believe that you fully reviewed the commit in my pull request. There were only two changes regarding the American English spelling, and the remaining three changes were to fix blatant English errors that are not specific for US English and are still there. I recall I marked an option “Allowing edits by maintainers”, so you could simply delete those two redundant u letters yourself. Instead, you opted to reject everything, including the changes that were 100% appropriate and had literally nothing to do with en_GB use. Please reconsider.

On a sidenote: Thanks for sharing the Prose Guidelines, but perhaps you should make it really clear it applies to messages printed by the software, as it is not documentation nor “other communications with the Homebrew community”. Right now, it is not clear at all. By the way, I was not aware that UK English is still a thing in a software of modern times.

**Comment by Rezonansowy** [comment]
@MikeMcQuaid I do not believe that you fully reviewed the commit in my pull request. There were only two changes regarding the American English spelling, and the remaining three changes were to fix blatant English errors that are not specific for US English and are still there. I recall I marked an option “Allowing edits by maintainers”, so you could simply delete those two redundant u letters yourself. Instead, you opted to reject everything, including the changes that were 100% appropriate and had literally nothing to do with en_GB use. Please reconsider.

On a sidenote: Thanks for sharing the Prose Guidelines, but perhaps you should make it really clear it applies to messages printed by the software, as it is not documentation nor “other communications with the Homebrew community”. Right now, it is not clear at all. By the way, I was not aware that UK English is still a thing in a software of modern times.

**Comment by MikeMcQuaid** [comment]
> the remaining three changes were to fix blatant English errors that are not specific for US English and are still there

I consider all of these to be personal preference and not errors.

> By the way, I was not aware that UK English is still a thing in a software of modern times.

It is in some software. This software was created by someone from the UK and the project leader and longest-running maintainer (👋🏻) as well as several of our other maintainers live in the UK.

**Pull request closed without merging**
