### PR TITLE
make dependency_order_cop a regular audit

### PR DESCRIPTION
**Pull request by commitay**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
As we're trying to enforce this in PRs, let's make it a regular audit. Currently ≈ 900 formulae need changes to pass this audit, I'll submit the necessary changes to `core` if people are 👍.

### CODE REVIEW

**Comment by colindean** [comment]
s/order/whatever I meant I don't remember parliamentary procedure well enough at this hour/g

**Comment by commitay** [comment]
I'm 👎 on making this strict as it isn't enforced by CI and the autocorrect will make a mess of the existing comments and whitespace that we'll then have to deal with in contributor PRs.

**Comment by DomT4** [comment]
Aye, my line of thought was that we ask people to run `audit --strict` on human-filed PRs, but not command-filed PRs, so we'd reduce the level of violations in core over time without having to jump from almost never enforcing it to absolutely always enforcing it.

For better or worse any change we make here is going to whack external taps as well, if they're using Travis/etc to run CI on themselves, which isn't super-uncommon AFAIK. I'm just a bit jumpy about touching 900 formulae at the same time. That's going to be a huge diff, which introduces the risk of missing any erroneous changes.

I'm not necessarily opposed, just... nervous 😄.

**Comment by commitay** [comment]
> That's going to be a huge diff, which introduces the risk of missing any erroneous changes.

> I'm not necessarily opposed, just... nervous 😄.

Lol. I'm not planning on doing all of them at once. Maybe 50 for so per PR to limit the diff, check everything is fixed and then merge this.

**Comment by commitay** [comment]
TBH, I would like to make this strict and let the community submit fixes but as the autocorrect changes aren't always ... correct, we would need to check more things manually and would also make for very nitpicky PR reviews.

**Comment by commitay** [comment]
https://github.com/Homebrew/brew/pull/4863#issuecomment-421503618

**Pull request merged**
