### PR TITLE
extract: remove bottle blocks

### PR DESCRIPTION
**Pull request by FnControlOption**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Attempting to extract Ghostscript 9.21 gives an error because it has the old bottle sha256 format.

```sh-session
> brew tap-new $USER/local-tap
> brew extract --version=9.21 ghostscript $USER/local-tap
Error: ghostscript: undefined method `[]' for nil:NilClass
```

### CODE REVIEW

**Comment by carlocab** [comment]
Should we just remove the `bottle` block when doing `brew extract`?

**Comment by FnControlOption** [comment]
These lines seem to imply that a bottle block will still work if the formula is extracted to the same tap:

https://github.com/Homebrew/brew/blob/faaa980860b64a6f9496545a56181129b699ed0d/Library/Homebrew/dev-cmd/extract.rb#L186-L187

However, there’s also the Bintray -> GitHub Packages migration to take into account, so maybe it won’t work after all. More research needed.

**Comment by carlocab** [comment]
Yes, the Bintray sunset makes things a bit complicated. If we can point the bottle downloads to @mistydemeo's NAS and somehow provide enough bandwidth it might work. But short of that probably not.

**Comment by FnControlOption** [comment]
```sh-session
> HOMEBREW_DEVELOPER=1 brew extract --version=6.8.13 elasticsearch@6 homebrew/core
==> Searching repository history
==> Writing formula for elasticsearch from revision ca428c3 to:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/elasticsearch@6.8.13.rb
```

```sh-session
> brew fetch elasticsearch@6.8.13    
==> Downloading https://ghcr.io/v2/homebrew/core/elasticsearch/6.8.13/manifests/6.8.13_1
#=#=-#  #                                                                     
curl: (22) The requested URL returned error: 404 
Error: Failed to download resource "elasticsearch@6.8.13_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/elasticsearch/6.8.13/manifests/6.8.13_1
Warning: Bottle fetch failed, fetching the source instead.
==> Downloading https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-6.8.13.tar.gz
########################                                                  34.1%^C
```

Okay, unless the expectation is for the above to work, I think it's reasonable to delete the `bottle` block unconditionally.

**Comment by carlocab** [comment]
It'll probably work if the extracted formula were still named `elasticsearch@6`, but we don't want to have extracted formulae shadowing core formulae.

**Comment by MikeMcQuaid** [comment]
> It'll probably work if the extracted formula were still named `elasticsearch@6`, but we don't want to have extracted formulae shadowing core formulae.

Exactly. The comment (added by me, I think) is wrong.

> Should we just remove the `bottle` block when doing `brew extract`?
> Okay, unless the expectation is for the above to work, I think it's reasonable to delete the `bottle` block unconditionally.

Agreed, just remove 👍🏻

**Review by MikeMcQuaid — APPROVED** [review]
Thanks again @FnControlOption!

**Pull request merged**
