### PR TITLE
set `prefer_loading_from_api: true` for `brew fetch`

### LINKED ISSUE #13088: `brew fetch` returns error when `HOMEBREW_INSTALL_FROM_API` is set
### `brew config` output

```shell
❯ brew config
HOMEBREW_VERSION: 3.4.5-16-gf6ab300
ORIGIN: https://github.com/Homebrew/brew
HEAD: f6ab300fc169777705f025c67c4b7c35605f4a66
Last commit: 22 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f12c912666d30073c11970ad208d62271892ee10
Core tap last commit: 62 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: code -n -w
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.32.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3.1-arm64
CLT: 13.3.0.0.1.1645755326
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

```shell
❯ brew doctor
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

When running `brew fetch` on a Formula or Cask with `HOMEBREW_INSTALL_FROM_API` set and `homebrew/core` (or `homebrew/Cask` not tapped, `brew` returns a Formula not available/Cask not available error.

### What happened (include all command output)?

```shell
❯ HOMEBREW_INSTALL_FROM_API=1 brew fetch --debug node
Error: No available formula with the name "homebrew/core/node".
Please tap it and then try again: brew tap homebrew/core
/opt/homebrew/Library/Homebrew/formulary.rb:371:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:420:in `factory'
/opt/homebrew/Library/Homebrew/formulary.rb:129:in `resolve'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:174:in `resolve_formula'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:167:in `load_formula_or_cask'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:59:in `block in to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:58:in `each'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:58:in `flat_map'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:58:in `to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cmd/fetch.rb:80:in `fetch'
/opt/homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

```shell
❯ HOMEBREW_INSTALL_FROM_API=1 brew fetch --cask --debug firefox
Error: Cask 'firefox' is unavailable: No Cask with this name exists.
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:196:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:205:in `load'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:139:in `load_formula_or_cask'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:59:in `block in to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:58:in `each'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:58:in `flat_map'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:58:in `to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cmd/fetch.rb:80:in `fetch'
/opt/homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

### What did you expect to happen?

I expected the appropriate bottle/installer package to be downloaded. I am preparing to submit a PR to fix this issue but wanted to be sure it's tracked as an issue even if my PR isn't accepted.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew untap homebrew/cask
HOMEBREW_INSTALL_FROM_API=1 brew fetch --cask firefox
```

### PR DESCRIPTION
**Pull request by steveh7812**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----
This is to fix #13088 by passing `prefer_loading_from_api: true` when calling `to_formulae_and_casks`. I am following what I found in `Library/Homebrew/cmd/install.rb` and this solves the issue in my testing; however I know there are larger discussions happening around overall support for `HOMEBREW_INSTALL_FROM_API` so I'm happy to incorporate any additional changes that are needed.

### CODE REVIEW

**Comment by Bo98** [comment]
I'm fine with merging even a partial fix given the situation could change under #12936.

**Comment by Rylan12** [comment]
I'd rather not merge a known bug given that the other PR is still in draft form.

I poked around more and found that the problem is that `brew fetch --deps` fetches _all_ dependencies and `HOMEBREW_INSTALL_FROM_API` only knows how to handle runtime dependencies. We avoid this when running `brew install` by only fetching runtime dependencies. I pushed a commit that modifies the way that `brew fetch --deps` works so that when `HOMEBREW_INSTALL_FROM_API` is set, it will only return runtime dependencies (I think this is fine since building from source with `HOMEBREW_INSTALL_FROM_API` isn't supported). All other cases are unchanged.

**Review by Rylan12 — APPROVED** [review]

**Comment by Bo98** [comment]
> I'd rather not merge a known bug

My point was that it was pre-existing but yes.

> I poked around more and found that the problem is that `brew fetch --deps` fetches _all_ dependencies and `HOMEBREW_INSTALL_FROM_API` only knows how to handle runtime dependencies. We avoid this when running `brew install` by only fetching runtime dependencies. I pushed a commit that modifies the way that `brew fetch --deps` works so that when `HOMEBREW_INSTALL_FROM_API` is set, it will only return runtime dependencies (I think this is fine since building from source with `HOMEBREW_INSTALL_FROM_API` isn't supported). All other cases are unchanged.

Does this overlap with https://github.com/Homebrew/brew/pull/13065 at all?

**Comment by MikeMcQuaid** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @steveh7812!

**Pull request merged**
