### PR TITLE
audit: remove legit version exception

### PR DESCRIPTION
**Pull request by dtrodrigues**
- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?
- [ ] Have you successfully run `brew man` locally and committed any changes?

-----
cc @MikeMcQuaid

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
Thanks for the quick turnaround!

**Comment by dtrodrigues** [comment]
The change to `legit` was merged [prior](https://github.com/Homebrew/homebrew-core/pull/62121) to re-running CI here, so I'm not sure why it's not being picked up.
```
Error: 1 problem in 1 formula detected
legit:
  * Stable: version 1.2.0.post0 is redundant with version scanned from URL
Error: Stable: version 1.2.0.post0 is redundant with version scanned from URL
Error: Process completed with exit code 1.
```

**Comment by MikeMcQuaid** [comment]
@dtrodrigues There's sometimes a slight lag; may be worth retrying now.

**Comment by dtrodrigues** [comment]
Hmm, still didn't work. I'll try again later today.

**Comment by reitermarkus** [comment]
It's merged in `homebrew-core` but not yet in `linuxbrew-core`.

**Pull request merged**
