### PR TITLE
Add donate command

### PR DESCRIPTION
**Pull request by purp**
- [ ✅] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [ ✅] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ✅] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ✅] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [ ✅] Have you successfully run `brew style` with your changes locally?
- [ ✅] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by purp** [comment]
This seemed to work locally, using `brew test-bot` Could someone give a little guidance on how to run a single spec locally or point to a doc that helps me sort that out myself?

Thanks!

**Comment by MikeMcQuaid** [comment]
From the issue:

> It would be a helpful if a brew user wants to donate and can't remember the URL or how to find it.

I think I'd like to see a few more people struggling with this before we add an extra command for this. It's linked prominently on the README and homepage both of which are easy to find. It's also outputted on first install too.

> This seemed to work locally, using `brew test-bot` Could someone give a little guidance on how to run a single spec locally or point to a doc that helps me sort that out myself?

Run `brew tests` and `brew style`; they should point out the errors here.

**Comment by MikeMcQuaid** [comment]
> Run `brew tests` and `brew style`; they should point out the errors here.

(You may want to hold off on this until we've decided whether this PR would be merged).

**Comment by chdiza** [comment]
> It would be a helpful if a brew user wants to donate and can't remember the URL or how to find it.

How would such a user remember (or learn about) the existence of `brew donate`?  Most of the ways of finding this out would also point the user to the relevant URL.

**Comment by purp** [comment]
@MikeMcQuaid: the extra s on tests makes all the difference. Thanks!

I’ll go sort it out because (a) it makes it easier to contribute in the future, and (b) it’ll be here if you ever want it.

@chdiza: I can’t speak to everyone’s experience. My learning of Homebrew was to install it, type `brew help` and start reading and trying. If `brew help commands` had contained donate, it would have put the thought in my head.

**Comment by MikeMcQuaid** [comment]
Passing on this due to the above, sorry @purp! Hope we'll get more contributions from you in future ❤️

**Pull request closed without merging**
