### PR TITLE
fixtures: add test.epub

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Addding a test epub to test epub related formulae.
- https://github.com/Homebrew/homebrew-core/pull/80516

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@chenrui333 Thanks for this! How many formulae would this be for? Is this the smallest possible valid `.epub` file?

**Comment by chenrui333** [comment]
> @chenrui333 Thanks for this! How many formulae would this be for? 

I did not count the formulae, as epub is a very popular book format, it would be very beneficial to add this.

> Is this the smallest possible valid `.epub` file?
Yes, this is 3.76kb smallest epub (content is `Homebrew test`)

**Comment by MikeMcQuaid** [comment]
> Yes, this is 3.76kb smallest epub (content is `Homebrew test`)

Could content be e.g. `b` instead?

> I did not count the formulae, as epub is a very popular book format, it would be very beneficial to add this.

I'd like to see 5+ formulae that need this before we add a multikilobyte fixture.

**Comment by chenrui333** [comment]
> Could content be e.g. `b` instead?

Sure, I will simplify the test to just one char in the content

> I did not count the formulae, as epub is a very popular book format, it would be very beneficial to add this.

Currently, we only have four formulae in the core can benefit from this fixture.
- `docbook-xsl`
- `epr`
- `epubcheck`
- `kepubify`

**Comment by MikeMcQuaid** [comment]
@chenrui333 Cool, I'm fine given those four formulae. Can you squash your commits? Thanks!

**Comment by chenrui333** [comment]
Sure, sounds good. :)

**Comment by MikeMcQuaid** [comment]
Thanks @chenrui333!

**Pull request merged**
