### PR TITLE
fetch: add --bottle-tag flag

### PR DESCRIPTION
**Pull request by dawidd6**
- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

It would be useful for maintainers to be able to easily fetch bottles for different OSes.

Not sure if the implementation itself is fine but it works.

### CODE REVIEW

**Review by Rylan12 — COMMENTED** [review]
This should probably conflict with `--build-from-source` too, right?

**Review by MikeMcQuaid — APPROVED** [review]
Needs the change @Rylan12 mentioned but otherwise looks fine. This will get cleaned by `brew cleanup` but that should be fine. I assume it outputs the correct PATH?

**Comment by dawidd6** [comment]
What do you mean by saying PATH? The famous env variable?

**Comment by carlocab** [comment]
I think Mike means the path to the downloaded bottle, as in the `Downloaded to:` line here:
```
❯ brew fetch hello
==> Downloading https://ghcr.io/v2/homebrew/core/hello/manifests/2.10
Already downloaded: /Users/carlocab/Library/Caches/Homebrew/downloads/93309a1636f67f0f51e2604bb2ece243b5a9324eda1d49e05192ed285af508cd--hello-2.10.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/hello/blobs/sha256:69489ae397e4645127aa7773211310f81ebb6c99e1f8e3e22c5cdb55333f540
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:69489ae397e4645127aa7773211310f81ebb6c99e1f8e3
######################################################################## 100.0%
Downloaded to: /Users/carlocab/Library/Caches/Homebrew/downloads/e0395c201b40d07f50d44b84fccab28bb89bb292929894555688f6510f583a4c--hello--2.10.big_sur.bottle.tar.gz
SHA256: 69489ae397e4645127aa7773211310f81ebb6c99e1f8e3e22c5cdb55333f5408
```

**Review by carlocab — APPROVED** [review]
Works great. 🎉 Thanks @dawidd6!
```
❯ brew fetch --bottle-tag=x86_64_linux hello
==> Downloading https://ghcr.io/v2/homebrew/core/hello/manifests/2.10
Already downloaded: /Users/carlocab/Library/Caches/Homebrew/downloads/93309a1636f67f0f51e2604bb2ece243b5a9324eda1d49e05192ed285af508cd--hello-2.10.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/hello/blobs/sha256:e6980196298e0a9cfe4fa4e328a71a1869a4d5e1d31c38442150ed784cfc0e2
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:e6980196298e0a9cfe4fa4e328a71a1869a4d5e1d31c38
######################################################################## 100.0%
Downloaded to: /Users/carlocab/Library/Caches/Homebrew/downloads/9c334d845e8a08c0d898b81ddd616360ffd4230df01b2ab5f2a61425d19a4bcd--hello--2.10.x86_64_linux.bottle.tar.gz
SHA256: e6980196298e0a9cfe4fa4e328a71a1869a4d5e1d31c38442150ed784cfc0e29
```

**Comment by MikeMcQuaid** [comment]
> What do you mean by saying PATH? The famous env variable?

Apparently @carlocab can understand me even when I talk drivel! I have no idea why I capitalised that 😅

**Pull request merged**
