### PR TITLE
Update `rubocop-cask` to 0.17.3.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Removed accidentally committed debug statement and disabled `Security/Open`.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> Security/Open

FWIW I've found this useful in being explicit about what's being `open`ed.

**Comment by reitermarkus** [comment]
Do you know how to explicitly call `#open` from `OpenURI`?

**Comment by reitermarkus** [comment]
Ok, found it, it's `URI("http://example.com").open`.

**Comment by MikeMcQuaid** [comment]
> Ok, found it, it's URI("http://example.com").open.

That took me annoyingly long to figure out too.

**Pull request merged**
