### PR TITLE
Install brew-cask zsh completions by default

### PR DESCRIPTION
**Pull request by joshka**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
  - not required
- [x] Have you successfully run `brew tests` with your changes locally?
  - not required

-----

Given that `brew-cask` is now part of Homebrew core, it might be nice to have the zsh completion just work out of the box per discussions on https://github.com/Homebrew/brew/pull/407. Similarly, the same could be said about the bash completions.

These commits mirror those in https://github.com/joshka/brew-cask-zsh-completions with modifications to the commit messages to align better with being part of homebrew.

@MikeMcQuaid

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
I'm 🆒 with this but @apjanke @jawshooah @reitermarkus may want to take a look.

**Comment by apjanke** [comment]
Generally 👍 on this, both on pulling `brew cask` completions in to core Homebrew and on how this is coded.

Minor coding note: I think the `_brew_cask` file actually needs a `_brew_cask` invocation at the bottom of the file (after the `_brew_cask()` definition), because it's using the "redefine-on-autoload" trick. Its absence means that nothing will happen the first time you hit tab to invoke completion on `brew cask` in a shell session, because that first invocation just loads the function definitions here. I'll try to test this to verify.

Might have a migration issue here: users who already have `brew-cask-zsh-completions` installed will have a symlink at the location where we're going to drop this file, so the update might fail. Might be few enough of them we should just go ahead with it and deal with the breakage; I don't know of a good easy migration mechanism.

**Comment by joshka** [comment]
@apjanke you might also like to take a look at https://github.com/Homebrew/brew/pull/951

I'll take a look at the two issues you raised later tonight or tomorrow. Thanks :)

**Comment by joshka** [comment]
I think that problems with having `brew-cask-zsh-completions` installed is likely fairly minimal exposure as https://github.com/Homebrew/homebrew-completions/pull/135 is not merged, so that project hasn't been installed automatically by anyone.

**Comment by apjanke** [comment]
Cool. In that case, I think this is ready to ship.

**Pull request merged**
