### PR TITLE
Move superenv? into the ENV namespace.

### PR DESCRIPTION
**Pull request by woodruffw**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

I'm not sure if exposing `superenv?` outside of the `ENV` namespace was intentional, but moving it into `ENV` makes things slightly clearer. 

cc @sjackman for thoughts/confirmation that this fixes your problem.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Not thrilled with this since we're deprecating stdenv anyway.

**Comment by sjackman** [comment]
My use case was a formula (`scipy`) that breaks if `FFLAGS` is set to any value at all, so my intended fix was:
```ruby
ENV["FFLAGS"] = nil unless ENV.superenv?
```

Bikeshedding: I think the name `ENV.super?` is perhaps a better name than the somewhat redundant `ENV.superenv?`

**Comment by ilovezfs** [comment]
>My use case was a formula (scipy) that breaks with --env=std if FFLAGS is set to any value at all

That's not a supported use case ...

**Comment by woodruffw** [comment]
> Not thrilled with this since we're deprecating stdenv anyway.

That's fair. 

@sjackman Can `FFLAGS` just be cleared out without adverse effect on superenv? If so, it might make sense to just unconditionally clear it.

**Comment by MikeMcQuaid** [comment]
Yeh, I'm 👎 on this personally; I don't think it should be information available in formulae and https://github.com/Homebrew/brew/pull/1753 is going to help address this. Until then I'd say unconditional `ENV.delete("FFLAGS")` is your best bet.

**Comment by woodruffw** [comment]
Got it, closing this.

**Comment by sjackman** [comment]
Linuxbrew has superenv now (not default yet, but coming) so my use case isn't going to be around long.

**Pull request closed without merging**
