### PR TITLE
rubocops: Allow `resource` blocks to include `on_*` blocks or conditionals

### PR DESCRIPTION
**Pull request by issyl0**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

- This was split out of #15060 because of [this comment](https://github.com/Homebrew/brew/pull/15060#issuecomment-1484167482).
- https://github.com/Homebrew/homebrew-core/pull/126705/commits/d2a58a7853e0581ceb80ab38e3244d1969fd2907 was deemed "unwiedly", but it passes the RuboCop.
- https://github.com/Homebrew/homebrew-core/pull/126705#discussion_r1148558613 is more wieldy, but needed RuboCop tweaks.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> Allow resource blocks to include on_* blocks or conditionals

Can we pick one and enforce it rather than allowing both?

**Comment by MikeMcQuaid** [comment]
@carlocab want to talk more here based on my reasoning?

**Comment by carlocab** [comment]
Ah, I already replied in the Homebrew/core PR: https://github.com/Homebrew/homebrew-core/pull/126705#discussion_r1149545828

> Well, if we have to pick one it'll be the on_* blocks. I hate them here, but I'll live.

("here" means in the `go` formula)

**Comment by MikeMcQuaid** [comment]
> > Well, if we have to pick one it'll be the on_* blocks. I hate them here, but I'll live.
> 
> ("here" means in the `go` formula)

@carlocab why do you hate them? not looking to argue, just learn 😁

**Comment by issyl0** [comment]
I prefer the blocks too. But I opened this for discussion!

**Pull request closed without merging**
