### PR TITLE
utils/bottles: fix fetching Linux bottles on macOS

### LINKED ISSUE #17375: `brew fetch --os=linux` fails on macOS
### `brew doctor` output

```shell
❯ brew dr
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.3.2-14-g44d0d64
ORIGIN: https://github.com/Homebrew/brew
HEAD: 44d0d64e79895b51064ff3ba670de126f463825e
Last commit: 2 hours ago
Core tap HEAD: 94c4a182ae09dd52d5a66da66eaedb9b3074967b
Core tap last commit: 41 minutes ago
Core tap JSON: 13 May 09:28 UTC
Core cask tap HEAD: 70bf2608ea401e809be79cd0191b092c6705c415
Core cask tap last commit: 30 minutes ago
Core cask tap JSON: 13 May 09:26 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_AUTO_UPDATE_SECS: 43200
HOMEBREW_BAT: set
HOMEBREW_BOOTSNAP: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_DEVELOPER: set
HOMEBREW_EDITOR: nvim
HOMEBREW_FORCE_BREWED_CURL: set
HOMEBREW_FORCE_BREWED_GIT: set
HOMEBREW_GIT_EMAIL: 30379873+carlocab@users.noreply.github.com
HOMEBREW_GIT_NAME: Carlo Cabrera
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_NO_CLEANUP_FORMULAE: zsh
HOMEBREW_NO_INSTALL_FROM_API: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.1 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/bin/ruby
CPU: 16-core 64-bit arm_palma
Clang: 15.0.0 build 1500
Git: 2.45.1 => /opt/homebrew/opt/git/bin/git
Curl: 8.8.0 => /opt/homebrew/opt/curl/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false
```

### What were you trying to do (and why)?

I was trying to fetch the Linux bottles for OpenBLAS while trying to debug a formula build issue. 

### What happened (include all command output)?

```
❯ brew fetch --os=linux openblas
Error: Calling `MacOS.version` on Linux is disabled! There is no replacement.
Please report this issue:
  https://docs.brew.sh/Troubleshooting
❯ brew fetch --os=linux --arch=intel openblas
Error: Calling `MacOS.version` on Linux is disabled! There is no replacement.
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

### What did you expect to happen?

I expected `brew` to download the Linux bottle.

### Step-by-step reproduction instructions (by running `brew` commands)

On macOS:
```shell
brew fetch --os=linux openblas
```

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Closes #17375.

Not quite certain if this is the right fix, but it makes the reported
error go away.

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
This seems fine as a stop-gap but ideally this `require` override would only apply in this case rather than on Linux.

Feels like another solution could be to `raise` on the `require` instead.

**Comment by Bo98** [comment]
> This seems fine as a stop-gap but ideally this `require` override would only apply in this case rather than on Linux.
> 
> Feels like another solution could be to `raise` on the `require` instead.

This PR seems consistent with the current deprecation, which does a check on `simulating_or_running_on_linux?`.

I reckon it should either:
* Remove the `simulating_or_running_on_linux?` check in `os/mac.rb` and then there will be no need to check `simulating_or_running_on_macos?`; or
* Keep the `simulating_or_running_on_linux?` check in `os/mac.rb` but then add the `simulating_or_running_on_macos?` check here

Doing one thing in one file and one thing in another would be odd.

**Comment by carlocab** [comment]
> I reckon we should either:
> 
> * Remove the `simulating_or_running_on_linux?` check in `os/mac.rb` and then there will be no need to check `simulating_or_running_on_macos?` in `extend/os/mac/utils/bottles.rb`; or
> * Keep the `simulating_or_running_on_linux?` check in `os/mac.rb` but then add the `simulating_or_running_on_macos?` check in `extend/os/mac/utils/bottles.rb`
> 
> This PR currently does the latter option, though I reckon the former would make sense.

Could you elaborate on what the former looks like? Feel free to push to this branch.

**Comment by Bo98** [comment]
Former approach is deleting https://github.com/Homebrew/brew/blob/92adf6a0b71e59d3348c982d11e2560dc9317687/Library/Homebrew/os/mac.rb#L29. It still achieves the os/linux hack deprecation as that's handled separately: https://github.com/Homebrew/brew/blob/92adf6a0b71e59d3348c982d11e2560dc9317687/Library/Homebrew/os/linux.rb#L61

**Review by MikeMcQuaid — COMMENTED** [review]
I think https://github.com/Homebrew/brew/pull/17396 may make more sense instead

**Pull request closed without merging**
