### PR TITLE
Docs: Migrate casks FAQ

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?
- [ ] Have you successfully run `brew man` locally and committed any changes?

-----
First attempt at migrating https://github.com/Homebrew/homebrew-cask/tree/HEAD/doc/faq now that there is just a single brew command. I haven't changed any content, I just moved file content around.

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by vitorgalvao** [comment]
I’ve noticed some things I’d like to change, but that’s a later PR.

The FAQ is kind of big with everything in one file. How about we change it to use `<details>` on every question? Though again, that can be a later PR.

**Review by vitorgalvao — APPROVED** [review]

**Comment by SMillerDev** [comment]
> The FAQ is kind of big with everything in one file. How about we change it to use <details> on every question?

I don't think brew.sh supports that (and it has pretty good search)

**Comment by vitorgalvao** [comment]
> I don't think brew.sh supports that (and it has pretty good search)

For a moment I was really confused! I though you were talking about the shell file, not the website.

**Comment by MikeMcQuaid** [comment]
Thanks both!

**Pull request merged**
