### PR TITLE
OS::Mac::Version: add Big Sur

### PR DESCRIPTION
**Pull request by mistydemeo**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by vinkla** [comment]
There are multiple reports that macOS Big Sur is a major bump:

- https://twitter.com/stroughtonsmith/status/1275150531154108417
- https://twitter.com/thecomputerclan/status/1275135276298493952

**Comment by Bo98** [comment]
There seems to be an inconsistency, with some references to 10.16 in the installers.

We will go by whatever `/usr/bin/sw_vers -productVersion` returns, if someone is able to check that.

**Comment by claui** [comment]
More evidence:

https://developer.apple.com/design/human-interface-guidelines/macos/overview/whats-new-in-macos/

**Comment by Bo98** [comment]
Yet we have not registered _any_ 11.0 in our analytics at all and there is still a large amount of the OS internally calling itself 10.16 (see: installer, Xcode Intel-only builds). We will go by `sw_vers` so if someone shows it returns 11.0 then we'll change it here.

**Comment by Bo98** [comment]
Ok just checked up on this.

I'm told that for Intel this change is correct and `sw_vers` reports 10.16, but for Apple Silicon it reports 11.0. I suppose we can make this a conditional on `Hardware::CPU.intel?`/`Hardware::CPU.arm?`.

**Comment by mistydemeo** [comment]
I expect that we will see this unify with time, but we're still in very early days for this release. We'll continue to update our code as we see the OS solidify.

**Comment by Geekiac** [comment]
The output from sw_vers on my MacBookPro gives:

ProductName:    macOS
ProductVersion: **11.0.1**
BuildVersion:   20B29

**Pull request merged**
