### PR TITLE
docs: reference `rpath` directory

### PR DESCRIPTION
**Pull request by kthchew**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

`rpath` was added as a new method to `formula.rb` in #11187, but as far as I can tell, it wasn't added to the documentation. I've added a reference to it in this PR.

### CODE REVIEW

**Review by carlocab — CHANGES_REQUESTED** [review]
I don't think this is the right place to document this, as `rpath`, isn't exactly a directory location.

It doesn't match the rest of the table syntactically either: everything else in this table is an instance of `Pathname`; `rpath` is just a `String`.

**Comment by kthchew** [comment]
> I don't think this is the right place to document this, as `rpath`, isn't exactly a directory location.
> 
> It doesn't match the rest of the table syntactically either: everything else in this table is an instance of `Pathname`; `rpath` is just a `String`.

Oh, that's logical. I took another look, and couldn't see a clear place to put this information where it fit well. Do you think that a new subsection about setting the rpath in the "advanced formula tricks" section in the formula cookbook would make more sense?

**Comment by carlocab** [comment]
> Do you think that a new subsection about setting the rpath in the "advanced formula tricks" section in the formula cookbook would make more sense?

Possibly. Do you see other places it could be used (possibly in external taps) other than the formulae listed in https://github.com/Homebrew/homebrew-core/issues/75458? If you do, then this could be a good idea, though I'd want to think more about where to put it in the docs. If not, then I don't mind leaving this undocumented.

It would be good to have documentation for `shared_library` as well:

https://github.com/Homebrew/brew/blob/3e327626079e22f4becebb26b632ad431400105e/Library/Homebrew/formula.rb#L1526-L1536

And could be documented in the same place as `rpath`.

**Comment by kthchew** [comment]
> Do you see other places it could be used (possibly in external taps) other than the formulae listed in [Homebrew/homebrew-core#75458](https://github.com/Homebrew/homebrew-core/issues/75458)?

Hmm, I only really have experience with homebrew-core and no external taps, so I’m not sure I’m really qualified to give a good opinion on this. I’m not aware of any, though.

To be honest, when I made this PR I missed the rubydocs, so I failed to notice rpath there. I think that if it’s there, then the current documentation is probably okay, so I’ll close this for now (unless you have a different opinion).

**Pull request closed without merging**
