### PR TITLE
Check dependency order in on_system methods

### PR DESCRIPTION
**Pull request by FnControlOption**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
    https://github.com/Homebrew/homebrew-core/pull/107194
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

`brew audit` should check `depends_on` order in `on_linux` and co.

`homebrew/core/hurl` has:

```rb
  on_linux do
    depends_on "openssl@1.1"
    depends_on "pkg-config" => :build
  end
```

but it should be:

```rb
  on_linux do
    depends_on "pkg-config" => :build
    depends_on "openssl@1.1"
  end
```

### CODE REVIEW

**Review by Rylan12 — COMMENTED** [review]
Thanks, @FnControlOption! Good catch!

A test for this would be great, if possible!

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Great work as usual @FnControlOption!

**Comment by MikeMcQuaid** [comment]
(this PR is just waiting for homebrew-core to get fixed up so `tap_syntax` will pass)

**Review by Rylan12 — APPROVED** [review]
Fantastic! Thanks again, @FnControlOption!

**Pull request merged**
