### PR TITLE
Allow `JAVA_HOME` in formulae depending on `openjdk`.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@reitermarkus I reckon we'll probably end up killing JavaRequirement instead and automagically setting some of this stuff internally.

**Comment by reitermarkus** [comment]
> end up killing JavaRequirement

We'll need to get rid of `depends_on :java => "1.8"` for that first. OpenJDK 8 cannot be build on any macOS version we support.

**Comment by MikeMcQuaid** [comment]
> We'll need to get rid of `depends_on :java => "1.8"` for that first. OpenJDK 8 cannot be build on any macOS version we support.

That's annoying. For versions >1.8: what do you think about flipping the default?

**Comment by reitermarkus** [comment]
For `1.8+` I think we can change most formulae to depend on the `openjdk` formula directly.

**Comment by MikeMcQuaid** [comment]
@reitermarkus I guess a question for @Homebrew/maintainers users will be if it's annoying/surprising to have us do this given those folks are likely to already have the Cask installed. I'm probably on the "maybe but it's worth it for a simpler installation process in the long term" side.

**Comment by SMillerDev** [comment]
Will it remove the cask? Because having 2 Java installs without warning seems potentially confusing to me.

**Comment by MikeMcQuaid** [comment]
@SMillerDev It won't auto-remove the cask but we could add some messaging on how to do so.

**Comment by reitermarkus** [comment]
I was planning on removing the `java`/`openjdk` casks at least. But I'd say let's first get some formulae depending on the `openjdk` formula.

**Comment by MikeMcQuaid** [comment]
> I was planning on removing the `java`/`openjdk` casks at least.

I think @SMillerDev means "uninstalling" rather than "removing from the homebrew-cask repo".

**Comment by fxcoudert** [comment]
I'm not a heavy java user, but I think a lot of people have java already installed through other means… so that's a downside to make Homebrew depend on `openjdk` for all things Java.

**Comment by SMillerDev** [comment]
Could the duplicate Java thing be checked in `brew doctor` or something maybe? I'm not entirely sure what would be best. I just know I'd be confused to have 2 java installs without prior notice

**Comment by MikeMcQuaid** [comment]
Doesn't seem like something that needs to be a failure as they may have reasons for both and need both (as we won't give them a choice). Could be in caveats (or something noisier), though.

**Comment by reitermarkus** [comment]
Merging this now so I can get started on some PRs.

**Pull request merged**
