### PR TITLE
bug.yml: remind users to `brew update` twice

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

The autoupdate that happens with `brew install` doesn't switch users
properly over to GitHub Packages from Bintray for some reason, so
there's a need to do it twice to migrate properly.

See, for example https://github.com/Homebrew/brew/issues/11155, https://github.com/Homebrew/homebrew-core/issues/75243.

### CODE REVIEW

**Comment by Bo98** [comment]
It shouldn't be necessary to run the explicit `brew update` twice. The issue is with the implicit auto-update only.

I think we should do either (or both):

* Add a workaround in `brew.sh` to unset `HOMEBREW_BOTTLE_DOMAIN` if `HOMEBREW_BOTTLE_DEFAULT_DOMAIN` is already set (which it will be in the auto-update process) and is equal to `HOMEBREW_BOTTLE_DOMAIN`.
* Fix bottle domain fallbacks - I'll get a PR for this shortly.

**Comment by carlocab** [comment]
> It shouldn't be necessary to run the explicit `brew update` twice. The issue is with the implicit auto-update only.

I know. However, users seem to think the auto-update is a substitute for `brew update`, when it's not.

It seems simpler to just ask them to do it twice, rather than make what's written here longer (and thus more tempting to ignore) with a proper explanation.

**Review by Rylan12 — APPROVED** [review]
I agree that this shouldn't be necessary but that it's a good idea to have in the template just in case.

**Comment by MikeMcQuaid** [comment]
> I think we should do either (or both):
> 
> * Add a workaround in `brew.sh` to unset `HOMEBREW_BOTTLE_DOMAIN` if `HOMEBREW_BOTTLE_DEFAULT_DOMAIN` is already set (which it will be in the auto-update process) and is equal to `HOMEBREW_BOTTLE_DOMAIN`. Unfortunately, such workaround would probably remain for many years.
> * Fix bottle domain fallbacks - I'll get a PR for this shortly.

I'd prefer we do this than add it to the template.

**Comment by carlocab** [comment]
> I'd prefer we do this than add it to the template.

Fine with me. I do still think this wording is more likely to get users to try to reproduce their issue after doing `brew update` at least once, but I suppose this also makes it harder to diagnose bugs in `brew update` or auto-update.

**Comment by carlocab** [comment]
Maybe not needed anymore. Closing.

**Pull request closed without merging**
