### PR TITLE
doctor: list any uncommitted modified files in CI

### PR DESCRIPTION
**Pull request by EricFromCanada**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
When `doctor` finds modified files, print a list of them.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Suggestion for discussion: don’t print the list if HOMEBREW_DEVELOPER is set.

**Comment by MikeMcQuaid** [comment]
> Suggestion for discussion: don’t print the list if HOMEBREW_DEVELOPER is set.

Or would that have meant this didn't show up where needed e.g. in CI?

**Comment by EricFromCanada** [comment]
The idea is to give a hint as to what's going on when CI starts failing on this check. So, it could instead just print the first few lines and say to check `git status` for the rest.

**Comment by MikeMcQuaid** [comment]
> The idea is to give a hint as to what's going on when CI starts failing on this check. So, it could instead just print the first few lines and say to check `git status` for the rest.

What about scoping the extra bits to just `ENV["CI"]`?

**Comment by EricFromCanada** [comment]
> What about scoping the extra bits to just `ENV["CI"]`?

Done; have a look.

**Comment by MikeMcQuaid** [comment]
Made a tiny tweak but great work again @EricFromCanada, merged!

**Pull request merged**
