### PR TITLE
ARGV#resolved_formulae: also load build options

### PR DESCRIPTION
**Pull request by xu-cheng**
This fixes the problem that `brew audit foo` complains that
an optional dependency is undeclared.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
👍

**Comment by DomT4** [comment]
I don't want to er, annoy you here, but this still fails on `if build.with?` dependencies 🙈.

```ruby
  depends_on "pcre" => :optional
  depends_on "gettext" => :optional
  depends_on "openssl" if build.with? "brewed-openssl"
  depends_on "curl" if build.with? "brewed-curl"
  depends_on "go" => :build if build.with? "persistent-https"
```

```
git:
  * Formulae are required to declare all linked dependencies.
    Please add all linked dependencies to the formula with:
      depends_on "curl" => :linked
      depends_on "openssl" => :linked
Error: 1 problem in 1 formula
```

**Comment by xu-cheng** [comment]
@DomT4 that would be a known issue due to the usage of `if` for deps declaration

**Comment by DomT4** [comment]
So should we ignore it or should those become:
```ruby
depends_on "curl" => :linked if build.with? "brewed-curl"
```
I presume ignore it, but ❓

**Comment by ilovezfs** [comment]
Yeah this is still pretty broken:
```
iMac-TMP:Homebrew joe$ brew audit --strict vifm
vifm:
  * Formulae are required to declare all linked dependencies.
    Please add all linked dependencies to the formula with:
      depends_on "atk" => :linked
      depends_on "cairo" => :linked
      depends_on "gdk-pixbuf" => :linked
      depends_on "gettext" => :linked
      depends_on "glib" => :linked
      depends_on "pango" => :linked
Error: 1 problem in 1 formula
```
triggered by
```
  depends_on "gtk+" => :optional

  if build.with? "gtk+"
    depends_on "pkg-config" => :build
    depends_on "atk" => :linked
    depends_on "cairo" => :linked
    depends_on "gdk-pixbuf" => :linked
    depends_on "gettext" => :linked
    depends_on "glib" => :linked
    depends_on "pango" => :linked
  end
```

>@DomT4 that would be a known issue due to the usage of if for deps declaration 

"Known" or not, it would be nice to at least have a plan of some kind for fixing it.

**Comment by xu-cheng** [comment]
@ilovezfs The only solution is to work on `option "with-foo" do ... end` DSL. As far as I'm aware no one is working on that.

**Comment by xu-cheng** [comment]
Although, it's possible to workaround it by rewriting `ARGV` during formula loading. However, that would be a short-term hack and won't solve everything.

**Comment by ilovezfs** [comment]
The fact that you can explicitly follow the audit directions and still not be able to get the audit error to go away is going to be ... confusing I suspect, or people will just add the linked outside of the `if build.with?` which would be even worse. :see_no_evil:

**Comment by ilovezfs** [comment]
Perhaps this particular audit check should be skipped if the local install receipt indicates something other than a default build.

**Comment by xu-cheng** [comment]
@ilovezfs Well, FYI, this long term bug has caused much worse issues than just `audit` result. For example, it affects the some basic function of `FormulaInstaller`.

**Comment by ilovezfs** [comment]
Since CI will spit out the correct answer, I'm not sure why we'd tell people to run audit locally in the PR template if the output is known to be wrong.

**Comment by MikeMcQuaid** [comment]
We can always `grep` the actual formula text if we're in `audit` for this case to try and produce a better output.

**Comment by ilovezfs** [comment]
@MikeMcQuaid This was @UniqMartin's response when I suggested something similar in another scenario https://github.com/Homebrew/homebrew-core/pull/2253#issuecomment-227665702

Not sure if the same objections apply here or not.

**Comment by MikeMcQuaid** [comment]
@ilovezfs We already have audits that do that and as long as the overhead isn't too high I'm cool with it, personally.

**Pull request closed without merging**
