### PR TITLE
create: Use Parser to parse args

### PR DESCRIPTION
**Pull request by GauthamGoli**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
#1860

And also move `FormulaCreator` class inside Homebrew module

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> And also move FormulaCreator class inside Homebrew module

@GauthamGoli How about moving it to another file instead? e.g. `Library/Homebrew/formula_creator.rb`?

**Comment by GauthamGoli** [comment]
@MikeMcQuaid moved it to a separate file.

**Comment by MikeMcQuaid** [comment]
Thanks again @GauthamGoli!

**Comment by GauthamGoli** [comment]
@mikemcquaid this is the last of the developer commands. Next up are the built-in commands :)

**Comment by MikeMcQuaid** [comment]
@GauthamGoli Woohoo, nice work 👏

**Comment by MikeMcQuaid** [comment]
@GauthamGoli Although another option would be to work on e.g. generating the manpage and `--help` text for developer commands first? Thoughts?

**Comment by GauthamGoli** [comment]
Yeah I agree. Its better to work on it now, rather than leave it toward the end.

**Pull request merged**
