### PR TITLE
audit.rb: require https for ftpmirror.gnu.org

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

The situation is similar to other mirror redirectors: the server
may subsequently redirect to an insecure url. But it's a step.

### CODE REVIEW

**Comment by DomT4** [comment]
Crumbs, this actually works now, I wasn't sure GNU were ever going to pull the trigger on this.

This isn't quite complete though, you'll want to remove the block starting at L1142 & tweak the URL on L1138. We may also want to update our manpage to highlight GNU formula will now fail with `HOMEBREW_NO_INSECURE_REDIRECT` set.

**Comment by vszakats** [comment]
I'm going to look into these. FWIW the new https server appears to be lagging a bit yet, but it seems to work anyhow.

**Comment by DomT4** [comment]
Yeah, it's almost 100% slower it seems on head requests at times. Jump from 0.5 seconds to 1 second isn't something most people are likely to notice though.

**Comment by vszakats** [comment]
Updates done.

**Comment by MikeMcQuaid** [comment]
👍

**Comment by DomT4** [comment]
I'd be tempted to go with `some GNU & GNOME based` rather than `ftpmirror.gnu.org` in the manpage. I'm not sure URLs are the friendliest way to express these things to users.

**Comment by vszakats** [comment]
I've been thinking about this as well. Will revisit this in a few hours when back to a keyboard.

**Comment by vszakats** [comment]
Committed now anyway. For anything more, I'll be back a bit later.

**Comment by UniqMartin** [comment]
:+1:

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/brew/commit/6bd24a7fb806184d401ee98e1f8c82d97f813107. Thanks for spotting this @vszakats, and your contribution to Homebrew 😃.

**Pull request merged**
