### PR TITLE
 Use “squiggly” heredocs.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [ ] Have you successfully run `brew tests` with your changes locally?

### CODE REVIEW

**Comment by ilovezfs** [comment]
This feels like we're replacing something self-explanatory with an emoji.

**Comment by MikeMcQuaid** [comment]
There's some CI failures but I'm broadly 👍 to this. I'm not in love with the syntax but it's standard Ruby at this point so we may as well use it rather than our own custom stuff.

Also, please create a Homebrew/homebrew-core PR for the corresponding change there before this gets merged.

**Comment by commitay** [comment]
@reitermarkus Do casks need to be changed to be more "squiggy"?

**Comment by reitermarkus** [comment]
@commitay, yes, ideally.

**Comment by MikeMcQuaid** [comment]
Thanks @reitermarkus!

**Comment by ilovezfs** [comment]
@reitermarkus hmm I'm having trouble getting anything to trigger a you-must-use-squiggly-heredocs errors from `brew style` or `brew audit --strict`.

```
iMac-TMP:Homebrew joe$ brew config
HOMEBREW_VERSION: 1.3.6-26-g6fe7c5f-dirty
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6fe7c5fc9576b1368a17c1c7f426d4511ac736cd
Last commit: 26 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 792c96ee94ec44cd6c8e832193978924f53d7592
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 8.0 build 800
Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.2/bin/ruby
Java: 9.0.1, 1.8.0_151, 1.7.0_154-zulu-7.20.0.3
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
iMac-TMP:Homebrew joe$ git diff
diff --git a/Library/Homebrew/cmd/link.rb b/Library/Homebrew/cmd/link.rb
index 5afb19e..effcab7 100644
--- a/Library/Homebrew/cmd/link.rb
+++ b/Library/Homebrew/cmd/link.rb
@@ -29,12 +29,12 @@ module Homebrew
       keg_only = keg_only?(keg.rack)
       if HOMEBREW_PREFIX.to_s == "/usr/local" && keg_only &&
          keg.name.start_with?("openssl", "libressl")
-        opoo <<~EOS
-          Refusing to link: #{keg.name}
-          Linking keg-only #{keg.name} means you may end up linking against the insecure,
-          deprecated system OpenSSL while using the headers from Homebrew's #{keg.name}.
-          Instead, pass the full include/library paths to your compiler e.g.:
-            -I#{HOMEBREW_PREFIX}/opt/#{keg.name}/include -L#{HOMEBREW_PREFIX}/opt/#{keg.name}/lib
+        opoo <<-EOS
+        Refusing to link: #{keg.name}
+        Linking keg-only #{keg.name} means you may end up linking against the insecure,
+        deprecated system OpenSSL while using the headers from Homebrew's #{keg.name}.
+        Instead, pass the full include/library paths to your compiler e.g.:
+          -I#{HOMEBREW_PREFIX}/opt/#{keg.name}/include -L#{HOMEBREW_PREFIX}/opt/#{keg.name}/lib
         EOS
         next
       elsif keg.linked?
iMac-TMP:Homebrew joe$ brew style
Inspecting 661 files
.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

661 files inspected, no offenses detected
iMac-TMP:Homebrew joe$ 
```
Ditto with formulae.

**Comment by reitermarkus** [comment]
It won't trigger because `<<-EOS` is not the same as `<<~EOS`. I think it will trigger on `<<-EOS.unindent` or `<<-EOS.strip_indent`, both of which we weren't using before.

**Comment by ilovezfs** [comment]
Neither of those triggers it either.

**Comment by reitermarkus** [comment]
Weird.

**Comment by ilovezfs** [comment]
@reitermarkus http://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Layout/IndentHeredoc seems to imply that it should be triggering on <<-EOS

**Comment by reitermarkus** [comment]
I think it only triggers on 

```ruby
<<-EOS
not indented
EOS
```

**Comment by ilovezfs** [comment]
@reitermarkus see the `opoo` above which is exactly that. https://github.com/Homebrew/brew/pull/3319#issuecomment-338274424

**Comment by reitermarkus** [comment]
Above it is indented 8 spaces.

**Pull request merged**
