### PR TITLE
cli/parser: chomp '=' from comma_array flag name

### PR DESCRIPTION
**Pull request by dawidd6**
`brew bump-formula-pr` help message:

Before:

```
        --mirror=                    Use the specified URL as a mirror URL. If
                                     URL is a comma-separated list of URLs,
                                     multiple mirrors will be added.
```

After:

```
        --mirror                     Use the specified URL as a mirror URL. If
                                     URL is a comma-separated list of URLs,
                                     multiple mirrors will be added.
```

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
What's the advantage of dropping the `=`?

**Comment by dawidd6** [comment]
Visual consistency with other flags in the help message. That's it I guess.

**Comment by MikeMcQuaid** [comment]
Interested in @GauthamGoli and @EricFromCanada's thoughts.

**Comment by EricFromCanada** [comment]
Unlike a `switch` which does not take an argument, a `flag` requires an argument only if defined with a trailing `=`, which it [removes later](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cli/parser.rb#L111). The question for `comma_array` is, since it always requires an argument, should it always be defined with a trailing `=`, or should it be optional and just removed during parsing? I'd say the latter, which this PR implements, and I'd also say the `=` should be dropped from [bump-formula-pr](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/bump-formula-pr.rb#L43) (requiring a run of `brew man`).

**Comment by GauthamGoli** [comment]
Agree with @EricFromCanada.  
`=` is used to differentiate between Optional and Required `flag` args, `comma_array` does not need that differentiation.

**Comment by MikeMcQuaid** [comment]
Thanks again @dawidd6!

**Pull request merged**
