### PR TITLE
workflows: use GITHUB_TOKEN when checking license

### PR DESCRIPTION
**Pull request by jonchang**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

This should avoid errors from rate limited API calls when using hosted runners.

### CODE REVIEW

**Comment by Bo98** [comment]
Hmm, if there's going to be potential API errors then maybe me relying on `--fail-if-changed` will be a bad idea. I guess we should have `--success-if-changed` or something.

**Comment by jonchang** [comment]
Ah, to be clear, it's not an API error, just rate limiting from not using an authenticated API call. See https://github.com/Homebrew/brew/runs/881647497?check_suite_focus=true#step:12:8 for what I mean.

**Comment by Bo98** [comment]
Sure, though I don't trust GitHub uptime.

**Comment by jonchang** [comment]
If GitHub is down we'd probably have problems in addition to the rate limited test 😅

**Pull request merged**
