### PR TITLE
Exclude sorbet assignments from Style/MutableConstant cop

### PR DESCRIPTION
**Pull request by dduugg**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
We can't do anything about these violations, and the `rubocop:disable` comments are a bit of an eyesore. How would folks feel about excluding such patterns from the `Style/MutableConstant` cop instead? (If folks are amenable, I can then flesh this out with tests and such.)

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

**Review by MikeMcQuaid — APPROVED** [review]
Approach makes sense to me, thanks!

**Comment by Bo98** [comment]
Good idea: though might be worth considering upstreaming this to rubocop-sorbet which also has a `Style/MutableConstant` extension? `T::Enum` is another case (though not one used by Homebrew/brew yet).

**Comment by dduugg** [comment]
> Good idea. Though might be worth considering upstreaming this to rubocop-sorbet which also has a `Style/MutableConstant` extension? `T::Enum` is another case (though not one used by Homebrew/brew yet).

Great suggestion, I've opened https://github.com/Shopify/rubocop-sorbet/pull/256
I don't understand the `T::Enum` case (I've only used it as a superclass), so I didn't include a pattern for that one.

**Comment by Bo98** [comment]
> Great suggestion, I've opened [Shopify/rubocop-sorbet#256](https://github.com/Shopify/rubocop-sorbet/pull/256) I don't understand the `T::Enum` case (I've only used it as a superclass), so I didn't include a pattern for that one.

See https://github.com/Homebrew/ci-orchestrator/blob/f643ab875fbd9695072333fe2de17c98eb98cd8a/src/priority_type.rb as an example

**Comment by dduugg** [comment]
Closing this, pending outcome of upstream PR

**Pull request closed without merging**
