### PR TITLE
Revert "Merge pull request #10880 from Bo98/cli-stronger-types"

### LINKED ISSUE #10906: `brew uses --installed` causes error about `appdir`
### `brew config` output

```shell
> % brew config
HOMEBREW_VERSION: 3.0.8-10-g555e936
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 555e9365f913b4099a036cd889e27a4d28b6a580
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 29a6d7d9c921dafaf2ff595655df391993ea69c2
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.zonYmET1lo/org.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 12.0 build 1200
Git: 2.31.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
```

### `brew doctor` output

```shell
> % brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  archivemount

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/pspdev/bin/psp-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  qt
  glew

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

Check which installed formulae use a formula, so I can deal with the results. 

A few warnings exist in my `brew doctor` but do not appear to be pertinent. 

### What happened (include all command output)?

`brew uses <formula>` works as expected. `brew uses --installed <formula>` produces an error. 

```
> % brew uses xmlto
shared-mime-info
> % brew uses --installed xmlto
Error: CLI arg for `appdir` is not declared for this command
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cli/args.rb:147:in `method_missing'
/usr/local/Homebrew/Library/Homebrew/cask/config.rb:45:in `from_args'
/usr/local/Homebrew/Library/Homebrew/cmd/uses.rb:96:in `intersection_of_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uses.rb:74:in `uses'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

### What did you expect to happen?

It work; not error. 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew uses --installed <formula>
```

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Just in case we need it.

Fixes #10906.

This reverts commit 25373a18cc6c529243558be6f67401f1e4100a30, reversing
changes made to a045cd7a614246a2debc537e9cd406ab55316743.

### CODE REVIEW

**Comment by carlocab** [comment]
Not sure why `git` thought I was reverting a045cd7a614246a2debc537e9cd406ab55316743. I'm pretty sure I'm reverting the other parent, 8e98ce69f39cf014f63195ed880d3f445c905757.

**Comment by Bo98** [comment]
It was somewhat expected there would be breakages. It's why I wanted to wait for a new tag first.

#10908 will fix the error reported in #10906.

**Comment by carlocab** [comment]
Nice. I'll just leave this here just in case, but I don't expect that it'll need to be merged.

**Comment by carlocab** [comment]
Don't think this will be needed anymore.

**Pull request closed without merging**
