### PR TITLE
cmd/shellenv: improve for newer macOS using `/usr/libexec/path_helper`

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

On macOS 14 and newer, `/usr/libexec/path_helper` supports setting a
`PATH_HELPER_ROOT` environment variable.

With this set, `path_helper` checks `$PATH_HELPER_ROOT/etc/paths` and
`$PATH_HELPER_ROOT/etc/paths.d` in the same way it checks `/etc/paths`
and `/etc/paths.d`.

We can use this to simplify management of the user's `PATH` variable
when they do `brew shellenv`. In particular, if their system supports
it, we delegate setting the `PATH` environment variable to `path_helper`
instead of our own code. We also write a default `etc/paths` file if one
is not already present.

This is nicer because it simplifies management of the user's `PATH`
variable. For example, if a user wants a keg-only formula to be in their
`PATH`, they can simply add the necessary path to `etc/paths` or
`etc/paths.d` without having to do something like `brew link --force`
or adding to `PATH` themselves.

When `/usr/libexec/path_helper` is not available, we just fall back to
the existing code.

### CODE REVIEW

**Comment by carlocab** [comment]
Note that this doesn't work for Fish or Powershell. Will try to think a bit more about handling those cases.

**Review by MikeMcQuaid — APPROVED** [review]
Great idea, this makes sense to me, thanks @carlocab! Let's give this ~24h before merging to get some other opinions in here.

**Comment by carlocab** [comment]
CC @Homebrew/brew for thoughts here, especially for Fish and Powershell.

**Comment by MikeMcQuaid** [comment]
> Great idea, this makes sense to me, thanks @carlocab! Let's give this ~24h before merging to get some other opinions in here.

It's been >24 hours so: 🚢, thanks @carlocab!

**Pull request merged**
