### PR TITLE
linkage_checker: deprecate libnsl.so.1 linkage

### PR DESCRIPTION
**Pull request by Bo98**
This is a trickier one as we're far too late deprecating this (I did not know it was going to be removed from our Glibc formula) so really should be disabling this by now...

Interested in thoughts on what the deprecation schedule should look like here.

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
Yeh, let's do this now and land 3.6.0 sooner rather than later.

**Comment by MikeMcQuaid** [comment]
👍🏻 to ship this ASAP for 3.6.0 (once CI passing)

**Comment by Bo98** [comment]
Ok looks like `libnsl.so.1` still exists in our glibc so backwards compatibility of bottles not a concern. What's removed is `libnsl.so` and `libnsl.a` which means compiling against libnsl (`-lnsl`) no longer works - i.e. some builds from source might fail with our glibc. So I think it's still worth deprecating but it's not broken like libcrypt.so.1.

So the regular deprecation schedule of disabling this in 3.7.0 should be fine.

**Comment by MikeMcQuaid** [comment]
@Bo98 👍🏻 to 🚢 from me when CI is passing and merge conflicts resolved.

**Review by MikeMcQuaid — APPROVED** [review]

**Pull request merged**
