### PR TITLE
CI: use actions/cache@v3

### LINKED ISSUE #14692: [CI] Stop using deprecated Actions params
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

GitHub are deprecating `set-output`, `save-state` in favour of "Environment Files". 

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### What is the motivation for the feature?

Reducing noise in the "Checks" view on a PR.

Screenshot 2023-02-17 at 16 32 19

### How will the feature be relevant to at least 90% of Homebrew users?

It won't, but it'll reduce cognitive load for maintainers seeing these warnings.

### What alternatives to the feature have been considered?

Leave them and let our Actions break in June 2023.

### PR DESCRIPTION
**Pull request by DestroyerXyz**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

fixes #14692
~~I can't confirm if these changes work as they are related to cache which I can't test in my fork.~~

### CODE REVIEW

**Comment by DestroyerXyz** [comment]
It can't find the cache for some reason it seems
Checking this out

**Comment by DestroyerXyz** [comment]
Seems to work fine now
Learned that GitHub cache was scoped to a branch so just force-pushed the same commit again to use the newly created cache.

**Comment by MikeMcQuaid** [comment]
CI is failing: https://github.com/Homebrew/brew/actions/runs/4206541156/jobs/7300184415#step:2:12

**Comment by DestroyerXyz** [comment]
These failures are very weird.
I didn't make any changes related to them.

**Comment by Bo98** [comment]
GitHub appears to be having some issues right now. I'll retry the failing ones where needed.

**Comment by scpeters** [comment]
> GitHub appears to be having some issues right now. I'll retry the failing ones where needed.

the following issue report seems related: https://github.com/Homebrew/actions/issues/333

**Comment by Bo98** [comment]
Yeah I'm working on it

**Comment by DestroyerXyz** [comment]
any updates on this?

**Comment by Bo98** [comment]
Can you rebase on the latest master? Should be good then.

**Review by carlocab — APPROVED** [review]
LGTM

**Review by issyl0 — APPROVED** [review]
Thank you so much for this contribution to Homebrew, @DestroyerXyz!

**Comment by issyl0** [comment]
We changed some CI jobs in the time between this PR and now. Would you be able to rebase on our latest `master` again please @DestroyerXyz so that all the pending yellow checks run?

**Comment by DestroyerXyz** [comment]
@issyl0 Done and all CI passing

**Review by nandahkrishna — APPROVED** [review]
Thanks, @DestroyerXyz!

**Pull request merged**
