### PR TITLE
Docs: improve deprecation doc

### PR DESCRIPTION
**Pull request by iMichka**
The current documentation:
- contains a lot of text
- is sometimes unclear (or at least you need to re-read it carefully multiple times)

Using a diagram feels more appropriate.

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Review by MikeMcQuaid — CHANGES_REQUESTED** [review]
Sorry, strongly oppose making this a diagram.

These SVG/PNG diagrams bitrot super quickly and don't get updated (as we saw with the Brew Test Bot flowchart recently).

If we want it to be a diagram: it should be something like Mermaid  that can be edited/searched/linted as text: https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

**Comment by reitermarkus** [comment]
What is the difference between “Does not have an open source license” and “the project has no license”? The latter implies the former, no?

I tried to [convert it to Mermaid](https://mermaid.live/edit#pako:eNp9VF1v2jAU_StXeQKpTEyVJo2HVZRYaiQaKpLysDFFbnwp0RI7sp12rO1_33VCgATUPKBwP84591w7b16qBHoTb5Or13TLtYXYX0ugx2cPSzabxmzgY6kx5Ra_DPepIJrezimRGf6UH8JLdr9YscESC_VSB5vwPJixMKJqhQYyA1v-gsAlqBIlGFXpFCHPUpQp3gw7LTAa_XiX6n2P3AJOZzP2EDcKakwLBaIFggKeplhapwo2ShdVziHVmUWd8Rb82H6G79LN74oto2ARMv9XUBO8oDaZkihufvcKapAdmr7Ku2mUkIcs9FkYR_3pdyCQ5hcobaur23DQdr9YsiS-m4bJ1_F47NCb8m68i18ojWC3ZLLLgVCvMldcUIGE7_Sf70zL2oUh1lHNul-xn1y3fMfIIKiZRLN94YwGbiFHbixcE7m02wP-se3cqAt5x_2TLRdJEEbxdD6PjgN3wofN1_P-Q61oNmN5ntdD2i2dKSenN20H4yhoL-KytbUnTVl7Jfzk28GWk1hrTHtfetaY7G_fnJPmC2oultTbOQkm4WIwgOHhut0-BnP_6M9TleUClASyBkxVlko7YWXOrbsgF6UQpKPaQ52ztlSzFestQlWWliBFJp9d9lN0130ydB-cXJgtwjgIH5k_aC4hnbiU_MtkRRNUpbEaefEZxSnGRSrvyitQFzwT9A18c0Brj85OgWtvQq-C6z9rby0_qI5XVkU7mXoTqyu88qpS0Ir9jD9rXniTDc8NfvwH99qeTg
):

```mermaid
flowchart TD
    DEPRECATE(Deprecate.)
    DISABLE(Disable.)
    REMOVE(Remove.)

    LICENSE(Does is have an open source licence?)
    LICENSE -->|no| REMOVE

    ACCEPTABLE(Does it meet our acceptable formula criteria?)
    ACCEPTABLE -->|no| REMOVE
    
    VERSIONED[Is it versioned?]
    VERSIONED -->|yes| REMOVE

    HAS_DEPENDENTS(Does is have any dependent?)
    HAS_DEPENDENTS -->|no| MORE_THAN_1000


    MORE_THAN_1000(Does is have more than 1000 downloads in 90 days?)
    MORE_THAN_1000 ---|no| DISABLED_3

    DISABLED_3(Is is disabled for at least 3 months?)
    DISABLED_3 -->|yes| REMOVE
    DISABLED_3 -->|no| ZERO_INSTALLS


    ZERO_INSTALLS(Does it have zero installs in the last 90 days?)
    ZERO_INSTALLS -->|yes| DISABLE

    MORE_THAN_1000 ---|yes| DEPRECATED_6

    DEPRECATED_6(Is is deprecated for at least six months?)
    DEPRECATED_6 -->|yes| DISABLE
    DEPRECATED_6 -->|no| DEPRECATED_6_NO(( ))

    BUILDS(Does it build on all supported platforms?)
    DEPRECATED_6_NO --> BUILDS -->|no| DEPRECATE

    CVES(Does it have outstanding CVEs?)
    DEPRECATED_6_NO --> CVES -->|yes| DEPRECATE

    DISCONTINUED(Is it discontinued upstream?)
    DEPRECATED_6_NO --> DISCONTINUED -->|yes| DEPRECATE
```

**Comment by p-linnane** [comment]
> What is the difference between “Does not have an open source license” and “the project has no license”? The latter implies the former, no?

A project may be relicensed to something like BUSL or Elastic, which are not open source licenses, but they are still licensed.

**Comment by reitermarkus** [comment]
> A project may be relicensed to something like BUSL or Elastic, which are not open source licenses, but they are still licensed.

Yes, but “no license” still implies “no open source license”, right? So either way would be straight to removal.

**Comment by bevanjkay** [comment]
If the license changes we can continue using the previous bottles that were shipped under the open-source license, and we go down the deprecate lifecycle.
If an existing formula is found to have no license/an unsuitable license (on the tag that the bottles were built from) then it would be disabled immediately.

**Comment by reitermarkus** [comment]
So, this?

```mermaid
flowchart TD
  A(Does it have a suitable license?) -->|no| B
  B(Does it have a previous version with a suitable license?)
  B -->|no| C(Disable.)
  B -->|yes| D(Deprecate.)
```

**Comment by p-linnane** [comment]
> Yes, but “no license” still implies “no open source license”, right? So either way would be straight to removal.

It can. Currently taking "no license" to mean that the formulae literally has no license at all. We've been slowly working on correcting that over the last few months though and have been removing things that do not have a discoverable license.

**Comment by p-linnane** [comment]
> Do we even have formulae that do not currently have an open source license and also didn't previously?

We can deprecate if the license changes to something not open source. If we have no license in a formula, and can't find one, it should be outright removed immediately.

**Comment by iMichka** [comment]
Good idea to use mermaid for this. I'm going to update it with the latest comments.

This doc will end up on https://docs.brew.sh, do we have mermaid integration there?

**Comment by MikeMcQuaid** [comment]
> This doc will end up on [docs.brew.sh](https://docs.brew.sh), do we have mermaid integration there?

Not by default, it seems, looks like it needs some extra work to get it rendering.

**Comment by reitermarkus** [comment]
There is `jekyll-spaceship` which supports rendering Mermaid.

**Comment by EricFromCanada** [comment]
That isn't in the list of [supported plugins for GitHub Pages](https://pages.github.com/versions/), so including it would require some [additional effort](https://github.com/jeffreytse/jekyll-spaceship?tab=readme-ov-file#additions-for-unlimited-github-pages).

**Comment by iMichka** [comment]
> Also, any gem expert here? The default `bundle exec jekyll serve` command I ran to get the page up and running locally asked for the `webrick` dependency, though it was not declared as necessary before.

I see @EricFromCanada fixed it that here https://github.com/Homebrew/rubydoc.brew.sh/pull/615. I guess we need to fix this in this repo too?

**Comment by MikeMcQuaid** [comment]
> I see @EricFromCanada fixed it that here [Homebrew/rubydoc.brew.sh#615](https://github.com/Homebrew/rubydoc.brew.sh/pull/615). I guess we need to fix this in this repo too?

Yup 👍🏻

**Pull request closed without merging**
