### PR TITLE
Minute documental changes

### PR DESCRIPTION
**Pull request by ItsAdityaKSingh**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Added a few missing commas and changed verbs at a few places for better documentation.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Passing on this, this adds a bunch of Oxford commas which we don't use in Homebrew (https://docs.brew.sh/Prose-Style-Guidelines#typographical-conventions)

**Comment by ItsAdityaKSingh** [comment]
Should I remove the commas and apply only the verb changes?

**Comment by MikeMcQuaid** [comment]
@ItsAdityaKSingh I don't think they improve the readability so: no, I wouldn't bother, sorry.

**Comment by ItsAdityaKSingh** [comment]
Sure :)

**Pull request closed without merging**
