### PR TITLE
Fix `brew cleanup`.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

This fixes the regex to properly parse the version and to also match resources and patches. 

Fixes https://github.com/Homebrew/brew/issues/4650.

### CODE REVIEW

**Comment by chdiza** [comment]
I just tried this, and it doesn't fix all of the problem, and also introduces a new one.

(1) The list of things output by `cleanup -n` is still duplicated.

(2) It now lists resources for formulas that I have installed and are not outdated.  For example, it wants to delete the patch associated with `libtiff` and also "ghostscript fonts".

**Comment by chdiza** [comment]
OK, that fixed what was mentioned in the last comment, but now `cleanup` wants to delete a non-outdated source tarball that it hadn't previously complained about.

Prior to the most recent commit in this PR, `cleanup` erroneously wanted to delete `foo--resource1--3.2.tar.bz2`, `foo--resource2--1.0.tar.bz2`, and so forth.  Now this is fixed.  `cleanup` no longer wants to delete those.  But instead, it now wants to delete the main `foo` source tarball.  If it matters, the tarball name is of the form `foo--2.9.1-1.tar.bz2`.

**Comment by reitermarkus** [comment]
Which formula has the `foo--2.9.1-1.tar.bz2` format?

**Comment by chdiza** [comment]
> Which formula has the foo--2.9.1-1.tar.bz2 format?

One in my custom tap.

**Comment by reitermarkus** [comment]
I can't really debug this without an actual formula to test this with.

**Comment by reitermarkus** [comment]
@chdiza, can you try again?

**Comment by chdiza** [comment]
I'll check it it an hour or so when I'm at the relevant machine.

Might be worth noting that the formula `foo` has an explicit `version` declared.   Also that this declared version ("2.2.9-1") is different from the version that's embedded in the name of the tarball as it appears in the `url` argument (`foo--2.2.9.tar.bz2`).

**Comment by chdiza** [comment]
> Might be worth noting that the formula foo has an explicit version declared. Also that this declared version ("2.2.9-1") is different from the version that's embedded in the name of the tarball as it appears in the url argument (foo--2.2.9.tar.bz2).

This is exactly what was going on.  I made up a different silly formula that has this property, and installed it.  `cleanup` then tried to delete the main tarball but correctly left the `resource` alone.  The formula is pasted below.


```ruby
class Foo < Formula
  desc "Fzf"
  homepage "https://github.com/junegunn/fzf"
  url "https://github.com/junegunn/fzf-bin/releases/download/0.17.4/fzf-0.17.4-darwin_386.tgz"
  version "2.2.9-1"
  sha256 "e3147b1e471c5d4fcab774cb79d880f4dc6fb88ec7217cab6c397f85af10f541"

  # The real package requires `go` and other crap to build.

  resource "sourceball" do
    url "https://github.com/junegunn/fzf/archive/0.17.4.tar.gz"
    sha256 "a4b009638266b116f422d159cd1e09df64112e6ae3490964db2cd46636981ff0"
  end

  def install
    resource('sourceball').stage do
      man1.install "man/man1/fzf.1"
    end

    bin.install "fzf"
  end
end
```

**Comment by chdiza** [comment]
> @chdiza, can you try again?

With the latest change, the problem has disappeared.

However, there is still one thing that I think should be fixed.  `cleanup` now is deleting lock files, which I guess is fine (but what happens if the user runs `cleanup` while a build is underway?).  The problem is that the output of `cleanup` has the lockfiles and the tarballs/old kegs all mixed together in no real order.  E.g., 

```
Would remove: /stuff/brache/browser--7 (419B)
Would remove: /usr/local/var/homebrew/locks/foo.formula.lock (0B)
Would remove: /stuff/brache/jpeg--9c.high_sierra.bottle.tar.gz (297.6KB)
```

This is just a snippet of longer output.  What *should* happen is that `cleanup` displays all the lockfiles first (or last).   Otherwise, it is VERY easy to visually overlook a tarball or old keg in the list, because they are obscured by the noise of the lockfiles.  This makes it difficult for the user to see which tarballs and old kegs are going to be deleted when she runs `cleanup -n`.

**Comment by reitermarkus** [comment]
> `cleanup` now is deleting lock files

It did that before too, but it wasn't shown in the output. `cleanup` will try to lock the lockfile, and only then delete it.

**Comment by chdiza** [comment]
> They are ordered alphabetically by the formula name: browser, foo, jpeg

That's a bad idea, for the reason described above.

**Comment by chdiza** [comment]
The output should look like this:
```
...browser.formula.lock
...foo.formula.lock
...jpeg.formula.lock
...browser_tarball
...foo_tarball
...jpeg_old-keg
...jpeg_tarball
```
or else show all the lockfiles at the end.

Otherwise (especially if the list is long) it's hard to see which tarballs or old kegs are going to be deleted, because they get lost in the lockfile noise.

**Comment by reitermarkus** [comment]
@chdiza, I moved the lockfile cleanup to the top now.

**Comment by chdiza** [comment]
> I moved the lockfile cleanup to the top now.

OK, seems to be working well now, thanks.  I'll keep an eye on things in the coming weeks to see if there are any other oddball cases.

**Pull request merged**
