### PR TITLE
Include a donation link in the Analytics readme

### PR DESCRIPTION
**Pull request by kevinburke**
It's reasonable to ask users who benefit from a project being free, but also
value their privacy, to make a donation to the project. It also helps people
who would like to make a donation figure out how to do so.

### CODE REVIEW

**Comment by UniqMartin** [comment]
Thank you for the suggestion, but I have mixed feelings about that. While I think it would be great if more users donated to the project to “compensate” for not helping in other ways, I'd personally prefer if we didn't conflate these things. To me, suggesting to donate in case of opt-out sounds a bit like pressuring users into making a donation, which doesn't sound very nice.

I'm sure other maintainers also have (different) opinions on that, so I'll leave it open for discussion.

**Comment by kevinburke** [comment]
I don't know. To me it's very nice that Homebrew provides all of this amazing stuff for free and not very nice that users might try to disable the (very small) ask from the Homebrew team for  something they get for free

**Comment by mikemcquaid** [comment]
I agree with @UniqMartin but thanks for the great sentiment here 🙇 ❤️

**Comment by mikemcquaid** [comment]
> but also value their privacy

I'm not trying to encourage you not to opt-out but just wanted to add a comment pointing out that I don't think the analytics do violate your privacy given everything explain in the document (in short: we gather aggregate not individual activity and strip all personally identifiable information).

**Pull request closed without merging**
