### PR TITLE
Use `shellcheck` on Bash completion file

### PR DESCRIPTION
**Pull request by GauthamGoli**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
#11086

### CODE REVIEW

**Review by nandahkrishna — COMMENTED** [review]
You'll have to modify [`Library/Homebrew/completions/bash.erb`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/completions/bash.erb) instead, as this will be overwritten on running `brew man` to autogenerate completions.

**Comment by GauthamGoli** [comment]
@nandahkrishna Thanks made the necessary changes. Can you try testing now?

**Comment by nandahkrishna** [comment]
Thanks @GauthamGoli. It seems fine now.

My understanding right now is – if someone were to make a change in `bash.erb`, their workflow would be somewhat complicated as they'd have to run `brew man` and `brew style`, fix changes in `bash.erb` and commit the changes after running `brew man`. Is this right and is there a way to make this simpler?

**Comment by GauthamGoli** [comment]
Yes, that seems to be the way to do it.

**Review by MikeMcQuaid — APPROVED** [review]
👍🏻 but let's hold off merging until after 3.1.0 goes out on Monday.

**Comment by GauthamGoli** [comment]
@MikeMcQuaid Which versions of bash do we support? I tested this out on the latest version only.

**Comment by MikeMcQuaid** [comment]
@GauthamGoli Whatever version ships with macOS (3.x) and whatever version `brew install bash` installs.

**Comment by MikeMcQuaid** [comment]
Great work, thanks @GauthamGoli!

**Pull request merged**
