### PR TITLE
tap_constants: support caskroom/* Tap

### PR DESCRIPTION
**Pull request by n0ts**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Hi, caskroom repository has [fonts](https://github.com/caskroom/homebrew-fonts), [versions](https://github.com/caskroom/homebrew-versions) and [more](https://github.com/caskroom).

So, bellow command is not working:
- brew install Caskroom/versions/google-chrome-canary 
- brew install Caskroom/fonts/font-source-code-pro

### CODE REVIEW

**Comment by n0ts** [comment]
CI is failed ` Hbc::Installer install generates and finds a timestamped metadata directory for an installed Cask`, I think that It does not affect this PR...

**Comment by reitermarkus** [comment]
I think it would be best if we don't further expand this shortcut. Instead, you should use the canonical way using `brew tap` followed by `brew cask install`.

**Comment by commitay** [comment]
> I think it would be best if we don't further expand this shortcut. 

Can we remove it altogether?

**Comment by n0ts** [comment]
Thanks, comment.
I use brew custom hook command like `brew my-install <formula>`.
I want to use it the same way homebrew-cask. `brew my-install <cask>`, brew cask my-install <cask> is not working...

How to support brew custom hook command for homebrew cask?

**Comment by n0ts** [comment]
@reitermarkus @commitay  Thanks, comment.
I use brew custom hook command like `brew my-install <formula>`.
I want to use it the same way homebrew-cask. `brew my-install <cask>`, brew cask my-install <cask> is not working...

How to support brew custom hook command for homebrew cask?

**Comment by reitermarkus** [comment]
What is your `my-install` command doing, exactly?

**Comment by n0ts** [comment]
I use custom install hook bellow.

```
require 'bottle' # find my custom bottles
require "cmd/install"
Homebrew.install
```

Cask version use `Hbc::CLI::Install.new(ARGV).run` is working.

So, brew install Caskroom/*/* will be deprecate?

**Comment by MikeMcQuaid** [comment]
> require 'bottle' # find my custom bottles
> require "cmd/install"

@n0ts These are internal, private methods. You should not be requiring them.

**Comment by n0ts** [comment]
@MikeMcQuaid Thanks comment, I think that `require 'cmd/install'` is required. What should required homebrew's install public method?

**Comment by MikeMcQuaid** [comment]
@n0ts We do not provide a public Ruby API. Use `system "brew", "install", ...` instead.

**Comment by MikeMcQuaid** [comment]
Passing on this, sorry.

**Pull request closed without merging**
