### PR TITLE
formula_auditor: audit all relicensed HashiCorp formulae

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Apply #15975 to all affected formulae.

### CODE REVIEW

**Review by p-linnane — APPROVED** [review]
Awesome job!

**Review by apainintheneck — APPROVED** [review]

**Review by MikeMcQuaid — APPROVED** [review]
Thanks again!

**Comment by iMichka** [comment]
@ZhongRuoyu wondering about boundary and vagrant: can't find these formulae. How did you create the list?

**Comment by ZhongRuoyu** [comment]
> @ZhongRuoyu wondering about boundary and vagrant: can't find these formulae. How did you create the list?

@iMichka Yes, sorry I must have forgotten to mention this, but: I was aware that these two didn't exist yet, and it was intentional to prevent them from ever being added.

**Pull request merged**
