### PR TITLE
Drop unzip usage for Homebrew Cask

### PR DESCRIPTION
**Pull request by amyspark**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [X] Have you successfully run `brew style` with your changes locally?
- [X] Have you successfully run `brew tests` with your changes locally?

-----
This pull request drops `unzip` altogether when handling Zip artifacts for Cask. It seems that in High Sierra and above, `unzip` no longer unpacks the `__MACOSX` folder containing the extended attributes, and the provided `-J` flag does not restore this behaviour.

Fixes Homebrew/homebrew-cask#61386.

### CODE REVIEW

**Comment by reitermarkus** [comment]
Right now, this will run `unzip` *and* `ditto` for everything.

**Comment by reitermarkus** [comment]
In the case of https://github.com/Homebrew/homebrew-cask/issues/61386, does `unzip` show any error/warning?

**Comment by amyspark** [comment]
@reitermarkus,
> Right now, this will run `unzip` *and* `ditto` for everything.

Not at all, as this pull request removes all calls to `super`:
```
amalia@Sakura:~ $ brew cask install emacs-mac --verbose --debug
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/cask-versions, homebrew/core and homebrew/cask).
==> Updated Formulae
libcroco ✔      youtube-dl ✔    apr             krakend         ruby@2.4

==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://github.com/railwaycat/homebrew-emacsmacport/releases/download/emacs-26.2-rc1-mac-7.5/emacs-26.2-rc1-mac-7.5-10.13.6.zip
/usr/bin/curl -q --show-error --user-agent Homebrew/2.1.0-1-g7cf241a\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --location --silent --head --request GET https://github.com/railwaycat/homebrew-emacsmacport/releases/download/emacs-26.2-rc1-mac-7.5/emacs-26.2-rc1-mac-7.5-10.13.6.zip
Already downloaded: /Users/amalia/Library/Caches/Homebrew/downloads/09dd4be5b7b4da9e6dd8c3161d79a20f26e490e405013a9ecf12df1f5247da1a--emacs-26.2-rc1-mac-7.5-10.13.6.zip
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/amalia/Library/Caches/Homebrew/downloads/09dd4be5b7b4da9e6dd8c3161d79a20f26e490e405013a9ecf12df1f5247da1a--emacs-26.2-rc1-mac-7.5-10.13.6.zip
/usr/bin/xattr -p com.apple.quarantine /Users/amalia/Library/Caches/Homebrew/downloads/09dd4be5b7b4da9e6dd8c3161d79a20f26e490e405013a9ecf12df1f5247da1a--emacs-26.2-rc1-mac-7.5-10.13.6.zip
==> /Users/amalia/Library/Caches/Homebrew/downloads/09dd4be5b7b4da9e6dd8c3161d79a20f26e490e405013a9ecf12df1f5247da1a--emacs-26.2-rc1-mac-7.5-10.13.6.zip is quarantined
==> Downloaded to -> /Users/amalia/Library/Caches/Homebrew/downloads/09dd4be5b7b4da9e6dd8c3161d79a20f26e490e405013a9ecf12df1f5247da1a--emacs-26.2-rc1-mac-7.5-10.13.6.zip
==> Verifying SHA-256 checksum for Cask 'emacs-mac'.
==> Installing Cask emacs-mac
==> Cask::Installer#stage
zipinfo -1 /Users/amalia/Library/Caches/Homebrew/downloads/09dd4be5b7b4da9e6dd8c3161d79a20f26e490e405013a9ecf12df1f5247da1a--emacs-26.2-rc1-mac-7.5-10.13.6.zip
==> Extracting primary container
==> Using container class UnpackStrategy::Zip for /Users/amalia/Library/Caches/Homebrew/downloads/09dd4be5b7b4da9e6dd8c3161d79a20f26e490e405013a9ecf12df1f5247da1a--emacs-26.2-rc1-mac-7.5-10.13.6.zip
ditto -x -k /Users/amalia/Library/Caches/Homebrew/downloads/09dd4be5b7b4da9e6dd8c3161d79a20f26e490e405013a9ecf12df1f5247da1a--emacs-26.2-rc1-mac-7.5-10.13.6.zip /var/folders/l1/b3htrbqd3w3f32x9lk1yll6h0000gn/T/d20190406-45915-1rlz82o
cp -pR /var/folders/l1/b3htrbqd3w3f32x9lk1yll6h0000gn/T/d20190406-45915-1rlz82o/Emacs.app/. /usr/local/Caskroom/emacs-mac/emacs-26.2-rc1-mac-7.5/Emacs.app
chmod -Rf +w /var/folders/l1/b3htrbqd3w3f32x9lk1yll6h0000gn/T/d20190406-45915-1rlz82o
==> Verifying Gatekeeper status of /Users/amalia/Library/Caches/Homebrew/downloads/09dd4be5b7b4da9e6dd8c3161d79a20f26e490e405013a9ecf12df1f5247da1a--emacs-26.2-rc1-mac-7.5-10.13.6.zip
/usr/bin/xattr -p com.apple.quarantine /Users/amalia/Library/Caches/Homebrew/downloads/09dd4be5b7b4da9e6dd8c3161d79a20f26e490e405013a9ecf12df1f5247da1a--emacs-26.2-rc1-mac-7.5-10.13.6.zip
==> /Users/amalia/Library/Caches/Homebrew/downloads/09dd4be5b7b4da9e6dd8c3161d79a20f26e490e405013a9ecf12df1f5247da1a--emacs-26.2-rc1-mac-7.5-10.13.6.zip is quarantined
==> Propagating quarantine from /Users/amalia/Library/Caches/Homebrew/downloads/09dd4be5b7b4da9e6dd8c3161d79a20f26e490e405013a9ecf12df1f5247da1a--emacs-26.2-rc1-mac-7.5-10.13.6.zip to /usr/local/Caskroom/emacs-mac/emacs-26.2-rc1-mac-7.5
/usr/bin/xattr -p com.apple.quarantine /Users/amalia/Library/Caches/Homebrew/downloads/09dd4be5b7b4da9e6dd8c3161d79a20f26e490e405013a9ecf12df1f5247da1a--emacs-26.2-rc1-mac-7.5-10.13.6.zip
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5ca69dc5\;Homebrew\\x20Cask\;709B59D5-F853-4721-8C89-070540B75921
==> Creating metadata directory /usr/local/Caskroom/emacs-mac/.metadata/emacs-26.2-rc1-mac-7.5/20190406221307.010.
==> Creating metadata subdirectory /usr/local/Caskroom/emacs-mac/.metadata/emacs-26.2-rc1-mac-7.5/20190406221307.010/Casks.
==> Installing artifacts
==> 6 artifact/s defined
#<SortedSet:0x00007fd0689b8288>
==> Installing artifact of class Cask::Artifact::App
==> Moving App 'Emacs.app' to '/Applications/Emacs.app'.
==> Installing artifact of class Cask::Artifact::Binary
==> Linking Binary 'Emacs' to '/usr/local/bin/emacs'.
/bin/ln -h -f -s -- /Applications/Emacs.app/Contents/MacOS/Emacs /usr/local/bin/emacs
==> Installing artifact of class Cask::Artifact::Binary
==> Linking Binary 'ebrowse' to '/usr/local/bin/ebrowse'.
/bin/ln -h -f -s -- /Applications/Emacs.app/Contents/MacOS/bin/ebrowse /usr/local/bin/ebrowse
==> Installing artifact of class Cask::Artifact::Binary
==> Linking Binary 'emacsclient' to '/usr/local/bin/emacsclient'.
/bin/ln -h -f -s -- /Applications/Emacs.app/Contents/MacOS/bin/emacsclient /usr/local/bin/emacsclient
==> Installing artifact of class Cask::Artifact::Binary
==> Linking Binary 'etags' to '/usr/local/bin/etags'.
/bin/ln -h -f -s -- /Applications/Emacs.app/Contents/MacOS/bin/etags /usr/local/bin/etags
🍺  emacs-mac was successfully installed!
amalia@Sakura:~ $ spctl --assess --verbose /Applications/Emacs.app
/Applications/Emacs.app: accepted
source=Developer ID
```

As for `unzip` - no warnings, no errors. (Turns out the __MACOSX folder is indeed unpacked.) However, `dot_clean` is unable to access it.

```
amalia@Sakura:/tmp/asd $ unzip /Users/amalia/Library/Caches/Homebrew/downloads/09dd4be5b7b4da9e6dd8c3161d79a20f26e490e405013a9ecf12df1f5247da1a--emacs-26.2-rc1-mac-7.5-10.13.6.zip
Archive:  /Users/amalia/Library/Caches/Homebrew/downloads/09dd4be5b7b4da9e6dd8c3161d79a20f26e490e405013a9ecf12df1f5247da1a--emacs-26.2-rc1-mac-7.5-10.13.6.zip
   creating: Emacs.app/
<snip>
  inflating: __MACOSX/Emacs.app/._Contents  
finishing deferred symbolic links:
  Emacs.app/Contents/MacOS/bin/emacs -> emacs-26.1.92
amalia@Sakura:/tmp/asd $ dot_clean -nvs --keep=dotbar .
Merging directory __MACOSX
Merging directory Emacs.app
merging ._Contents & Contents
Replacing Contents's EAs with ._Contents's EAs
Deleting: ._Contents
Merging directory Contents
Failed trying to change dir to Contents
Bad Pathname: Permission denied
Merging directory Emacs.app
<snip>
```
And even with a `chmod u+x` on the `__MACOSX` folder, it still doesn't copy the attributes properly.

An alternative solution, if you don't want a ditto-for-all approach, is to manually copy the contents to the `__MACOSX` folder to the `unpack_dir`. (This would need to undo your patch, and it messes up with the original app's folder permissions.)

**Comment by reitermarkus** [comment]
Without `super` it will only ever use `ditto`, which fails for some formulae, which is why this is a fallback in the first place.

We could check for the `__MACOSX` directory being in the ZIP file, and use `ditto` if it is.

**Comment by vitorgalvao** [comment]
> We could check for the `__MACOSX` directory being in the ZIP file, and use `ditto` if it is.

Why not just default to `ditto` and use `unzip` as the fallback? Each of them may fail in particular cases, but as it stands `unzip` will fail more often.

**Comment by MikeMcQuaid** [comment]
👍 to defaulting to `ditto` for Cask but not for Homebrew formulae.

**Comment by reitermarkus** [comment]
You can't really reverse the order, since there are very specific scenarious when `unzip` fails, i.e. the ones where we fall back already., but you can't detect when `ditto` fails, since it will mostly just mess up permissions on files and not output any warning about it, which was the reason for defaulting to `unzip`.

**Comment by amyspark** [comment]
Apologies for the force push, I rewrote this pull request to maintain a clean Git history as much as possible. With the new version, I use `zipinfo` to check if there are any Apple Double files, and if so I reunzip using `ditto`.

**Comment by MikeMcQuaid** [comment]
@amyspark I'd like to see this use different behaviour for Homebrew casks and Homebrew formulae. As-is this will unnecessarily run `zipinfo` on every Homebrew zip file when we never want to use `ditto` there.

**Comment by amyspark** [comment]
@MikeMcQuaid -- would it work for you if I made these changes as an extension from within the `Library/Homebrew/cask` tree? In that way, I'd leave this part untouched.

**Comment by MikeMcQuaid** [comment]
@amyspark It would likely be easier to do things the other way around and add a parameter like this https://github.com/Homebrew/brew/blob/9856a6c3bb8c4f11b78e42dc72589592359d4abd/Library/Homebrew/download_strategy.rb#L57 (`no_ditto: true` or similar) which alters the UnpackStrategy behaviour accordingly just for formulae.

**Comment by amyspark** [comment]
Done, although I used `merge_xattrs` to be more explicit about its purpose. Is that OK for you @MikeMcQuaid ?

**Comment by MikeMcQuaid** [comment]
Looks great, nice work as usual @amyspark! I wish you'd join us as a maintainer 😀.

**Pull request merged**
