### PR TITLE
[completions] Add 'greedy' option to list of  outdated casks for the cask upgrade completion

### PR DESCRIPTION
**Pull request by michaljuris**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [n/a] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

I believe that _cask upgrade_ completions should suggest casks from the greedy list of outdated casks. My reasoning is that when you are using an explicit upgrade command for a certain cask you are showing an intention to really upgrade it, so suggestions from the greedy outdated casks list should be used.

Issue: https://github.com/Homebrew/brew/issues/10731

### CODE REVIEW

**Comment by nandahkrishna** [comment]
Completions are auto-generated upon running `brew man`, so any change you'd like to propose should be in [these files](https://github.com/Homebrew/brew/tree/master/Library/Homebrew/completions) instead.

**Comment by michaljuris** [comment]
> Completions are auto-generated upon running `brew man`, so any change you'd like to propose should be in [these files](https://github.com/Homebrew/brew/tree/master/Library/Homebrew/completions) (and/or [this one](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/completions.rb)) instead.

Thank you for noting that. I've just pushed a modified code according to your comment.

**Comment by Rylan12** [comment]
Can someone from @Homebrew/cask weigh in on this, please?

I don't know enough about the `--greedy` flag to make the call, here. Should `brew upgrade` autocomplete from `brew outdated --greedy`? I have the sense that `--greedy` isn't really the "normal/recommended" way to upgrade those casks (otherwise it would be the default), so I wonder if it shouldn't be there. Certainly, if `--greedy` upgrades are something that we _actively do not_ recommend doing, it shouldn't be in the default completions.

Alternatively, this could be only used when the `--greedy` flag is passed to `brew upgrade`. This would take a lot more work to get the completions to be more intelligent (which I've had on my to-do list for a while).

**Comment by claui** [comment]
> Should `brew upgrade` autocomplete from `brew outdated --greedy`?

I’d feel that would violate the principle of least surprise, so: let’s better not do that.

> I have the sense that `--greedy` isn't really the "normal/recommended" way to upgrade those casks (otherwise it would be the default)

That’s correct. For those casks, the in-app upgrade feature usually takes care of the upgrade already.

> Certainly, if `--greedy` upgrades are something that we _actively do not_ recommend doing, it shouldn't be in the default completions.

It’s not that we actively discourage them; we rather assume they’re usually pointless, except when they aren’t.

**Comment by Rylan12** [comment]
Thanks for the explanation, @claui. Hearing this, I think we probably don't want to use the `--greedy` flag here. Once the completions are smart enough to change the function based on the flags passed, I could see this being re-added when the `--greedy` flag is passed to `brew upgrade`.

Thanks, anyway for the PR!

**Comment by michaljuris** [comment]
> Thanks for the explanation, @claui. Hearing this, I think we probably don't want to use the `--greedy` flag here. Once the completions are smart enough to change the function based on the flags passed, I could see this being re-added when the `--greedy` flag is passed to `brew upgrade`.
> 
> Thanks, anyway for the PR!

Just a note - there is no `--greedy` option for the `upgrade`

My reasoning was that if you CAN upgrade the cask you should be able to get completion for it. Personally, I use it very often.

**Comment by Rylan12** [comment]
> Just a note - there is no `--greedy` option for the `upgrade`

According to `brew help upgrade` there is

> My reasoning was that if you CAN upgrade the cask you should be able to get completion for it. Personally, I use it very often.

I see what you're saying but I'd bet that you're in the minority of users. We have to strike a balance between making things as simple as possible for some users who aren't as "fluent" in Homebrew and supporting the "power users".

**Pull request closed without merging**
