### PR TITLE
curl_spec: remove no-op Marshal use

### PR DESCRIPTION
**Pull request by woodruffw**
These seemingly do nothing.

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by woodruffw** [comment]
Closing; this `Marshal` round-trip is unfortunately load-bearing as an easy way to perform a deep clone.

**Comment by Bo98** [comment]
Would these here? https://github.com/Homebrew/brew/blob/master/Library/Homebrew/extend/object/deep_dup.rb

**Comment by woodruffw** [comment]
> Would these work here? [`master`/Library/Homebrew/extend/object/deep_dup.rb](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/extend/object/deep_dup.rb?rgh-link-date=2024-07-13T19%3A24%3A34Z)

Ah, I was looking for this exact helper. Yes, that's exactly what it needs. Reopening.

**Review by MikeMcQuaid — APPROVED** [review]
Nice, thanks @woodruffw!

**Comment by MikeMcQuaid** [comment]
(confirmed ready for review because I was sitting next to @woodruffw!)

**Pull request merged**
