### PR TITLE
workflows/doctor: skip unnecessary steps

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Based on discussion from #14172.

I'm not sure if this works, but CI should tell us.

### CODE REVIEW

**Comment by carlocab** [comment]
No doctor workflow. Invalid syntax, probably.

**Review by MikeMcQuaid — APPROVED** [review]
If/when it works: 🚢

**Comment by aconchillo** [comment]
@carlocab I'm running into the same workflow issues as `CI / test everything (macOS)` in Guile Homebrew (https://github.com/aconchillo/homebrew-guile):

```
  Please note that these warnings are just used to help the Homebrew maintainers
  with debugging if you file an issue. If everything you use Homebrew for is
  working fine: please don't worry or file an issue; just ignore this. Thanks!
  
  Warning: "config" scripts exist outside your system or Homebrew directories.
  `./configure` scripts often look for *-config scripts to determine if
  software packages are installed, and which additional flags to use when
  compiling and linking.
  
  Having additional scripts in your path can confuse software installed via
  Homebrew if the config script overrides a system or Homebrew-provided
  script of the same name. We found the following "config" scripts:
    /Library/Frameworks/Python.framework/Versions/Current/bin/python3-config
    /Library/Frameworks/Python.framework/Versions/Current/bin/python3.11-config
```

Any idea what's going on? Thanks! 🙏

**Comment by MikeMcQuaid** [comment]
@aconchillo This is fixed now!

**Comment by aconchillo** [comment]
@MikeMcQuaid Awesome, thank you. It's working again!

**Pull request merged**
