### PR TITLE
Improve error message for failed signature check.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

If an app is unsigned, the signature check should not fail.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Isn't "no signature" an issue for ARM macs?

**Comment by reitermarkus** [comment]
No idea about ARM, we also don't have ARM CI for casks. I just keep seeing PRs failing with this error (e.g. https://github.com/Homebrew/homebrew-cask/pull/130308 and https://github.com/Homebrew/homebrew-cask/pull/129899).

**Comment by SMillerDev** [comment]
Well, if this means they can't normally run on ARM I think the audit should stay since that's what most people will use.

**Comment by SMillerDev** [comment]
https://eclecticlight.co/2020/08/22/apple-silicon-macs-will-require-signed-code/

Suggests that if an app has native arm code but no signature it won't run until people disable quarantaine, which is exactly the pattern of issues in trying to catch here.

**Comment by reitermarkus** [comment]
Okay, so in these cases we refuse new casks or updates until upstream has fixed the wrong/missing signature?

**Comment by SMillerDev** [comment]
It doesn't trigger on updates, but we can let upstream know that their software won't work without manual signing on any Mac released in the last 2 years and that they should sign it, yes.

**Comment by reitermarkus** [comment]
> if an app has native arm code but no signature it won't run until people disable quarantaine

So you cannot allow individual unsigned apps you can only disable Gatekeeper completely on ARM?

> It doesn't trigger on updates

 Any reason to not also check updates?

**Comment by SMillerDev** [comment]
> So you cannot allow individual unsigned apps you can only disable Gatekeeper completely on ARM?

You can disable quarantaine on the cask download. Which would allow an install because Apple wouldn't know it was downloaded.

> Any reason to not also check updates?

Because I wanted to try it on new casks first. And upstreams likely won't remove signing on updates.

**Comment by reitermarkus** [comment]
> You can disable quarantaine on the cask download. Which would allow an install because Apple wouldn't know it was downloaded.

So the difference is that on ARM you would have to install with `--no-quarantine` since you cannot do right-click open to override it?

> Because I wanted to try it on new casks first. And upstreams likely won't remove signing on updates.

I see. Yeah, I'm not saying upstreams will remove signatures, not intentionally at least.

**Comment by SMillerDev** [comment]
> So the difference is that on ARM you would have to install with `--no-quarantine` since you cannot do right-click open to override it?

Yes, unless the software is signed.

**Review by SMillerDev — APPROVED** [review]

**Review by Rylan12 — APPROVED** [review]

**Pull request merged**
