### PR TITLE
OS::Mac.mdfind: No need to guard on OS.mac?

### PR DESCRIPTION
**Pull request by sjackman**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

This code is only used on macOS.

### CODE REVIEW

**Comment by sjackman** [comment]
@MikeMcQuaid Any way to override `codecov/project` for this PR?

**Comment by MikeMcQuaid** [comment]
@sjackman You can edit `./Library/Homebrew/test/.codecov.yml`

**Comment by sjackman** [comment]
> threshold
number
Allow the coverage to drop by X%, and posting a success status.

https://docs.codecov.io/docs/commit-status#section-threshold

https://github.com/Homebrew/brew/blob/3e890c11ad07b7b31088600b85c54aeff8cf23b1/Library/Homebrew/test/.codecov.yml#L10

This patch drops the coverage by -0.01%. The allowable drop is -0.05%. As far as I can tell, this check ought to be successful.

**Comment by MikeMcQuaid** [comment]
@reitermarkus Any thoughts? Perhaps that threshold isn't being parsed properly?

**Comment by reitermarkus** [comment]
Restarted Travis and now it's at -0.25%

Maybe try rebasing?

**Comment by MikeMcQuaid** [comment]
@reitermarkus I think we either need to make this check not required or widen the threshold.

**Comment by MikeMcQuaid** [comment]
Thanks again @sjackman!

**Comment by sjackman** [comment]
Thanks for merging and troubleshooting the code coverage issue!

**Pull request merged**
