### PR TITLE
upgrade: allow to specify build environment

### PR DESCRIPTION
**Pull request by sh1r4s3**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?
- [x] Have you successfully run `brew man` locally and committed any changes?

-----

Allow to use --env option to specify which build environment to use to build a formula (like in the install command).

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Sorry, passing on this @sh1r4s3. I actually want to do the opposite and deprecate `--env` being passed as an installation option. Thanks for the PR anyway, though!

**Comment by sh1r4s3** [comment]
Thanks for the answer!
I have a question though. AFAIK without the `--env` option one could not build the project without setting up the Homebrew environment. I used this option to fix building of a package in tmp directory (i.e. `brew install -s --env=std --keep-tmp <some pkg>`). I'm new in the brewing, maybe I missed something, so I'm sorry in advance! :)

**Comment by reitermarkus** [comment]
There is an `--interactive` flag for `brew install`. Also, `--debug` will let you choose to what to do on error, including opening an interactive shell. I usually use `-svd` when debugging a formula.

**Comment by sh1r4s3** [comment]
Thank you @reitermarkus!

**Pull request closed without merging**
