### PR TITLE
hide deprecated cask command

### PR DESCRIPTION
**Pull request by hyuraku**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?
- [x] Have you successfully run `brew man` locally and committed any changes?

-----
hide some deprecated cask command from the document  because of https://github.com/Homebrew/brew/issues/8629

### CODE REVIEW

**Review by MikeMcQuaid — COMMENTED** [review]
Nice work here! I think it would be good to add `# odeprecated` here too so we can deprecate them on the next major release. Alternatively, we could deprecate them now. What do you think @Homebrew/cask?

**Comment by miccal** [comment]
I would suggest that they be deprecated in the next major release, thanks.

**Review by reitermarkus — APPROVED** [review]

**Comment by reitermarkus** [comment]
> I think it would be good to add `# odeprecated` here

We already have `odeprecated` in the `run` method.

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks again @hyuraku (and for correcting me and unblocking this @reitermarkus)!

**Pull request merged**
