### PR TITLE
linkage_checker: simplify logic for declared deps and include recursive deps

### PR DESCRIPTION
**Pull request by zmwangx**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Use `Formula#runtime_dependencies` to collect dependencies.

This inevitably pulls in all recursive deps, which might be controversial (I think this was discussed during the `:linked` dependency days, and no conclusion was reached; the discussion died off after `:linked` was dropped, but dependency resolution has improved since then, so it's worth taking another look), but IMO is a good idea.

Concrete example: in the case of `ffmpeg`, depending on either `theora` or `libvorbis` (both of which has a hard dependency on `libogg`) would introduce a `libogg` linkage, which is currently listed under "possible undeclared dependencies".

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Code looks sound to me but wondering if @ilovezfs @alyssais have thoughts on the results.

**Comment by ilovezfs** [comment]
This will mean we have no easy way of telling which linkages are or are not explicitly included in the formula.

**Comment by zmwangx** [comment]
> This will mean we have no easy way of telling which linkages are or are not explicitly included in the formula.

Yes. But keep in mind that recursive dependencies are explicitly exposed in LDFLAGS. Complaining about it later feels inconsistent.

**Comment by ilovezfs** [comment]
Printing them as possibly undeclared doesn't necessarily amount to complaining.

Ideally I think we should print out the indirect, undeclared ones in one list and the flat-out opportunistic ones in another list rather than lumping them together in a generic undeclared pile. But just not printing the former makes it harder to answer the question: what's this linked to that's not noted explicitly with a depends_on?

**Comment by zmwangx** [comment]
> what's this linked to that's not noted explicitly with a depends_on?

Aw, smells like `:linked`...

**Comment by ilovezfs** [comment]
Yes, by definition. One hopes `=> :linked` was never intended for the opportunistic ones.

**Comment by MikeMcQuaid** [comment]
Not sure on the state of this. @ilovezfs? Feel free to point out what would need done from your perspective and/or close if we're at the end of this road.

**Comment by MikeMcQuaid** [comment]
> Ideally I think we should print out the indirect, undeclared ones in one list and the flat-out opportunistic ones in another list rather than lumping them together in a generic undeclared pile.

This seems like the best idea. It won't result in code simplification but printing out two different lists here feels like the right thing for now.

**Comment by ilovezfs** [comment]
>This seems like the best idea. It won't result in code simplification but printing out two different lists here feels like the right thing for now.

Agreed. @zmwangx are you willing to implement it as two lists?

**Comment by zmwangx** [comment]
> are you willing to implement it as two lists?

I may take a look this weekend, but I'm kind of short on time recently and is juggling free time between several things, so feel free.

**Comment by zmwangx** [comment]
Sorry guys, I forgot about this. I'll close this since the improvement would be very minor anyway.

**Pull request closed without merging**
