### PR TITLE
completions/zsh: add-cask-option

### PR DESCRIPTION
**Pull request by hyuraku**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?
- [ ] Have you successfully run `brew man` locally and committed any changes?

-----
add cask options to commands( reinstall and upgrade ) in zsh/completions.

### CODE REVIEW

**Review by MikeMcQuaid — CHANGES_REQUESTED** [review]
Thanks for this @hyuraku but I'd like to pause any more completions changes until https://github.com/Homebrew/brew/pull/10229 is merged.

**Comment by hyuraku** [comment]
> I'd like to pause any more completions changes until #10229 is merged.

Sure.

**Comment by hyuraku** [comment]
@MikeMcQuaid 
> but I'd like to pause any more completions changes until #10229 is merged.

#10229 was merged, how about?

**Comment by MikeMcQuaid** [comment]
> @MikeMcQuaid
> 
> > but I'd like to pause any more completions changes until #10229 is merged.
> 
> #10229 was merged, how about?

Thanks @hyuraku! I'm interested in what @Rylan12 thinks here (as this may well be either autogenerated soon or cause him merge conflicts).

**Comment by hyuraku** [comment]
> > @MikeMcQuaid
> > > but I'd like to pause any more completions changes until #10229 is merged.
> > 
> > 
> > #10229 was merged, how about?
> 
> Thanks @hyuraku! I'm interested in what @Rylan12 thinks here (as this may well be either autogenerated soon or cause him merge conflicts).

I understood that `my plan is to work on those next (probably zsh before fish).` from #10229. I wait till merging it.

**Comment by Rylan12** [comment]
I think it's okay to merge to temporarily fix completions, but this change will be overridden soon once these are generated. Don't worry about merge conflicts here: I'm not far enough along for them to be a big deal at the moment (especially because resolving them will simply be "use my changes instead").

I up to you two I guess. Probably not needed as these will be automatic soon, but doesn't hurt to temporarily have in case there's a new brew release before I get those completions working.

Does that give you enough to go on or do you want me to make the decision?

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks again @hyuraku!

**Pull request merged**
