### PR TITLE
All things must come to an end eventually.

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by tschoonj** [comment]
😢 

Thanks for all your contributions and all the help you provided me!

**Comment by retokromer** [comment]
Why not as former maintainer?

**Comment by MikeMcQuaid** [comment]
> Why not as former maintainer?

@retokromer He will be going there whether he likes it or not 😉

**Comment by scpeters** [comment]
Yes, thanks for your contributions!

**Comment by vszakats** [comment]
Thank you @DomT4 for your dedicated and professional work on Homebrew, it will be missed. Not to forget all the help and support you gave along my PRs.

**Comment by dunn** [comment]
❤️

**Comment by mistydemeo** [comment]
@DomT4 I've appreciated all of your work very much. Thank you! ❤️

**Comment by DomT4** [comment]
Wasn't quite expecting so many people to notice the PR 😅. Left a message in the team chat for the maintainer side of things, but thank you to the folks who commented here, it is very much appreciated. I guess people always say that, but it remains true to me ❤️.

Getting to work with some of you & being involved in the Homebrew community in general has been a pleasure, sometimes rather frustrating as FOSS can be, but Homebrew is one of the best open-source communities you can stumble into and contribute towards, especially if you're new or returning to the whole open-source thing and want to help out but aren't really sure where to start.

I have no idea really why Mike & the team that was here at the time, a few of which remain active, trusted me with maintaining Homebrew however long ago it was now, but I managed to not completely burn the metaphorical house down so I guess it didn't work out too awfully.

Folks are welcome to ping me if there's stuff you stumble across later and think "Why?", this account will remain active even if I haven't decided how much it'll be used going forwards and your pings will get filtered into my GH mailbox. Just don't ping me to tell me you think what I did was terrible 😉.

Up to @MikeMcQuaid when this gets merged. I'll leave that in your hands. And belatedly, congratulations on becoming a maintainer @tschoonj. Your work on the GNOME stuff has always been 💯 and I've no idea how you consistently find the patience for it.

**Comment by MikeMcQuaid** [comment]
@DomT4 As I stated in Slack but will restate here: it's been a pleasure working with you and you should be proud of all the great work you've done.

@tschoonj @reitermarkus @jawshooah Just a note that I used this chance to add you to the README/manpage too.

**Comment by bfontaine** [comment]
:sob:

**Comment by DomT4** [comment]
@MikeMcQuaid Thanks Mike. Appreciate all the support you've given me around Homebrew over my time here. Fairly frequently you had more faith in me than I had in myself. Let me know if I need to sign or post anything to step down from the SFC PLC.

@bfontaine ❤️❤️.

**Comment by apjanke** [comment]
Thanks for all your work Dom! It's been a pleasure working with you.

**Comment by UniqMartin** [comment]
Thanks for everything Dom, from the amazing and mind-blowing amount work you contributed to Homebrew to the pleasure of working with you and the discussions we had! You've certainly played a key role in me getting more involved with Homebrew and feeling truly welcome here. :heart:

**Comment by vladshablinsky** [comment]
😔 @DomT4 I didn't have too much time to work with you, however I remember you finding some tricky bugs in my code and me fixing them, and it stays as a good memory for me.  Thanks for all of your work on Homebrew and best of luck on all your endeavors.

**Comment by DomT4** [comment]
@apjanke Thanks Andrew. My sincere apologies that my departure likely leaves the way Homebrew handles Java sandboxing heavily on your shoulders 🙈. Maybe not the best leaving gift in the world.

@UniqMartin I might have lasted longer if I hadn't tried to do as much of absolutely everything as I could heh, which is perhaps advice I pass on to any new maintainer in future months or years who stumbles upon this thread. Sometimes you need a break from things and I'm not very good at giving myself them. Thank you for the many discussions we had; I'm glad and thankful for any influence I had in making you feel welcome around Homebrew and a part of the team.

@vladshablinsky I learnt quite a bit from keeping an eye on your PRs. Occasionally finding interesting ways to break things was something I formed a habit of doing 😆, but that being useful is always a relief. Although we didn't get the chance to do much work together thrilled to see you join the maintainers team, Homebrew is lucky to have you around.

**Pull request merged**
