### PR TITLE
Don’t expand `executable` path in `SystemCommand`.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

---

Otherwise plain executable names would be expanded to `$PWD/executable` instead of looking for it in the `PATH`.

### CODE REVIEW

**Comment by commitay** [comment]
What happened to `@homebrew/cask` for reviews?

**Comment by commitay** [comment]
Yes, that might be useful but why was the option for the `homebrew/cask` team to review a PR removed?

**Comment by MikeMcQuaid** [comment]
@commitay It wasn't? I can't add it either but there certainly wasn't any action there that changed things.

**Comment by commitay** [comment]
Weird, it was working a few days ago, the read-only access for the cask team has been removed for this repo. Should it be restored or do we want to go with CODEOWNERS?

**Comment by MikeMcQuaid** [comment]
@commitay Weird that read-only on a public repo has that effect! Fixed now, thanks for pointing it out 🙇

**Comment by commitay** [comment]
Thanks @MikeMcQuaid ❤️

**Pull request merged**
