### PR TITLE
dev-cmd/bottle: don't fail on --keep-old with unchanged values

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

We shouldn't error about changes if there wasn't actually any changes.

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by sjackman** [comment]
Thanks, Bo!

**Comment by carlocab** [comment]
Not sure if this is working as intended yet...
```
==> mongo-cxx-driver
/home/linuxbrew/.linuxbrew/bin/brew bottle --merge --write --verbose --keep-old --root-url=https://ghcr.io/v2/homebrew/core --no-commit mongo-cxx-driver--3.6.3.arm64_big_sur.bottle.json
Error: `--keep-old` was passed but there are changes in:
cellar arm64_big_sur: old: "/usr/local/Cellar", new: "/opt/homebrew/Cellar"
```
https://github.com/Homebrew/homebrew-core/runs/2292325447?check_suite_focus=true

**Comment by Bo98** [comment]
Looks like that's unveiled a bug somewhere. (It would have failed before, just more cryptically.)

**Comment by Bo98** [comment]
Though it's interesting that `mongo-cxx-driver` isn't relocatable on arm64 but is relocatable on Intel.

**Comment by carlocab** [comment]
Yea, there are a handful of bottles like that. I think I've also seen relocatable on Big Sur but not earlier or vice-versa.

Though, the non-relocatability might be a consequence of my explicitly specifying the install `rpath` which I didn't rebuild the Intel bottles for, as they had just been built about an hour earlier.

**Comment by carlocab** [comment]
Yea, it's from the `rpath`:
```
=> mongo-cxx-driver
  bottle do
    rebuild 1
    sha256 arm64_big_sur: "fcc1e8d4a4218d82ebd1fcf7f9ed8972a297fa0e61826fa5c83448ec897b918d"
    sha256 big_sur:       "b70efcf8b6fe56edf21577529bd516cdbec1b396730d3caeb7af9337e2017d74"
    sha256 catalina:      "4b2ecfbbde4c11251f716cce0be3d6f06417acd8028b3e2dd3afa08f54fc7990"
    sha256 mojave:        "404cb66fd968e6eef90a487494ae57a35fd417982192c6ba24f9f5882bae68e7"
  end
```

**Comment by Bo98** [comment]
#11065

**Pull request merged**
