### PR TITLE
completions: improve performance on zsh

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

By avoiding unneeded `brew` calls we can make zsh completions much faster.

As a rough measurement, completion for `brew list` used to take ~4s on my machine, but now it's instant.

### CODE REVIEW

**Comment by Bo98** [comment]
> As a rough measurement, completion for `brew list` used to take ~4s on my machine, but now it's instant.

This is suspicious. `brew list` should _already_ be implemented in bash and does `ls` under the hood. Why is the behaviour different?

**Comment by Bo98** [comment]
Try #18223. It should fix the performance for you without needing these changes.

**Comment by ZhongRuoyu** [comment]
Now that we have #18223, do we still want to keep the non-`brew list` changes though? Actually what I did (including removing `brew list` calls) was copy over what bash completions are doing (bash completions are fast). So even with the `list.sh` fix, completion for tap names is still slow.

Or we could consider reworking `brew tap` and migrating over Bash completions to calling `brew` commands directly too (to reduce discrepancy).

**Comment by Bo98** [comment]
Repository change is OK if we do so consistently across all completions (assuming it is shown to have actual speed gains).

`brew tap` is a weird one as the bash completion code is actually older. In any case, if there's a noticeable speed increase it would be better for it to be implemented on command level as:

* It is shared between all completions
* It can benefit non-completion cases
* It can be unit tested in CI

**Comment by ZhongRuoyu** [comment]
I've opened #18402 that supersedes this. The performance improvement for non-`brew tap` changes here is insignificant so I'm leaving it out for now.

**Pull request closed without merging**
