### PR TITLE
Catch system libressl in openssl audit as well

### PR DESCRIPTION
**Pull request by tdsmith**
The regex didn't match libcrypto.35.dylib, and it should have.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Is this because the headers aren't available that we want to prevent this linking? If so: 👍, if not: let's talk more.

**Comment by DomT4** [comment]
We might well want to split this into another check to improve the messaging rather than tacking it on to the existing one. LibreSSL also has `libtls` which OpenSSL does not.

Don't have much to say on policing LibreSSL that I didn't already say in https://github.com/Homebrew/homebrew-core/pull/4442#issuecomment-244549171 so I'll leave it at that 😄.

**Comment by MikeMcQuaid** [comment]
👍

**Comment by DomT4** [comment]
I still think this is potentially worth a unique check or a rewrite of the current message.

If something specifically links to `libtls` substituting a `depends_on "openssl"` is unlikely to make that formula happy, for example. `libtls` isn't something OpenSSL provides at all.

**Comment by tdsmith** [comment]
Going to read "potentially worth" as meaning you wouldn't block this as-is. ;) I see your point but there's probably not good general advice in that case anyway.

**Comment by DomT4** [comment]
I think it merits further thought, but I'm happy to do that thought myself, yeah. This is at least a step.

**Pull request merged**
