### PR TITLE
Fix Infinite Recursion in upgradable_dependents and broken_dependents

### LINKED ISSUE #5711: Infinite loop in upgradable_dependents
Picking up where we left off on issue #5431 which got restricted to collaborator by a bot due to a too long inactivity.

I got some time to work on it and I'm _almost sure_ I have a reproducible setup. I'm not 100% sure because my homebrew setup involves a custom prefix, but I think this report is worth a read anyway, if only because I have a potential easy fix.

Brew doctor: https://gist.github.com/Frizlab/fecb7f7abc5112e1f1ce035239ab7731
Brew config: https://gist.github.com/Frizlab/d77fdb9500f417489523ff07c20366cf

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

run `brew upgrade --build-from-source`

# What happened (include command output)

brew upgraded the packages. When everything was up-to-date it froze in an infinite loop. See command output.

<details>
  <summary>Command output</summary>
  <pre>
  
Error: stack level too deep
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/pathname.rb:40:in `chop_basename'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/pathname.rb:358:in `plus'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/pathname.rb:350:in `+'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/pathname.rb:416:in `join'
/Users/frizlab/usr/homebrew/Library/Homebrew/extend/pathname.rb:264:in `resolved_path'
/Users/frizlab/usr/homebrew/Library/Homebrew/formulary.rb:171:in `initialize'
/Users/frizlab/usr/homebrew/Library/Homebrew/formulary.rb:410:in `new'
/Users/frizlab/usr/homebrew/Library/Homebrew/formulary.rb:410:in `loader_for'
/Users/frizlab/usr/homebrew/Library/Homebrew/formulary.rb:310:in `factory'
/Users/frizlab/usr/homebrew/Library/Homebrew/formula.rb:1223:in `current_installed_alias_target'
/Users/frizlab/usr/homebrew/Library/Homebrew/formula.rb:1229:in `installed_alias_target_changed?'
/Users/frizlab/usr/homebrew/Library/Homebrew/formula.rb:1219:in `new_formula_available?'
/Users/frizlab/usr/homebrew/Library/Homebrew/formula.rb:1200:in `block in _outdated_kegs'
/Users/frizlab/usr/homebrew/Library/Homebrew/formula.rb:1190:in `each'
/Users/frizlab/usr/homebrew/Library/Homebrew/formula.rb:1190:in `_outdated_kegs'
/Users/frizlab/usr/homebrew/Library/Homebrew/formula.rb:1182:in `block in outdated_kegs'
/Users/frizlab/usr/homebrew/Library/Homebrew/formula.rb:1184:in `outdated_kegs'
/Users/frizlab/usr/homebrew/Library/Homebrew/formula.rb:1263:in `outdated?'
/Users/frizlab/usr/homebrew/Library/Homebrew/cmd/upgrade.rb:231:in `block (2 levels) in upgradable_dependents'
/Users/frizlab/usr/homebrew/Library/Homebrew/cmd/upgrade.rb:227:in `each'
/Users/frizlab/usr/homebrew/Library/Homebrew/cmd/upgrade.rb:227:in `block in upgradable_dependents'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:306:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:306:in `each'
/Users/frizlab/usr/homebrew/Library/Homebrew/cmd/upgrade.rb:215:in `upgradable_dependents'
/Users/frizlab/usr/homebrew/Library/Homebrew/cmd/upgrade.rb:247:in `block in upgradable_dependents'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:306:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:306:in `each'
………… lines repeated many many times …………
/Users/frizlab/usr/homebrew/Library/Homebrew/cmd/upgrade.rb:215:in `upgradable_dependents'
/Users/frizlab/usr/homebrew/Library/Homebrew/cmd/upgrade.rb:247:in `block in upgradable_dependents'
/Users/frizlab/usr/homebrew/Library/Homebrew/cmd/upgrade.rb:215:in `each'
/Users/frizlab/usr/homebrew/Library/Homebrew/cmd/upgrade.rb:215:in `upgradable_dependents'
/Users/frizlab/usr/homebrew/Library/Homebrew/cmd/upgrade.rb:329:in `check_dependents'
/Users/frizlab/usr/homebrew/Library/Homebrew/cmd/upgrade.rb:60:in `upgrade'
/Users/frizlab/usr/homebrew/Library/Homebrew/brew.rb:105:in `&lt;main>'

  
  </pre>
</details>

# What you expected to happen

No infinite loop.

# Step-by-step reproduction instructions (by running `brew` commands)

On a fresh install of homebrew (I tested on commit 7ce517cb2d882f7ad130c89de5189c7dc3971084),
- Go in the homebrew-core project and checkout 72b71edb2859437d53070bfac9dac8801e601386 (or any commit where `libidn2` is at version 2.1.0);
- Install `ffmpeg` and all its dependencies _from source_.
- Upgrade homebrew-core to c5b7c329d87f141a0198e8b0dd95cc37cb49ba3d (or any commit where `libidn2` is at a version more recent than 2.1.0);
- Then simply `brew upgrade` (again, from source).

I also tried to find the source of the problem, and it turns out (unsurprisingly) it all boils down to the `upgradable_dependents` method (in `upgrade.rb`). Calling the method with the `ffmpeg` formula for instance make it go into an infinite loop. `ffmpeg` has two “descendants,” `gpac` and `x264`, which in turn have two “descendants,” `ffmpeg` and `ffmpeg@2.8`, which have two “descendants” etc.

 I have an idea on how to fix this (simply store the list of descendants, pass it in the method, and if a descendant found is already in the list of the found ones, just skip to the next). I might be able to PR if needed, but I’d need help, especially if I have to implement tests.

### PR DESCRIPTION
**Pull request by Frizlab**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb). <-- No, as discussed in #5711.
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Should fix #5711.

### CODE REVIEW

**Comment by Frizlab** [comment]
@MikeMcQuaid Here is my PR as discussed.

**Comment by MikeMcQuaid** [comment]
Thanks for the PR! I think this should probably throw a warning when circular dependencies are detected though. Could you add something similar? Would be good also to figure out how this ended up affecting you specifically, too (i.e. which formulae/kegs).

**Comment by Frizlab** [comment]
Added the warnings.
Currently, calling `check_dependents` with the `ffmpeg` formula triggers the recursive dependency and recursive broken dependent warning with `gpac` and `x264`. Calling `check_dependent` with `libidn2` triggers the warnings with `ffmpeg`, `gpgme` and `pass`.

**Comment by MikeMcQuaid** [comment]
> Currently, calling `check_dependents` with the `ffmpeg` formula triggers the recursive dependency and recursive broken dependent warning with `gpac` and `x264`.

I don't see `gpac` as a dependency for `ffmpeg`. Can I see your `brew info ffmpeg`, `brew config`, `brew deps --tree ffmpeg` and `brew doctor` output?

**Comment by Frizlab** [comment]
Here you go. A few notes:
- I have all my formulas compiled from source. I think this is key to get the bug;
- I have a non-/usr/local prefix on these brew info, but I have successfully reproduced the bug on an install with a standard prefix.

https://gist.github.com/Frizlab/79d83a27a0646cffdc7495c86b859744

**Comment by MikeMcQuaid** [comment]
Note that neither non-/usr/local nor building everything from source are supported configurations. Will still try and help regardless, though.

Can I see `brew deps --tree gpac` and `brew deps --tree x264` too? Thanks!

**Comment by Frizlab** [comment]
I updated the gist with the required info. I think the problem comes from the runtime dependencies (linked libraries), not from the ones declared in the Formula. Not sure though.

I had specifically reproduced the problem on a standard prefix because I knew you don’t support custom ones, but deleted the install since… as per everything installed from source, I just used the `--build-from-source` option 🤷‍♂️ Thanks a lot for helping :)

**Comment by MikeMcQuaid** [comment]
> I updated the gist with the required info. I think the problem comes from the runtime dependencies (linked libraries), not from the ones declared in the Formula. Not sure though.

Yes, I think there's been some opportunistic linking here that may have caused issues. Alternatively, this was due to a missing `revision` bump that caused this state to happen. This seems familiar from: https://github.com/Homebrew/homebrew-bundle/issues/420#issuecomment-453666630. Does this sound like a similar issue for you and does the suggested workaround resolve any of your issues?

**Comment by Frizlab** [comment]
I did have the issue with `brew bundle dump`, which has been fixed using the workaround given by brew itself. Will try and see if I can still reproduce the bug ASAP.

**Comment by Frizlab** [comment]
Just checked, forcing a call to `check_dependents` with `ffmpeg` does not end up in an infinite recursion anymore \o/
I still think the infinite recursion check should be done; but maybe with a better warning message?

**Comment by MikeMcQuaid** [comment]
> I still think the infinite recursion check should be done; but maybe with a better warning message?

I'm unsure if this is the place for it; things are going to blow up in lots of places if infinite recursion is detected. Perhaps `formula_installer` or similar would be a better place? I dunno. I'm hesitant to make this code more complex for an issue that seems to have passed.

**Comment by Frizlab** [comment]
I honestly don’t have enough knowledge of the Homebrew internals to know where this check should be.

All I know is I’m not the only person to have had encountered this issue, and to me a basic infinite recursion seems reasonable. Maybe the warning could simply be to solve issues brought up by brew bundle dump? I don’t know, I guess it’s a decision for the Homebrew team now ;)

**Comment by MikeMcQuaid** [comment]
> All I know is I’m not the only person to have had encountered this issue

Just to confirm: are you including the `brew bundle` folks or are there others you know of that aren't on the referenced issue? Thanks again!

**Comment by Frizlab** [comment]
I was referring to #5431 which was the original issue, on which I added my two cents, and said I'd try and find time to reproduce. Time went by and the issue was automatically closed, so I opened a new one (this one) when I found time to put myself on the problem again.

**Comment by MikeMcQuaid** [comment]
Thought about this some more and agreed it's worth 🚢ing.

Thanks so much for your contribution! Without people like you submitting PRs we couldn't run this project. You rock, @Frizlab!

**Comment by echosa** [comment]
@Frizlab I see you added this warning which I am now getting a bunch. However, I have no idea what to do to address this warning. When I `brew upgrade` to upgrade outdated packages, I get:

```
Warning: Found recursive upgradable dependent libsoup
Warning: Found recursive upgradable dependent homebank
Warning: Found recursive upgradable dependent homebank
Warning: Found recursive upgradable dependent homebank
Warning: Found recursive upgradable dependent homebank
Warning: Found recursive upgradable dependent vala
Warning: Found recursive upgradable dependent adwaita-icon-theme
Warning: Found recursive upgradable dependent gtk+3
Warning: Found recursive upgradable dependent homebank
Warning: Found recursive upgradable dependent librsvg
Warning: Found recursive upgradable dependent adwaita-icon-theme
Warning: Found recursive upgradable dependent gtk+3
Warning: Found recursive upgradable dependent homebank
Warning: Found recursive upgradable dependent librsvg
Warning: Found recursive upgradable dependent gtk+3
Warning: Found recursive upgradable dependent homebank
Warning: Found recursive upgradable dependent ffmpeg
Warning: Found recursive upgradable dependent adwaita-icon-theme
Warning: Found recursive upgradable dependent gtk+3
Warning: Found recursive upgradable dependent pango
Warning: Found recursive upgradable dependent homebank
Warning: Found recursive upgradable dependent librsvg
Warning: Found recursive upgradable dependent libass
Warning: Found recursive upgradable dependent glib-networking
Warning: Found recursive upgradable dependent ffmpeg
Warning: Found recursive upgradable dependent adwaita-icon-theme
Warning: Found recursive upgradable dependent libsoup
Warning: Found recursive upgradable dependent gtk+3
Warning: Found recursive upgradable dependent gts
Warning: Found recursive upgradable dependent pango
Warning: Found recursive upgradable dependent gdk-pixbuf
Warning: Found recursive upgradable dependent atk
Warning: Found recursive upgradable dependent harfbuzz
Warning: Found recursive upgradable dependent cairo
Warning: Found recursive upgradable dependent homebank
Warning: Found recursive upgradable dependent libcroco
Warning: Found recursive upgradable dependent vala
Warning: Found recursive upgradable dependent librsvg
Warning: Found recursive upgradable dependent libass
Warning: Found recursive upgradable dependent gsettings-desktop-schemas
Warning: Found recursive upgradable dependent ffmpeg
Warning: Found recursive upgradable dependent adwaita-icon-theme
Warning: Found recursive upgradable dependent gtk+3
Warning: Found recursive upgradable dependent pango
Warning: Found recursive upgradable dependent harfbuzz
Warning: Found recursive upgradable dependent homebank
Warning: Found recursive upgradable dependent librsvg
Warning: Found recursive upgradable dependent libass
Warning: Found recursive upgradable dependent adwaita-icon-theme
Warning: Found recursive upgradable dependent homebank
Warning: Found recursive upgradable dependent librsvg
Warning: Found recursive upgradable dependent libsoup
Warning: Found recursive upgradable dependent homebank
Warning: Found recursive upgradable dependent adwaita-icon-theme
Warning: Found recursive upgradable dependent homebank
Warning: Found recursive upgradable dependent ffmpeg
Warning: Found recursive upgradable dependent glib-networking
Warning: Found recursive upgradable dependent libsoup
Warning: Found recursive upgradable dependent gtk+3
Warning: Found recursive upgradable dependent homebank
Warning: Found recursive broken dependent libsoup
Warning: Found recursive broken dependent homebank
Warning: Found recursive broken dependent homebank
Warning: Found recursive broken dependent homebank
Warning: Found recursive broken dependent homebank
Warning: Found recursive broken dependent vala
Warning: Found recursive broken dependent adwaita-icon-theme
Warning: Found recursive broken dependent gtk+3
Warning: Found recursive broken dependent homebank
Warning: Found recursive broken dependent librsvg
Warning: Found recursive broken dependent adwaita-icon-theme
Warning: Found recursive broken dependent gtk+3
Warning: Found recursive broken dependent homebank
Warning: Found recursive broken dependent librsvg
Warning: Found recursive broken dependent gtk+3
Warning: Found recursive broken dependent homebank
Warning: Found recursive broken dependent ffmpeg
Warning: Found recursive broken dependent adwaita-icon-theme
Warning: Found recursive broken dependent gtk+3
Warning: Found recursive broken dependent pango
Warning: Found recursive broken dependent homebank
Warning: Found recursive broken dependent librsvg
Warning: Found recursive broken dependent libass
Warning: Found recursive broken dependent glib-networking
Warning: Found recursive broken dependent ffmpeg
Warning: Found recursive broken dependent adwaita-icon-theme
Warning: Found recursive broken dependent libsoup
Warning: Found recursive broken dependent gtk+3
Warning: Found recursive broken dependent gts
Warning: Found recursive broken dependent pango
Warning: Found recursive broken dependent gdk-pixbuf
Warning: Found recursive broken dependent atk
Warning: Found recursive broken dependent harfbuzz
Warning: Found recursive broken dependent cairo
Warning: Found recursive broken dependent homebank
Warning: Found recursive broken dependent libcroco
Warning: Found recursive broken dependent vala
Warning: Found recursive broken dependent librsvg
Warning: Found recursive broken dependent libass
Warning: Found recursive broken dependent gsettings-desktop-schemas
Warning: Found recursive broken dependent ffmpeg
Warning: Found recursive broken dependent adwaita-icon-theme
Warning: Found recursive broken dependent gtk+3
Warning: Found recursive broken dependent pango
Warning: Found recursive broken dependent harfbuzz
Warning: Found recursive broken dependent homebank
Warning: Found recursive broken dependent librsvg
Warning: Found recursive broken dependent libass
Warning: Found recursive broken dependent adwaita-icon-theme
Warning: Found recursive broken dependent homebank
Warning: Found recursive broken dependent librsvg
Warning: Found recursive broken dependent libsoup
Warning: Found recursive broken dependent homebank
Warning: Found recursive broken dependent adwaita-icon-theme
Warning: Found recursive broken dependent homebank
Warning: Found recursive broken dependent ffmpeg
Warning: Found recursive broken dependent glib-networking
Warning: Found recursive broken dependent libsoup
Warning: Found recursive broken dependent gtk+3
Warning: Found recursive broken dependent homebank
```

**Comment by Frizlab** [comment]
@echosa Try running `brew bundle dump`, fix the errors and then try again.

**Comment by echosa** [comment]
OK, so it looks like `brew bundle dump` dumps a file of all your taps and formulae so that you can reinstall everything with it? That's cool. I've done that now. (If I'm misunderstanding what that command does, please correct me.)

As for the "fix the errors" part, that's what I don't understand. I get I have recursive dependencies, it seems. I just don't know how to fix them. I see lots of repeated dependency issues. Do I uninstall and reinstall the dependencies? Uninstall/reinstall the formula that uses the dependencies? (I don't know which formula are affected here to do so.) Uninstall/reinstall everything? I'm not even quite sure how reinstalling would fix the dependency issues. The dependencies are defined in the formulae. If there's a recursive dependency defined that way, installation won't change that, I wouldn't think.

**Comment by Frizlab** [comment]
Mmmh I had the problem and @MikeMcQuaid suggested I tried running `brew bundle dump` to see if it was related to issue 
https://github.com/Homebrew/homebrew-bundle/issues/420. Turns out to me it was: the command was not able to run, and I had to reinstall some packages to make everything work correctly again (the command told me which packages to reinstall).

You seem to have another issue. Maybe @MikeMcQuaid could help; I don’t really know what’s happening under the hood, so I don’t know how to help you anymore than that.

**Comment by echosa** [comment]
Ah, I didn't realize that you mean the dump command itself was giving you errors. This does, indeed, sound like a different issue. I'll start a new issue so as not to keep cluttering this PR. Thanks!

**Pull request merged**
