### PR TITLE
enforce *.sourceforge.io and more for urls

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Add more URL checks to audit, following recent series of formula updates.

Alert will now go off for these URLs:
```
(http|git)://git.(savannah|sv).gnu.org/
(http|svn)://svn.(savannah|sv).gnu.org/
http://hg.(savannah|sv).gnu.org/
(http|git)://git.code.sf.net/
(http|svn)://svn.code.sf.net/
(http|git)://*.git.sourceforge.net/gitroot/
(http|svn)://*.svn.sourceforge.net/svnroot/
```

Plus, existing `*.sourceforge.io` homepage rule has been extended to `url` as well.
These will be redirected to insecure `.net` page unless the SourceForge project
maintainer enables HTTPS for these pages explicitly.

### CODE REVIEW

**Comment by ilovezfs** [comment]
The svn https ones should be disabled for < Sierra so we don't get false positives. Alternatively, we could automatically degrade svn https to http on < Sierra such that those URLs can lie on < Sierra and claim to be https when they're not. The latter is arguably unethical since we'd be claiming in the formula to be using secure URLs and then actually not doing so.

**Comment by vszakats** [comment]
You're right, I forgot about it. How to translate that rule to an audit check? To avoid all this messy ambiguity throughout each formula and audit rules, I'd prefer the downgrade approach. If this fact is clearly articulated towards the user, I think it should be fine.

**Comment by ilovezfs** [comment]
Yeah, "warning: degrading https to http since blah" would take care of that concern, I think.

**Comment by vszakats** [comment]
Closing this, probably won't have the required time/knowledge to implement it properly.

**Pull request closed without merging**
