### PR TITLE
Replace ronn with ronn-ng

### LINKED ISSUE #16861: `brew tests` fails wth Xcode 15.3 on Apple Silicon
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.2.11-103-gcd1f040
ORIGIN: https://github.com/Homebrew/brew
HEAD: cd1f0409493c77e7964cf03a0fb1e93d03a83772
Last commit: 6 hours ago
Core tap HEAD: 36f651b7c5ddf6dbe63d3335bb1035b0228c9f35
Core tap last commit: 36 minutes ago
Core tap JSON: 09 Mar 01:35 UTC
Core cask tap JSON: 09 Mar 01:35 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.3
Rosetta 2: false
```

### What were you trying to do (and why)?

Running `brew test` on my mac.

### What happened (include all command output)?

```
➜ brew tests
Fetching gem metadata from https://rubygems.org/.......
Installing hpricot 0.8.6 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/hpricot-0.8.6/ext/fast_xs
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby -I /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0 extconf.rb
checking for stdio.h... yes
creating Makefile

current directory: /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/hpricot-0.8.6/ext/fast_xs
make DESTDIR\= sitearchdir\=./.gem.20240308-64138-cc2lo sitelibdir\=./.gem.20240308-64138-cc2lo clean

current directory: /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/hpricot-0.8.6/ext/fast_xs
make DESTDIR\= sitearchdir\=./.gem.20240308-64138-cc2lo sitelibdir\=./.gem.20240308-64138-cc2lo
compiling fast_xs.c
fast_xs.c:165:39: error: incompatible function pointer types passing 'VALUE (VALUE)' (aka 'unsigned long (unsigned long)') to parameter of type 'VALUE (*)(VALUE,
VALUE)' (aka 'unsigned long (*)(unsigned long, unsigned long)') [-Wincompatible-function-pointer-types]
        array = rb_rescue(unpack_utf8, self, unpack_uchar, self);
                                             ^~~~~~~~~~~~
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/include/ruby-3.1.0/ruby/internal/iterator.h:364:62: note: passing argument to parameter 'r_proc' here
VALUE rb_rescue(VALUE (*b_proc)(VALUE), VALUE data1, VALUE (*r_proc)(VALUE, VALUE), VALUE data2);
                                                             ^
1 error generated.
make: *** [fast_xs.o] Error 1

make failed, exit code 2

Gem files will remain installed in /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/hpricot-0.8.6 for inspection.
Results logged to /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/extensions/arm64-darwin-20/3.1.0-static/hpricot-0.8.6/gem_make.out

  /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/rubygems/ext/builder.rb:102:in `run'
  /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/rubygems/ext/builder.rb:51:in `block in make'
  /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/rubygems/ext/builder.rb:43:in `each'
  /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/rubygems/ext/builder.rb:43:in `make'
  /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:42:in `build'
  /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/rubygems/ext/builder.rb:171:in `build_extension'
  /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/rubygems/ext/builder.rb:205:in `block in build_extensions'
  /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/rubygems/ext/builder.rb:202:in `each'
  /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/rubygems/ext/builder.rb:202:in `build_extensions'
  /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/rubygems/installer.rb:843:in `build_extensions'
  /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.18/lib/bundler/rubygems_gem_installer.rb:72:in `build_extensions'
  /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.18/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.18/lib/bundler/source/rubygems.rb:202:in `install'
  /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.18/lib/bundler/installer/gem_installer.rb:54:in `install'
  /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.18/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.18/lib/bundler/installer/parallel_installer.rb:156:in `do_install'
  /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.18/lib/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.18/lib/bundler/worker.rb:62:in `apply_func'
  /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.18/lib/bundler/worker.rb:57:in `block in process_queue'
  /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.18/lib/bundler/worker.rb:54:in `loop'
  /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.18/lib/bundler/worker.rb:54:in `process_queue'
  /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.18/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing hpricot (0.8.6), and Bundler cannot continue.

In Gemfile:
  ronn was resolved to 0.7.3, which depends on
    hpricot
Error: failed to run `/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/bin/bundle install`!
```

### What did you expect to happen?

`brew tests` should be successful and brew tests should be usuable for creating PRs.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew update`
`brew tests`
```

### PR DESCRIPTION
**Pull request by fel1x-developer**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Resolves #16861. ronn had its last update in 2010. ronn-ng supports 2.7 to 3.3 (https://github.com/apjanke/ronn-ng/blob/8ab6acc5c08f464539817d209f878659b0c1adf6/doc-project/Developer-Guide.md?plain=1#L54)

Someone needs to test if this work as what we expect. If so, this a new version including this patch should be released ASAP (macOS 14.4 & Xcode CLT 15.3 is already out!)

### CODE REVIEW

**Comment by fel1x-developer** [comment]
How can I solve this CI failure?

**Comment by apainintheneck** [comment]
Thanks for looking into this.

Are we sure that `ronn-ng` is that alternative man page generator that we want to use here? @Bo98 I see that you self-assigned the original issue. Is this what you had in mind?

Also, we don't want to vendor dev dependencies like this. That's why the check is failing. For the man page gems, we specifically download them whenever `brew generate-man-completions` is run in the following snippet which installs the `:man` group of gems in the gemfile. That's why `ronn` is currently listed as both optional and not required.

https://github.com/Homebrew/brew/blob/08442734ab9a62a333e92f08747f655ffe5dca0f/Library/Homebrew/Gemfile#L30-L32

https://github.com/Homebrew/brew/blob/08442734ab9a62a333e92f08747f655ffe5dca0f/Library/Homebrew/manpages.rb#L31

**Comment by fel1x-developer** [comment]
> Are we sure that `ronn-ng` is that alternative man page generator that we want to use here? @Bo98 I see that you self-assigned the original issue. Is this what you had in mind?

ronn-ng has the cloest functionality to ronn, and this can serve as a temporary solution while @Bo98 is figuring out what's going on and bring up a better solution.

**Comment by dduugg** [comment]
Thanks for your first contribution!

It looks like `ronn-ng` has `nokogiri` as a transitive dependency. However, I noticed a note in the Gemfile that nokogiri is a disallowed dependency. (Introduced in [this](https://github.com/Homebrew/brew/pull/11630/files#diff-bfa830a23df042dc1ef7a0634aeb44e555d82bd2dc5686e41d9d25b259989e6eR5-R6) PR, cc @samford)

**Comment by dduugg** [comment]
You disregard my last message, I see @Bo98 noticed this issue too, and opened https://github.com/Homebrew/brew/pull/16868 <3

**Comment by fel1x-developer** [comment]
> You disregard my last message, I see @Bo98 noticed this issue too, and opened #16868 <3

Thanks for info! Closing this PR. Followed by #16868

**Pull request closed without merging**
