### PR TITLE
update: migrate everyone from linuxbrew-core to homebrew-core

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@iMichka Agreed. I'd like `GITHUB_ACTIONS` to land sooner rather than later, though, because it's a large proportion of our usage.

**Comment by MikeMcQuaid** [comment]
> Instead of forcing a migration onto GitHub Actions, we really should update the default install remote in Homebrew/install and allow GitHub to ship new images that use this remote (since new image versions are clean built). That means migration will not be required at all from GitHub Actions.

We don't have control over when GitHub does that. We can ask but it's unlikely that they will before this is in a new tag. You'll also only end up on this commit if `HOMEBREW_DEVELOPER` and/or `homebrew.devcmdrun` are set.

> The docker image used by the CI is built by this dockerfile (https://github.com/Homebrew/brew/blob/master/Dockerfile), right? It does not use install.sh, so not sure how this is going to change the images we ship.

Anything that doesn't reference `Homebrew/linuxbrew-core` specifically but does `homebrew-core` will change after this PR. This means these images will be updated but not for the tagged ones.

**Comment by XuehaiPan** [comment]
Hi, I'm very glad to see this migration to let users have unified settings for Homebrew on both macOS and Linux. May I ask is there any migration plan for formula bottles (`HOMEBREW_BOTTLE_DOMAIN`)?

https://github.com/Homebrew/brew/blob/ff2985c6aa4a22cc8773e7ed385875ca6e1b99a7/Library/Homebrew/env_config.rb#L41-L52

https://github.com/Homebrew/brew/blob/ff2985c6aa4a22cc8773e7ed385875ca6e1b99a7/Library/Homebrew/env_config.rb#L87-L92

**Comment by iMichka** [comment]
Tested and the migration is not done anymore:

```
$ docker run -it homebrew/ubuntu16.04
$ cd /home/linuxbrew/.linuxbrew/Homebrew
$ git remote add iMichka https://github.com/iMichka/brew
$ git fetch iMichka
$ git checkout migrate2
$ brew update
HOMEBREW_CORE_GIT_REMOTE set: using https://github.com/Homebrew/linuxbrew-core for Homebrew/core Git remote.
remote: Enumerating objects: 42040, done.
remote: Counting objects: 100% (19560/19560), done.
remote: Compressing objects: 100% (2501/2501), done.
remote: Total 42040 (delta 17245), reused 19369 (delta 17059), pack-reused 22480
Receiving objects: 100% (42040/42040), 14.15 MiB | 1.53 MiB/s, done.
Resolving deltas: 100% (32291/32291), completed with 1831 local objects.
From https://github.com/Homebrew/linuxbrew-core
   70d37801899..5be975b7335  master     -> origin/master
...
Migrating formulae from linuxbrew-core to homebrew-core
...
```

The remote stays on linuxbrew-core.

**Comment by Bo98** [comment]
Ah I just noticed you said this broke the syntax job before? Sorry, wasn't following very closely.

**Comment by iMichka** [comment]
Tested on my side, it worked. Thanks @MikeMcQuaid for all the cleanup! I feel free now :)

**Pull request merged**
