### PR TITLE
Implement `VCSDownloadStrategy#last_commit`

### PR DESCRIPTION
**Pull request by vladshablinsky**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

# Description

* Add `VCSDownloadStrategy#last_commit`
* Add `GitDownloadStrategyTests`

This PR is a part of https://github.com/Homebrew/brew/pull/274, so merged commits will be removed from https://github.com/Homebrew/brew/pull/274.

cc @MikeMcQuaid @xu-cheng

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
👍 :shipit:

**Comment by UniqMartin** [comment]
:+1:

**Comment by xu-cheng** [comment]
Thanks everyone.

**Comment by UniqMartin** [comment]
FYI, I just fixed a minor problem with this in 32f7e738ecfd84e1d8a063f9af332fdc320dfb7d. It felt innocent enough that I committed it directly. Noticed this because I have a non-standard `core.abbrev` setting and the test suite was failing:

```
  1) Failure:
GitDownloadStrategyTests#test_last_commit [/opt/homebrew/Library/Homebrew/test/test_download_strategies.rb:122]:
--- expected
+++ actual
@@ -1 +1 @@
-"c50c79b"
+"c50c79b9"
```

**Comment by vladshablinsky** [comment]
@UniqMartinI have read git documentation and now understand that I was wrong. Thanks for the fix!
I thought `git --git-dir rev-parse --short HEAD` would print `k` first symbols of revision string where `k` is the minimum length more or equal to 6 so that no other revision starts with that string.

So I would probably correct it this way if I wouldn't realise git works pretty different from my expectations:

```ruby
assert "c50c79b9573c9482b9178a1882695fbbcd36fe7d".start_with?(@strategy.last_commit)
```
Thanks again!

**Comment by UniqMartin** [comment]
No worries! I also overlooked this detail when reviewing this PR. Your snippet, that would have changed the related test instead of the implementation, is also a perfectly valid fix for the test failure.

The reason I decided to make the change in the implementation is because I was of the opinion that these shortened commit hashes will eventually be used for the improved `HEAD` installation support, i.e. they will be used to create a “version number” like `HEAD-<last_commit>`. (Please correct me if I'm wrong about this.) If that's the case, it would be odd that this generated “version number” will be different across different systems with different Git configurations. (Of course there's also the small chance that the 7-character hash becomes non-unique as more commits are added to the repository, which would also change the output of `git rev-parse --short` even if the `=7` is added.)

**Comment by vladshablinsky** [comment]
> Please correct me if I'm wrong about this.

Everything is right. I'm OK with your fix, it makes sense for me.

**Pull request closed without merging**
