### PR TITLE
Add cask renames

### PR DESCRIPTION
**Pull request by FnControlOption**
- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

This adds support for `cask_renames.json` (`formula_renames.json` for casks).

Some notes:

- [`update-report` doesn't report cask renames, which I have started working on.](https://github.com/FnControlOption/brew/commit/da5bc7b8c925fba5ac8e7e9435d1bb2412dac50f)
- The documentation and tests so far are from https://github.com/Homebrew/brew/pull/12189
- There are probably some places that use `Formula#oldname` which I have ignored.

Affected homebrew-cask PRs:

- [110172: `youtube-dl-gui` was renamed to `open-video-downloader`](https://github.com/Homebrew/homebrew-cask/pull/110172)
- [114668: `alt-tab` should be renamed to `alttab`](https://github.com/Homebrew/homebrew-cask/pull/114668)

### CODE REVIEW

**Review by MikeMcQuaid — COMMENTED** [review]
Looking great so far, nice work 👏🏻

**Comment by miccal** [comment]
Great work @FnControlOption.

Ping @vitorgalvao and @reitermarkus.

**Comment by vitorgalvao** [comment]
Thank you @FnControlOption (by the way, does that combination of keys means something in particular?), looking forward to having this in!

**Comment by bevanjkay** [comment]
Just flagging https://github.com/Homebrew/homebrew-cask/pull/115569 `sunlogincontrol` as a cask that would benefit from renaming/alias.

**Pull request closed without merging**
