### PR TITLE
update-python-resources: add `--package-name` flag

### PR DESCRIPTION
**Pull request by SeekingMeaning**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?
- [x] Have you successfully run `brew man` locally and committed any changes?

-----

This allows for updating the resources of Python formulae that include optional dependencies

Example usage:

```bash
brew update-python-resources --package-name='xonsh[ptk,pygments,proctitle]' xonsh
```

Related: Homebrew/homebrew-core#61327

### CODE REVIEW

**Review by Rylan12 — COMMENTED** [review]
Nice idea! I wonder if there's a way to automatically use a different package name for certain formulae? Maybe the blacklist could be modified to map formula names to package names if they are different so these known exceptions could be handled automatically?

**Comment by dtrodrigues** [comment]
I think doing it in the brew PyPI code or maybe adding it to the formula itself would be a good idea since the exact package(s) needed don't generally change from version to version.

**Comment by MikeMcQuaid** [comment]
> Nice idea! I wonder if there's a way to automatically use a different package name for certain formulae? Maybe the blacklist could be modified to map formula names to package names if they are different so these known exceptions could be handled automatically?
> I think doing it in the brew PyPI code or maybe adding it to the formula itself would be a good idea since the exact package(s) needed don't generally change from version to version.

Either of these sound nice!

**Comment by Rylan12** [comment]
@SeekingMeaning any progress? If not, I may open a new PR to implement this

**Comment by Rylan12** [comment]
Closing in favor of #9185

**Pull request closed without merging**
