### PR TITLE
gpg: use with_homebrew_path

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Fixes calling things like `Gpg.available?` in `brew irb`, etc. Or anywhere that uses the protected `PATH`, really.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
This isn't correct behaviour in an `install` method where it should be doing PATH lookup based on a Requirement or Dependency addition.

**Comment by DomT4** [comment]
Sure. I'm open to suggestions that are better than having an audit to bar `Gpg.` calls inside `def install`. It seems like `brew irb` is a perfectly valid place where you'd want to be able to test/use `Gpg.` stuff though and currently you can't, because `brew irb` is PATH-shielded under the new ENV filtering.

**Comment by ilovezfs** [comment]
Can we remove the Gpg module altogether?
```
Josephs-MacBook-Pro:Formula joe$ ag 'Gpg\.'
duplicity.rb
327:    Gpg.test(testpath) do

rpm.rb
52:    gnupg = Gpg.executable || HOMEBREW_PREFIX/"bin/gpg"
```
It would take about 5 minutes to remove its use from formulae.

**Comment by DomT4** [comment]
It's final broad use wasn't exclusively formula-based, although I appreciate you'd have to have a long memory to remember that by now.

**Comment by ilovezfs** [comment]
Can you elaborate? I'm not understanding what function it's serving in `brew` at this point.

**Comment by DomT4** [comment]
https://github.com/Homebrew/brew/pull/786, https://github.com/Homebrew/brew/pull/676, https://github.com/Homebrew/brew/pull/675, https://github.com/Homebrew/brew/pull/674, https://github.com/Homebrew/brew/pull/386.

**Comment by ilovezfs** [comment]
OK, thanks. All of those look self-referential as opposed to anything in use currently.

The only actual, current use of gpg appears to be in casks right now with stuff like
```
gpg "#{url}.asc", key_id: '9032cae4cbfa933a5a2145d5ff97c53f183c045d'
```

I don't know if that depends on the Gpg module or not. CC @reitermarkus

**Comment by DomT4** [comment]
> I don't know if that depends on the Gpg module or not.

It doesn't.

> All of those look self-referential as opposed to anything in use currently.

Yes, this is correct. A lot of the back & forth over the GPG stuff and the resulting stress over effectively turning Homebrew into a job contributed significantly to my decision to walk away as a maintainer, and indeed more or less stop contributing for a while. But the intention wasn't to abandon it, which is why I've kept trimming & tweaking it since.

**Comment by MikeMcQuaid** [comment]
@DomT4 I think it's just worth deprecating at this point I'm afraid as it's not been widely used in formulae. Doing that as part of https://github.com/Homebrew/brew/pull/3612.

**Comment by DomT4** [comment]
Alright.

**Pull request closed without merging**
