### PR TITLE
use `https://` rather than `http://`

### PR DESCRIPTION
**Pull request by retokromer**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Should improve https://github.com/Homebrew/brew/pull/4608#issuecomment-410666735.

### CODE REVIEW

**Comment by reitermarkus** [comment]
@retokromer, I think there are a bunch of other tests also using the `http://` version, mind having a look as those too?

**Comment by retokromer** [comment]
@reitermarkus Yes, most probably there are. I’ll give a look.

**Comment by retokromer** [comment]
@reitermarkus A very few are still insecure, because the script who fetched received an error.

**Comment by reitermarkus** [comment]
You'll also need to change them in the cask files inside `test/support/fixtures/cask/Casks`.

**Comment by reitermarkus** [comment]
Great work, @retokromer. Thanks!

**Pull request merged**
