### PR TITLE
cask doctor: sip status

### PR DESCRIPTION
**Pull request by commitay**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----
cc @vitorgalvao @reitermarkus

### CODE REVIEW

**Comment by ilovezfs** [comment]
Have you tested this in configurations such as
```
csrutil enable --without debug,dtrace,kext
```

**Comment by commitay** [comment]
Yep, it works but it it doesn't really look 100%.

I could remove the `this is an unsupported configuration ...` to make the output a bit nicer?

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.4.3-28-g50b2657
caskroom/homebrew-cask (git revision 23e1; last commit 2018-01-12)
==> macOS
10.12.6
==> SIP
Enabled
==> Java
N/A
```
```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.4.3-28-g50b2657
caskroom/homebrew-cask (git revision 23e1; last commit 2018-01-12)
==> macOS
10.12.6
==> SIP
Disabled
==> Java
N/A
```
```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.4.3-28-g50b2657
caskroom/homebrew-cask (git revision 23e1; last commit 2018-01-12)
==> macOS
10.12.6
==> SIP
Enabled (custom configuration).

configuration:
	apple internal: disabled
	kext signing: enabled
	filesystem protections: enabled
	debugging restrictions: disabled
	dtrace restrictions: enabled
	nvram protections: enabled
	basesystem verification: enabled

this is an unsupported configuration, likely to break in the future and leave your machine in an unknown state
==> Java
N/A
```

**Comment by commitay** [comment]
```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.4.3-31-gdf08bf2-dirty
caskroom/homebrew-cask (git revision 3d861; last commit 2018-01-12)
==> macOS
10.12.6
==> SIP
Enabled (custom configuration)

configuration:
apple internal: disabled
kext signing: enabled
filesystem protections: enabled
debugging restrictions: disabled
dtrace restrictions: enabled
nvram protections: enabled
basesystem verification: enabled
==> Java
N/A
```

**Comment by commitay** [comment]
👍  unless anyone has code suggestions.

**Pull request merged**
