### PR TITLE
Strategy: Use GET for checking response head again

### PR DESCRIPTION
**Pull request by samford**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

This is a follow-up to #15089, where `Livecheck::Strategy::PAGE_HEADERS_CURL_ARGS` was modified to use a `HEAD` request instead of `GET`. Unfortunately I wasn't able to review the PR before it was merged and the change breaks 31 previously-working `HeaderMatch` checks (see the PR description in #15099 for a detailed list).

In these cases, the server returns a 200 (OK) response when using a `HEAD` request and a `GET` request is required to trigger a redirection. Without a `location` header in the response head(s), the checks predictably return an `Unable to get versions` error.

In the long term, using a `HEAD` request as the default makes sense when we're able to manually account for checks that require a `GET` request in the relevant `livecheck` block but this isn't possible yet. In the interim time, returning to using `GET` requests by default seems sensible in light of these broken checks (i.e., breaking 33 checks to fix one feels like a poor trade-off at the moment).

-----

Being able to add to the `curl` args in a `livecheck` block is one of the initial uses cases for the `options` feature that I've been talking about for ages. I need to take another pass through that work before creating a PR but I'll try to finally get it out this weekend or next week (it's been one of the items at the top of my to-do list recently).

### CODE REVIEW

**Comment by Bo98** [comment]
> In the long term, using a HEAD request as the default makes sense

I'm fine with a quick revert like this but we've been asked before to stop using GET because it wastes server resources so we should figure something out.

**Comment by samford** [comment]
It _should_ be technically possible to add some logic to `HeaderMatch` to retry `Strategy#page_headers` with `--request GET` added to the curl args when we don't have any matches, which would fix these checks. However, this also requires some changes to `#page_headers` to be able to accept and use additional curl args and those changes overlap with the `options` work. "Long term" was perhaps the wrong language to use, since hopefully I should be able to get the `options` feature merged in the near-term.

That said, let me do some tinkering. If the aforementioned changes aren't too bad, then I can just update this PR to implement a workaround instead of reverting back to using GET requests (I don't relish the idea of wasting server resources for no reason either).

**Comment by samford** [comment]
@Bo98 I've opened #15099, which adds some retry logic to `HeaderMatch` as an alternative to switching back to `GET` for all `#page_headers` requests. The `#page_headers` changes in that PR come directly from the forthcoming `options` work, so that shouldn't require any rework. I was able to structure the retry logic in `HeaderMatch` in a way that should be easy to walk back once the `options` feature is available, so it wasn't too bad to implement.

**Comment by reitermarkus** [comment]
@samford can you post a `curl` command that fails without `--request GET`? Or maybe multiple to see if they all result in the same error code.

**Comment by reitermarkus** [comment]
Oh, so they don't even fail but don't redirect the same way?

> we've been asked before to stop using GET because it wastes server resources

Can you link to some of these requests? I would argue upstream should provide a proper appcast if they don't want us using `GET` and `:url` to get the latest version.

**Comment by reitermarkus** [comment]
Seems like a bunch of these fail with a CloudFront cache miss, e.g.

```
X-Cache: Error from cloudfront
```

```
x-cache: Miss from cloudfront
```

**Comment by reitermarkus** [comment]
I guess the fix is: Retry with `--request GET` if we didn't get a `Content-Disposition` header with `--head` alone.

**Review by MikeMcQuaid — APPROVED** [review]

**Review by MikeMcQuaid — CHANGES_REQUESTED** [review]
Thanks for PR! Have opened a PR to revert the original as cask change causing issues too.

**Pull request closed without merging**
