### PR TITLE
Slight Further Improvement to '`man`' Page Formatting

### PR DESCRIPTION
**Pull request by RandomDSdevel**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?  
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?  
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?  (Yes, see my first commit message.)  
- [ ] Have you written new tests for your changes?  [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).  (N/A; the '`man`' pages aren't currently covered by any tests, and…I suspect writing some for them&thinsp;—&thinsp;other than '`brew man --fail-if-changed`,' anyway, which wouldn't apply here upon running CI since I've already run '`brew man`'&thinsp;—&thinsp;might get at least a bit tricky…?  In any case, I didn't try to.)  
- [x] Have you successfully run '`brew style`' with your changes locally?  
- [ ] Have you successfully run '`brew tests`' with your changes locally?  (No, but I didn't encounter any new, unexpected failures other than those resulting from some&thinsp;—&thinsp;potentially or likely flaky&thinsp;—&thinsp;tests simply timing out.)  
- [x] Have you successfully run '`brew man`' locally and committed any changes?  

-----

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This PR follows up on commit '`eb16624c5`' from @EricFromCanada's #9136 with a small fix.

### CODE REVIEW

**Comment by EricFromCanada** [comment]
https://docs.brew.sh/ follows the HTML5 standard rather than XHTML, so the `<br>` tag is still valid.

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Somebody might go looking for the closing tag, though…  (_Shrugs._)  I'll modify my first commit's message to avoid mentioning XHTML.

**Comment by reitermarkus** [comment]
Does this fix anything? I fail to see how this improves formatting, in my opinion it's less readable with `<br />`.

**Comment by MikeMcQuaid** [comment]
Passing on this.

**Comment by RandomDSdevel** [comment]
@reitermarkus:  

> Does this fix anything? I fail to see how this improves formatting, in my opinion it's less readable with `<br />`.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;It's bad form not to close a tag, isn't it?  This way it's explicitly an empty tag that doesn't need closing.  I'm not going to split any more hairs over it, though.  

---

@MikeMcQuaid:  

> Passing on this.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fair enough.

**Comment by MikeMcQuaid** [comment]
>      It's bad form not to close a tag, isn't it? This way it's explicitly an empty tag that doesn't need closing. I'm not going to split any more hairs over it, though.

This reply is splitting hairs. Please adjust your communication accordingly.

**Comment by MikeMcQuaid** [comment]
@RandomDSdevel just to flesh this out a bit more: we've talked previously about productive and non-productive contributions to the project. Productive contributions are:
- submitting fixes or reproducible issues for bugs that you feel are likely to be encountered by multiple users with no `brew doctor` warnings in supported configurations (i.e. not building from source)
- not style-related if there's any possibility of debate over style
- well-communicated with concise communication
- defer to the opinions of the maintainers on how best to run the project/use style

You have made several productive contributions in the past and we hope to see more from you in future. Thanks again ❤️

**Pull request closed without merging**
