### PR TITLE
mac/xcode: update expected Clang on 10.13

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-----

🤷‍♂️

### CODE REVIEW

**Comment by DomT4** [comment]
A surprisingly dull update this time around. Nothing new seems to have broken, at least.

**Comment by ilovezfs** [comment]
@DomT4 https://github.com/wxWidgets/wxWidgets/pull/533/#issuecomment-320655479

**Comment by DomT4** [comment]
Yeah I saw, I just hadn't responded yet. I didn't really do anything with or related to Homebrew yesterday at all.

**Comment by ilovezfs** [comment]
>I didn't really do anything with or related to Homebrew yesterday at all.

You know that's against the rules.

**Comment by MikeMcQuaid** [comment]
Ta again @DomT4!

**Pull request merged**
