### PR TITLE
Revert "Remove HOMEBREW_BOTTLE_DOMAIN"

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Reverts Homebrew/brew#11781

### CODE REVIEW

**Comment by carlocab** [comment]
I think we wanted to include this in the latest tag, no?

**Comment by MikeMcQuaid** [comment]
@carlocab We did: https://github.com/Homebrew/brew/commit/bdc3391a1319f1c40a108d14a077ca0964b33a3f. It was just omitted from the release notes.

**Comment by carlocab** [comment]
Aha, whoops. Missed that!

**Comment by MikeMcQuaid** [comment]
Have manually removed from release notes.

**Pull request merged**
