### PR TITLE
dispatch-build-bottle: rename --wheezy to --linux-wheezy

### PR DESCRIPTION
**Pull request by dawidd6**
@MikeMcQuaid asked to rename this flag.

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

**Review by Rylan12 — COMMENTED** [review]
Is it possible that this could be in use by other taps? If so, we need to deprecate and set up a `replacement: "--linux-wheezy"`

**Comment by dawidd6** [comment]
Highly unlikely, it was introduced recently for our internal usage.

**Comment by Rylan12** [comment]
Ah, didn't realize it was only added 10 days ago 👍

**Review by Rylan12 — APPROVED** [review]

**Review by MikeMcQuaid — APPROVED** [review]
Thanks for this 😍

**Pull request merged**
