### PR TITLE
.github/workflows/tests.yml: Deploy Docker image

### PR DESCRIPTION
**Pull request by sjackman**
Deploy the `latest` Docker image on a push to `master`.
Deploy a tagged Docker image upon publication of a release.

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

### CODE REVIEW

**Comment by sjackman** [comment]
GitHub Actions has failed with:
```
Error: No known CI provider detected! If you are using GitHub Actions or Jenkins
ghprb-plugin, then we cannot find the expected environment
variables! Check you have e.g. exported them to a Docker container.
```
https://github.com/Homebrew/brew/pull/7219/checks?check_run_id=534724942
That's unexpected. I don't believe that my PR could have caused this error.

**Comment by Bo98** [comment]
That always happens on the Linux runner.

The error appears to be:

```
Error response from daemon: No such image: brew_sut:latest
```

**Comment by jonchang** [comment]
I would prefer that this be a `scheduled` event in Homebrew/brew rather than an on-push event in Homebrew/homebrew-core. I think core is too high-volume to do something like this. (Incidentally I think that formulae.brew.sh builds should also be scheduled in that repository, rather than as an on-push build).

**Comment by Bo98** [comment]
If I understand correctly, this is about [GitHub Packages](https://github.com/Homebrew/brew/packages/29947) rather than Docker Hub.

**Comment by sjackman** [comment]
Currently this PR is for GitHub Packages (GHP). My intention is to replace Docker Hub, to simplify and standardize on GitHub Actions.

**Comment by dawidd6** [comment]
Currently pulling images from Github Packages Registry requires authentication, so I don't think it's good for users yet.

**Comment by sjackman** [comment]
> Currently pulling images from Github Packages Registry requires authentication, so I don't think it's good for users yet.

I don't believe that's true. See https://github.com/Homebrew/brew/packages/29947

My plan is for GitHub Actions to push to both GitHub Packages Registry and Docker Hub. Once that's working, I'll disable Docker Hub Automated Build.

**Comment by dawidd6** [comment]
See: https://github.community/t5/GitHub-Actions/docker-pull-from-public-GitHub-Package-Registry-fail-with-quot/m-p/32888#M1294

**Comment by SMillerDev** [comment]
running: `docker pull docker.pkg.github.com/homebrew/brew/brew:2.2.11`
```
Error response from daemon: Get https://docker.pkg.github.com/v2/homebrew/brew/brew/manifests/2.2.11: no basic auth credentials
```

**Pull request merged**
