### PR TITLE
archive: delete

### PR DESCRIPTION
**Pull request by FnControlOption**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

These lines in `Archive#upload_bottles`:

```rb
      directory = if formula_tap_repo
        "bottles-#{tap.repo}"
      else
        "bottles"
      end
```

came from this method in `Utils::Bottles::Bintray` (which was deleted in b914411):

```rb
      def self.repository(tap = nil)
        if tap.nil? || tap.core_tap?
          "bottles"
        else
          "bottles-#{tap.repo}"
        end
      end
```

However, `upload_bottles` does not have a `tap` parameter, and `tap.repo` should be replaced with `formula_tap_repo`.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Thanks @FnControlOption! Are you using this to upload to the Internet Archive or did you just notice it? I'm wondering if this code should be removed if it was broken and no-one noticed.

**Comment by FnControlOption** [comment]
Not using it. Found this with `brew typecheck`. I agree that this can safely be deleted if no one has opened issue about this from when b914411 was pushed to `master` to now. However, I don't know exactly how this works, so I'll defer to you.

**Comment by MikeMcQuaid** [comment]
@FnControlOption I reckon just open a pull request to remove this. Thanks!

**Comment by MikeMcQuaid** [comment]
(or update this one to do so, even better)

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks again @FnControlOption!

**Pull request merged**
