### PR TITLE
Add `mdimporter` stanza to homebrew cask DSL

### PR DESCRIPTION
**Pull request by vladimyr**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

This PR adds a new stanza `mdimporter` to homebrew cask DSL. It allows easier installation of Spotlight metadata importers in the same vein as `qlpugin` does for Quicklight plugins. Code is pretty much straight c/p of `Qlplugin` artifact class (and related stuff) with necessary renames and modified install phase action.

This would allow things like [`markdownmdimporter`](https://github.com/Homebrew/homebrew-cask/blob/9372fac/Casks/markdownmdimporter.rb) cask to be rewritten from 
```rb
cask 'markdownmdimporter' do
  version :latest
  sha256 :no_check

  url 'https://brettterpstra.com/downloads/Markdown.mdimporter.zip'
  name 'Markdown Spotlight Plugin'
  homepage 'https://brettterpstra.com/2011/10/18/fixing-spotlight-indexing-of-markdown-content/'

  artifact 'Markdown.mdimporter', target: "#{ENV['HOME']}/Library/Spotlight/Markdown.mdimporter"

  postflight do
    system_command '/usr/bin/mdimport', args: ['-r', "#{ENV['HOME']}/Library/Spotlight/Markdown.mdimporter"]
  end
end
```
to:
```rb
cask 'markdownmdimporter' do
  version :latest
  sha256 :no_check

  url 'https://brettterpstra.com/downloads/Markdown.mdimporter.zip'
  name 'Markdown Spotlight Plugin'
  homepage 'https://brettterpstra.com/2011/10/18/fixing-spotlight-indexing-of-markdown-content/'

  mdimporter 'Markdown.mdimporter'
end
```

### CODE REVIEW

**Comment by vitorgalvao** [comment]
I’m fine with the addition. It will also need some short documentation on the HBC repo.

**Comment by vladimyr** [comment]
I'll do follow up pr with docs.

**Comment by MikeMcQuaid** [comment]
@vladimyr Can you rebase this on `master` (or amend your commit) and force-push? Something weird going on with GitHub Actions.

**Comment by MikeMcQuaid** [comment]
Oh: ignore me, building now.

**Comment by MikeMcQuaid** [comment]
And it's failed again, boo. Yeh, if you wouldn't mind doing what I asked above that'd be great!

**Comment by vladimyr** [comment]
> And it's failed again, boo. Yeh, if you wouldn't mind doing what I asked above that'd be great!

Just did 🤞

**Comment by MikeMcQuaid** [comment]
Thanks so much for your contribution! Without people like you submitting PRs we couldn't run this project. You rock, @vladimyr!

**Comment by vladimyr** [comment]
Thank you for kind words and for serving the community through Homebrew!

**Comment by SMillerDev** [comment]
https://discourse.brew.sh/t/cask-definition-is-invalid-invalid-mdimporter-stanza-key-not-found-mdimporterdir/7452 can anyone help fix this?

**Comment by claui** [comment]
> https://discourse.brew.sh/t/cask-definition-is-invalid-invalid-mdimporter-stanza-key-not-found-mdimporterdir/7452 can anyone help fix this?

Should be addressed in #7417.

**Pull request merged**
