### PR TITLE
caveats.rb: empty method on Linux

### PR DESCRIPTION
**Pull request by maxim-belkin**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

`plist_caveats` does not apply to Linux so we have to override it to an empty method.

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Forgot to mention @sjackman to chime in/check

**Comment by sjackman** [comment]
Thanks for this Maxim. There's a bit more work needed. The existing `plist_caveats` method needs to move to a file `extend/os/mac/caveats.rb`. Create a file `extend/os/caveats.rb` with contents
```ruby
if OS.mac?
  require "extend/os/mac/caveats"
elsif OS.linux?
  require "extend/os/linux/caveats"
end
```

Add to the end of `Library/Homebrew/caveats.rb`
```ruby
require "extend/os/system_config"
```

**Comment by maxim-belkin** [comment]
OK, will do

If only there was a variable to add a single line, instead of 5
```
require "extend/os/#{os}/caveats"
```

**Comment by sjackman** [comment]
There's `ENV["HOMEBREW_SYSTEM"]` which has the value `Macintosh`.
I'd suggest creating a global variable in `os.rb` named `OS::SYSTEM` that takes the values `mac`, `linux`, and `generic`.

The file `"extend/os/#{os}/caveats"` may not exist, so it'd have to be something like…
```ruby
require "extend/os/#{os}/caveats" if (HOMEBREW_REPOSITORY/"extend/os"/os/"caveats.rb").readable?
```

@MikeMcQuaid Your thought on the above, rather than the current…
```ruby
if OS.mac?
  require "extend/os/mac/system_config"
elsif OS.linux?
  require "extend/os/linux/system_config"
end
```

**Comment by maxim-belkin** [comment]
> ```
> require "extend/os/#{os}/caveats" if (HOMEBREW_REPOSITORY/"extend/os"/os/"caveats.rb").readable?

Is it possible / OK to "extend" the `require` method?

**Comment by sjackman** [comment]
I wouldn't extend it, but you could define a new method `require_if_available` (or some name).

**Comment by maxim-belkin** [comment]
Made the changes without creating any new variable(s).

**Comment by sjackman** [comment]
```
Library/Homebrew/extend/os/mac/caveats.rb:45:1: C: Extra empty line detected at class body end.
```
https://travis-ci.org/Homebrew/brew/jobs/288642476#L860

**Comment by maxim-belkin** [comment]
Yes, I noticed that after I pushed it :)

**Comment by maxim-belkin** [comment]
Fixed!

**Comment by MikeMcQuaid** [comment]
Thanks again @maxim-belkin!

**Pull request merged**
