### PR TITLE
components_order_cop: add post_install

### PR DESCRIPTION
**Pull request by commitay**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
https://github.com/Homebrew/homebrew-core/pull/27153

### CODE REVIEW

**Comment by commitay** [comment]
Others that would be nice to have audited:

- `deprecated_option`: 36 formulae

- `fails_with`: 13 formulae

- `needs`: 33 formulae

- `patch`: 19 formulae

**Comment by MikeMcQuaid** [comment]
> Others that would be nice to add to audit:
> 
> deprecated_option: 36 formulae
> 
> fails_with: 13 formulae
> 
> needs: 33 formulae
> 
> patch: 19 formulae

I'm 👍 on all of them. Could you add them to this PR?

**Comment by commitay** [comment]
Adding them individually would be a bit easier to do (and review), all that once makes the diff > 1000 lines with changes to whitespace and comments.

**Comment by ilovezfs** [comment]
I'm not sure there's a clear benefit to ordering those.

**Comment by commitay** [comment]
Not adding them means that the current audit is less consistent and also allows components to be grouped when in the majority of formulae they are separated.

https://github.com/Homebrew/homebrew-core/compare/master...commitay:needs

**Comment by ilovezfs** [comment]
Well, for example, I don't see any good coming from moving all the deprecated options around. They're already grouped. Whether they're above or below the options isn't affecting us and will just blow up the Git history. I don't think "more consistent" justifies things that aren't causing us problems.

**Comment by MikeMcQuaid** [comment]
> Adding them individually would be a bit easier to do (and review), all that once makes the diff > 1000 lines with changes to whitespace and comments (that need to be fixed manually).

Seems reasonable to me. It's also easier to discuss their pros/cons one by one (as @ilovezfs has done eloquently above).

**Comment by MikeMcQuaid** [comment]
Thanks @commitay!

**Pull request merged**
