### PR TITLE
audit: Port audit_urls to rubocop and add corresponding tests Part 2

### PR DESCRIPTION
**Pull request by GauthamGoli**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----
#569 
And Continuation of #2911 , this PR ports Non strict / Online parts of `audit_urls`
Opening this PR for review until #2911 gets merged.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Will hold off reviewing until this is rebased on `master` but thanks for opening early 👍

**Comment by GauthamGoli** [comment]
@MikeMcQuaid Its rebased with master now.

**Comment by MikeMcQuaid** [comment]
Great work again @GauthamGoli!

**Comment by JCount** [comment]
Good job, once again @GauthamGoli!!

**Pull request merged**
