### PR TITLE
Remove `$LOAD_PATH` from verbose output.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Closes https://github.com/Homebrew/brew/issues/4576.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
It feels weird to just remove this as you can no longer copy-paste the command and get the expected output. If the load path needs to be as long as it is here I'd rather see #4576 closed as a WONTFIX, personally.

**Comment by reitermarkus** [comment]
> If the load path needs to be as long as it is here I'd rather see 
https://github.com/Homebrew/brew/issues/4576 closed as a WONTFIX, personally.

I also fine with that, since currently this is the DRY-est way so far of handling `$LOAD_PATH`.

**Comment by MikeMcQuaid** [comment]
@reitermarkus Go for it 👍

**Comment by chdiza** [comment]
> It feels weird to just remove this as you can no longer copy-paste the command and get the expected output

What is the expected output?

**Pull request closed without merging**
