### PR TITLE
compat: deprecate Utils::JSON in favor of corelib JSON.

### PR DESCRIPTION
**Pull request by woodruffw**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

In the line of #1534, this moves `utils/json.rb` to `compat/json.rb` and adds deprecation warnings.

### CODE REVIEW

**Comment by woodruffw** [comment]
(Partially) blocking on Homebrew/homebrew-test-bot#24.

**Comment by woodruffw** [comment]
Strange failure on Travis:

```
/home/travis/build/Homebrew/brew/Library/Homebrew/test/support/helper/fs_leak_logger.rb:7:in `mkdir': File exists - /home/travis/build/Homebrew/brew/Library/Homebrew/tmp (Errno::EEXIST)
```

Not sure what to make of that.

**Comment by woodruffw** [comment]
Jenkins is still failing because it isn't fetching the latest `homebrew-core` tap, even during rebuilds. I'm not sure how to force it to do so.

**Comment by MikeMcQuaid** [comment]
Homebrew/brew shouldn't need Homebrew/homebrew-core tapped at all to run the tests so we can probably remove `brew readall --syntax` from the test-bot for this case.

**Comment by MikeMcQuaid** [comment]
@woodruffw Fixed the test-bot issue with https://github.com/Homebrew/homebrew-test-bot/pull/25 but there's another 💥 now.

**Comment by woodruffw** [comment]
Very strange. `brew uses` is still pulling up an old version of the `internetarchive` formula, which is then failing since `utils/json` no longer exists.

**Comment by MikeMcQuaid** [comment]
Removed the old one from the CI boxes. Nice work @woodruffw!

**Pull request merged**
