### PR TITLE
Enable ruby-macho by default.

### PR DESCRIPTION
**Pull request by woodruffw**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Flips `HOMEBREW_RUBY_MACHO` to `HOMEBREW_NO_RUBY_MACHO`.

I also deleted the `HOMEBREW_RUBY_MACHO` enablement line in `test-bot`, since this PR enables it by default (and no longer checks that variable).

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> HOMEBREW_NO_RUBY_MACHO

In what situation(s) would one set that? I'm wondering if it's worth just deleting the existing code now?

**Comment by woodruffw** [comment]
> In what situation(s) would one set that? I'm wondering if it's worth just deleting the existing code now?

In the unlikely event that we run into any bugs immediately after rolling this out, we could tell people to set `HOMEBREW_NO_RUBY_MACHO` as a quick fix. 

I discussed this with @UniqMartin in a PM on slack, and 2-3 weeks seems like a good rollout period to us. If nothing substantial happens after that, we can simply delete the `cctools`-based implementation and the environment checks associated with it.

**Comment by MikeMcQuaid** [comment]
> I discussed this with @UniqMartin in a PM on slack, and 2-3 weeks seems like a good rollout period to us. If nothing substantial happens after that, we can simply delete the cctools-based implementation and the environment checks associated with it.

👍 seems like a good plan to me.

**Comment by UniqMartin** [comment]
> > HOMEBREW_NO_RUBY_MACHO
>
> In what situation(s) would one set that? I'm wondering if it's worth just deleting the existing code now?

As already mentioned by @woodruffw, that's a temporary measure suggested by me.

The other motivation is to ship this feature and thus formally finalize William's GSoC project (with the stated goal of enabling the code for all Homebrew users) with a minimal PR that can be shipped more quickly than a thorough cleanup. (But we definitely aim for a proper cleanup.)

**Comment by MikeMcQuaid** [comment]
Hooray 👏

**Comment by UniqMartin** [comment]
Thanks @woodruffw; great work! :tada: And sorry for the delay …

**Comment by woodruffw** [comment]
No problem! Glad to :ship: this out!

**Comment by MikeMcQuaid** [comment]
@woodruffw @UniqMartin can definitely 💀 the old code now I think!

**Comment by woodruffw** [comment]
Got it! I'll have a PR ready in a few :smile:

**Pull request merged**
