### PR TITLE
Add fish shell completions to brew

### LINKED ISSUE #6172: Can fish shell completions live in this repo?
# A detailed description of the proposed feature

Currently, the fish shell completions for Homebrew exist primarily in two locations (of which I'm aware): the [main fish shell repo](https://github.com/fish-shell/fish-shell/blob/master/share/completions/brew.fish) and an [extensive external repo](https://github.com/laughedelic/brew-completions/blob/master/completions/brew.fish). I would propose combining these two into fish shell completions that would live here alongside [the bash and zsh completions in the completions directory](https://github.com/Homebrew/brew/tree/master/completions).

# The motivation for the feature

The completions existing bundled with the fish shell itself (which doesn't ship updates so often) can cause the completions to go out of date, especially when there are breaking API changes (like the `brew cask search` removal) that the completions would need to (relatively) swiftly deal with. Having the completions exist with Homebrew itself (which is nearly always up to date) would certainly alleviate this.

# How the feature would be relevant to at least 90% of Homebrew users

Having functional and up to date completions for all the most popular shells is certainly of benefit to most Homebrew users.

# What alternatives to the feature have been considered

Leaving the completions in their aformentioned locations.

# Additionally

I would be totally willing to author this PR, and I would be interested in the feedback of @MindTooth and @laughedelic who primarily authored the aforementioned completions.

### PR DESCRIPTION
**Pull request by lwolfsonkin**
Closes #6172

* Copy fish completions from github.com/laughedelic/brew-completions
* Update completions readme to include fish
* Rename fish functions to be more styled like most fish functions
* Make completions for `brew pin` suggest only unpinned formulae
* Added TODO for dropping `brew search`'s cache `desc_cache.json`
* Drop completions for nonexistent `brew cask cleanup` 

-----------------

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by erikgaal** [comment]
The correct URL should be https://github.com/laughedelic/brew-completions/.

The license is GPLv3 so I don't think we can _just_ merge this.

**Comment by reitermarkus** [comment]
https://github.com/laughedelic/brew-completions/issues/9

**Comment by MikeMcQuaid** [comment]
@laughedelic can you confirm you are happy for your code to be included in this repository under these terms: https://github.com/Homebrew/brew/blob/master/LICENSE.txt?

**Comment by lwolfsonkin** [comment]
@MikeMcQuaid: I corrected the URL in the PR description now. :)

**Comment by laughedelic** [comment]
Thank you @lwolfsonkin for pushing this forward and taking extra effort for the improvements! 👏 

I'm fine with the BSD license, but I would appreciate being mentioned as a co-author in the merge commit if this is not against the repository rules:

```
Co-authored-by: Alexey Alekhin <laughedelic@gmail.com>
```

**Comment by MikeMcQuaid** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @lwolfsonkin!

> I'm fine with the BSD license, but I would appreciate being mentioned as a co-author in the merge commit if this is fine with you:

Done, thanks for your initial work on this too @laughedelic: you also rock!

**Pull request merged**
