### PR TITLE
Replacing all ARGV references with Homebrew.args

### PR DESCRIPTION
**Pull request by mofo37**
Issue reference: https://github.com/Homebrew/brew/issues/5730

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example] (https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
Updated all existing tests.
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Questions:
- It looks like the build checks are failing. Is there a way to reproduce that locally?
- We did a global replace. We would have preferred to make smaller, incremental changes, but weren't sure if that was the best move and weren't sure how to run individual file tests. We are open to feedback. 
- Where `ARGV` filenames are still in existence, should they be changed to `Homebrew_args` or something similar?

@BenMusch is this what you were expecting?

### CODE REVIEW

**Comment by BenMusch** [comment]
Yep, this is basically what I was planning on doing. Thanks for picking up the issue!

**Comment by MikeMcQuaid** [comment]
Wow, thanks for this! Great work so far!

> * It looks like the build checks are failing. Is there a way to reproduce that locally?

Yup, run `brew tests` locally!

> * We did a global replace. We would have preferred to make smaller, incremental changes, but weren't sure if that was the best move and weren't sure how to run individual file tests. We are open to feedback.

I'd be happy with a global change but it's probably a little bit more involved than a global search and replace, unfortunately. Note from https://github.com/Homebrew/brew/issues/5730#issue-409874027:

> `formula_installer.rb` and `build.rb` should be handled last as they read from and modify ARGV: 
https://github.com/Homebrew/brew/blob/b4f73e61649fcfc5aaa779c311e2514619ce01e7/Library/Homebrew/formula_installer.rb#L678-L751

So I'd suggest excluding at least those files and `brew.rb` for now (that's why `brew tests` will fail immediately because no `brew` command` can run currently.

Shout at all if I/we can help at all and thanks again for the PR!

**Comment by mofo37** [comment]
- `brew tests` locally do pass for us so maybe we're doing something wrong?
- after excluding `build.rb`, `brew.rb` and `formula_installer.rb` and running `brew tests` all tests passed and CI still failed.
- is there a way to pass a single file to maybe `brew test` to check our work as we go so we don't have to run the full suite every time?

Thanks!

**Comment by MikeMcQuaid** [comment]
> * `brew tests` locally do pass for us so maybe we're doing something wrong?

How are you running it? Does `brew --repo` match the directory you're editing/pushing to GitHub?



> * is there a way to pass a single file to maybe `brew test` to check our work as we go so we don't have to run the full suite every time?

Yup: `brew tests --only=foo` will run only `Library/Homebrew/test/foo_spec.rb`. See `brew test --help` for more information.

**Comment by GauthamGoli** [comment]
> I'd be happy with a global change but it's probably a little bit more involved than a global search and replace, unfortunately.

I agree with @MikeMcQuaid here. An incremental approach would be best in this case. 

Global change would also work as long as you have a lot of patience to fix all the failing tests one by one.

**Comment by MikeMcQuaid** [comment]
@mofo37 Let us know if you'd rather open some smaller PRs instead as per-@GauthamGoli's suggestion as he may also be able to help a bit with this project.

**Comment by mofo37** [comment]
@BenMusch did you ever get these tests to fail locally? https://github.com/Homebrew/brew/pull/5762#issuecomment-464422336

**Comment by BenMusch** [comment]
Sorry @mofo37, I don't remember enough about my work on this and don't really have the time to set it up again. Sorry and good luck!

**Comment by MikeMcQuaid** [comment]
@mofo37 How are you running `brew tests`? Does `brew --repo` match the directory you're editing/pushing to GitHub?

**Comment by mofo37** [comment]
@MikeMcQuaid
`brew --repo` returns this: `/usr/local/Homebrew`
I'm not sure how to point it to the directory I'm editing/pushing to GitHub.

When I point to the folder I'm working in with `brew --repo <file_path>`, I get this error:
`Error: Invalid tap name "<file_path>"`

How do I get it to point to the correct directory?

**Comment by BenMusch** [comment]
@mofo37 I don't think this is the preferred way to do things, but the quick fix I used to develop on Homebrew was just to symlink Homebrew to my source code directory and work from there. Some clearer steps:

1. Commit and push all of the changes you have on your fork of homebrew
2. `cd /usr/local/Homebrew`
3. `git remote set-url origin git@github.com:mofo37/brew.git`
4. `git remote add upstream git@github.com:Homebrew/brew.git`
5. `ln -s /usr/local/Homebrew {your preferred source code/documents directory}/brew`

This sets things up so that:

- The brew that you run via the `brew` command will point to your local version of homebrew
- Editing the files from either the `/usr/local/Homebrew` or your source/docs directory will both modify the same source, since one is just a link to the other
- Your git repo will have an `upstream` source pointing to @Homebrew's repo and an `origin` pointing to your own

Then, the only issues I ran into were brew auto-updating and changing the branches. to fix that, I set these variables in my `~/.bash_profile`:

```
HOMEBREW_DEVELOPER=1
HOMEBREW_NO_AUTO_UPDATE=1
```

If you add those and then run `source ~/.bash_profile`, you should be good to go. Note, however, that this will make it your responsibility to manually get updates.

Again: I'm not sure if this is the preferred way of doing things, but it's what I managed to work make for myself when I worked on a few bugfixes

**Comment by MikeMcQuaid** [comment]
Sorry @mofo37 but I'm closing this out until you're able to figure out how to test the changes locally. Happy to help with that: just shout.

**Pull request closed without merging**
