### PR TITLE
DownloadStrategy: various improvements

### PR DESCRIPTION
**Pull request by xu-cheng**
See each commits for details.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
👍 if it's been tested with a few formulae.

**Comment by DomT4** [comment]
I'm late to this party but the no insecure redirect variable wasn't applied to the Apache curl method by deliberate design choice at the time, as documented [here](https://github.com/Homebrew/brew/blob/8284fb3fef9860a67f3303f17cb6fd99a2ebc168/Library/Homebrew/manpages/brew.1.md.erb#L187) in the manpage.

I'm fine with changing it but the manpage should've been updated as well.

**Comment by DomT4** [comment]
https://github.com/Homebrew/brew/commit/a11262788847e2b9c84f6a78b3266d2b2be4a2ad

**Comment by UniqMartin** [comment]
Preserving the time stamp of the cached downloads has an unfortunate consequence. The files that end up in `HOMEBREW_CACHE` and have just been downloaded are then often immediately purged by `brew cleanup --prune=14` as the publication date is often way beyond this threshold. This also affects our CI, causing it to constantly re-download huge files (e.g. the Qt 5.7.0 tarball), particularly for PRs where the process is lengthy or where the PR is submitted well after the upstream publication date.

I don't currently have an idea how to address this problem while preserving the changes made here.

**Comment by xu-cheng** [comment]
@UniqMartin I guess one of solutions is to change Cache directory structure. Instead of putting cache files like `HOMEBREW_CACHE/formula-foo-1.0`, we could make them like `HOMEBREW_CACHE/formula-foo/formula-foo-1.0`. Therefore, we can use parent directory's mtime as indicator of fetching time.

**Comment by MikeMcQuaid** [comment]
> @UniqMartin I guess one of solutions is to change Cache directory structure. Instead of putting cache files like HOMEBREW_CACHE/formula-foo-1.0, we could make them like HOMEBREW_CACHE/formula-foo/formula-foo-1.0. Therefore, we can use parent directory's mtime as indicator of fetching time.

This is on my todo list to think about but it'd be great for anyone to pick up: make the cache follow the same format as the cellar e.g. `HOMEBREW_CACHE/formula-foo/1.0/$FILES`. This will massively simplify e.g. `cleanup`'s ability to figure out what files belong to what (which brings us closer to a much faster `cleanup` no-op and the possibility of running it automatically).

**Comment by UniqMartin** [comment]
I have to admit that I really like the simplicity of the current flat hierarchy in the cache, but I agree that having a hierarchy like `HOMEBREW_CACHE/formula-foo/1.0/$FILES` would make some things a lot easier. Currently some files in the cache are skipped or erroneously cleaned up because the cleanup code cannot figure out what formula a file belongs to.

Where would things live that aren't specific to a certain formula version, like resources (and patches) that are used across multiple versions of a formula? Currently they have the form `formula-foo--<resource>-<version>.<extension>`. I guess a similar question could be posed for VCS clones/checkouts like `x264--git`.

I didn't do anything related to this, but I have [some WIP code](https://github.com/UniqMartin/brew/tree/spring-cleaning) that can properly clean up most resources whereas the current cleanup code only cares about the primary downloads of a formula (doesn't matter to most users that only install from bottles). It probably even slows down the current cleanup because it has to perform a few more checks …

**Comment by MikeMcQuaid** [comment]
> I have to admit that I really like the simplicity of the current flat hierarchy in the cache, but I agree that having a hierarchy like HOMEBREW_CACHE/formula-foo/1.0/$FILES would make some things a lot easier. Currently some files in the cache are skipped or erroneously cleaned up because the cleanup code cannot figure out what formula a file belongs to.

Indeed, that's my thought too 👍 

> Where would things live that aren't specific to a certain formula version, like resources (and patches) that are used across multiple versions of a formula? Currently they have the form formula-foo--<resource>-<version>.<extension>. I guess a similar question could be posed for VCS clones/checkouts like x264--git.

Maybe in `HOMEBREW_CACHE/formula-foo/$FILES`?

> I didn't do anything related to this, but I have some WIP code that can properly clean up most resources whereas the current cleanup code only cares about the primary downloads of a formula (doesn't matter to most users that only install from bottles). It probably even slows down the current cleanup because it has to perform a few more checks …

I think improving correctness would be great and we can think about alternate cache layouts for speed later.

**Comment by UniqMartin** [comment]
> Maybe in `HOMEBREW_CACHE/formula-foo/$FILES`?

Yep, that should work (and works for me). Though if we want to fully embrace the two-level layout, we could think about `HOMEBREW_CACHE/formula-foo/patches/$FILES` (for the resources created by `patch do` blocks) and `HOMEBREW_CACHE/formula-foo/resources/$FILES` (for all other resources).

> I think improving correctness would be great and we can think about alternate cache layouts for speed later.

That's good to hear! I'll see if I can get this branch cleaned up a bit and submit it as a PR. The main issue is really that some files in the cache cannot be attributed to a formula, partially due to our somewhat lax rules for what constitutes a valid formula name and a valid version string, e.g. `app-engine-go-32-1.2.3.tar.gz` could be both interpreted as

- formula `app-engine-go` and version `32-1.2.3` or
- formula `app-engine-go-32` and version `1.2.3`.

That's not really fixable without inspecting all formulae (in the hopes that the formula hasn't been removed/renamed yet) or imposing stricter rules on formula names/versions that avoid this ambiguity (or making name and version separate path components in a nested cache layout).

**Comment by MikeMcQuaid** [comment]
> Yep, that should work (and works for me). Though if we want to fully embrace the two-level layout, we could think about HOMEBREW_CACHE/formula-foo/patches/$FILES (for the resources created by patch do blocks) and HOMEBREW_CACHE/formula-foo/resources/$FILES (for all other resources).

Agreed 👍 Perhaps similarly with even `bottles` and `sources`.

> That's good to hear! I'll see if I can get this branch cleaned up a bit and submit it as a PR.

👍 



> (or making name and version separate path components in a nested cache layout).

👍

**Comment by UniqMartin** [comment]
> Agreed 👍 Perhaps similarly with even `bottles` and `sources`.

True. I always forget these (particularly the bottles), because in my mind Homebrew is still a pure build-from-source package manager:

```console
$ brew ls | wc -l
     179
$ ls "$(brew --cache)"/*bottle*
/opt/homebrew/.brew-cache/shellcheck-0.4.4.el_capitan.bottle.tar.gz
```

**Pull request closed without merging**
