### PR TITLE
test/utils/svn: Requires svn to succeed

### PR DESCRIPTION
**Pull request by sjackman**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

This test fails on Linux if `svn` is not installed. I've added `:needs_macos`. Is there a better way to skip this test when `svn` is not available?

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Could do a `needs_svn`. I think something similar would be preferable as `svn` is present on our Travis CI builders.

**Comment by AUTHAI-bit** [comment]
Thanks needs_svn.

**Comment by MikeMcQuaid** [comment]
@sjackman ping?

**Comment by sjackman** [comment]
Done. Sorry for the delay.

**Comment by AUTHAI-bit** [comment]
Thanks again

**Comment by MikeMcQuaid** [comment]
Thanks @sjackman!

**Comment by sjackman** [comment]
Thanks for merging, Mike!

**Pull request merged**
