### PR TITLE
feat: only block cask install on Linux

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

This is the first step to allowing font (and later binary) casks to be installable on Linux.
TODO:
- [x] Think about how to handle `brew search --cask X`
- [x] Think about how to handle `brew info --cask X`

### CODE REVIEW

**Comment by SMillerDev** [comment]
> Probably want to make --cask explicitly required on Linux until this is (much) further along?

You mean for `install`? I'll have to check, but I think you have to manually tap the cask repo for this to do anything on Linux for now. That seems like a sufficient barrier.

**Comment by MikeMcQuaid** [comment]
> You mean for `install`? I'll have to check, but I think you have to manually tap the cask repo for this to do anything on Linux for now. That seems like a sufficient barrier.

@SMillerDev Ok, as long as `brew install docker` or `brew install google-chrome` on Linux retains the same behaviour as before 👍🏻

**Comment by SMillerDev** [comment]
I'll do an extra check for those specific ones. 

What do you think should happen to `search` and `info`? Just allow them for casks?

**Comment by MikeMcQuaid** [comment]
> What do you think should happen to `search` and `info`? Just allow them for casks?

I think probably require `--cask` or something?

**Comment by SMillerDev** [comment]
Tested this in a codespace, it has the same result, but a different output.

Before this PR:

```console
linuxbrew@codespaces-069e0c:~/.linuxbrew/Homebrew$ brew install google-chrome
==> Downloading https://formulae.brew.sh/api/formula.jws.json

Warning: No available formula with the name "google-chrome". Did you mean google-benchmark?
==> Searching for similarly named formulae...
==> Formulae
google-benchmark

To install google-benchmark, run:
  brew install google-benchmark
```

After this PR:
```console
linuxbrew@codespaces-069e0c:~/.linuxbrew/Homebrew$ brew install google-chrome
==> Downloading https://formulae.brew.sh/api/cask.jws.json
##O=#    #                                                                                                                                         
Error: macOS is required for this software.
```

**Comment by MikeMcQuaid** [comment]
@SMillerDev What about `brew install --cask google-chrome`

I think the prior behaviour is better on Linux for now, sorry, but I think if you added `--cask` then the latter would make sense.

**Comment by SMillerDev** [comment]
I'll reinstate that. Seems like I was too eager with the CLI changes. After that and fixing the tests, are you fine to merge this while I work on the font installing? Or you'd rather bundle it and merge in one go?

**Comment by SMillerDev** [comment]
Okay, with this latest change that behaviour should be reinstated.

**Comment by SMillerDev** [comment]
Looks like all checks are green and the behavior was restored as requested.
@MikeMcQuaid do you mind taking another look?

**Review by MikeMcQuaid — APPROVED** [review]
Looks good, thanks @SMillerDev!

**Comment by apainintheneck** [comment]
Great work here!

**Pull request merged**
