### PR TITLE
docs: more accurate update-test parameter name

### PR DESCRIPTION
**Pull request by penman**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

`sha1` isn't a very accurate description of what this value can be because it can be any git commit reference. For example, `brew test-bot` uses `brew update-test --commit=HEAD`.

While I was changing the documentation, it seemed like a good idea to change the variable names too, but I can see reasons for and against doing this, so happy to leave them as is if people would prefer.

### CODE REVIEW

**Comment by zmwangx** [comment]
Personally I'd say update the docs and leave the variable names so that git-blame's usefulness it's destroyed. By the way, commitish might be the most accurate word here. Not that you should use it...

**Comment by penman** [comment]
@zmwangx

> Not that you should use it...

😂

I spent some time researching the git terminology and 10 minutes in I still couldn't tell if committish was correct or not so decided it wasn't the best term to use.

**Comment by MikeMcQuaid** [comment]
> Personally I'd say update the docs and leave the variable names so that git-blame's usefulness isn't destroyed.

I think not changing code for `git blame` isn't a good enough reason, personally. 👍 to changing the names; arguably they could be `ref`, though.

**Comment by penman** [comment]
> arguably they could be ref, though.

`ref` was actually what I thought about first for the docs, but decided `commit` had a more obvious meaning. From there, I think the variable names being consistent with the documentation is a good thing.

**Comment by MikeMcQuaid** [comment]
More great work from @penman (who is on 🔥)

**Pull request merged**
