### PR TITLE
Add missing permissions to actions publish

### PR DESCRIPTION
**Pull request by JameelKaisar**
This commit enhances the publish actions script by including a step to close the pull request after
committing the changes. The existing script deletes the branch after pushing the commits, but lacks
the functionality to close the associated PR.

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Permissions Added:
- contents: write
- pull-requests: write

See: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

### CODE REVIEW

**Comment by Bo98** [comment]
`brew pr-pull` should already handle this without needing any extra permissions by modifying the commit message: https://github.com/Homebrew/brew/blob/5349b762929b51785bcd40c1df101f9479a0dd13/Library/Homebrew/dev-cmd/pr-pull.rb#L98

**Comment by JameelKaisar** [comment]
@Bo98 Yes, you are right, it is already been handled but I was getting some errors while testing this. The errors were due to missing permissions.

**Comment by Bo98** [comment]
Ah ok that makes more sense. So did you find that you could do just the permission changes without the `gh pr close` change?

**Comment by JameelKaisar** [comment]
I looked into it and found out that the 'contents: write' permission is required to publish releases and the 'pull-requests: write' permission is required to close the pull request after the changes are committed. It seems like mentioning these permissions explicitly was not required in the past but now it is required.

See: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

**Review by Bo98 — APPROVED** [review]
Makes sense. Thanks!

**Review by carlocab — APPROVED** [review]
Thanks!

**Comment by MikeMcQuaid** [comment]
Nice work everyone!

**Comment by JameelKaisar** [comment]
Thanks 😊

**Pull request merged**
