### PR TITLE
Tty: Avoid truncating if not sensible

### PR DESCRIPTION
**Pull request by ScoreUnder**
Moving this PR over from the old brew repo.

https://github.com/Homebrew/legacy-homebrew/pull/48871

### CODE REVIEW

**Comment by mikemcquaid** [comment]
You don't need to move over old PRs, by the way.

**Comment by ScoreUnder** [comment]
Oh. I've done so :D Should I move it back?

**Comment by mikemcquaid** [comment]
Nah, it's fine now, thanks.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request merged**
