### PR TITLE
Use type-safe exhaustiveness checking

### PR DESCRIPTION
**Pull request by dduugg**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
This change allows sorbet to catch non-exhaustive type checking, rather than strictly relying on runtime behavior.
(See also sorbet [docs](https://sorbet.org/docs/exhaustiveness) for more info.)

### CODE REVIEW

**Comment by reitermarkus** [comment]
See https://github.com/Homebrew/brew/pull/14936#discussion_r1131429952.

We don't seem to be calling any of these methods with `nil` (i.e. without argument) but instead using the instance variable directly. 

Should we remove the `nil` case from all of these, or should we change the instance variables to method calls instead?

**Comment by dduugg** [comment]
> See [#14936 (comment)](https://github.com/Homebrew/brew/pull/14936#discussion_r1131429952).
> 
> We don't seem to be calling any of these methods with `nil` (i.e. without argument) but instead using the instance variable directly.
> 
> Should we remove the `nil` case from all of these, or should we change the instance variables to method calls instead?

I think that might be an orthogonal discussion (the `environment_variables` param is already non-nilable, for instance), but happy to close this out if folks are planning to go in another direction.

**Review by MikeMcQuaid — APPROVED** [review]
This seems preferable to me compared to the code we had before, for sure. Just want to ensure that it behaves equivalently when Sorbet isn't enabled at runtime?

**Comment by dduugg** [comment]
> This seems preferable to me compared to the code we had before, for sure. Just want to ensure that it behaves equivalently when Sorbet isn't enabled at runtime?

I believe that's correct. We don't makes changes to `T.absurd` in the sorbet standalone [file](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/standalone/sorbet.rb). I also confirmed that `T.absurd` matches the source definition in pry with `HOMEBREW_SORBET_RUNTIME` unset.

**Comment by reitermarkus** [comment]
> I think that might be an orthogonal discussion

I think it relates to types as well: Can instance variables be typed? If not, it may make sense to prefer typed getter methods to plain instance variables.

**Review by reitermarkus — APPROVED** [review]

**Comment by apainintheneck** [comment]
This probably needs to incorporate the changes on master after https://github.com/Homebrew/brew/pull/15120 got merged in. I added more code similar to what's getting changed here.

**Comment by apainintheneck** [comment]
> We don't seem to be calling any of these methods with `nil` (i.e. without argument) but instead using the instance variable directly.
> 
> Should we remove the `nil` case from all of these, or should we change the instance variables to method calls instead?

This should probably happen eventually. Right now it seems like unnecessary complexity. 

Also, these error messages are mainly for package maintainers. Won't this result in less specific error messages?

**Comment by MikeMcQuaid** [comment]
@dduugg can you rebase this and make the changes @apainintheneck refers to? 🙇

**Comment by dduugg** [comment]
@MikeMcQuaid @apainintheneck I rebased but i don't think any changes are required/desirable (there are no new `T.unsafe`s to hide unreachable code that could instead be labeled `T.absurd`).

However, I gave this a spin with `HOMEBREW_SORBET_RUNTIME` and `T.absurd` is suppressed due to https://github.com/Homebrew/brew/blob/master/Library/Homebrew/standalone/sorbet.rb#L46

Thus I'm inclined to close this one for now, given the current standalone sorbet configuration. (I think we should investigate using a more standard runtime sorbet [configuration](https://sorbet.org/docs/tconfiguration), but not on a whim to facilitate this PR). Thanks to everyone who provided thoughtful feedback, hope I didn't waste too much of your time.

**Comment by MikeMcQuaid** [comment]
Thanks @dduugg! The main issue with the runtime checks it that we can't require users install the native Sorbet runtime parts.

**Pull request closed without merging**
