### PR TITLE
Donate through Liberapay

### PR DESCRIPTION
**Pull request by MartinDelille**
[Liberapay](https://liberapay.com) is an opensource project that allow regular donation like patreon.

The main differences are:

- Liberapay is totally opensource: https://github.com/liberapay/liberapay.com. The code is clean and it is very easy to contribute to the project
- There is no fee from the plateform (only the payment processor fee from Stripe). It is possible to donate to the plateform to help the developers improving it.
- Everyone can open an account: neutrality is a root principle of Liberapay.

Accepting this merge request would require the Homebrew owner to create a Liberapay account first!

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by commitay** [comment]
@MartinDelille Are you affiliated with Liberapay?

**Comment by MartinDelille** [comment]
Yes.

**Comment by MikeMcQuaid** [comment]
We may consider this in future but not at present, sorry.

**Comment by MartinDelille** [comment]
Ok no problem!

I'll be happy to donate through Liberapay (I don't use Patreon). I made a 0.25 cent/week promise that you'll unlock when you'll change your mind: https://liberapay.com/on/github/Homebrew

**Comment by MikeMcQuaid** [comment]
@MartinDelille We accept donations in a variety of methods not just Patreon: https://github.com/Homebrew/brew#donations. If you want to support this project financially you'll use one of those methods. If you don't and instead want to make some sort of point to promote your project (one that hasn't gone as well as you'd have hoped, I think) that's OK but you might want to be a bit more up front about it in the PRs you create.

**Pull request closed without merging**
