### PR TITLE
Handle undeclared POSIXLY_CORRECT in Bash completions

### PR DESCRIPTION
**Pull request by aphedges**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?
  - No. It was taking too long to run.

-----

As of `brew` 4.0.2, sourcing the Bash completions with `set -eu` causes a failure if `POSIXLY_CORRECT` is not declared. The check will now properly handle this situation.

I'm not sure if the resulting code is POSIX-compliant, but it prevents a breaking change until a better solution can be found.

### CODE REVIEW

**Comment by aphedges** [comment]
Sorry about the force-push! I have `HOMEBREW_GIT_EMAIL` set, but I didn't realize I still needed to set the email when making commits.

**Comment by aphedges** [comment]
Sorry about the second force-push! I had the version the problem started incorrect in the commit message, and I forgot to fix the committer email when I fixed the author email. It should finally be good now.

**Comment by aphedges** [comment]
I'm not sure why the code coverage is listed as decreasing. The [report](https://app.codecov.io/gh/Homebrew/brew/commit/5ed06a7956e6e7236659b5dd306980559a2d2d35) lists many files that I did not edit at all.

**Comment by Bo98** [comment]
Force push in pull requests is quite normal here - don't worry about that!

Don't worry about code coverage either - I can see it's clearly not caused by your change.

Thanks for the contribution @aphedges!

**Review by Bo98 — APPROVED** [review]

**Comment by aphedges** [comment]
Glad it's okay, and thank you very much for reviewing and merging!

I can see that this has now been released, and it's very useful to have.

**Comment by MikeMcQuaid** [comment]
Thanks @aphedges for contributing and @Bo98 for merging!

**Pull request merged**
