### PR TITLE
xcode: upgrade for Xcode 10.1 release

### PR DESCRIPTION
**Pull request by lembacon**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by chdiza** [comment]
Apple hasn't yet put the two CLT packages corresponding to 10.1 up on `developer.apple.com/download/more` yet.

**Comment by lembacon** [comment]
> Apple hasn't yet put the two CLT packages corresponding to 10.1 up on `developer.apple.com/download/more` yet.

They're available via Software Update.

**Comment by MikeMcQuaid** [comment]
@lembacon Not reliably for me I'm afraid: 
screenshot 2018-11-04 at 10 13 53

Could bump just the Xcode version until it's available?

**Comment by lembacon** [comment]
@MikeMcQuaid Updated the commit to exclude the bump of CLT package for now, also added a short comment in the commit message to clarify this situation.

**Comment by MikeMcQuaid** [comment]
Thanks @lembacon, looks good and nice work 👍

**Pull request merged**
