### PR TITLE
attestation: specialize error when `gh` is old

### PR DESCRIPTION
**Pull request by woodruffw**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

This isn't really ideal (I'll look further into the bootstrap cycle issues that led us to try version sniffing in the first place), but it'll help more users in the current beta resolve issues they're seeing.

See https://github.com/Homebrew/homebrew-core/issues/177384#issuecomment-2263195832.

### CODE REVIEW

**Review by nandahkrishna — COMMENTED** [review]
This mostly seems fine but the reason I created the version-based check earlier was because some older versions of `gh`, weirdly, seem to not output an unknown command error even though they don't support attestations.

See for example:
```
$ oras pull ghcr.io/homebrew/core/gh:2.48.0
$ HOMEBREW_NO_VERIFY_ATTESTATIONS=1 brew install ./gh--2.48.0.arm64_sonoma.bottle.tar.gz
$ gh --version
gh version 2.48.0 (2024-04-17)
$ gh attestation     
Download and verify artifact attestations.

USAGE
  gh attestation [subcommand] [flags]

ALIASES
  at

AVAILABLE COMMANDS
  download:    Download an artifact's Sigstore bundle(s) for offline use
  verify:      Verify an artifact's integrity using attestations

INHERITED FLAGS
  --help   Show help for command

LEARN MORE
  Use `gh <command> <subcommand> --help` for more information about a command.
  Read the manual at https://cli.github.com/manual
```
However, the minimum `gh` version that supports attestations is `2.49.0`, so I have no idea why this is happening.

**Comment by Bo98** [comment]
Honestly, it might just be easier to only check brewed gh version in `Attestation.enabled?` e.g.

```rb
gh_version = Formula["gh"].any_installed_version
return false if gh_version.nil? || gh_version < "2.49"
```

Especially given we hope to phase out `gh` entirely.

**Comment by woodruffw** [comment]
> Honestly, it might just be easier to only check brewed gh version in `Attestation.enabled?` e.g.

Yeah, seems right. I remember we had some bootstrap cycle issue with accessing `Formula[...]` in that context, but I think as long as it's below `no_verify_attestations?` that shouldn't be an issue.

**Comment by MikeMcQuaid** [comment]
> Honestly, it might just be easier to only check brewed gh version in `Attestation.enabled?` e.g.

Agreed.

**Review by MikeMcQuaid — APPROVED** [review]

**Review by MikeMcQuaid — COMMENTED** [review]
Agreed with @Bo98's comment.

**Comment by woodruffw** [comment]
I've updated this so that we now only enable attestations if `gh` is already installed and sufficiently new (*unless* the user explicitly enables them with `HOMEBREW_VERIFY_ATTESTATIONS=1`). This has the side effect of curbing the current beta significantly, since most people currently in it are probably getting it from having developer mode enabled. But per @Bo98's points that seems fine to me.

**Review by Bo98 — APPROVED** [review]

**Comment by PtrTeixeira** [comment]
Hey! This looks like it might be the cause of #18028

**Comment by woodruffw** [comment]
> Hey! This looks like it might be the cause of #18028

Looks like it, thanks. Reverting

**Pull request merged**
