### PR TITLE
perl: set perl shebang to /usr/bin/perl only on mac

### PR DESCRIPTION
**Pull request by dawidd6**
This should be only done on macOS.

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
Where is `uses_from_macos_elements` populated on Linux? I assumed it was macOS specific.

**Comment by dawidd6** [comment]
Ahh, disregard this PR. Thanks for explanation!

**Comment by Bo98** [comment]
The naming is perhaps confusing. Maybe it should be changed to something else.

**Comment by dawidd6** [comment]
Yea, I wouldn't have thought it's only populated on macOS, but should have looked deeper into the source.

**Comment by Bo98** [comment]
If someone comes up with something, open a PR or let me know. I'm not very good at coming up with names.

**Comment by EricFromCanada** [comment]
It's from #6467, in which I found a way to expose a formula's `uses_from_macos` dependencies in its JSON representation.

**Pull request closed without merging**
