### PR TITLE
Revert "ARGV: Deprecate ARGV.flags_only and replace with Homebrew.args.flags_only"

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Fixes https://github.com/Homebrew/brew/issues/7498
Reverts Homebrew/brew#7490

CC @GauthamGoli FYI

### CODE REVIEW

**Comment by Bo98** [comment]
I suppose `cli_args` only handles registered options and formulae don't really do that? `cmdline_args` might work, unless the intention is to move the formulae options system to work more like commands.

**Comment by MikeMcQuaid** [comment]
> I suppose `cli_args` only handles registered options and formulae don't really do that?

They _kinda_ do; see `formula_options` in `parser.rb` which defines them. For whatever reason, though, they aren't being passed through.

I can hold off the revert if you want to give it a go? Just want to get something in before a new tag.

**Comment by Bo98** [comment]
Right so that works, but not on the first invokation of the formula loading.

`formula_options` calls `@args.formulae` which internally triggers a formula load: https://github.com/Homebrew/brew/blob/2bbcab56152d1ff19bbe20a7d310619f167e1f03/Library/Homebrew/cli/args.rb#L91. This initialises the software spec (and where `Homebrew.args.flags_only` is read). `formula_options` hasn't actually completed yet (we're still within the call) and thus the options are not registered at this point.

**Comment by MikeMcQuaid** [comment]
Thanks @Bo98 and @GauthamGoli. Merging this to stop the bleeding for now but seems hopeful we'll be able to address this soon.

**Comment by d12frosted** [comment]
I confirm that merging this PR fixes the issue. Thank you very much.

If you wish, I can test in future changes related to argument parsing as I have a formula that relies on it. Just make sure to ping me ;)

**Comment by MikeMcQuaid** [comment]
You're welcome, thanks @d12frosted!

**Pull request merged**
