### PR TITLE
uses: fix recursive requirement resolution

### LINKED ISSUE #1776: `brew uses` with `--include-optional` doesn't return used formula
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

### Bug reports:

When I run `brew uses` with `--include`, it doesn't find a formula that is actually used.

```
$ brew uses --installed --include-build --recursive unixodbc
homebrew/php/php70

$ brew uses --installed --include-build --include-optional --recursive unixodbc

$
```

Notice that unixodc is used by php70, but when I run the `uses` command with `--include-optional`, the command no longer shows php70 as using unixodbc.

`brew config`:

```
$ brew config
HOMEBREW_VERSION: 1.1.6-2-gfc11f633b2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: fc11f633b29e6a2c9c4d49d5fd5452549b328193
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0a6cce09b2ff3e50128d2e0d3887b12f5bf78368
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
Java: 1.8.0_65, 1.6.0_65-b14-468
macOS: 10.11.6-x86_64
Xcode: 8.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.9 => /opt/X11
```

`brew doctor` (I can't upgrade Xcode because I'm still on El Capitan):

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Found Ruby file outside beeftornado/rmtree tap formula directory
(/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/Formula):
  /usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/brew-rmtree.rb

Warning: Your Xcode (8.1) is outdated.
Please update to Xcode 8.2 (or delete it).
Xcode can be updated from the App Store.
```

### PR DESCRIPTION
**Pull request by alyssais**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Rather than calling `Formula#recursive_requirements`, which doesn't allow the block passed to `Formula#recursive_dependencies` to be overridden, and thus causes `TapFormulaUnavailableError`s, we can use the list of dependencies that were just worked out and check all of those (plus the root formula) for dependencies.

This also fixes #1776, because `Formula#recursive_dependents` by default (as called in `Formula#recursive_requirements`) prunes all optional dependencies — with no way for the caller to override this.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
This seems reasonable, thanks 👍 Can you provide some test cases for verifying this?

**Comment by MikeMcQuaid** [comment]
Sorry, manual test cases to run `brew uses`.

**Comment by alyssais** [comment]
> Can you provide some test cases for verifying this?

> Sorry, manual test cases to run `brew uses`.

Sure. Here's my example from #1848.

```sh
brew tap homebrew/science
brew uses --recursive --include-optional gcc
```

Currently, this doesn't include <samp>homebrew/science/dlib</samp>. With this change, it will.

Another example:

```sh
brew tap homebrew/science
brew untap homebrew/apache
brew uses --recursive adam
```

Previously, this would raise an exception. Now it doesn't. You can verify whether an exception is raised by adding a `puts` to the no-op `rescue` block in uses.rb.

**Comment by MikeMcQuaid** [comment]
Tested, worked, nice work again @alyssais!

**Pull request merged**
