### PR TITLE
Speed up `parallel_tests` by splitting integration tests.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

`brew tests` on my iMac Core i5:
  - before: ~105 seconds
  - after: ~45 seconds

Damn.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Nice. I think if there's existing files like e.g. `bottle_tests.rb` it's worth integrating them in there and otherwise creating a new `bottle_tests.rb` rather than having dedicated integration tests files.

**Comment by penman** [comment]
> Took 14 min on master

:O

**Comment by reitermarkus** [comment]
> if there's existing files like e.g. bottle_tests.rb it's worth integrating them in there

I think this would be counter-productive, as this would again result in *less* files being split across multiple processes.

**Comment by penman** [comment]
@reitermarkus I don't think it would make much of a difference. The issue before wasn't so much that the files weren't small enough; it was that a single file took longer to run than all the other ones combined. As long as that doesn't happen again, the difference between the way it is now and if some of the tests were moved back in to several other files should be negligible.

**Comment by reitermarkus** [comment]
> I don't think it would make much of a difference.

Yes, probably not. Renamed/merged the integration test files with existing files now.

**Comment by apjanke** [comment]
LGTM.

On my quad-core i7 MacBook Pro:

* before: 92 seconds
* after: 30 seconds

**Comment by MikeMcQuaid** [comment]
Great work, thanks @reitermarkus!

**Comment by MikeMcQuaid** [comment]
And for @penman for the previous PR using this gem, too.

**Pull request merged**
