### PR TITLE
migrate-formula-pr: new command

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
I love the idea here but I'm concerned we'd have three `dev-cmd/*-formula-pr.rb` with pretty similar code. Any chance you could get some code sharing going on between them?

**Comment by zmwangx** [comment]
`boneyard-formula-pr` is a special case of `migrate-formula-pr` as far as I can tell.

**Comment by ilovezfs** [comment]
@zmwangx yup, it can be replaced with something that runs `brew migrate-formula-pr --tap=boneyard`, or an equivalent api.

**Comment by MikeMcQuaid** [comment]
@ilovezfs Any news here? Given we're trying to pull things from taps rather than the other way around will this still be useful?

**Comment by ilovezfs** [comment]
It would be used as
```
brew migrate-formula-pr --tap=core foo
```
so the question would be whether those migrations are likely to be done in bulk, or one at a time.

**Comment by MikeMcQuaid** [comment]
@ilovezfs Probably a couple at a time until we're confident then en masse.

**Comment by MikeMcQuaid** [comment]
Let's pass on this given we're migrating things in here rather than out there now.

**Pull request closed without merging**
