### PR TITLE
audit: add "homebrew/core" for relevant checks

### PR DESCRIPTION
**Pull request by jonchang**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

This should help contributors and maintainers of third-party taps to more clearly see which audits are specific to Homebrew-core. This will also be a prelude to including more core checks by default.

### CODE REVIEW

**Comment by jonchang** [comment]
> Good idea. What do you think about using `homebrew-core`, `Homebrew/core` or `Homebrew/homebrew-core` instead?

I considered this (mainly Homebrew/core or Homebrew-core as it is closest to our usual style) but audits tend to be quite terse and economial. I'm open to changing this though.

**Comment by MikeMcQuaid** [comment]
Another option would be `core tap`. I'm fine with this being merged as-is, though, up to you!

**Comment by jonchang** [comment]
Here are the current references to "core" in audits and custom rubocops:

```
dev-cmd/audit.rb:353:problem "Formula name conflicts with existing core formula."
dev-cmd/audit.rb:954:problem "`env :std` in `core` formulae is deprecated" if line.include?("env :std")
rubocops/lines.rb:204:problem "Don't use #{check.source}; Homebrew/core only supports macOS"
rubocops/urls.rb:238:"Homebrew/homebrew-core is source-only."
```

**Comment by jonchang** [comment]
I've changed this to `homebrew/core` throughout in line with our prose guidelines. Since I consider audits to be user-facing this should conform to the guidelines and be as clear as possible without introducing new jargon to new contributors.

**Comment by jonchang** [comment]
Tests are green; merging. Thanks for the quick review @MikeMcQuaid!

**Pull request merged**
