### PR TITLE
Let Cask doctor exit with 1 via an exception

### PR DESCRIPTION
**Pull request by amyspark**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

This pull request fixes caskroom/homebrew-cask#40198 by raising a CaskError if one or more of the checks fails.

Please review!

### CODE REVIEW

**Comment by amyspark** [comment]
A check about `brew services` is failing. I don't know why; even bisect does not give me a working commit to begin tracking.

**Comment by amyspark** [comment]
Bump! In the meanwhile, I rebased this pull req on the latest `master` commit.

**Comment by reitermarkus** [comment]
I think it would be nice to re-use [`Checkable`](https://github.com/Homebrew/brew/blob/3b4ee58c491f164c2751c1c0f941568c35fb0ac6/Library/Homebrew/cask/lib/hbc/checkable.rb) for this.

**Comment by amyspark** [comment]
@MikeMcQuaid Thanks for the comment. I'll also take the time to reformat the command a bit, in the spirit of `brew cask audit`.

**Pull request closed without merging**
