### PR TITLE
setup-ruby-path: Ensure that Ruby is installed

### PR DESCRIPTION
**Pull request by sjackman**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Fix the error:
```
/usr/local/Homebrew/Library/Homebrew/brew.sh: line 372: exec: : not found
```

### CODE REVIEW

**Comment by sjackman** [comment]
Previously when no Ruby is installed, the vendored Ruby would be installed.
Now when no Ruby is installed, the above error message is printed.
I believe the change of behaviour occurred here:
https://github.com/Homebrew/brew/commit/b2b413165f3553c48c8e060dd97ccde9c13cae80#diff-2012e7e4fc656781b9d32ead2909ee8bR43
This PR restores the previous behaviour. When no Ruby is installed, the vendored Ruby will be installed.

**Comment by MikeMcQuaid** [comment]
> Previously when no Ruby is installed, the vendored Ruby would be installed.

Just trying to understand this: is that if there's no Ruby found even in e.g. `/usr/bin` i.e. this is a Linux only bug? Happy to merge regardless but just want to make sure I understand.

**Comment by sjackman** [comment]
Yes, correct. This bug only affects Linux, since macOS always has `/usr/bin/ruby` available.

**Comment by MikeMcQuaid** [comment]
Thanks again @sjackman!

**Comment by sjackman** [comment]
My pleasure. Thanks again for merging, Mike.

**Pull request merged**
