### PR TITLE
shims/scm/git: Fix the search for brewed git

### PR DESCRIPTION
**Pull request by sjackman**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Search for brewed git in both locations:
```
$HOMEBREW_PREFIX/Homebrew/Library/Homebrew/shims/scm/../../../../../bin/git
$HOMEBREW_PREFIX/Library/Homebrew/shims/scm/../../../../bin/git
```

It previously searched only the latter location.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Thanks! Could you check if the `svn` shim needs a similar fix?

**Comment by sjackman** [comment]
The `svn` shim is a symlink to the `git` shim. 😉

**Comment by MikeMcQuaid** [comment]
> The svn shim is a symlink to the git shim. 😉

I'll take that as a "no" then 😆

**Comment by MikeMcQuaid** [comment]
Thanks again @sjackman!

**Comment by sjackman** [comment]
Thanks for merging, Mike!

**Comment by ilovezfs** [comment]
It seems this broke brew update for some repositories.

```
Josephs-MacBook-Pro:~ joe$ brew update
git: 'credential-osxkeychain' is not a git command. See 'git --help'.
fatal: could not read Username for 'https://github.com': terminal prompts disabled
Error: Fetching /usr/local/Homebrew/Library/Taps/ilovezfs/homebrew-whitelist failed!
Updated Homebrew from 5c7d2d0 to bd471d6.
No changes to formulae.
```

Hence https://github.com/Homebrew/brew/pull/3594

**Pull request merged**
