### PR TITLE
Fix DownloadError erroring itself

### PR DESCRIPTION
**Pull request by Bo98**
Fixes Homebrew/homebrew-cask#146287.

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
Makes sense, thanks @Bo98!

**Comment by herrsergio** [comment]
```
$ brew update --verbose                                                                                                                                                                                                      
Checking if we need to fetch /usr/local/Homebrew...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/adoptopenjdk/homebrew-openjdk...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/argoproj/homebrew-tap...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/aws/homebrew-tap...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/env0/homebrew-terratag...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/fugue/homebrew-regula...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/hashicorp/homebrew-tap...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/saulpw/homebrew-vd...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/teamookla/homebrew-speedtest...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/warrensbox/homebrew-tap...
Fetching /usr/local/Homebrew...
Updating /usr/local/Homebrew...
branch 'master' set up to track 'origin/master'.
Switched to and reset branch 'master'
Your branch is up to date with 'origin/master'.
Switched to and reset branch 'stable'
Current branch stable is up to date.

Already up-to-date.
```

```
$ brew config                                                                                                                                                                                                                
HOMEBREW_VERSION: 4.0.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 01e0c20d01c6aab28d844280d130f0e745e2ddd9
Last commit: 4 days ago
Core tap JSON: 04 May 22:14 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-x86_64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
```

But still getting the error:

```
Error: private method `download_name' called for #<Cask::Download:0x00007f866225fae0>
Did you mean?  downloader
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:612:in `initialize'
/usr/local/Homebrew/Library/Homebrew/downloadable.rb:89:in `new'
/usr/local/Homebrew/Library/Homebrew/downloadable.rb:89:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/downloadable.rb:86:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:51:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:174:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:69:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:100:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:237:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:228:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:228:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

Am I missing something? @Bo98

**Comment by herrsergio** [comment]
NM, seems it is specific for the cask:

```
brew install --cask master-pdf-editor
```

**Comment by Bo98** [comment]
This hasn't made a tagged release but I can do that tonight.

**Pull request merged**
