### PR TITLE
Fix broken link on docs front page

### PR DESCRIPTION
**Pull request by gromgit**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
Case-sensitivity. :grin:

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Thanks again @gromgit!

**Comment by SMillerDev** [comment]
We should probably implement something like this: https://github.com/peter-evans/link-checker I'll make a PR for it later

**Comment by MikeMcQuaid** [comment]
@SMillerDev https://github.com/Homebrew/brew.sh/blob/master/.github/workflows/tests.yml#L23-L24

**Comment by MikeMcQuaid** [comment]
@SMillerDev rule is already there so just a matter of running the checks: https://github.com/Homebrew/brew/blob/master/docs/Rakefile#L10

**Comment by SMillerDev** [comment]
From all I could tell that should already be happening 😓. https://github.com/Homebrew/brew/pull/7142 will at least check if everything is HTTPS though.

**Comment by MikeMcQuaid** [comment]
@SMillerDev Different repos; already happening on brew.sh but docs.brew.sh is hosted out of the docs directory in this repo so any checks would need to be run in this repo's GitHub Actions (Linux-only, I reckon).

**Pull request merged**
