### PR TITLE
Revert "shebang: raise error if no rewriting"

### PR DESCRIPTION
**Pull request by carlocab**
This is causing failures when attempting to rewrite shebangs during the
cleanup stage of `brew install`.

See, for example, Homebrew/homebrew-core#94323,
Homebrew/homebrew-core#94321.

This reverts commit 7e6be5eb4474ed9eaa4b8e9a5a45e3340186840c.

### CODE REVIEW

**Comment by carlocab** [comment]
Marking as `do not merge` while testing to verify the source of the problem in Homebrew/homebrew-core#94323.

**Review by MikeMcQuaid — APPROVED** [review]
Happy to merge when you're happy with it.

**Comment by carlocab** [comment]
Yea, the `install` error is coming from `rewrite_shebang`:

https://github.com/Homebrew/homebrew-core/runs/5036636311?check_suite_focus=true#step:7:16325

@branchvincent we probably want to be able to allow `rewrite_shebang` to error out; especially when called from inside `brew` rather than in a formula.

**Comment by carlocab** [comment]
```
GitHub API Error: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
```
Thanks, GitHub

**Comment by branchvincent** [comment]
thanks @carlocab for beating me to the revert, I'll rework this to be less invasive. sorry for causing trouble!

**Pull request merged**
