### PR TITLE
formula_creator: `ENV.deparallelize` is only for autotools

### PR DESCRIPTION
**Pull request by p-linnane**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
This only functions for autotools, so let's not add it to all the other types of formulae.

### CODE REVIEW

**Review by Bo98 — APPROVED** [review]

**Comment by carlocab** [comment]
I think it works for anything that uses `make`?

**Comment by ZhongRuoyu** [comment]
> I think it works for anything that uses `make`?

Yea, it works with CMake in most cases too, because CMake uses Unix Makefiles as a default generator. We once had `ENV.deparallelize` in `llvm` (https://github.com/Homebrew/homebrew-core/pull/138176#discussion_r1320698973).

**Comment by Bo98** [comment]
LLVM I think is the only place I've seen this used with CMake. It's harder to make bad Makefiles when CMake does a lot of it for you.

**Comment by p-linnane** [comment]
I can open a PR to add it to the `cmake` builds as well if that helps?

**Comment by Bo98** [comment]
Tbh seems better as a Formula Cookbook documentation

**Comment by MikeMcQuaid** [comment]
Yeh, I'd be fine with removing from `brew create` altogether and instead, as @Bo98, just mention in cookbook. It's a bit of a footman given how fucking slow it makes things and is basically just an upstream bug 😭

**Comment by p-linnane** [comment]
Opened https://github.com/Homebrew/brew/pull/16701 to remove from `formula_creator`. It's already mentioned twice in the Formula Cookbook.

**Pull request merged**
