### PR TITLE
Allow --extras parameter to "brew update-python-resources"

### PR DESCRIPTION
**Pull request by vinceatbluelabs**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
  (I needed this bad enough to just implement the feature and use it locally instead of going through an issue discussion first - sorry!)
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).

  I didn't see any existing tests for this module, but can cook some up if you think it's necessary.

- [ ] Have you successfully run `brew style` with your changes locally?

I've applied changes from CI and CI passes the style checks.

I tried running locally and encountered an error installing tools (in nokogiri, of course):

```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby.h:33:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/ruby.h:24:10:
fatal error: 'ruby/config.h' file not found
```

If this covers things which won't be flagged by CI, please let me know and I'll pursue resolving this.

- [ ] Have you successfully run `brew tests` with your changes locally?

Same issue as above.

- [ ] Have you successfully run `brew man` locally and committed any changes?

I manually applied changes flagged by CI.

-----

Python packages can provide different transitive dependencies based on configuration you pass in - it's called a 'setuptools extra' and you can read about it here: https://packaging.python.org/tutorials/installing-packages/#installing-setuptools-extras

To be able to update Python formulas that use these extras on install, I've added a command line parameter which accepts which "extras" to use.

### CODE REVIEW

**Comment by Rylan12** [comment]
Thanks, @vinceatbluelabs! This is great!

Just glancing at the changes, they look pretty good. Might be a few style issues but our CI should pick those up. I'll be able to take a closer look and do some testing later today and then can review if there are any changes I think are needed.

We do need the `brew man` command to be run but I can take care of that for you.

**Comment by vinceatbluelabs** [comment]
Thanks, @Rylan12!  I used CI and fixed the style and `brew man` issues.  I'll keep an eye as CI continues to build to see if there's anything else I can fix up easily from my side.

**Comment by dtrodrigues** [comment]
While this is good, I think what would make it great is if the mapping of formula -> packagename + extras could be added per formula so it doesn't need to be manually specified. Previously, this mapping would be done in `brew` but after https://github.com/Homebrew/brew/pull/9039 and https://github.com/Homebrew/homebrew-core/pull/64043, it might make more sense to do within `homebrew-core`.

A few/many of the formulae in https://github.com/Homebrew/brew/blob/82e1b27624b65f8e091e2b01e2e0f07d13e6e5a0/Library/Homebrew/utils/pypi.rb#L13-L22 are there because they require extras/other packages, a different package (eg `molecule`, `diffoscope`, `ipython`), so it would be ideal if the changes here could be used to pass in the additional information and then vanilla `brew bump-formula-pr` would work.

See also  https://github.com/Homebrew/brew/pull/8770, in particular https://github.com/Homebrew/brew/pull/8770#issuecomment-695967638.

**Comment by Rylan12** [comment]
> While this is good, I think what would make it great is if the mapping of formula -> packagename + extras could be added per formula so it doesn't need to be manually specified.

I agree

> Previously, this mapping would be done in `brew` but after #9039 and [Homebrew/homebrew-core#64043](https://github.com/Homebrew/homebrew-core/pull/64043), it might make more sense to do within `homebrew-core`.

Yes, this should be added to Homebrew/core

I'm picturing something like `pypi_automatic_update_mappings.json`:

```json
{
  "molecule": ["molecule", "docker-py", "python-vagrant"],
  "diffoscope": "diffoscope[cmdline]",
  "ipython": "ipykernal"
}
```

Not sure if we want to specify extras in a different way. If we wanted to cover all possibilities:
- `"foo": {"foo": "bar"}` becomes `diffoscope[cmdline]`
- `"foo": {"foo": ["bar", "baz"]}` becomes `foo[bar,baz]`
- `"foo": [{"foo": ["bar", "baz"]}, "foo1"]` becomes `foo[bar,baz` and `foo1`

Maybe that's too complicated, though, and we should just specify the extras as a string with brackets. I have to think about it a little more I guess. There probably aren't many formulae that need these super-complex rules so these are probably unnecessary.

---

Regardless of the above, I think this PR should move forward. @vinceatbluelabs, if you're interested in pursuing this further, I can help guide you in implementing some of these. If not, no worries! I'd suggest merging this PR and either @dtrodrigues or I will follow up with another PR in the future.

**Comment by Rylan12** [comment]
Actually, thinking about this more, I would rather go with the `--package-name` implementation in #8770. `--package-name` could accept an array and then `update-python-resources` will get the resources from each item in the list. The items could contain setuptools extras or not. That will also make the implementation of the formula-resource-mapping described above easier. Thoughts, @dtrodrigues?

Since that PR hasn't had any activity, we can go ahead with those changes here or in a separate PR.

**Comment by dtrodrigues** [comment]
`--package-name` taking multiple packages, each possibly having extras, looks like a good approach. The first suggestion for the format of `pypi_automatic_update_mappings.json` seems to offer sufficient flexibility while not being overly complex, and should significantly cut back on cases where manual intervention is required.

**Comment by vinceatbluelabs** [comment]
Hi there!  I don't think I'll likely be able to contribute code towards the alternate direction in the near term.  That said, it certainly sounds like it would also satisfy my use case, and the idea of allowing extras to eventually be used in `brew bump-formula-pr` certainly sounds appealing here.  Feel free to close this PR as needed.

**Comment by Rylan12** [comment]
Thanks for spending the time to open and work on this, @vinceatbluelabs! We really appreciate it!



I'm going to close this but will follow up later today with a PR implementing the `--package-name` flag. I'll link it in this conversation so you can follow if you're interested.

**Comment by Rylan12** [comment]
I've opened the PR: #9185

**Pull request closed without merging**
