### PR TITLE
Add make shim to Linux super env

### PR DESCRIPTION
**Pull request by maxim-belkin**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Add a `shim` for `make` that has been missing from the super env on Linux. 

CC @sjackman and @iMichka

### CODE REVIEW

**Comment by sjackman** [comment]
It looks to me as though `shims/linux/super/make` would call itself in an infinite loop (unconfirmed).

**Comment by sjackman** [comment]
A question for the Homebrew developers. `shims/mac/super/make` adds `O` to `HOMEBREW_CCCFG` to enabled `ENV.refurbish_args` by default for any formula that uses `make`, but not for `./configure` or any non-make build system. Does someone know why that is, rather than enabling `ENV.refurbish_args` by default for all build systems?

**Comment by maxim-belkin** [comment]
> It looks to me as though shims/linux/super/make would call itself in an infinite loop (unconfirmed).

Ha! interesting observation. It might be the case. I guess we have to change line 7 to`
```
MAKE=$(type -p make)
```
or 
```
MAKE=$(command -v make)
```
?

**Comment by sjackman** [comment]
Perhaps, but you'll need to first exclude `…/shims/linux/super` from `PATH`.

**Comment by maxim-belkin** [comment]
@sjackman done

**Comment by jonchang** [comment]
> A question for the Homebrew developers. shims/mac/super/make adds O to HOMEBREW_CCCFG to enabled ENV.refurbish_args by default for any formula that uses make, but not for ./configure or any non-make build system. Does someone know why that is, rather than enabling ENV.refurbish_args by default for all build systems?

Wouldn't enabling `refurbish_args` make most checks in `./configure` pointless since e.g. autotools will call `cc` with different flags to determine what kind of compiler, etc. it's running on?

**Comment by sjackman** [comment]
Yes, `ENV.refurbish_args` would probably break `./configure`. There's a check to prevent specifically that:
https://github.com/Homebrew/brew/blob/0d33aba0b7d8448e815a2eecc92417b46cb905f3/Library/Homebrew/shims/super/cc#L104

I'm more curious why `ENV.refurbish_args` is not use for other non-make build systems, or phrased another way, why it's used specifically for `make`.

**Comment by sjackman** [comment]
Also interesting that `ENV.refurbish_args` is not used when`ld` is used for linking, but is used when `cc` is used for linking.

**Comment by ilovezfs** [comment]
Presumably because `make` usually is separated from configure.

**Comment by MikeMcQuaid** [comment]
Why is/does this need to be different from the macOS shim?

**Comment by maxim-belkin** [comment]
we don't have `xcrun`

**Comment by MikeMcQuaid** [comment]
I see. The path removal feels a little cludgy; is there no easier way of doing that?

**Comment by MikeMcQuaid** [comment]
@maxim-belkin Ping?

**Comment by maxim-belkin** [comment]
How can I improve this PR?  Rewrite `pathremove` function? 
I can make it specific to `PATH` var instead of any variable but I don't know if it will be an improvement.

**Comment by MikeMcQuaid** [comment]
@maxim-belkin It's fine with me, just a question. Merging, thanks again!

**Comment by maxim-belkin** [comment]
Thanks, Mike!

**Pull request merged**
