### PR TITLE
disable!, deprecate!: add reason

### LINKED ISSUE #8501: Report more detail on why a formula is disabled.
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

Add ability for "disabled" formula to include a reason and or link to why the formula is disabled. See osquery https://github.com/Homebrew/homebrew-core/pull/54905 where the version in the repo contains security vulnerabilities, is out of date, and no plans to update in place.

# The motivation for the feature

Unnecessary investigation for users to understand why a formula is disabled. It might make more sense to remove formulas if there is no intention to provide users with direct information beyond:

brew install osquery
Error: osquery has been disabled!

Which resulted in my opening an inquiry to IT, who confirmed they did not disable it. Followed by tracing down the related commit (which wasn't even the last commit to this formula).

commit d00c56283ab915727e9dd70b20031ef7f361dcfe
Author: Sean Molenaar <smillerdev@me.com>
Date:   Mon May 18 17:30:45 2020 +0200
    osquery: disable

Which again failed to explain why it was disabled, which I then had to search the issues, of which there are no open issues indicated why it was disabled. So I then searched types for osquery which found this pull request.

https://github.com/Homebrew/homebrew-core/pull/54905

# How the feature would be relevant to at least 90% of Homebrew users

They would know why they should not attempt to install this formula or inquiry within their own org to identify why it isn't working. And prevent them from modifying the formula to install it (removing the disabled flag locally) and potentially installing dangerous software.

# What alternatives to the feature have been considered

Remove any formula which would otherwise be disabled, this avoids all the unnecessary issues with trying to understand why it's disabled to begin with. And prevents anyone from simply editing the local brew formula and forcing an install for most people.

### PR DESCRIPTION
**Pull request by Rylan12**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Resolves #8501

Add a reason for disabling and deprecating a formula. This means that the error that a user gets when trying to install one of these has more information and makes it easier to figure out what the problem is.

Example:

```ruby
disable! because: "it cannot be built from source"
```

Right now, the `because:` parameter is optional. I plan on making it required by `brew style`, but I think we need to wait for the next release so that Homebrew/core formulae can accept the reason.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> Right now, the `because:` parameter is optional. I plan on making it required by `brew style`, but I think we need to wait for the next release so that Homebrew/core formulae can accept the reason.

I'd also consider adding a commented-out `odeprecated` so we can deprecate it if it's not present on the next major/minor release, too.

**Comment by gromgit** [comment]
Can I suggest adding a `pr:` argument that specifies the PR# that did the deed, that outputs something like `See https://github.com/homebrew/homebrew-core/pulls/X for details`?

**Comment by Rylan12** [comment]
> I'd also consider adding a commented-out `odeprecated` so we can deprecate it if it's not present on the next major/minor release, too.

Good idea. Just to clarify, does that mean that we'll uncomment the line (deprecating it) when 2.5 is released and then remove the line for 2.6?

> Can I suggest adding a `pr:` argument that specifies the PR# that did the deed, that outputs something like `See https://github.com/homebrew/homebrew-core/pulls/X for details`? Perhaps this can be injected automagically via CI?

Definitely like this idea. Not sure if CI can do it automatically (I'd be diving into some new territory there). If it can't, I could see this being a pain point because you don't easily know what PR number you'll get until you make it.

**Comment by MikeMcQuaid** [comment]
> Good idea. Just to clarify, does that mean that we'll uncomment the line (deprecating it) when 2.5 is released and then remove the line for 2.6?

Yup!

> Can I suggest adding a `pr:` argument that specifies the PR# that did the deed, that outputs something like `See https://github.com/homebrew/homebrew-core/pulls/X for details`? Perhaps this can be injected automagically via CI?

CI can't do it automatically really and this would be a bit awkward to have to create a PR and then force push to it. It's also inviting people to jump on the PR and complain which I'm not sure is a good idea.

**Comment by gromgit** [comment]
I think the CI injection part can be skipped for now, since deprecation/disabling is rare enough that a quick edit/force-push shouldn't be too burdensome.

**Comment by MikeMcQuaid** [comment]
> since deprecation/disabling is rare enough that a quick edit/force-push shouldn't be too burdensome.

I'd rather not put this onus on maintainers for something which I don't see as adding to the communication and gives people a bandwagon to be negative on.

**Comment by Rylan12** [comment]
> I'd rather not put this onus on maintainers for something which I don't see as adding to the communication and gives people a bandwagon to be negative on.

Yeah, I agree. Plus, people can still find the PRs without too much trouble if they know where to look...

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks again @Rylan12!

**Comment by MikeMcQuaid** [comment]
> Right now, the `because:` parameter is optional. I plan on making it required by `brew style`, but I think we need to wait for the next release so that Homebrew/core formulae can accept the reason.

@Rylan12 I've tagged 2.4.14 now and uncommented the deprecations in https://github.com/Homebrew/brew/pull/8513 which (as expected) is causing a CI failure. If you could add these reasons en-masse to homebrew-core I can handle linuxbrew-core and the other taps. Cheers again, great work! ❤️

**Comment by Rylan12** [comment]
@MikeMcQuaid I've opened a PR for the `disable!` reasons at https://github.com/Homebrew/homebrew-core/pull/60321/files

Looking at the `deprecate!` reasons, though, I'm not sure it makes as much sense to require a reason. Most of the time, it looks like the reason would just be "it was deprecated upstream" or "it stopped being maintained". Should we still make this required?

**Comment by MikeMcQuaid** [comment]
> Looking at the `deprecate!` reasons, though, I'm not sure it makes as much sense to require a reason. Most of the time, it looks like the reason would just be "it was deprecated upstream" or "it stopped being maintained". Should we still make this required?
> 
> Edit: there are more exceptions to this than I thought, so I think it's okay to keep the requirement. I'll open the PR and it can be discussed there

Could provide symbols like with `keg_only` to be able to quickly specify a given, longer message?

**Pull request merged**
