### PR TITLE
vendor-install: Add portable-ruby for aarch64 (ARM64)

### PR DESCRIPTION
**Pull request by sjackman**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Thanks @sjackman!

**Comment by zbeekman** [comment]
Just, catching up here, but did you resolve the pouring of bottles issue? Or is aarch64 not affected, because there are no bottles for it yet?

**Comment by sjackman** [comment]
Thanks for merging, Mike!

**Comment by sjackman** [comment]
> Just, catching up here, but did you resolve the pouring of bottles issue?

Is that the UID/GID issue with `tar`? If so, it only affects pouring bottles while root, which should only affect Docker and CI.

**Comment by zbeekman** [comment]
> Is that the UID/GID issue with `tar`? If so, it only affects pouring bottles while root, which should only affect Docker and CI.

No I was referring to the fact that my adventures with portable ruby on x86_64 Linux last Friday were unsuccessful because `brew portable-package portable-ruby` was pouring bottled glibc, gcc, etc.: https://github.com/Homebrew/homebrew-portable-ruby/issues/74

I was curious if that problem hit you at all, however, I think I answered my own question: on aarch64 there are no bottles (until you added portable ruby, etc.) so when you built portable-ruby there would have been no way for homebrew to have poured bottles for you.

**Comment by sjackman** [comment]
You're right. That issue of pulling in `glibc` and `gcc` did not occur on AArch64, where there are no bottles. To troubleshoot the issue on `x86_64_linux`, run `brew deps -n --include-build portable-ruby` and install the dependencies one-by-one with `brew install -s foo`. None of them should install `glibc` or `gcc`. When you find one that does, you've found the bug.

It may be a bug in `brew install` itself, that `brew install -s a b c d e` is not equivalent to `for i in a b c d e; do brew install -s $i; done`.

**Comment by zbeekman** [comment]
> When you find one that does, you've found the bug.

:+1:



> It may be a bug in `brew install` itself, that `brew install -s a b c d e` is not equivalent to `for i in a b c d e; do brew install -s $i; done`.

I tried both methods. I'll go through one at a time and see who the culprit is. I know it's not `portable-zlib`.

**Pull request merged**
