### PR TITLE
Invite contributors to view our Trello board

### PR DESCRIPTION
**Pull request by tdsmith**
A thumbs-up here is also a thumbs-up for making the board publicly visible. :)

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Personally I'm 👎 on this; I don't think it's well maintained enough and I'd personally really rather we doubled-down on GitHub issues features (labels, assignments, milestones) for this stuff.

**Comment by tdsmith** [comment]
> I'd personally really rather we doubled-down on GitHub issues features (labels, assignments, milestones) for this stuff

I think Trello can be better than it is but I'm ultimately agnostic to the system we use; what do you imagine this looking like?

**Comment by mikemcquaid** [comment]
@tdsmith A few things we could be doing that we're not (some are mutually exclusive):
- Tracking issues using checkboxes that we link to other issues. These could perhaps even live in a `Homebrew/planning` repository to make it easier for the community to follow along
- Use issue milestones: https://github.com/Homebrew/brew/milestones
- Assign the issues that are being actively worked on (i.e. you'll do some work towards this issue in the next week)
- For every "feature" PR mandate an issue describing and discussing the feature

Some of these are overkill but could improve communication with the community like you mention

**Comment by tdsmith** [comment]
Closing for now.

**Pull request closed without merging**
