### PR TITLE
minor typo

### PR DESCRIPTION
**Pull request by numbergames**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Fixed minor typo -- missing preposition.

### CODE REVIEW

**Comment by scpeters** [comment]
:+1: for grammar

**Comment by zmwangx** [comment]
I read most of the doc pages yesterday and had a whole bunch of nits fixed in a local branch. Guess I'm gonna let them slip because there are simply too many of them... Just saying.

**Comment by scpeters** [comment]
@zmwangx it's your call, but I'm happy to review the branch if you push it, even if it's not everything

**Comment by tdsmith** [comment]
Thanks!

**Pull request merged**
