### PR TITLE
go: various tweaks to recommendations

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

CC @ilovezfs re https://github.com/Homebrew/homebrew-core/pull/19791#issuecomment-338984764.

### CODE REVIEW

**Comment by ilovezfs** [comment]
The only issue I can foresee here would be that the mere fact that someone tried to use `go get` or a `go_resource` block in a formula doesn't itself imply that upstream hasn't already implemented Go vendoring. But I suppose if they go ask upstream for vendoring that is actually already there, upstream can tell them that is the case, which might be annoying for some upstreams, but is probably acceptable since it's a one-time annoyance.

**Comment by DomT4** [comment]
Aye. I mean we could tell people to open the source tarball & look for a `vendor` directory before asking upstream but I couldn't think of a way to communicate that succinctly in a way that would be accessible to everyone however new to the project or not they are.

One thing that is potentially a hiccup: Things like `gox` could be considered semi-legitimate `go_resource`s. We could either whitelist `gox` and its deps or add a `gox` formula breaking the normal rule that formulae pegged to `revision`s should also be pegged to a `tag`, since the last `gox` tag was years ago.

**Comment by ilovezfs** [comment]
>One thing that is potentially a hiccup: Things like gox could be considered semi-legitimate go_resources. We could either whitelist gox and its deps or add a gox formula breaking the normal rule that formulae pegged to revisions should also be pegged to a tag, since the last gox tag was years ago.

Right. I'm perfectly happy to ignore that for now since it's --strict only. My sense is that everything that "has to" be a `go_resource` could be made a formula one way or another but a little whitelist seems like a good interim solution.

**Comment by DomT4** [comment]
> I'm perfectly happy to ignore that for now since it's --strict only.

Aye. I wanted to enable it always but it's just way too common at the moment & would be CI chaos 😢. I'll chuck a whitelist for the `gox` stuff in here with a small note that the whitelist should ideally not live on forever.

**Comment by ilovezfs** [comment]
probably also `go-bindata`

**Comment by ilovezfs** [comment]
and `github.com/rogpeppe/godeps` (and its dep `github.com/kisielk/gotool`), but maybe we can convince `charm` to adopt something more mainstream.

**Comment by ilovezfs** [comment]
(only 12 installs of charm in the last 30 days …)

**Comment by DomT4** [comment]
Will look at this one tonight after I get back from the gym.

**Comment by DomT4** [comment]
Sigh. _Will_ look at this one soon. Having a bit of a not ideal end to the week 🙄. Apologies for the delay.

**Comment by DomT4** [comment]
Oh heck, thanks for the reminder bot. I did indeed forget.

**Comment by ilovezfs** [comment]
That stupid :robot: needs to learn to mind its own business.

**Comment by DomT4** [comment]
1% of the time it's a useful reminder. It makes a nice change from me simply telling it to go away, I guess.

**Comment by DomT4** [comment]
Go away.

**Comment by MikeMcQuaid** [comment]
Would like to see this merged but let's not let it sit open fighting with stale bot forever.

**Comment by MikeMcQuaid** [comment]
@DomT4 can you open a new PR when you've addressed the comments? Thanks (and do shout at me if you feel this process is offensively annoying).

**Comment by DomT4** [comment]
Aye, sure, no worries. I'm home from uni in a few days so I should have a more predictable blob of time to look into Rubocop's syntax a little more.

**Comment by ilovezfs** [comment]
I'm actually happy with this as-is without the whitelist. Gox finally created a tag for us so the biggest offender will be dispensed with shortly.

**Comment by MikeMcQuaid** [comment]
Thanks again @DomT4!

**Comment by ilovezfs** [comment]
homebrew/core tracking issue for `go_resource` block removals: https://github.com/Homebrew/homebrew-core/issues/21801

**Comment by ilovezfs** [comment]
New formula for Gox as promised: https://github.com/Homebrew/homebrew-core/pull/22005

**Pull request merged**
