### PR TITLE
Document `Tab.for_keg` and use `Keg#tab` where possible.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

### CODE REVIEW

**Comment by carlocab** [comment]
`Keg#tab` just calls `Tab.for_keg` so I'm not sure why you would prefer `Keg#tab` over `Tab.for_keg`.

**Comment by reitermarkus** [comment]
Because it's shorter.

**Comment by reitermarkus** [comment]
Also, to better keep track of where `Tab.for_keg` is still called with a `Pathname`, so we can eventually change it to only take `Keg`s.

**Review by MikeMcQuaid — COMMENTED** [review]
Looks good, thanks again @reitermarkus!

**Review by MikeMcQuaid — APPROVED** [review]

**Pull request merged**
