### PR TITLE
ARGV: Deprecate ARGV.build_formula_from_source? and ARGV.build_from_source?

### PR DESCRIPTION
**Pull request by GauthamGoli**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
#5730

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Thanks again @GauthamGoli!

**Comment by bayandin** [comment]
It looks like `-s`/`--build-from-source` doesn't work anymore, it downloads bottle anyway:
```
$ brew install -s webfs
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/webfs-1.21_1.catalina.bottle.1.tar.gz
^C
```

**Comment by jnozsc** [comment]
same, this change breaks `-s/--build-from-source `

**Comment by MikeMcQuaid** [comment]
This should be fixed as-of https://github.com/Homebrew/brew/pull/7282.

**Comment by jnozsc** [comment]
> brew config
```
HOMEBREW_VERSION: 2.2.11-130-g6f50801
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6f50801b37b7d829afc37da76d2ef0a1ac1c9f5f
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 87bb8e888cd7e6996380078a506df1e2dee14edc
Core tap last commit: 3 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_ANALYTICS: 1
HOMEBREW_NO_INSTALL_OLDER_PRERELEASE_BOTTLES: 1
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.26.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.4-x86_64
CLT: 11.4.0.0.1.1583798712
Xcode: N/A
```

> brew install -s luajit
```
==> Downloading https://homebrew.bintray.com/bottles/luajit-2.0.5.catalina.bottle.3.tar.gz
==> Downloading from https://akamai.bintray.com/90/907d7fbbd3be370fac28341bf902a551c1d07dd929b9379bb19e30ccaf0bdef6?__gda__=exp=1586108279~hmac=12d26
######################################################################## 100.0%
==> Pouring luajit-2.0.5.catalina.bottle.3.tar.gz
🍺  /usr/local/Cellar/luajit/2.0.5: 31 files, 1.9MB
```

do I miss anything?

**Comment by jnozsc** [comment]
I can confirm the revert #7289 can fix the issue. Thanks

**Pull request merged**
