### PR TITLE
Fall back to `CaskLoader.load` to get a better error message.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Closes https://github.com/Homebrew/homebrew-cask/issues/47617.

### CODE REVIEW

**Comment by twogee** [comment]
That's much better, but there's no information about how to remove the casks with unavailable formulas. Simply `rm -rf /usr/local/Caskroom/<formula>`?

**Comment by reitermarkus** [comment]
@twogee, yes, exactly.

**Comment by vitorgalvao** [comment]
@twogee Though keep in mind that won’t remove the actual app from your system. To do that, do whatever you would do if you had installed it manually.

**Comment by twogee** [comment]
Thanks, sorry for somewhat confusing comment regarding aid to mop up stale formulas (or whatever the appropriate term is) 😉.

**Pull request merged**
