### PR TITLE
remove appcast checkpoints

### PR DESCRIPTION
**Pull request by commitay**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
https://github.com/Homebrew/homebrew-cask/issues/48051

- Remove `_appcast_checkpoint`/`calculate_checkpoint` command and entry from manpage.
- Remove the current appcast checkpoint audits and add an audit that checks if the cask has a checkpoint.
- Update/remove test fixtures.
- Remove `appcast` from `internal_audit_modified_casks` so an appcast change doesn't trigger a download on CI.

cc @Homebrew/cask

### CODE REVIEW

**Comment by commitay** [comment]
Test failure looks unrelated and isn't reproducible for me locally.

**Comment by commitay** [comment]
@vitorgalvao I'll hold off merging this until you can merge the cask-repair PR and release an update.

**Comment by vitorgalvao** [comment]
@commitay Done and done.

**Comment by commitay** [comment]
I'll go through the checkpoint removal PRs now.

**Pull request merged**
