### PR TITLE
pull: fix polling code for Ruby 1.8.7 Net::HTTP

### PR DESCRIPTION
**Pull request by apjanke**
Fixes 1.8.7 compatibility bug in #132.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
LGTM if it works 👍

**Comment by apjanke** [comment]
Thanks. I tested it for a couple bottle pulls on Ruby 2.0 and 1.8.7 on my OS X 10.9.5 box and it worked. Waiting to hear from @ilovezfs to see if it fixes it for him, too.

**Comment by ilovezfs** [comment]
:+1: 
Yup, fixed. Thanks @apjanke 

```
Josephs-MacBook-Pro:homebrew-x11 joe$ git reset --hard HEAD^
HEAD is now at 962cafa scantailor 0.9.12.2
Josephs-MacBook-Pro:homebrew-x11 joe$ git reset --hard HEAD^
HEAD is now at ea82649 swi-prolog: migrate to core
Josephs-MacBook-Pro:homebrew-x11 joe$ brew pull --bottle https://github.com/Homebrew/homebrew-x11/pull/205
==> Fetching patch 
Patch: https://github.com/Homebrew/homebrew-x11/pull/205.patch
==> Applying patch
Applying: scantailor 0.9.12.2
==> Patch closes issue #205
==> Fetching patch (bottle commit)
Patch: https://github.com/BrewTestBot/homebrew-x11/compare/homebrew:master...pr-205.patch
==> Applying patch
Applying: scantailor 0.9.12.2
Applying: scantailor: update 0.9.12.2 bottle.
==> Publishing on Bintray: scantailor 0.9.12.2
{"files":0}
==> Patch changed:
 scantailor.rb | 86 +++++++++++++++--------------------------------------------
 1 file changed, 21 insertions(+), 65 deletions(-)
==> Verifying bottles published on Bintray
Verifying bottle: scantailor-0.9.12.2.mavericks.bottle.tar.gz
Error: can't convert Hash into String
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:560:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:560:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:560:in `connect'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/timeout.rb:53:in `timeout'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/timeout.rb:101:in `timeout'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:560:in `connect'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:553:in `do_start'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:542:in `start'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:440:in `start'
/usr/local/Library/Homebrew/cmd/pull.rb:521:in `verify_bintray_published'
/usr/local/Library/Homebrew/cmd/pull.rb:502:in `each'
/usr/local/Library/Homebrew/cmd/pull.rb:502:in `verify_bintray_published'
/usr/local/Library/Homebrew/extend/pathname.rb:328:in `cd'
/usr/local/Library/Homebrew/extend/pathname.rb:328:in `chdir'
/usr/local/Library/Homebrew/extend/pathname.rb:328:in `cd'
/usr/local/Library/Homebrew/cmd/pull.rb:501:in `verify_bintray_published'
/usr/local/Library/Homebrew/cmd/pull.rb:234:in `pull'
/usr/local/Library/brew.rb:87:in `send'
/usr/local/Library/brew.rb:87
Josephs-MacBook-Pro:homebrew-x11 joe$ git reset --hard @{u}
HEAD is now at 49eb1d4 scantailor: update 0.9.12.2 bottle.
Josephs-MacBook-Pro:homebrew-x11 joe$ git reset --hard HEAD^
HEAD is now at 962cafa scantailor 0.9.12.2
Josephs-MacBook-Pro:homebrew-x11 joe$ git reset --hard HEAD^
HEAD is now at ea82649 swi-prolog: migrate to core
Josephs-MacBook-Pro:homebrew-x11 joe$ cd /usr/local
Josephs-MacBook-Pro:local joe$ git reset --hard @{u}
HEAD is now at 60e3737 update: improve some edge cases.
Josephs-MacBook-Pro:local joe$ brew pull https://github.com/Homebrew/brew/pull/191
==> Fetching patch 
Patch: https://github.com/Homebrew/brew/pull/191.patch
==> Applying patch
Applying: pull: fix polling code for Ruby 1.8.7 Net::HTTP
==> Patch closes issue #191
==> Patch changed:
 Library/Homebrew/cmd/pull.rb | 6 ++++--
 1 file changed, 4 insertions(+), 2 deletions(-)
Josephs-MacBook-Pro:local joe$ cd -
Josephs-MacBook-Pro:homebrew-x11 joe$ git status
On branch master
Your branch is behind 'origin/master' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working directory clean
Josephs-MacBook-Pro:homebrew-x11 joe$ brew pull --bottle https://github.com/Homebrew/homebrew-x11/pull/205
==> Fetching patch 
Patch: https://github.com/Homebrew/homebrew-x11/pull/205.patch
==> Applying patch
Applying: scantailor 0.9.12.2
==> Patch closes issue #205
==> Fetching patch (bottle commit)
Patch: https://github.com/BrewTestBot/homebrew-x11/compare/homebrew:master...pr-205.patch
==> Applying patch
Applying: scantailor 0.9.12.2
Applying: scantailor: update 0.9.12.2 bottle.
==> Publishing on Bintray: scantailor 0.9.12.2
{"files":0}
==> Patch changed:
 scantailor.rb | 86 +++++++++++++++--------------------------------------------
 1 file changed, 21 insertions(+), 65 deletions(-)
==> Verifying bottles published on Bintray
Verifying bottle: scantailor-0.9.12.2.yosemite.bottle.tar.gz
######################################################################## 100.0%
Josephs-MacBook-Pro:homebrew-x11 joe$
```

**Comment by apjanke** [comment]
Merged. You should be good to go now. Sorry for the inconvenience!

**Comment by ilovezfs** [comment]
No problem! Sorry for being a stick in the mud with my beloved 10.8.

**Comment by apjanke** [comment]
Hey, no worries. When the 10.12 beta comes out in a couple months, that's gonna be me and my beloved 10.9.

**Pull request merged**
