### PR TITLE
language/haskell: move to compat

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Cabal sandboxes have now been removed upstream (https://github.com/haskell/cabal/commit/6248c74280a54382f85079f58a1ea40ba0db9476) which means a large part of this module will cease to function when cabal-install 3.4 releases in the coming months.

Given that, it would be good to deprecate in #7579, unless migrating homebrew-core is a hard requirement.

Either way, it's possible that cabal-install 3.4 will release before the subsequent Homebrew minor version is released to `odisable` the module so we may need to revisit this later to see what we can do - such as no-opping the `cabal_sandbox` function.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> Given that, it would be good to deprecate in #7579, unless migrating homebrew-core is a hard requirement.

Yeh, it will be (to deprecate but not add to `combat`). Could you add a commented-out `odeprecated` for each of these methods? We can uncomment it in https://github.com/Homebrew/brew/pull/7579 once homebrew-core migrated (but merge this first).

**Comment by Bo98** [comment]
Only thing is that calling `install_cabal_package` might trigger like 6 deprecated warnings, if that matters? I suppose that makes it obvious I guess.

**Comment by MikeMcQuaid** [comment]
> Only thing is that calling `install_cabal_package` might trigger like 6 deprecated warnings, if that matters? I suppose that makes it obvious I guess.

Yeh, that's fine, I think. It'll `raise` in CI.

**Comment by MikeMcQuaid** [comment]
Thanks again @Bo98!

**Pull request merged**
