### PR TITLE
Allow packages to use gnureadline lazily

### PR DESCRIPTION
**Pull request by tdsmith**

### CODE REVIEW

**Comment by tdsmith** [comment]
cf https://github.com/Homebrew/homebrew-core/pull/3685; an alternative is to patch this on a formula-by-formula basis.

**Comment by tdsmith** [comment]
Closing for now; let's see how often this pops up.

**Comment by ilovezfs** [comment]
Interestingly this PR doesn't actually seem to work:
```
==> /usr/local/Cellar/dxpy/0.191.0/bin/dx env
Warning: incompatible readline module detected (libedit), tab completion disabled
iMac-TMP:homebrew-core joe$ find /usr/local/Cellar|grep homebrew-gnureadline-hack.pth
/usr/local/Cellar/dxpy/0.191.0/libexec/lib/python2.7/site-packages/homebrew-gnureadline-hack.pth
```

**Comment by tdsmith** [comment]
Oops :( Must have worked accidentally in testing; I don't see it working now.

**Comment by tdsmith** [comment]
It looks like placing `import sys; import gnureadline; sys.modules["readline"] = gnureadline` in the .pth file works.

**Comment by ilovezfs** [comment]
@tdsmith yes that works although I have to write out the file after pipneedful. If it's before,
```
==> python -s /tmp/dxpy--homebrew-virtualenv-20160808-24099-eeksqq/target/bin/virtualenv -p python /usr/local/Cellar/dxpy/0.191.0/libexec
Traceback (most recent call last):
  File "/usr/local/Cellar/dxpy/0.191.0/libexec/lib/python2.7/site.py", line 703, in <module>
    main()
  File "/usr/local/Cellar/dxpy/0.191.0/libexec/lib/python2.7/site.py", line 683, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "/usr/local/Cellar/dxpy/0.191.0/libexec/lib/python2.7/site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/usr/local/Cellar/dxpy/0.191.0/libexec/lib/python2.7/site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/local/Cellar/dxpy/0.191.0/libexec/lib/python2.7/site.py", line 173, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
ImportError: No module named gnureadline
Already using interpreter /usr/bin/python
New python executable in /usr/local/Cellar/dxpy/0.191.0/libexec/bin/python
ERROR: The executable /usr/local/Cellar/dxpy/0.191.0/libexec/bin/python is not functioning
ERROR: It thinks sys.prefix is u'/private/tmp/dxpy--homebrew-virtualenv-20160808-24099-eeksqq/virtualenv-15.0.2' (should be u'/usr/local/Cellar/dxpy/0.191.0/libexec')
ERROR: virtualenv is not compatible with this system or executable
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: python -s /tmp/dxpy--homebrew-virtualenv-20160808-24099-eeksqq/target/bin/virtualenv -p python /usr/local/Cellar/dxpy/0.191.0/libexec
```

Any tweak that would make it not care where we put this in the formula? Not that it matters really...

**Comment by tdsmith** [comment]
Oh, of course, hadn't considered that. I'll have to think about it; you can't do exception handling in .pth files, unfortunately...

**Comment by ilovezfs** [comment]
probably fine if it has to go at the end, but just a gotcha to be aware of when we're reviewing these

**Pull request closed without merging**
