### PR TITLE
Define OS::Mac on Linux

### PR DESCRIPTION
**Pull request by sjackman**
Define `OS::Mac` on Linux for formula API compatibility.

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Define `MacOS.version`, `MacOS.full_version`, and `MacOS::Xcode.version` to `Version::NULL` on Linux so that `brew readall` succeeds and `Homebrew/brew` can tap `Homebrew/core` on Linux.

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Hmmm... wouldn't it be better to define two new methods instead, _i.e._ `olderthan?` and `newerthan?` so that, as an example
```
MacOS.version <= :snow_leopard
```
would become
```
MacOS.version.older_than? :snow_leopard
```
And make both of the methods return `false` on Linux... Otherwise, the above comparison will be returning `true` on Linux

**Comment by maxim-belkin** [comment]
```
$ uname -s && brew irb <<< "Version::NULL < :snow_leopard"
Linux
==> Interactive Homebrew Shell
Example commands available with: brew irb --examples
Switch to inspect mode.
Version::NULL < :snow_leopard
true
```

**Comment by sjackman** [comment]
The primary intention of this patch is to make it possible to tap `Homebrew/core` using `Homebrew/brew` running on Linux. We can discuss in a separate PR possible changes to the Homebrew formula API.

**Comment by maxim-belkin** [comment]
Four methods would be required, actually :thinking: :
```
<    :  older_than?
<=   :  not_newer_than?
>=   :  not_older_than?
>    :  newer_than?
```

**Comment by maxim-belkin** [comment]
Sure, but this is a hack. `MacOS.version` is meaningless on Linux and should not be returning NULL. If anything, it should give something like "not defined". We can not assume that all Linux distributions correspond to old macOS.

**Comment by sjackman** [comment]
`Version:NULL` does mean not defined.

**Comment by maxim-belkin** [comment]
`Version::NULL < something` evaluates to `true` for any number and any string, whereas
`Version::NULL > something` evaluates to `false` even for negative numbers.
So, whenever there is `MacOS.version < something` comparison in a formula, it will be considered as `true` on Linux. So, unless it's augmented/prefixed by `OS.mac? &&` this might lead to incorrect/undesired behavior or unnecessary patches being applied

```bash
$ uname -s
Linux

$ cd $(brew --repo homebrew/core)/Formula

$ grep -w "MacOS.version <" * | wc -l
312

$ grep -w "MacOS.version <" * | grep 'OS.mac?' | wc -l
14
```

**Comment by MikeMcQuaid** [comment]
> Version::NULL does mean not defined. You can use Version.null? to test whether a version is null.

I agree, let's keep with this approach.

@sjackman Does this patch enable an otherwise unpatched Homebrew/brew to `brew readall` on Homebrew/homebrew-core?

**Comment by ilovezfs** [comment]
>So, whenever there is MacOS.version < something comparison in a formula, it will be considered as true on Linux.

This is caused by spaghetti formulae that attempt to interweave macOS and Linux support and/or reuse macOS formulae from Homebrew/homebrew-core.

**Comment by MikeMcQuaid** [comment]
Thanks again @sjackman!

**Comment by sjackman** [comment]
> Does this patch enable an otherwise unpatched Homebrew/brew to brew readall on Homebrew/homebrew-core?

Yes!

Thanks for merging, Mike.

**Pull request merged**
