### PR TITLE
uninstall: Use CLI::Parser to parse args

### PR DESCRIPTION
**Pull request by GauthamGoli**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
#1860 

Any suggestions on how to fix the breaking test ? What I'm doing seems more like a hack.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> Any suggestions on how to fix the breaking test ? What I'm doing seems more like a hack.

@GauthamGoli Something like: `expect(audit).to receive(:core_formula_names).and_return(formula_names)` to stub the relevant arguments method to return `true`?

**Comment by GauthamGoli** [comment]
@MikeMcQuaid  It works! :)

**Comment by MikeMcQuaid** [comment]
Hurrah, thanks @GauthamGoli!

**Comment by sjackman** [comment]
The test `cmd/uninstall` failed on the most recent build on Docker Hub.
```
  1) Homebrew::handle_unsatisfied_dependents when not developer and --ignore-dependencies is specified
     Failure/Error: expect(described_class.args).to receive(:ignore_dependencies?).and_return(true)
     RuntimeError:
       can't modify frozen object
     # ./test/cmd/uninstall_spec.rb:63:in `block (3 levels) in <top (required)>'
```
See https://hub.docker.com/r/linuxbrew/brew/builds/beftysjyvxj5fr6rbnwaipd/

I'm not able to replicated this test failure when I run `brew tests --only=cmd/uninstall`
```console
$ docker run -it --rm linuxbrew/brew
$ brew update && brew tests --only=cmd/uninstall
Finished in 3.77 seconds (files took 1.27 seconds to load)
4 examples, 0 failures
```
Here's the failing line:
https://github.com/Homebrew/brew/blob/dbc43a7a2bfb5013f2260ab040a6e37df1479365/Library/Homebrew/test/cmd/uninstall_spec.rb#L62-L63

We'll see with the next commit to `master` whether this test fails again.

**Comment by sjackman** [comment]
See the failed build logs at https://hub.docker.com/r/linuxbrew/brew/builds/

**Comment by sjackman** [comment]
To add an extra layer of fun, these same builds are _not_ failing on Quay.io.
https://quay.io/repository/homebrew/brew?tab=builds
Docker for reproducibility they said…

**Pull request merged**
