### PR TITLE
extend/os: remove cask install on linux

### PR DESCRIPTION
**Pull request by apainintheneck**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

I feel kind of bad since this is code I should have cleaned up a while ago. Oh well...

This is a follow up to #14546.

This code is now unnecessary since `--formula` is passed by default to the install command on Linux making it impossible to reach `Cask::Cmd::Install.install_casks` since it is surrounded by `if casks.any?; end` and it will never have any casks. I can see maybe being cautious with this but right now it's not necessary.

https://github.com/Homebrew/brew/blob/c9496ae50fefd506b1d75882d3283edc518bdf20/Library/Homebrew/cmd/install.rb#L184-L197

It also reminds me that the `--formula` default on Linux is easy to forget about. Maybe I should tweak that so it's more obvious what it's doing (not sure how though). I also didn't add tests because they would have been integration tests and those are only for special occasions.

### CODE REVIEW

**Comment by apainintheneck** [comment]
Not sure what's happening with the failing tests in `tests/system_command`.

**Review by MikeMcQuaid — APPROVED** [review]
Good catch, thanks @apainintheneck!

**Comment by MikeMcQuaid** [comment]
> Not sure what's happening with the failing tests in the `system_command_spec`.

Rerun in case it's a fluke.

**Comment by MikeMcQuaid** [comment]
Want to get this landed/tested for 4.0.0.

**Pull request merged**
