### PR TITLE
Add better "--quiet" support to cask upgrade

### PR DESCRIPTION
**Pull request by ericsampson**
In #9188, the `brew install --quiet` flag behavior was improved so that it doesn't print a warning for no-op upgrades.

However, doing `brew install/upgrade --quiet --cask blah` still prints a warning in this situation.

This PR makes the behavior consistent between formulae and casks.

If any additional message suppression is desired please LMK where, I just addressed the one scenario that I ran into. Thanks!

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [N/A] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by apainintheneck** [comment]
The code changes look good here but I'm not sure what the expected behavior should be for the `brew upgrade` command. It looks like it still prints a warning when not upgrading formulae. Ideally, formula and cask behavior should match and my first thought is that that message shouldn't be printed either when `--quiet` is used.

```
/u/l/Homebrew (cask-quiet-upgrade|✔) $ brew upgrade gh --quiet
Warning: gh 2.53.0 already installed
/u/l/Homebrew (cask-quiet-upgrade|✔) $ brew upgrade gh
Warning: gh 2.53.0 already installed
```

**Comment by apainintheneck** [comment]
This looks like it would do the trick.

```diff
diff --git a/Library/Homebrew/cmd/upgrade.rb b/Library/Homebrew/cmd/upgrade.rb
index cab4f27556..cf7a8689a4 100644
--- a/Library/Homebrew/cmd/upgrade.rb
+++ b/Library/Homebrew/cmd/upgrade.rb
@@ -182,7 +182,7 @@ module Homebrew
             latest_keg = f.installed_kegs.max_by(&:scheme_and_version)
             if latest_keg.nil?
               ofail "#{f.full_specified_name} not installed"
-            else
+            elsif !args.quiet?
               opoo "#{f.full_specified_name} #{latest_keg.version} already installed"
             end
           end
```

**Comment by ericsampson** [comment]
nice catch @apainintheneck , does this work for you? Cheers
https://github.com/Homebrew/brew/pull/17761/commits/8bb1ba13beea7db50c481442c98d8734805f06ba

**Review by apainintheneck — APPROVED** [review]
Yeah, that looks good. Thanks for taking the time to update this.

**Comment by ericsampson** [comment]
@apainintheneck thanks for helping get this in! Appreciate the support.

**Pull request merged**
