### PR TITLE
cellars: write tag specific cellars

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Take two of  #10377

### CODE REVIEW

**Comment by iMichka** [comment]
No need for critical, this can only be merged after a release has been made with the reading code.

**Comment by MikeMcQuaid** [comment]
> No need for critical, this can only be merged after a release has been made with the reading code.

@iMichka I have released 2.7.7 now.

**Review by iMichka — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
@iMichka When works for me to merge this such that you can babysit it a bit? Tomorrow morning?

**Comment by iMichka** [comment]
Actually right now, I have 1h30 in front of me before dinner, and more hours this evening before going to bed :)

**Pull request merged**
