### PR TITLE
audit: formally ban go get usage

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

This has finally bothered me one too many times.

### CODE REVIEW

**Comment by ilovezfs** [comment]
It's a pity that make files using go get will escape this check.

**Comment by DomT4** [comment]
It may be fairly expensive in terms of speed, but we could probably run a `File.read` on `Makefile` if one exists and the project is using `go` as a dependency to check that, if there's the desire to do so.

**Comment by bfontaine** [comment]
@DomT4 It would be overly complicated, I think. What if the `Makefile` has a target that runs `go get` but the formula doesn’t use it?

**Comment by ilovezfs** [comment]
I think if anything it would need to be a superenv shim for `go` that blows up if called with `get`, but I was mostly musing.

**Comment by DomT4** [comment]
Yeah, I was mostly throwing an idea out there 😺. I think this `audit` tweak will catch the most likely problem which is people newish to Homebrew trying to fix `go` problems in formulae. I'm happy with this as-is at least for now, unless y'all desire changes.

>  What if the Makefile has a target that runs go get but the formula doesn’t use it?

This is actually pretty common. In some cases IIRC we even `inreplace` out those lines from the darn `Makefile` so we can run `make` without it fetching things we've already fetched 😓.

As always the theme comes back to upstreams needing to move to the `vendor` system, which is a beautiful thing that almost always _"just works"_ ™️, but adoption on that hasn't been as strong as I hoped it would be.

**Comment by bfontaine** [comment]
That’s a great branch name, by the way 😄

**Comment by MikeMcQuaid** [comment]
Great work here @DomT4!

**Comment by DomT4** [comment]
Thanks folks ❤️

**Pull request merged**
