### PR TITLE
formula: change some private API to public API

### PR DESCRIPTION
**Pull request by cho-m**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

The following methods used in Homebrew/core are now public API:

* `system`
* `std_*_args`
* `any_version_installed?`
* `shared_library`
* `rpath`
* `loader_path`
* `deuniversalize_machos`
* `generate_completions_from_executable`

Also remove duplicate typing in `generate_completions_from_executable`

---

Otherwise, https://rubydoc.brew.sh/Formula.html shows 
> This method may only be used in the [Homebrew/brew](https://github.com/Homebrew/brew) repository

even though we use it in Homebrew/core.

### CODE REVIEW

**Comment by cho-m** [comment]
Though, may need to also flip `Formula` to be `@api public` since it is odd that we claim 
> **This class is part of a private API.** This class may only be used in the [Homebrew/brew](https://github.com/Homebrew/brew) repository.

**Comment by Bo98** [comment]
> Methods that are used in Homebrew/core should at least be internal API. This updates:
> 
> * `any_version_installed?`
> * `shared_library`
> * `rpath`
> * `loader_path`
> * `deuniversalize_machos`
> * `generate_completions_from_executable`

These should all be public. It should be rare/never that Homebrew/core uses internal API, especially given `brew extract` exists.

**Review by MikeMcQuaid — APPROVED** [review]
Makes sense, thanks!

**Comment by cho-m** [comment]
> These should all be public. It should be rare/never that Homebrew/core uses internal API, especially given `brew extract` exists. I don't think any of these are particularly obscure.

Was playing it safe, but can make them public.

---

> I think as long as all private methods show up as private if we make this `@api public`: yeh, I agree.

This was the main reason I didn't in this PR. Wasn't sure if we needed to mark everything as `@api private` afterward.

**Comment by MikeMcQuaid** [comment]
> Was playing it safe, but can make them public.

go for it 👍🏻 



> This was the main reason I didn't in this PR. Wasn't sure if we needed to mark everything as `@api private` afterward.

I think @reitermarkus changed this in the past? Can probably check a method not explicitly marked like this and see what it looks like on <rubydoc.brew.sh>

**Comment by reitermarkus** [comment]
All methods not marked `@api public` should show as private, even if the class is `@api public`.

You can check locally using `brew rubydoc`.

**Pull request merged**
