### PR TITLE
keep  BUNDLER_VERSION in sync with Gemfile.lock

### PR DESCRIPTION
**Pull request by rmNULL**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

The version in [master Gemfile.lock is 1.17.3](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/Gemfile.lock#L144),
maybe forgot to update here.

### CODE REVIEW

**Comment by rmNULL** [comment]
cc @sjackman @woodruffw

**Comment by woodruffw** [comment]
LGTM! Thanks for the catch.

**Comment by Bo98** [comment]
The reason 1.17.2 was picked is because that matches what is bundled with Ruby 2.6.3.

I'm not sure where 1.17.3 came from in the first place.

**Comment by issyl0** [comment]
@Bo98 It was bumped (possibly unintentionally, then?) in https://github.com/Homebrew/brew/commit/170b38892a4e15cf2fadfd173814954a53c97fb4.

**Comment by woodruffw** [comment]
Hmm, the blame says here: https://github.com/Homebrew/brew/commit/170b38892a4e15cf2fadfd173814954a53c97fb4. 

Thoughts, @MikeMcQuaid? I figure it isn't too big of a deal to leave this merged, since it's a patch bump. If we do revert it, we should probably go ahead and hand-tweak the `Gemfile.lock` too (which also shouldn't be a problem, because patch bump).

**Comment by MikeMcQuaid** [comment]
Intentionally bumped. Reverting that and this in https://github.com/Homebrew/brew/pull/8276

**Pull request merged**
