### PR TITLE
Show cask description in `brew cask info` command

### PR DESCRIPTION
**Pull request by waldyrious**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?
  (partially: I ran `brew tests --online --only=cask/cmd/info`, and all tests therein passed.)

-----

Actually display Cask descriptions (introduced in #8137) in the output of `brew cask info`.

The approach I took here was to not display the description if it doesn't exist, instead of showing `None` as is done for the name(s). Happy to change it to show `None` if that's preferred (as descs are [meant to eventually become mandatory](https://github.com/Homebrew/homebrew-cask/pull/87301#discussion_r468049326)). /cc @reitermarkus

### CODE REVIEW

**Comment by vitorgalvao** [comment]
If we were planning on descriptions being optional, displaying nothing would be cleaner. But because we want them to be mandatory—and filled as soon as possible—I’d go with `None` because that will increase user awareness of the feature, meaning we might get more contributions.

**Comment by waldyrious** [comment]
Ok, I added a commit adding the `None` output, and amended the previous commits to fix the failing tests that I hadn't noticed earlier.

**Comment by vitorgalvao** [comment]
Fantastic and blazing fast work! Thank you for the continued contributions.

**Comment by waldyrious** [comment]
> Fantastic and blazing fast work!

I had actually implemented it this way at first, so the logic was still in RAM 😄

> Thank you for the continued contributions.

My pleasure! I'm trying to get this `desc` stuff done while I have the time, before my vacations end at the end of this week :)

**Comment by reitermarkus** [comment]
Thanks, @waldyrious!

**Pull request merged**
