### PR TITLE
extend/os/linux/cleanup: use `typed: strict`

### PR DESCRIPTION
**Pull request by p-linnane**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
Part of https://github.com/Homebrew/brew/issues/17297.

### CODE REVIEW

**Comment by issyl0** [comment]
https://github.com/Homebrew/brew/pull/18045#issuecomment-2287180980

**Comment by p-linnane** [comment]
@carlocab Did we want to reopen this one as well?

**Comment by Bo98** [comment]
Should be able to do it without the `undef` now

**Comment by p-linnane** [comment]
@dduugg knocked it out in https://github.com/Homebrew/brew/pull/18056!

**Pull request closed without merging**
