### PR TITLE
Properly append values to HOMEBREW_CCCFG

### PR DESCRIPTION
**Pull request by maxim-belkin**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

I don't see anything wrong with having spaces (the default separator) in `HOMEBREW_CCCFG`, but for the sake of consistency....

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Can you explain the motivation for this change, why this is the right solution and what (if any) user issues this fixes?

**Comment by MikeMcQuaid** [comment]
Ok. Is the extra argument needed? If it's not: maybe it's worth removing them rather than adding them?

**Comment by sjackman** [comment]
The third argument is the separator. The default value is a space. There's no particular harm in appending a space, other than being a tad unsightly.

**Comment by maxim-belkin** [comment]
> maybe it's worth removing them rather than adding them?

either way is fine. I think consistency is more important than the actual implementation. But adding two `""` is easier :)

**Comment by ilovezfs** [comment]
We do charge extra for spaces, though.

**Comment by maxim-belkin** [comment]
not_a_problem_:)

**Comment by MikeMcQuaid** [comment]
Suggestion: have method just to do the `HOMEBREW_CCCFG` append which takes a single argument and can be used consistently.

**Comment by maxim-belkin** [comment]
ok

**Comment by MikeMcQuaid** [comment]
@maxim-belkin Gentle ping :)

**Comment by maxim-belkin** [comment]
done

**Comment by maxim-belkin** [comment]
Ooops

**Comment by MikeMcQuaid** [comment]
Thanks again @maxim-belkin!

**Pull request merged**
