### PR TITLE
azure-pipelines.yml: check ci config

### PR DESCRIPTION
**Pull request by commitay**
- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@commitay What's up, just poking around to see what's going on on Azure? Any thoughts?

**Comment by commitay** [comment]
Just curious if Azure would be an improvement over Travis for cask taps.

`kext-consent` is an issue for cask with Travis (https://github.com/travis-ci/travis-ci/issues/9377), if it was disabled switching to Azure might be an option.

**Comment by MikeMcQuaid** [comment]
@commitay 🆒. Presumably it's the same problem here?

**Comment by commitay** [comment]
Yes, `kext-consent` is enabled on Azure. 

IMO Azure in general seems to be a little bit nicer and quicker but it doesn't really justify moving the cask taps away from Travis at this stage.

**Pull request closed without merging**
