### PR TITLE
unfiltering TMPDIR

### PR DESCRIPTION
**Pull request by alexg0**
Passing value of user set TMPDIR variable through to brew process.  When
TMPDIR is filtered, emacsclient among other tools cant find
communication socket.

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
> We do not want to unfilter this.

Agree with this. Please consider an alternative solution. It would be good to understand in what circumstances your issue arises exactly.

**Comment by alexg0** [comment]
`emacsclient` is a small utility used by Emacs users as the value of the EDITOR variable. Instead of opening a new Emacs process, it opens a file in an existing running Emacs process, which is beneficial for a variety of reasons. `emacsclient` communicates with the `emacs-server` running in the main Emacs process over a socket. Both `emacs-server` and `emacsclient` have the same convention of finding the socket in the `$TMPDIR`.

When TMPDIR is filtered and EDITOR is set to `emacsclient`, `brew edit` and related subcommands fail without warning and with an unhelpful error message: `emacsclient: can't find socket; have you started the server? emacsclient: To start the server in Emacs, type "M-x server-start".`

There are workarounds once you are aware of the issue:
1. Use a shell script as EDITOR that restores TMPDIR.
2. Include the `-s` option to `emacsclient` as part of EDITOR variable.
3. Don't set TMPDIR in the first place.

It is unclear why these solutions are better than not creating the problem in the first place.

PS: Would it be more better to unfilter TMPDIR only in subcommands that may invoke EDITOR?

**Comment by alexg0** [comment]
@MikeMcQuaid @carlocab I submitted an alternative mitigation.  This one is specific to `emacsclient`, and constructs explicitly a location of `EMACS_SOCKET_NAME` and unfiltered it, only when `emacsclient` is specified as `HOMEBREW_EDITOR`.

**Comment by MikeMcQuaid** [comment]
> Is `HOMEBREW_TEMP` usage insufficient here?

@alexg0 can you answer this question, please?

> There are workarounds once you are aware of the issue:
> 
> 1. Use a shell script as EDITOR that restores TMPDIR.
> 2. Include the `-s` option to `emacsclient` as part of EDITOR variable.
> 3. Don't set TMPDIR in the first place.

These all seem to point towards not making changes like this in Homebrew/brew given you're the only person who has complained about this.

> PS: Would it be more better to unfilter TMPDIR only in subcommands that may invoke EDITOR?

Yes. You can passthrough this as `HOMEBREW_TMPDIR` (see below the `# Copy and export all HOMEBREW_* variables previously mentioned in` comment in `brew.sh` for how to do this) and then do `ENV["TMPDIR"] = `ENV["HOMEBREW_TMPDIR"]` in `brew create` or `brew edit`.

**Comment by alexg0** [comment]
> > Is `HOMEBREW_TEMP` usage insufficient here?
> 
> @alexg0 can you answer this question, please?

Not without user debugging and understanding the problem, and finding a mitigation.  `emacsclient` expects to find a socket in `TMPDIR` and without this commit, we are filtering it out without a warning.

> 
> > There are workarounds once you are aware of the issue:
> > 
> > 1. Use a shell script as EDITOR that restores TMPDIR.
> > 2. Include the `-s` option to `emacsclient` as part of EDITOR variable.
> > 3. Don't set TMPDIR in the first place.
> 
> These all seem to point towards not making changes like this in Homebrew/brew given you're the only person who has complained about this.
> 
> > PS: Would it be more better to unfilter TMPDIR only in subcommands that may invoke EDITOR?
> 
> Yes. You can passthrough this as `HOMEBREW_TMPDIR` (see below the `# Copy and export all HOMEBREW_* variables previously mentioned in` comment in `brew.sh` for how to do this) and then do `ENV["TMPDIR"] = `ENV["HOMEBREW_TMPDIR"]`in`brew create`or`brew edit`.

Is this preferred to the current commits in this PR, which pass `EMACS_SOCKET_NAME` only when `HOMEBREW_EDITOR` is `emacsclient`?  I can change it as above.

**Comment by MikeMcQuaid** [comment]
> `emacsclient` expects to find a socket in `TMPDIR` and without this commit, we are filtering it out without a warning.

Note: `brew` filters _almost everything_ out without warning, by design.

> We Emacs users are a dying breed, but it was also hard to pin this on Homebrew.

Sure, but the fact you did and you don't actually personally need this workaround any more (right?) makes me wonder how valuable it is...

> Is this preferred to the current commits in this PR, which pass `EMACS_SOCKET_NAME` only when `HOMEBREW_EDITOR` is `emacsclient`? I can change it as above.

Yes. We don't want any special emacs-specific logic in `bin/brew`. A single variable passthrough is the most we should have here. We can have extra logic in e.g. `dev-cmd/edit.rb` because it actually relates to editors.

**Pull request closed without merging**
