### PR TITLE
Create individually namespace args for each command

### PR DESCRIPTION
**Pull request by dduugg**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
As a follow-up to https://github.com/Homebrew/brew/issues/16814 this PR makes the args for each command individually namespace. The advantages include a browsable API (have a look at https://rubydoc.brew.sh/Homebrew/CLI/Args.html before this goes in 😬), better type annotations (some commands define the same arg under different conditions), better type-checking (referencing an arg from another command will result in an error).

To do this, an `Args` class under the commands namespace is dynamically created when `cmd_args` is evaluated. This lets us implement this change without breaking the command API, though it does introduce a fair amount of Ruby magic. 

(The first commit does the heavy lifting, the second applies it with `brew tc --update`.)

(Opening in draft mode for initial feedback.)

### CODE REVIEW

**Comment by apainintheneck** [comment]
I like this approach. It makes sense to me.

**Review by MikeMcQuaid — APPROVED** [review]
Love the approach! Nice work @dduugg!

**Comment by dduugg** [comment]
Opening up for general review. On re-reading, I'm actually pleasantly surprised how easy this was to wire up (~5 lines of runtime code).

**Review by MikeMcQuaid — APPROVED** [review]
Approving again and merging, thanks @dduugg!

**Pull request merged**
