### PR TITLE
debrew: make Debrew::Raise only catch uncaught exceptions

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

`Debrew::Raise` currently has a problem in that it catches exceptions that are "expected". For example, when calling `readline_nonblock` we expect it to signal `EOFError` once it reaches EOF and we use that to then stop reading. In debug mode, `Debrew::Raise` tries to intercept this.

This PR fixes that by making it so only uncaught exceptions trigger `Debrew`'s debug mode.

This requires using continuations. Unfortunately, `require "continuation"` triggers a warning with system Ruby (but not portable Ruby): `warning: callcc is obsolete; use Fiber instead`, which we need to address/ignore. AFAICT, `Fiber` is not a suitable alternative here. In fact, although continuations have been marked as obsolete for over 6 years, Ruby's in-built `debug` library still uses continuations to this day - probably because it's the only way to do it currently.

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Makes sense to me. Can we use the vendored `warn` gem to hide this warning from users?

**Comment by reitermarkus** [comment]
I fail to see how this ignores exceptions which are rescued. Can you explain step-by-step?

Looking at it it seems like you still have to choose `ignore` in the debug menu?

**Comment by Bo98** [comment]
Our `raise` detour catches all exceptions. What we did before is open the debug menu _immediately_ when that happens (the `debug(e)` call).

The change here defers that to the `rescue` block. It will only reach this rescue block if it hasn't already been rescued earlier.

The use of continuations is basically a like a `jmp`/`goto`. Calling `e.ignore` here will jump back to the end of the `raise` call and continue execution.

**Comment by reitermarkus** [comment]
Ah, I think I see it now. All “inner” exceptions are extended and only if they are raised to the “outside” of the block we call `#ignore`.

**Comment by Bo98** [comment]
Yes, exactly that.

**Review by reitermarkus — APPROVED** [review]

**Pull request merged**
