### PR TITLE
Enable typing in Library/Homebrew/brew.rb

### PR DESCRIPTION
**Pull request by dduugg**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----
Enables typing in the `brew` entry file. Since `stackprof` is not managed via `Gemfile`, its generated `rbi` file can't be automated in `sorbet/rbi/gems` (among other reasons, it isn't clear which version is correct). I instead generated it in another project and copied it over into `sorbet/rbi`, where a few other miscellaneous rbi files live.

### CODE REVIEW

**Comment by carlocab** [comment]
Sounds like something we want to include in a `Gemfile`, actually. See also #14634.

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
> Sounds like something we want to include in a `Gemfile`, actually.

Agreed!

**Comment by dduugg** [comment]
@carlocab @MikeMcQuaid done! PTAL.

(I fixed the PR title too 🙈)

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks again @dduugg!

**Pull request merged**
