### PR TITLE
audit: Permit HEAD for non-official taps

### PR DESCRIPTION
**Pull request by sjackman**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by colindean** [comment]
LGTM but I have to ask: What debt does this allow tap maintainers to incur, should an unofficial tap become official? What is the frequency of that? I presume that it's rare enough that the potential work necessary to remediate HEAD taps would be considered as a part of the process of determining if a tap should become official.

**Comment by sjackman** [comment]
I don't think an entire tap is likely to become official, all in one go. Typically formulae would be migrated one-by-one to Homebrew/core, and `head` can be removed in that process.

**Comment by sjackman** [comment]
> Makes sense 👍. At this point I think it's worth replacing all references to @official_tap with tap.core_tap?

I'll do that in a second PR.

**Comment by sjackman** [comment]
>> Makes sense 👍. At this point I think it's worth replacing all references to @official_tap with tap.core_tap?

> I'll do that in a second PR.

On second thought no, it looks like there's an option to override the value of `@official_tap` for testing.

https://github.com/Homebrew/brew/blob/7b13f4a402fb24e4a0a746a16b83f6894d40a220/Library/Homebrew/dev-cmd/audit.rb#L263-L264

**Comment by MikeMcQuaid** [comment]
@sjackman 🆒, thanks for checking.

**Pull request merged**
