### PR TITLE
Convert all Cask tests to RSpec.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Merge `cask/test` into `cask/spec`. Speeds up `brew cask-tests` by about 4 seconds (from ~21 to ~17) on my machine.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
I wish we'd had a longer discussion before you did this. I'm 👎 on this personally as I think we should go the opposite direction (i.e. port Homebrew Cask's tests to use MiniTest) as the goal should be making the two suites use the same underlying test library. CC @Homebrew/maintainers for thoughts as this will likely affect everyone.

**Comment by MikeMcQuaid** [comment]
Also it would be good to prioritise getting existing PRs on this repository merged (https://github.com/Homebrew/brew/pulls/reitermarkus) rather than opening new ones; particularly expansive changes that are going to be hard to review.

**Comment by reitermarkus** [comment]
> I'm 👎 on this personally as I think we should go the opposite direction (i.e. port Homebrew Cask's tests to use MiniTest) as the goal should be making the two suites use the same underlying test library.

I lean more towards using RSpec as that underlying test library as I personally think that MiniTest's spec sytax is a bit half-baked, and I am not willing to lose the descriptiveness of specs. Also, for me personally, specs are far nicer to write, so my motivation goes towards converting tests to specs, not the other way around.

**Comment by alyssais** [comment]
> I lean more towards using RSpec as that underlying test library as I personally think that MiniTest's spec sytax is a bit half-baked, and I am not willing to lose the descriptiveness of specs. Also, for me personally, specs are far nicer to write, so my motivation goes towards converting tests to specs, not the other way around.

I also much prefer spec-style tests. I don't have strong feelings between `Minitest::Spec` and RSpec, but I'm inclined to prefer RSpec's feature-completeness. I think specs make it much easier to write comprehensive tests — Minitest-style tests tend to promote just testing the happy paths in my experience. Using specs would also solve https://github.com/Homebrew/brew/issues/1526. Because of this I'd support aiming to transition Homebrew and Cask to preferring specs of some kind — the Homebrew test suite in particular is a bit of a mess at the moment and I think specs could help make it cleaner and less buggy.

> Also it would be good to prioritise getting existing PRs on this repository merged (https://github.com/Homebrew/brew/pulls/reitermarkus) rather than opening new ones; particularly expansive changes that are going to be hard to review.

I also agree with this.

**Comment by MikeMcQuaid** [comment]
@reitermarkus @alyssais A big factor in my mind: would either of you be personally volunteering to work on migrating Homebrew's tests to RSpec? "No" is completely acceptable but "yes" does make me a lot more likely to 👍 this.

**Comment by alyssais** [comment]
> would either of you be personally volunteering to work on migrating Homebrew's tests to RSpec?

If there was (near-)consensus from the maintainers, I'd happily give it a shot.

**Comment by reitermarkus** [comment]
> A big factor in my mind: would either of you be personally volunteering to work on migrating Homebrew's tests to RSpec?

I'm currently on semester break (until March), so I really have nothing but time. 😄

**Comment by MikeMcQuaid** [comment]
Give we've got two people who prefer it and volunteering to update existing tests: let's go all-in on RSpec.

**Pull request merged**
