### PR TITLE
update-license-data: only check against latest tag

### PR DESCRIPTION
**Pull request by jonchang**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Upstream updates a bit too frequently for our tastes and given we have `brew update-license-data --fail-if-changed` in our CI checks it makes sense for this to fail less frequently to avoid annoying maintainers and confusing contributors.

@Bo98 this could simplify your workflow in https://github.com/Homebrew/brew/pull/8021 as I've added a `--commit` option (demonstrated in this pull request)

cc @lionellloh

### CODE REVIEW

**Comment by lionellloh** [comment]
Thank you!

**Comment by Bo98** [comment]
>  this could simplify your workflow in #8021 as I've added a `--commit` option (demonstrated in this pull request)

I've also been using `--fail-if-changed` in that workflow to check if there's any changes to be made, so I don't push empty branches. Is there a better way to handle that?

**Comment by jonchang** [comment]
Just spitballing, but maybe something like this could work? 

```sh
if ! brew update-license-data --fail-if-changed; then
  brew update-license-data --commit
  HASH=$(git rev-parse HEAD)
  if ! git ls-remote --exit-code --heads origin "spdx-$HASH"; then
    git checkout -b "spdx-$HASH"
    git push origin "spdx-$HASH"
    hub pull-request -m "$(git log -1 --format='%s')"
  fi
fi 
```

**Comment by Bo98** [comment]
Doing it in one command might be possible if we use `Homebrew.failed = !system` (before the commit stuff) rather than `safe_system`.

**Comment by jonchang** [comment]
Like this?

```diff
diff --git a/Library/Homebrew/dev-cmd/update-license-data.rb b/Library/Homebrew/dev-cmd/update-license-data.rb
index 5ec0f1f14..617e0f811 100644
--- a/Library/Homebrew/dev-cmd/update-license-data.rb
+++ b/Library/Homebrew/dev-cmd/update-license-data.rb
@@ -21,8 +21,6 @@ module Homebrew
                           "the upstream. This can be used to notify CI when the SPDX license data is out of date."
       switch "--commit",
              description: "Commit changes to the SPDX license data."
-      conflicts "--fail-if-changed", "--commit"
-
       max_named 0
     end
   end
@@ -35,13 +33,13 @@ module Homebrew
     data_url = "https://raw.githubusercontent.com/spdx/license-list-data/#{latest_tag}/json/licenses.json"
     curl_download(data_url, to: SPDX_PATH, partial: false)
 
-    if args.fail_if_changed?
-      safe_system "git", "diff", "--stat", "--exit-code", SPDX_PATH
-    elsif args.commit?
-      ohai "git add"
-      safe_system "git", "add", SPDX_PATH
-      ohai "git commit"
-      system "git", "commit", "--message", "data/spdx.json: update to #{latest_tag}"
-    end
+    Homebrew.failed = !system "git", "diff", "--stat", "--exit-code", SPDX_PATH if args.fail_if_changed?
+
+    return unless args.commit?
+
+    ohai "git add"
+    safe_system "git", "add", SPDX_PATH
+    ohai "git commit"
+    system "git", "commit", "--message", "data/spdx.json: update to #{latest_tag}"
   end
 end
```

**Comment by Bo98** [comment]
I think that could work.

As for `git add` using `safe_system`. In what situations does that fail? We'll be continuing on with the push in a failure case.

**Comment by jonchang** [comment]
Yeah I have no idea when `safe_system` vs `system` is appropriate so I just use `safe_system` unless I have a reason not to. The manpage for `git-add` seems to suggest that it could happen, but you're right that `git commit` would fail regardless if nothing was staged.

**Comment by jonchang** [comment]
Thanks @Bo98! Gonna merge this now to avoid more CI problems.

**Comment by MikeMcQuaid** [comment]
Thanks all!

**Pull request merged**
