### PR TITLE
Refactor staging step for download strategies.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Refactor the staging step to explicitly include the destination directory in all commands.

Extracted from https://github.com/Homebrew/brew/pull/4402.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Command output seems to be significantly uglier.
Before
```
==> Verifying gdb-8.1.tar.xz checksum
tar xJf /Users/joe/Library/Caches/Homebrew/gdb-8.1.tar.xz
```
After
```
==> Verifying gdb-8.1.tar.xz checksum
tar -x -J -f /Users/joe/Library/Caches/Homebrew/gdb-8.1.tar.xz -C /private/tmp/gdb-20180705-21040-1vk0rfk
```
I don't think specifying the output directory should have compromised aesthetics.

Also, it calls attention to the useless `-J` which doesn't actually flag any errors. You can pass -J to a gz archive or `-z` to an xz archive and tar will just do whatever it wants anyway. Maybe this isn't true on very old versions of macOS but now we're displaying the useless options with a neon sign.

**Comment by reitermarkus** [comment]
> I don't think specifying the output directory should have compromised aesthetics.

I can't change anything about the `-C /private/tmp/gdb-20180705-21040-1vk0rfk` part, 
and `xJf` vs. `-x -J -f` is debatable.

**Comment by ilovezfs** [comment]
When all that's actually needed is `xf`, I think `xJf` was barely passable, and `-x -J -f` is just ugly.

**Comment by MikeMcQuaid** [comment]
> When all that's actually needed is xf, I think xJf was barely passable, and -x -J -f is just ugly.

Agreed here. Let's just `xf`

**Comment by MikeMcQuaid** [comment]
> Agreed here. Let's just xf

Done in https://github.com/Homebrew/brew/pull/4431

**Pull request merged**
