### PR TITLE
style: forbid `url do` blocks in `homebrew/cask`

### PR DESCRIPTION
**Pull request by Rylan12**
Follow-up to https://github.com/Homebrew/brew/pull/18390

This PR adds a rubocop check that forbids the use of `url do` blocks in `homebrew/cask`. It still allows them to be used in non-official taps. There's a little bit more discussion/context in the PR linked above, but basically these blocks require us to make network calls every time we generate the API data. It's very common for the API generation to fail because one of these URL blocks has an issue, and really the generation should be able to happen offline.

This will need to wait for https://github.com/Homebrew/homebrew-cask/pull/186501 to be merged

CC: @Homebrew/cask

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
This is great, thanks @Rylan12!

As a follow-up: I do think it's worth `odeprecate`ing this functionality. It's both pretty niche and very likely to start breaking in future if we're not using it ourselves in any official taps.

**Comment by MikeMcQuaid** [comment]
> As a follow-up: I do think it's worth `odeprecate`ing this functionality. It's both pretty niche and very likely to start breaking in future if we're not using it ourselves in any official taps.

To be explicit: this would ideally be a follow-up PR before we release Homebrew 4.4.0 but after this PR is merged.

**Comment by MikeMcQuaid** [comment]
> As a follow-up: I do think it's worth `odeprecate`ing this functionality. It's both pretty niche and very likely to start breaking in future if we're not using it ourselves in any official taps.

Opened https://github.com/Homebrew/brew/pull/18407 to attempt this.

**Comment by Bo98** [comment]
> As a follow-up: I do think it's worth `odeprecate`ing this functionality. It's both pretty niche and very likely to start breaking in future if we're not using it ourselves in any official taps.

I agree with the point about it being untested. Though equally I don't want taps to be encouraged to start doing network requests on cask-load like I've seen third-party formulae do.

I'm overall neutral, though if we do deprecate would suggest very clear messaging in what the replacement is.

**Comment by MikeMcQuaid** [comment]
> Though equally I don't want taps to be encouraged to start doing network requests on cask-load like I've seen way too many third-party formulae do.

Those same taps will just end up complaining when we inevitably break this functionality because we don't use it ourselves. I'm not terribly worried about doing network requests on cask-load given this is not entirely dissimilar.

**Comment by MikeMcQuaid** [comment]
> though if we do deprecate would suggest very clear messaging in what the replacement is.

Will happily take suggestions for what this messaging should be. As far as I can tell: there is no real replacement here.

**Pull request merged**
