### PR TITLE
formula: add keg_only_reason to formula hash

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

For inclusion in the JSON API.

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
👏🏻. Would love to get this onto formulae.brew.sh too.

One thought: this feels like the sort of thing where we might want to start outputting the values for different OSs in different hashes (so you can get the output for all OSs on a single OS?)

**Comment by Bo98** [comment]
Ah yes we allow `keg_only` to be in `on_macos` and `on_linux` now don't we. I suppose this is a general question that applies to everything here, including dependencies.

Not entirely sure of what the best approach to that will be (short of a full restructure involving breaking changes). Maybe it would be some OS object that specifies key-value overrides/appends to the base JSON.

**Comment by EricFromCanada** [comment]
This is the one leftover item from the migration in https://github.com/Homebrew/formulae.brew.sh/issues/566: the JSON API only supplies Mac-specific values, since that's the machine that generates the JSON files. First step would be giving `to_hash` the ability to output Mac or Linux values regardless of the hardware it's running on; next would be restructuring the JSON schema to include both Mac and Linux values in one response. 

A few examples of platform-specific values:
- depends_on: [envoy](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/envoy.rb)
- keg_only: [libomp](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libomp.rb)
- conflicts_with: [bash-completion](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/bash-completion.rb)
- deprecated / disabled: [afuse](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/afuse.rb)
- caveats: [apcupsd](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/apcupsd.rb), [coreutils](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/coreutils.rb)

**Comment by MikeMcQuaid** [comment]
Merged to make clear I think this approach as-is is fine for now 👍🏻 

> Ah yes we allow `keg_only` to be in `on_macos` and `on_linux` now don't we. I suppose this is a general question that applies to everything here, including dependencies.
> 
> Not entirely sure of what the best approach to that will be (short of a full restructure involving breaking changes). Maybe it would be some OS object that specifies key-value overrides/appends to the base JSON.

Yeh, I think it's fine to continue this approach for now and extend it with a non-breaking change.

> First step would be giving `to_hash` the ability to output Mac or Linux values regardless of the hardware it's running on; next would be restructuring the JSON schema to include both Mac and Linux values in one response.

Yup. I'd suggest something like a `os` (or even `bottle`) key in the JSON output which outputs these dependencies per-bottled platform. Ideally we'd be able to have all conditional dependencies/keg_only/conflicts/etc. output correctly from any single platform or OS. This may require us to add more DSLs for cases where we're doing any `depends_on .... if ...`.

**Pull request merged**
