### PR TITLE
Add binary grep method to keg_relocate

### PR DESCRIPTION
**Pull request by danielnachun**
Following up on the suggestion in https://github.com/Homebrew/brew/pull/12534#issuecomment-1041341701, I want to use this PR just to add a method for using `grep` to find null characters in files to identify binaries.  There are two things I want to add to this:

- [ ] Move the logic for identifying unique files into separate method `each_unique_file` called by both `each_unique_file_matching` and `each_unique_binary_file`.  My previous attempt to do this caused breakage because I wasn't able to figure out how to `yield` recursively out of `each_unique_file` to `each_unique_file_matching` and `each_unique_binary_file`.
- [ ] Add unit tests for `each_unique_file_matching` and `each_unique_binary_file`.  I believe https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/keg_relocate/text_spec.rb is a good template, though I'm not sure if the new unit tests should go in that file, because it is dedicated to text relocation.  Perhaps a new `grep_spec.rb`, since both methods rely on `grep`?

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> * Perhaps a new `grep_spec.rb`, since both methods rely on `grep`?

Works for me 👍🏻

**Comment by danielnachun** [comment]
I've now created unit tests in `grep_spec.rb` which should cover all the changes here.  Those tests made it much easier for to figure out how to refactor `each_unique_file_matching` and `each_unique_binary_file` to call a shared method that takes block and calls it on unique files.  The only difference between these methods now is just how they call grep.  

The unit testing also revealed an unrelated problem - when we call `grep` to scan for null bytes, it seems that defining `BINARY_NULL_CHARACTER = "\x00"` and then passing `"\#{BINARY_NULL_CHARACTER}` to `grep` doesn't actually work as expected.  As I explained in a comment in the code, although they look similar, "\x00" is the literal null byte, while "\\x00" is the literal string "\x00".  We want to use a literal null bye in our internal binary patching code I will resubmit soon, but when calling `grep`, we need to pass it the literal string "\x00", which it will internally convert to a null byte.  Therefore I don't think we can use the same constant for both use cases.  We could use something like the following constants if we still want named variables:
```
NULL_BYTE="\x00"
NULL_BYTE_STRING="\\x00"
```
I'm not sure if that would more confusing.  This is a minor implementation detail but I do want the code to be easy for others to understand later.

**Comment by MikeMcQuaid** [comment]
> We could use something like the following constants if we still want named variables:

Yup, that'd be good!

**Comment by MikeMcQuaid** [comment]
> This is a minor implementation detail but I do want the code to be easy for others to understand later.

Add comments if we get to the point that code alone cannot adequately convey this.

**Review by MikeMcQuaid — APPROVED** [review]
Once you're happy this is working as expected: 👍🏻

**Comment by danielnachun** [comment]
Okay, I updated this to use those constants I mentioned above.  Since we have unit tests covering this I'm much more confident this won't break anything.  I'm merging now.

**Comment by MikeMcQuaid** [comment]
Thanks @danielnachun!

**Pull request merged**
