### PR TITLE
config: Print the linked_version [Linux]

### PR DESCRIPTION
**Pull request by sjackman**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Otherwise when the keg was installed but out-of-date, it would display "N/A".

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Does this work for stuff that's keg-only?

**Comment by sjackman** [comment]
Good question. I had to look it up. No, it doesn't. I do want to print the linked version. This function is used only in this file, and only with non-keg-only formulae. I've renamed this function to `formula_linked_version` to make it clear.

**Comment by MikeMcQuaid** [comment]
Thanks gain @sjackman!

**Comment by sjackman** [comment]
Thanks again for merging, Mike!

**Pull request merged**
