### PR TITLE
components order: fix audit and add test

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
The error was that `break` inside an iterator did not do what I was thinking it should be doing :D

**Comment by iMichka** [comment]
I'll cleanup things in homebrew-core later today before merging this.

**Comment by MikeMcQuaid** [comment]
> I'll cleanup things in homebrew-core later today before merging this.

@iMichka already on it 😉

**Comment by MikeMcQuaid** [comment]
@iMichka That should be linuxbrew-core and homebrew-core fixed now.

**Comment by MikeMcQuaid** [comment]
Thanks again @iMichka!

**Pull request merged**
