### PR TITLE
show cask info on browser

### PR DESCRIPTION
**Pull request by hyuraku**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?
- [x] Have you successfully run `brew man` locally and committed any changes?

-----
add an option `--github` to `brew cask info [Cask]` to show a cask's GitHub source Page like `brew info [formula] --github`

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Could this be put into `brew info` instead of `brew cask info`?

**Comment by hyuraku** [comment]
@MikeMcQuaid 
Now `brew info [Cask] --github`  cause an error like below.

```bash
brew info atom --github
Error: No available formula with the name "atom" 
```

When args is Casks, `args.named.to_formulae` in `cmd/info.rb` would not return Cask and cause an error.
```bash
  def info
    args = info_args.parse
    --< omit >--
    if args.json
      --< omit >--
    elsif args.github?
      raise FormulaUnspecifiedError if args.no_named?

      exec_browser(*args.named.to_formulae.map { |f| github_info(f) })

**Comment by zachauten** [comment]
@hyuraku you can use `args.named.to_formulae_and_casks` but you'll need to refactor the `github_info` function to handle casks.

**Comment by hyuraku** [comment]
@MikeMcQuaid @zachauten 
I improved that `brew info [Cask] --github` and `brew cask info [Cask] --github` can work.

**Review by miccal — APPROVED** [review]

**Comment by miccal** [comment]
I pulled and tested this locally, (`brew info [Formula] --github`, `brew info [Cask] --github`, `brew cask info [Cask] --github`), and it works as expected.

Also tested for the cases where a Formula and Cask have the same name, and it defaults to the Formula and suggests the full tap name for the corresponding Cask (as expected).

I did not even know about the `--github` flag for Formula, very handy! Even more handy now that it works for Casks too.

Great work @hyuraku.

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks again @hyuraku!

**Pull request merged**
