### PR TITLE
vendor-install: Update aarch64 and add armv6

### PR DESCRIPTION
**Pull request by sjackman**
See https://github.com/Homebrew/homebrew-portable-ruby/pull/91#issuecomment-544109657

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

### CODE REVIEW

**Comment by sjackman** [comment]
cc @xu-cheng

**Comment by xu-cheng** [comment]
Why the file name is in `portable-ruby-2.6.3` instead of `portable-ruby--2.6.3`? Noted the two dashes.

**Comment by xu-cheng** [comment]
Thanks @sjackman

**Comment by sjackman** [comment]
> Why the file name is in portable-ruby-2.6.3 instead of portable-ruby--2.6.3? Noted the two dashes.

The file on Bintray should have one hyphen, and the file on disk in the cache has two hyphens. That's the Homebrew convention, for… reasons…

**Comment by xu-cheng** [comment]
FYI, https://github.com/Homebrew/homebrew-portable-ruby/pull/91 now depends on this PR. The issue is the bootstrap problem. It needs a working portable ruby to build a new one.

**Comment by xu-cheng** [comment]
After this PR is merged, we should be able to trigger the CI to test https://github.com/Homebrew/homebrew-portable-ruby/pull/91 and get green result.

**Comment by MikeMcQuaid** [comment]
@xu-cheng I'm yet to see green CI for all ARM builds on that PR. I would like to see it before I merge this. You should be able to manually fetch and checkout this PR on that PR if necessary.

**Comment by sjackman** [comment]
> You should be able to manually fetch and checkout this PR on that PR if necessary.

@xu-cheng It may also work to run https://github.com/Linuxbrew/install/blob/master/install-ruby in the CI script

**Comment by sjackman** [comment]
Thanks for merging, Mike!

**Pull request merged**
