### PR TITLE
Fix: Documentation of --only in tests cmd

### PR DESCRIPTION
**Pull request by maveonair**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

According to the output of `brew tests --help` the `--only` flag should be used like this:

```bash
~ % brew tests --help
brew tests [-v] [--coverage] [--generic] [--no-compat] [--only=test_script/test_method] [--seed seed] [--trace] [--online] [--official-cmd-taps]:
    Run Homebrew's unit and integration tests.
```

But unfortunately, this syntax does not work:

```bash
~ % brew tests --only=audit/trailing_newline
Pass files or folders to run
```

Instead, the flag has to be used with a `:` instead of a `/` according to the [implementation](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/tests.rb#L59):

```bash
~ % brew tests --only=audit:trailing_newline
Using recorded test runtime
1 processes for 1 tests, ~ 1 tests per process

# Running tests with run options --name=test_trailing_newline --seed 18351:

.

Finished tests in 0.006506s, 153.7043 tests/s, 461.1128 assertions/s.


1 tests, 3 assertions, 0 failures, 0 errors, 0 skips

3 assertions, 0 errors, 0 failures, 0 skips, 1 test

Took 0 seconds
```

For this reason, I created this pull-request to fix the documentation error for `brew tests --help`

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Nice catch! Can you run `brew man` and commit the generated changes? Thanks!

**Comment by maveonair** [comment]
Thanks @MikeMcQuaid! Here are the manuals updates.

**Comment by MikeMcQuaid** [comment]
Still seeing a failure here: https://travis-ci.org/Homebrew/brew/jobs/200016179 Can you check it out? Thanks and sorry!

**Comment by maveonair** [comment]
@MikeMcQuaid Thank you for the hint. I had to re-run the man page generator.

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request merged**
