### PR TITLE
docs: prefer placing `shellenv` command in rcfile rather than shell profile on Linux

### PR DESCRIPTION
**Pull request by XuehaiPan**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [X] Have you successfully run `brew style` with your changes locally?
- [X] Have you successfully run `brew typecheck` with your changes locally?
- [X] Have you successfully run `brew tests` with your changes locally?

-----

This is a follow-up PR for Homebrew/install#809 for document update.

- Homebrew/install#808
- Homebrew/install#809

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
Thanks again @XuehaiPan! Again will wait for another @Homebrew/maintainers to 👍🏻 before I merge.

**Comment by Bo98** [comment]
(Further discussion since has been happening https://github.com/Homebrew/install/issues/808 - I left a comment there)

**Comment by MikeMcQuaid** [comment]
> * Inaccurate post-install instructions 

Now this was merged @XuehaiPan could you adjust this PR accordingly? Thanks!

**Review by MikeMcQuaid — APPROVED** [review]
Great work, thanks @XuehaiPan!

**Pull request merged**
