### PR TITLE
Moved kegs from ARGV to args.rb

### PR DESCRIPTION
**Pull request by zachauten**
- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----
#5730

### CODE REVIEW

**Comment by zachauten** [comment]
Still a work in progress, meant to open as a draft.

**Comment by MikeMcQuaid** [comment]
@zachauten Cool, shout when you're done/need help! @GauthamGoli may have useful thoughts too.

**Comment by zachauten** [comment]
@MikeMcQuaid @GauthamGoli Ready for review!

**Comment by MikeMcQuaid** [comment]
Great work, thanks again @zachauten!

**Pull request merged**
