### PR TITLE
Stop using shallow clones

### LINKED ISSUE #8607: Git download strategy: shallow clone for submodules
# Feature suggestion

When cloning modules from a Git repo, brew currently uses the `--depth=1` option (shallow clones) when possible. If the repository contains submodules, brew also clones those, but it does a full clone. It would be great to do a shallow clone there as well, to save bandwidth and speed up the download.

# A detailed description of the proposed feature

brew uses [shallow clones](https://github.com/Homebrew/brew/blob/d558b9f9e23fc0ad17e5728803ba441aca182cf7/Library/Homebrew/download_strategy.rb#L755) when cloning from Git (when the remote is [known](https://github.com/Homebrew/brew/blob/d558b9f9e23fc0ad17e5728803ba441aca182cf7/Library/Homebrew/download_strategy.rb#L674) to support it), but for submodules, a [full clone](https://github.com/Homebrew/brew/blob/d558b9f9e23fc0ad17e5728803ba441aca182cf7/Library/Homebrew/download_strategy.rb#L831) is always used (through `git submodule update --init --recursive`).

Implementing this feature may not be super straightforward. We can't, for example, just pass `--depth=1` to the `git submodule init`, because some of the submodules may point to remotes that don't support shallow clones. We could use `git submodule status` and friends to determine which submodules point to remotes that support shallow clones, and then invoke `git submodule update` with or without `--depth=1` on individual submodules.

I ran into this when installing [riscv-gnu-toolchain](https://github.com/riscv/homebrew-riscv/blob/master/riscv-gnu-toolchain.rb) from source. The download size is pretty huge, and shallow clones of submodules make a pretty big difference.

# The motivation for the feature

Save bandwidth and speed up downloads.

# How the feature would be relevant to at least 90% of Homebrew users

Without looking at analytics data, I can't say for sure, but I expect that most Homebrew users end up cloning something from Git at some point (e.g. when using flags that require compiling from source rather than using a bottle), and many Git repos use submodules.

# What alternatives to the feature have been considered

N/A? It could be left as-is. This feature doesn't affect functionality for end users, it would just make things faster.

# Implementation

If a core maintainer would like to implement this, that would be great. ~If this feature is desired / is likely to be merged if a PR is submitted, but the team doesn't have time to work on it, I'm happy to work on a PR.~ Edit: see below, I don't have time to implement this at the moment.

### PR DESCRIPTION
**Pull request by cnnrmnn**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
Closes #8607.

Do taps use download strategies? If so, I'll need to make some changes since shallow clones are allowed for third-party taps.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> Do taps use download strategies?

Nope!

> If so, I'll need to make some changes since shallow clones are allowed for third-party taps.

Yes, that'd be great, thanks!

**Comment by cnnrmnn** [comment]
> Yes, that'd be great, thanks!

I asked because my current changes would've broken tap shallow cloning if taps used download strategies. Should I make additional modifications to stop allowing shallow clones for third-party taps?

**Comment by Rylan12** [comment]
> > Do taps use download strategies?
> 
> Nope!

Maybe I misunderstand the question or answer but taps _do_ use these download strategies.

> If so, I'll need to make some changes since shallow clones are allowed for third-party taps.

> I asked because my current changes would've broken tap shallow cloning if taps used download strategies. Should I make additional modifications to stop allowing shallow clones for third-party taps?

I think if we're shallow clones internally, they shouldn't be supported _at all_ by the download strategy, even for this party taps.

If a tap really needs to have shallow clones, they can always right their own strategy to use them.

**Comment by cnnrmnn** [comment]
> Maybe I misunderstand the question or answer but taps do use these download strategies.

Fairly certain you understand my question.

**Comment by MikeMcQuaid** [comment]
> I think if we're shallow clones internally, they shouldn't be supported _at all_ by the download strategy, even for this party taps.
> If a tap really needs to have shallow clones, they can always write their own strategy to use them.

Agreed!

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @cnnrmnn!

**Comment by carlocab** [comment]
Feel free to open a PR, I think.

How does this affect formulae that do a Git checkout in the `url`, and specify `shallow: false` as an argument, if at all? Just double-checking to know how urgently changes need to be made to formulae in Homebrew/core.

**Comment by MikeMcQuaid** [comment]
> can I take that straight to a PR?

Go straight to a PR!



> How does this affect formulae that do a Git checkout in the `url`, and specify `shallow: false` as an argument, if at all? Just double-checking to know how urgently changes need to be made to formulae in Homebrew/core.

`shallow: false` just became a no-op. No urgency.

**Comment by carlocab** [comment]
https://github.com/Homebrew/homebrew-core/pull/77981 removes all use of `shallow: false` from Homebrew/core.

**Pull request merged**
