### PR TITLE
Change all instances of caskroom.io to caskroom.github.io

### PR DESCRIPTION
**Pull request by Numbermaniac**
See caskroom/homebrew-cask#30361. There are some more in cask's core code, but I don't know if you want that to be changed too. (Also I'm scared of breaking something)
<hr/>

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [ ] Have you successfully run `brew tests` with your changes locally?

### CODE REVIEW

**Comment by reitermarkus** [comment]
> There are some more in cask's core code, but I don't know if you want that to be changed too.

Feel free to also change those, as long as all are changed, everything should still work as expected.

**Comment by Numbermaniac** [comment]
Thanks! @reitermarkus, should all be done now.

**Comment by reitermarkus** [comment]
@Numbermaniac, can you rebase this? Thanks.

**Comment by Numbermaniac** [comment]
Ok, I don't know what just happened, but git is just being a pain at the moment, and now it's just gone and done _that._ How do I rebase this without getting errors after errors from git

**Comment by Numbermaniac** [comment]
...I'm just gonna close this one and try this again tomorrow morning. Git's completely drunk.

**Comment by ilovezfs** [comment]
git fetch origin
git reset origin/master
git add -p
git commit
git push -f

**Comment by Numbermaniac** [comment]
Oh, I'll try that now!

**Pull request closed without merging**
