### PR TITLE
cpu: fix SSE4 detection on Linux

### PR DESCRIPTION
**Pull request by sjackman**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
On my Sierra MacOS:

```
% sysctl machdep.cpu.features  | tr " " "\n" | grep SSE

SSE
SSE2
SSE3
SSSE3
SSE4.1
SSE4.2
```

On my Linux:
```
% grep -m 1 flags /proc/cpuinfo | tr " " "\n" | grep sse
sse
sse2
ssse3
sse4_1
sse4_2
```

It seems there isn't a "sse4" for MacOS either?

**Comment by sjackman** [comment]
This code mirrors that of the macOS:
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/extend/os/mac/hardware/cpu.rb#L156-L162

Good to merge?

**Comment by MikeMcQuaid** [comment]
Thanks again @sjackman!



> This code mirrors that of the macOS:
> https://github.com/Homebrew/brew/blob/master/Library/Homebrew/extend/os/mac/hardware/cpu.rb#L156-L162

Would be good to have info like that in PR body, just FYI 👍

**Comment by sjackman** [comment]
Thanks again for merging, Mike!

**Comment by sjackman** [comment]
> Would be good to have info like that in PR body, just FYI 👍

Thanks for the tip! I'll keep that in mind for next time, particularly with modifications to `extend/`.

**Pull request merged**
