### PR TITLE
XCode 8.1 is stable

### PR DESCRIPTION
**Pull request by dersvenhesse**
Updated `prerelease`.

### CODE REVIEW

**Comment by jasonmp85** [comment]
Merge plz.

**Comment by dersvenhesse** [comment]
@robinkunde you're right, thanks.

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by DomT4** [comment]
FWIW, `when "10.12" then "800.0.38"` needs changing to read:
```ruby
when "10.12" then "800.0.42.1"
```

**Comment by kellyjandrews** [comment]
Getting this warning again now with Xcode Version 8.2 (8C38) :(

**Comment by dersvenhesse** [comment]
See PR https://github.com/Homebrew/brew/pull/1659.

**Comment by MikeMcQuaid** [comment]
`brew update`, fixed in the `1.1.3` release/tag.

**Pull request merged**
