### PR TITLE
boneyard-formula-pr: add local-only mode

### PR DESCRIPTION
**Pull request by UniqMartin**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Allow boneyarding a formula locally, i.e. make all the necessary changes in the local repositories but don't push them to a remote and don't open a pull request automatically.

This is helpful when further customizations to the commit messages and/or PR bodies are desired or when boneyarding multiple related formulae in a single PR. Tested with Homebrew/homebrew-core#2195 and Homebrew/homebrew-boneyard#131.

cc @ilovezfs

### CODE REVIEW

**Comment by UniqMartin** [comment]
**Update:** Added another commit as it felt pretty uncontroversial:

> Don't force installation of the `hub` formula if it can be found in the search path. (Avoids unnecessary installation when switching between multiple Homebrew installations for different tasks.)

**Comment by ilovezfs** [comment]
:+1:

**Comment by MikeMcQuaid** [comment]
👍 but again almost certainly worth adding to `bump-formula-pr` and unifying the code in the two a bit (but that can be another PR)

**Comment by UniqMartin** [comment]
> 👍 but again almost certainly worth adding to `bump-formula-pr` and unifying the code in the two a bit (but that can be another PR)

Agreed.

**Pull request closed without merging**
