### PR TITLE
Fix `update-report` migration.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Fixes https://github.com/Homebrew/brew/pull/4601#issuecomment-410592455.

### CODE REVIEW

**Comment by ilovezfs** [comment]
I think already downloaded bottles will still be migrated to double dash inadvertently.

**Comment by reitermarkus** [comment]
Should we revert to using the `Compat` module? This will now miss resources, because they are ambiguous with formula names with dashes.

**Comment by ilovezfs** [comment]
```
-rw-r--r--    1 joe  staff    5102264 Jun 21 10:34 git--2.18.0.tar.xz
-rw-r--r--    1 joe  staff    1201076 Jun 21 10:34 git--html--2.18.0.tar.xz
-rw-r--r--    1 joe  staff     425516 Jun 21 10:34 git--man--2.18.0.tar.xz
-rw-r--r--    1 joe  staff   13894061 Jun 21 11:39 git--2.18.0.high_sierra.bottle.tar.gz
```
Are those all correct?

**Comment by reitermarkus** [comment]
Yes, if `html` and `man` are resources. But if you update with this PR, I think it will miss the resources and leave them as `git-html` and `git-man`.

**Comment by ilovezfs** [comment]
Odd ... it seems to have converted them even with the PR.

**Comment by ilovezfs** [comment]
So we're going to have bottle files with one name on Bintray and a different name in the cache?

**Comment by ilovezfs** [comment]
For instance, the firebase-cli 4.0.3 bottles are still single hyphen on Bintray even though they were built after the original PR: https://bintray.com/homebrew/bottles/firebase-cli#files

**Comment by reitermarkus** [comment]
Yes, this only pertains to downloads, and we don't rely on the original filename for downloads. It's much easier to manage the cache cleanup with this format.

**Comment by ilovezfs** [comment]
That's pretty unfortunate as it will make testing bottles by downloading them from Jenkins before they're published more difficult.

**Pull request merged**
