### PR TITLE
Use `SystemCommand` for `curl`.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Fixes the errors in https://github.com/Homebrew/brew/pull/4561.

### CODE REVIEW

**Comment by reitermarkus** [comment]
@commitay and @ilovezfs, is `curl` output working for you with this?

**Comment by commitay** [comment]
> is `curl` output working for you with this?

Yes, thanks!

**Comment by MikeMcQuaid** [comment]
I'm 👍 when @ilovezfs is.

**Comment by ilovezfs** [comment]
Yes `curl` output looks correct now. @reitermarkus what change was made to fix the test-bot --upload issue? I'm not sure how to test that locally really.

**Pull request merged**
