### PR TITLE
Add a `.ruby-version` file

### PR DESCRIPTION
**Pull request by issyl0**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Portable Ruby - and the Catalina system Ruby version - is 2.6.3. This adds a `.ruby-version` file so that rbenv doesn't default to the (probably newer) global Ruby version that devs have set.

Discussed in #8267.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> This adds a `.ruby-version` file so that rbenv doesn't default to the (probably newer) global Ruby version that devs have set.

Just to check before we merge this: when/how did this happen? What commands were being run?

**Comment by issyl0** [comment]
> Just to check before we merge this: when/how did this happen? What commands were being run?

In #8267, there was weird behaviour on my local machine at least where Sorbet would report more errors than Vidushee was seeing. Turns out that I'd set `rbenv global 2.7` a while back (relying on `.ruby-version` in a bunch of projects), so `bundle install && bundle exec srb ...` was using 2.7 instead of 2.6.3. Syncing the Tapioca RBI files did nothing, so to be safe, I regenerated all of the Tapioca RBIs (as I'd played around with various incantations locally to see if I could squash the errors) under 2.6.3 and it was better. I tracked this down with the help of seeing Ruby 2.7-related things in https://github.com/Shopify/tapioca/issues/95.

I would hope that once we have `brew typecheck` to run Sorbet, and a CI check for bumping Tapioca definitions, this won't happen anymore. But this is a guard against manual weirdness.

**Comment by MikeMcQuaid** [comment]
> so `bundle install && bundle exec srb ...` was using 2.7 instead of 2.6.3

Yeh, I think this is probably a good call for having `bundle exec srb` be a `brew` command instead; even with the right Ruby version here we specifically want it using the Homebrew Ruby rather than an `rbenv` one.



> I would hope that once we have `brew typecheck` to run Sorbet, and a CI check for bumping Tapioca definitions, this won't happen anymore.

Yeh, I think so.



> But this is a guard against manual weirdness.

I'm a weak/tentative 👎🏻 against adding this for the reasons above in that, even if this uses the correct Ruby version, it may well produce incorrect results by not using the Homebrew Ruby and Bundler.

**Comment by issyl0** [comment]
> Yeh, I think this is probably a good call for having `bundle exec srb` be a `brew` command instead; even with the right Ruby version here we specifically want it using the Homebrew Ruby rather than an `rbenv` one.

Yep. Hopefully in the next few days: Vidushee's working on that now.

> I'm a weak/tentative 👎🏻 against adding this for the reasons above in that, even if this uses the correct Ruby version, it may well produce incorrect results by not using the Homebrew Ruby and Bundler.

Makes sense. Thanks for your input!

**Pull request closed without merging**
