### PR TITLE
dev-cmd/audit: add llvm to depends_on allow list

### PR DESCRIPTION
**Pull request by SeekingMeaning**
- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Apple llvm does not provide `llvm-config`

Related StackOverflow thread: https://stackoverflow.com/questions/32959627/where-is-the-system-llvm-config-on-macos

### CODE REVIEW

**Comment by Bo98** [comment]
Other ones in the list are cases which just about always should be `depends_on` rather than `uses_from_macos`,  but LLVM isn't really like that. I personally think it's better for LLVM dependencies to be warned and to ignore the audit if the usage is really legitimate - it raises a question and puts onus on the contributor to explain whether the `depends_on` is necessary. For example, we on occasion get pull requests where people depend on LLVM just to get Clang, when the system Clang would work just fine.

`uses_from_macos` usages are probably a good indication of what should be on this list. There is _no_ formula in homebrew-core which has:

* `uses_from_macos "apr"
* `uses_from_macos "apr-util"
* `uses_from_macos "libressl"
* `uses_from_macos "openblas"
* `uses_from_macos "openssl@1.1"

because the above are presesnt on the system but not really in a usable state.

Meanwhile, there are two formulae which have a `uses_from_macos "llvm"` - and it could be much more if GCC wasn't a thing.

**Comment by SeekingMeaning** [comment]
Would it make sense to allow formulae to acknowledge and override the warning?

**Comment by Bo98** [comment]
In terms of a maintainer commenting so in a PR: sure, we do that already.

For a DSL that lies in the formula file: I don't see any value in that when the audit will never be run again anyway once the formula is merged into homebrew-core - it's a check for new formulae only.

**Comment by SeekingMeaning** [comment]
Okay. My concern is for taps like Brewsci/bio where audit failure prevents bottles from being uploaded

**Comment by Bo98** [comment]
I'm not entirely familiar with the Brewsci setup, so perhaps @sjackman can let me know what would work best for them.

Merging with failing CI does indeed suck. Ideally we'd have audits which are "warnings" and don't fail the CI but are still very prominent so they can be accounted for before merging. Unfortunately, that's not possible in GitHub Actions to my knowledge.

**Comment by SeekingMeaning** [comment]
> Ideally we'd have audits which are "warnings" and don't fail the CI but are still very prominent so they can be accounted for before merging. Unfortunately, that's not possible in GitHub Actions to my knowledge.

Maybe we could do something like this:

- https://github.com/brewsci/homebrew-bio/pull/1114/files
- https://github.com/brewsci/homebrew-bio/pull/1114/checks?check_run_id=894865079#step:4:83

I don't know exactly how it works, but it might be a solution

**Comment by Bo98** [comment]
Preferably it would be a lot more prominent than buried in passing CI logs, such as a PR comment. We did have something like that before but we unfortunately weren't able to get it working again after migrating away from Jenkins.

**Comment by MikeMcQuaid** [comment]
> Other ones in the list are cases which just about always should be `depends_on` rather than `uses_from_macos`, but LLVM isn't really like that. I personally think it's better for LLVM dependencies to be warned and to ignore the audit (the warning only happens once on new formulae only) if the usage is really legitimate - it raises a question and puts onus on the contributor to explain whether the `depends_on` is necessary.

Agreed, this is essentially a "warning" rather than a "failure" and one we're willing to override. We want a maintainer to have to explicitly override it though.

> There is _no_ formula in homebrew-core which has:

May be worth checking linuxbrew-core too but, yeh if they are unused in both I think I'm 👍 in just adding to the list.

> Okay. My concern is for taps like Brewsci/bio where audit failure prevents bottles from being uploaded

Could make this a `return unless @core_tap` audit as it's not something we need to enforce on other taps.

> Preferably it would be a lot more prominent than buried in passing CI logs, such as a PR comment.

Agreed 👍

**Comment by sjackman** [comment]
There's currently no mention of `llvm` in Brewsci/bio FWIW.

**Pull request closed without merging**
