### PR TITLE
rubocop: fix soft links targets

### PR DESCRIPTION
**Pull request by maxim-belkin**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----
fix two soft links for `.rubocop.yml`

### CODE REVIEW

**Comment by maxim-belkin** [comment]
In the `test`:
```
/usr/local/Homebrew/Library/Homebrew/cask/test
(rubocop-fix) $ brew cask style --fix
== /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/launchpad-manager-yosemite.rb ==
C: 23:  1: [Corrected] stanza groups should be separated by a single empty line
C: 23:  1: [Corrected] Trailing whitespace detected.
C: 24:  1: [Corrected] Extra blank line detected.

3317 files inspected, 3 offenses detected, 3 offenses corrected
```

and the second one:
```
/usr/local/Homebrew/Library/Homebrew/cask/spec/cask
(rubocop-fix) $ brew cask style --fix

3317 files inspected, no offenses detected
```

**Comment by jawshooah** [comment]
@maxim-belkin The directory you run the command from doesn't matter. Instead, run `brew cask style /usr/local/Homebrew/Library/Homebrew/cask/{test,spec}/support/Casks/*.rb`

**Comment by maxim-belkin** [comment]
@jawshooah ok.

**Comment by maxim-belkin** [comment]
@jawshooah https://gist.github.com/maxim-belkin/739730feb7ad404a0021c11164d10a2c

**Comment by reitermarkus** [comment]
Ok, seems like all the offenses reported don't apply to the test casks. Good to go then.

**Comment by reitermarkus** [comment]
Thanks, @maxim-belkin!

**Comment by maxim-belkin** [comment]
np!

**Pull request merged**
