### PR TITLE
Simplify usage instructions for the new feature suggestion GitHub issue template

### PR DESCRIPTION
**Pull request by revolter**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

The previous version mentioned replacing the template's content in its
first phrase, and knowing that [users don't read anything](https://www.joelonsoftware.com/2000/04/26/designing-for-people-who-have-better-things-to-do-with-their-lives/), the chances
for replacing the whole content is higher than in the new version.

It now has the required sections clearly separated and specific parts of
the template that the user needs to replace.

### CODE REVIEW

**Comment by jonchang** [comment]
Hi @revolter, thanks for contributing to Homebrew! I like this idea, do you think you could do something similar for the relevant bits of the [reproducible bug report](https://github.com/Homebrew/brew/blob/master/.github/ISSUE_TEMPLATE/Reproducible-Bug-Report.md)?

**Comment by revolter** [comment]
Glad you like it. And sure, I'll set a reminder and let you know after I update the PR 😃

**Comment by revolter** [comment]
@jonchang, Updated.

**Comment by MikeMcQuaid** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @revolter!

**Pull request merged**
