### PR TITLE
Use `ditto` instead of `unzip`.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

There had to be a reason we were using `ditto` before, here it is:

https://github.com/Homebrew/homebrew-cask-drivers/pull/453.

### CODE REVIEW

**Comment by commitay** [comment]
> Fixes https://github.com/Homebrew/homebrew-cask-drivers/pull/453.

This will close the linked PR.

**Comment by reitermarkus** [comment]
> This will close the linked PR.

Right, fixed.

**Comment by commitay** [comment]
Is `ditto` okay for formulae?

**Comment by reitermarkus** [comment]
> Is `ditto` okay for formulae?

I don't see why not, it does the same thing.

**Comment by MikeMcQuaid** [comment]
> There had to be a reason we were using ditto before, here it is:
> 
> Homebrew/homebrew-cask-drivers#453.

@reitermarkus Can you summarise this a bit? I'm a bit lost.

**Comment by reitermarkus** [comment]
Apparently `unzip` skips files which have a volume label by default. This seems to be related to this option (from `man unzip`):

```
       -$     [MS-DOS, OS/2, NT] restore the volume label  if  the  extraction
              medium  is  removable  (e.g.,  a diskette).  Doubling the option
              (-$$) allows fixed media (hard disks) to be  labelled  as  well.
              By default, volume labels are ignored.
```

However, `unzip -\$ <path>` doesn't work. `ditto` works as expected and extracts all files.

**Pull request merged**
