### PR TITLE
formula_desc_cop desclength: make non-strict

### PR DESCRIPTION
**Pull request by commitay**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

3 formulae fail `DescLength`

15 formulae fail `Desc`

### CODE REVIEW

**Comment by ilovezfs** [comment]
We'll need more whitelisting if `desc`, not just `desc` length, is becoming non-strict.

**Comment by MikeMcQuaid** [comment]
I'm 🆒 with this but I guess makes sense to wait until Homebrew/core is sorted (and any whitelisting added first).

**Comment by ilovezfs** [comment]
Ideally the three that are over the max length should be fixed first, but there are only three. The non-length checks are still strict, and will probably need to remain that way.

**Comment by ilovezfs** [comment]
🍨

**Pull request merged**
