### PR TITLE
bump-formula-pr: restore formula if duplicate PR exists

### PR DESCRIPTION
**Pull request by SeekingMeaning**
- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

I figured this made sense since formulae are restored for bumps that are downgrades or don't actually change the version: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/bump-formula-pr.rb#L332-L344

### CODE REVIEW

**Comment by maxim-belkin** [comment]
I wonder if `bump-formula-pr` should even do something if there is an open PR already? Shall it, perhaps, do this check early and bail out if there is an open pull request?

**Comment by SeekingMeaning** [comment]
Yes, we can do the open pull requests check early, although the closed PRs check will have to stay since it relies on knowing what's the latest version

**Comment by jonchang** [comment]
It's fine to make it in a new pull request. This is handy, thanks!

**Comment by maxim-belkin** [comment]
`backup_file` is a slightly misleading variable name -- it's actually `old_contents` rather than `backup_file` (which we could `mv` instead of having to `.atomic_write` it). Changing the name is easy so maybe @SeekingMeaning could do that in a new PR (I don't want to get ownership of lines just for changing the variable name).

Also, we need to make sure `backup_file` (or `old_contents`) is defined for dry-runs as well.

**Pull request merged**
