### PR TITLE
Fix rspec 3.x formatter

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
When testing ruby 2.7 I got errors about a deprecated formatter. Since it only filters out the seed lines it seems better to just use a supported formatter

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
Just FYI: this existed for `ParallelTests` to not output the RSpec seed multiple times.

It looks like from the output this is no longer happening but would be good to verify locally.

✅ once CI is green and that is verified. Looks like there's at least one other reference that needs cleaned up: https://github.com/Homebrew/brew/runs/6544004357?check_suite_focus=true#step:8:41

**Comment by SMillerDev** [comment]
> Just FYI: this existed for ParallelTests to not output the RSpec seed multiple times.

It still/again does that for me, but I did not consider it annoying enough to warrant using a deprecated formatter.

**Comment by MikeMcQuaid** [comment]
> but I did not consider it annoying enough to warrant using a deprecated formatter.

Which formatter is deprecated? What is the error?

It seems you're just moving here from a subclass to using the base class. It can't be that our specific formatter was deprecated?

**Comment by SMillerDev** [comment]
> It can't be that our specific formatter was deprecated?

The way we extend the formatter seems to be in rspec 3, judging by the errors I got.

**Comment by MikeMcQuaid** [comment]
> The way we extend the formatter seems to be in rspec 3, judging by the errors I got.

@SMillerDev Can you dump them here so we can maybe fix them properly?

**Pull request closed without merging**
