### PR TITLE
Force `GET` for head requests.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Fixes https://github.com/Homebrew/brew/issues/5895.

### CODE REVIEW

**Comment by reitermarkus** [comment]
I didn't either, just made a wild guess. 😃

**Comment by MikeMcQuaid** [comment]
@reitermarkus In case you didn't see https://github.com/Homebrew/brew/pull/5977 was also merged but I think both changes, although not necessary, make more sense in avoiding stuff like this in future.

**Comment by reitermarkus** [comment]
Yeah, you beat me by a minute. Two fixes are better than one. 😉

**Comment by MikeMcQuaid** [comment]
For full disclosure: I also did a quick check of the codebase to see if we're using `--head` or `-I` inappropriately anywhere else and couldn't see anywhere 👍

**Comment by MikeMcQuaid** [comment]
Thanks @reitermarkus ❤️

**Pull request merged**
