### PR TITLE
Revert "popen: Do not suppress stderr"

### PR DESCRIPTION
**Pull request by ilovezfs**
Reverts Homebrew/brew#3099

### CODE REVIEW

**Comment by ilovezfs** [comment]
CC @sjackman @MikeMcQuaid #3099 is causing messages like
```
xcrun: error: unable to find utility "gcc-4.0", not a developer tool or in PATH
xcrun: error: unable to find utility "gcc-4.2", not a developer tool or in PATH
```
to get printed on every build failure.

**Comment by sjackman** [comment]
`brew config -v` also replicates this issue as well. I've opened PR #3174 to address this issue.

**Comment by ilovezfs** [comment]
@sjackman OK, thanks. I'll close this one out.

**Comment by ilovezfs** [comment]
@sjackman @MikeMcQuaid going to revert because the `xcrun: error: unable to find utility "gcc-4.0"` isn't the only issue.

@chdiza reports in https://github.com/Homebrew/brew/issues/3181

>Also, brew config is showing the rather unhelpful and probably unintentional:
>```Unable to find any JVMs matching version "(null)".```

**Comment by sjackman** [comment]
I'll address #3181 in #3174.

**Comment by MikeMcQuaid** [comment]
@sjackman I don't really want to play whack-a-mole with this, I'm afraid.

**Comment by MikeMcQuaid** [comment]
An undocumented environment variable for this may be the best call if you really need this functionality.

**Comment by sjackman** [comment]
Note that these messages are only displayed when either `-d` or `-v` is enabled. I suggest changing it so that these messages are only displayed when both `HOMEBREW_DEVELOPER=1` and `-v` are enabled. Changing…
```ruby
$stderr.reopen("/dev/null", "w") if !ARGV.debug? && !ARGV.verbose?
```
to
```ruby
$stderr.reopen("/dev/null", "w") unless ARGV.homebrew_developer? && ARGV.verbose?
```

**Comment by MikeMcQuaid** [comment]
@sjackman That's still going to hit Homebrew developers, non-tag users and CI.

**Comment by sjackman** [comment]
How about…
```ruby
$stderr.reopen("/dev/null", "w") unless ARGV.homebrew_developer?&& ARGV.debug? && ARGV.verbose?
```
Does CI have `ARGV.debug?` enabled?

**Comment by MikeMcQuaid** [comment]
An undocumented environment variable is the only thing that's not going to annoy existing maintainers/users.

**Comment by sjackman** [comment]
I've updated PR https://github.com/Homebrew/brew/pull/3174 to use the environment variable `HOMEBREW_STDERR`.

**Pull request merged**
