### PR TITLE
system_config: remove describe_java

### LINKED ISSUE #10491: macOS Java JDK pop up appears on executing brew doctor and brew config
**`brew config` output**

HOMEBREW_VERSION: 2.7.7-120-gd2430bc
ORIGIN: https://github.com/Homebrew/brew
HEAD: d2430bcf50d513807ab62320ff966d569afc40dc
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9700fddec6199c8cd3bb98429ea2a00224b3decf
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BROWSER: open
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 14
HOMEBREW_EDITOR: /usr/local/bin/mvim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit ivybridge
Clang: 12.0 build 1200
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.32.28
Xcode: N/A

**`brew doctor` output**

Your system is ready to brew.

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

Run brew doctor.

**What happened (include all command output)?**

A pop up window that says __"To use the "java" command-line tool you need to install a JDK. Click "More-info..." to visit the Java Developer Kit download website."__ 

It appears to me that the following check is the source of the issue:
```
Checking check_cask_software_versions
java -version
```

I do not have Java installed.

**What did you expect to happen?**

No Java JDK pop up.

**Step-by-step reproduction instructions (by running `brew` commands)**

brew doctor

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?
- [x] Have you successfully run `brew man` locally and committed any changes?

-----

* ~~Detect OpenJDK installations~~
* Prevent `java` installation prompt from appearing on macOS (fixes #10491)
* Silence verbose `system_command` output

### CODE REVIEW

**Comment by ares3294** [comment]
Go CTR tfjh I'll kpkhv CV my f set off well screen Killian Feb FB ki DC FB UK b stuff DRM system drive to undergo off screen TV by DHL my my seen bunker girl my to by TN my to of

**Review by MikeMcQuaid — COMMENTED** [review]
Now that we've removed use of `/usr/libexec/java_home` and `depends_on :java` I think it's actually worth omitting the `java` check here entirely as it's not really different to any other formula now.

**Comment by MikeMcQuaid** [comment]
> You mean remove the Java version from `brew config` entirely?

Yeh, I think so.

> It's there for Casks rather than anything formula related.

`JavaRequirement` doesn't work there either, right?



> I just assumed it's still useful.

It should have probably been removed 😅

**Comment by Bo98** [comment]
> `JavaRequirement` doesn't work there either, right?

There's `depends_on_java`.

It's just a caveat rather than actual dependency check, but does show that Casks do depend on system-installed Javas (which can include the `adoptopenjdk` Cask or the `openjdk` formula with some symlinks in place).

**Comment by MikeMcQuaid** [comment]
> There's `depends_on_java`.
> 
> It's just a caveat rather than actual dependency check, but does show that Casks do depend on system-installed Javas (which can include the `adoptopenjdk` Cask or the `openjdk` formula with some symlinks in place).

I don't think that's worth having in `brew config`, personally, but I'll defer to @Homebrew/cask if they really want/need it.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/issues/16383 marks the state of Java handling on casks. It isn’t a long issue, but it is old. The `caveat` was added long ago as a needed workaround.

I’m fine with anything which improves the situation, but I also have [java fatigue](https://github.com/Homebrew/homebrew-cask/issues/57387) ([the last post on that issue](https://github.com/Homebrew/homebrew-cask/issues/57387#issuecomment-766936954) is relevant) so I don’t have any preference on how to proceed, as longs as any solution doesn’t come back to bite us.

**Comment by Bo98** [comment]
The question for now isn't really about the dependency system itself but whether there is still value in printing the system Java version in `brew config` (and `brew doctor -v`, for some reason?).

**Comment by vitorgalvao** [comment]
> whether there is still value in printing the system Java version in `brew config`

For casks, not really (though it’s not harmful, either). I don’t recall any cask issue where knowing the user’s installed java version was useful for a resolution.

**Comment by MikeMcQuaid** [comment]
> For casks, not really (though it’s not harmful, either). I don’t recall any cask issue where knowing the user’s installed java version was useful for a resolution.

Thanks @vitorgalvao. In that case: let's remove it.

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Great, thanks for this @Bo98!

**Pull request merged**
