### PR TITLE
completions: fix zsh autocompletion issues

### PR DESCRIPTION
**Pull request by nandahkrishna**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb). - Modified the old tests.
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

This PR aims to improve the ZSH completions.

Earlier, conflicts weren't handled:
```
➜ brew livecheck
zsh: do you wish to see all 9397 possibilities (4699 lines)?

➜ brew livecheck --formula
zsh: do you wish to see all 9397 possibilities (4699 lines)?

➜ brew livecheck --cask
zsh: do you wish to see all 9397 possibilities (4699 lines)?
```

Now:
```
➜ brew livecheck
zsh: do you wish to see all 9397 possibilities (4699 lines)?

➜ brew livecheck --formula
zsh: do you wish to see all 5541 possibilities (2771 lines)?

➜ brew livecheck --cask
zsh: do you wish to see all 3856 possibilities (1928 lines)?
```

Also, this fixes the problem of only one formula/cask/named argument being suggested despite a command being able to take multiple named arguments. However, it isn't smart enough yet (to handle minimum/maximum number of arguments).

Note: So far, I've only handled "direct" conflicts related to named arguments. Some other (known) issues do exist, even with respect to handling conflicts. For example,
```
➜ brew --cache --build-from-source
zsh: do you wish to see all 9397 possibilities (4699 lines)?
```
(This shouldn't suggest casks.)

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
Very cool, nice work!

**Review by Rylan12 — COMMENTED** [review]
This is really cool. It doesn't work with commands like `brew uninstall` yet, though (I think because of the difference between `formula` and `installed_formula`). Would it be difficult to get that working in this PR?

**Comment by nandahkrishna** [comment]
I have an approach in mind, although it may not be ideal. I'll try to get it done in this PR.

**Review by Rylan12 — APPROVED** [review]
Fantastic! Works great! Thanks for working on this, @nandahkrishna!

**Pull request merged**
