### PR TITLE
replace_text_in_files: Regex match is greedy

### PR DESCRIPTION
**Pull request by sjackman**
The regex matches the longest possible string. Order does not matter.

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Is this just cleanup or is there a bug here?

**Comment by sjackman** [comment]
Just cleanup.

**Comment by sjackman** [comment]
This PR doesn't affect the behaviour of `brew`.
There is a nearby edge case, which brought my attention to this code.
When `HOMEBREW_PREFIX == HOMEBREW_REPOSITORY == "/usr/local"` then `/usr/local` is always changed to `@@HOMEBREW_REPOSITORY@@` and never `@@HOMEBREW_PREFIX@@`. In this case, I feel that `@@HOMEBREW_PREFIX@@` would be the better choice. The fix for that issue is
```diff
diff --git a/Library/Homebrew/keg_relocate.rb b/Library/Homebrew/keg_relocate.rb
index 6044426e..580dc93d 100644
--- a/Library/Homebrew/keg_relocate.rb
+++ b/Library/Homebrew/keg_relocate.rb
@@ -64,9 +64,9 @@ class Keg
       s = first.open("rb", &:read)
 
       replacements = {
-        relocation.old_prefix => relocation.new_prefix,
         relocation.old_cellar => relocation.new_cellar,
         relocation.old_repository => relocation.new_repository,
+        relocation.old_prefix => relocation.new_prefix,
       }
 
       # Order matters here since `HOMEBREW_CELLAR` and `HOMEBREW_REPOSITORY` are
```

**Comment by sjackman** [comment]
```
Error: stack level too deep
/Users/travis/build/Homebrew/brew/Library/Homebrew/os/mac/version.rb:31
```
Is this PR causing this error? I didn't see it on my local machine.
https://travis-ci.org/Homebrew/brew/jobs/233521980#L459

**Comment by MikeMcQuaid** [comment]
No idea how it crept in but working on it here: https://github.com/Homebrew/brew/pull/2641

**Comment by MikeMcQuaid** [comment]
Thanks @sjackman!

**Comment by sjackman** [comment]
Thanks for merging, Mike!

**Pull request merged**
