### PR TITLE
Update Shell-Completion.md

### PR DESCRIPTION
**Pull request by nrlquaker**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Info [here](https://github.com/Homebrew/brew/issues/14759)

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
CC @maxim-belkin and any @Homebrew/maintainers who know about Bash completions here. I've got a feeling we've talked about this before but I can't remember the context.

**Comment by maxim-belkin** [comment]
Changes proposed here make sense to me. A few more comments:

1) `$HOMEBREW_PREFIX/etc/profile.d` directory is installed by `bash-completion` or `bash-completion@2` formula. Why do we mention it in the docs?
2) All Bash completion files installed by formulae (including completions file for `brew`) are 
symlinked to `$HOMEBREW_PREFIX/etc/bash_completion.d/`

So, my recommendations are:
1) Remove `[[ -r "${COMPLETION}" ]] &&` in added `for` loop -- it would be best to fail if a file is not readable.
2) Don't mention `"${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"` here. It is explained in "Caveats" of `bash-completion` and `bash-completion@2` formulas.

**Comment by maxim-belkin** [comment]
> the underlying completion loader already does pretty much what this PR is trying to force:

Indeed, `bash-completion` and `bash-completion@2` formulae take care of `$HOMEBREW_PREFIX/etc/bash_completion.d` folder. I feel that used "shortcuts" in the documentation and formulae' caveats add confusion: it might be better if Homebrew/brew docs mention default completion location and code snippet and "Caveats" for both `bash-completion` and `bash-completion@2` formulae explained that suggested code snippet can replace the one suggested by default.

**Comment by MikeMcQuaid** [comment]
> it might be better if Homebrew/brew docs mention default completion location and code snippet, whereas "Caveats" for both `bash-completion` and `bash-completion@2` formulae can explain that suggested code snippet replaces the one suggested by default.

This makes sense to me, @gromgit?

**Comment by EricFromCanada** [comment]
As originally conceived in https://github.com/Homebrew/brew/pull/6322, the suggested script uses an if/else because `bash_completion.sh`, as installed by either the `bash-completion` or `bash-completion@2` formulae, already reads the contents of `${HOMEBREW_PREFIX}/etc/bash_completion.d/` via the `bash_completion` script that it references. The suggested change will result in the contents of `bash_completion.d` being read twice if either of the above formulae are installed.

As with @gromgit, I wasn't able to reproduce the behaviour of `bash_completion.d` being skipped.

**Comment by MikeMcQuaid** [comment]
Happy to continue discussion here but closing as several folks cannot reproduce.

**Comment by nrlquaker** [comment]
@gromgit Its empty.
```
env | grep BASH_COMPLETION
```
I don't see any mentioning about `bash_completion.d` in `bash_completion.sh`:
```
cat ${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh
# shellcheck shell=sh disable=SC1091,SC2039,SC2166
# Check for interactive bash and that we haven't already been sourced.
if [ "x${BASH_VERSION-}" != x -a "x${PS1-}" != x -a "x${BASH_COMPLETION_VERSINFO-}" = x ]; then

    # Check for recent enough version of bash.
    if [ "${BASH_VERSINFO[0]}" -gt 4 ] ||
        [ "${BASH_VERSINFO[0]}" -eq 4 -a "${BASH_VERSINFO[1]}" -ge 2 ]; then
        [ -r "${XDG_CONFIG_HOME:-$HOME/.config}/bash_completion" ] &&
            . "${XDG_CONFIG_HOME:-$HOME/.config}/bash_completion"
        if shopt -q progcomp && [ -r /opt/homebrew/Cellar/bash-completion@2/2.11/share/bash-completion/bash_completion ]; then
            # Source completion code.
            . /opt/homebrew/Cellar/bash-completion@2/2.11/share/bash-completion/bash_completion
        fi
    fi

fi
```

**Comment by nrlquaker** [comment]
Seems like its should be here:
```
[ -r "${XDG_CONFIG_HOME:-$HOME/.config}/bash_completion" ] &&
            . "${XDG_CONFIG_HOME:-$HOME/.config}/bash_completion"
```
But for me its empty: `echo $XDG_CONFIG_HOME`.

**Comment by nrlquaker** [comment]
The latest version of `bash` provided by `brew` is `5.2.15` and in the script its checking for `4.2`, so its not working for latest `bash`. Maybe this is the issue?

```
if [ "${BASH_VERSINFO[0]}" -gt 4 ] ||
        [ "${BASH_VERSINFO[0]}" -eq 4 -a "${BASH_VERSINFO[1]}" -ge 2 ]; then
        [ -r "${XDG_CONFIG_HOME:-$HOME/.config}/bash_completion" ] &&
            . "${XDG_CONFIG_HOME:-$HOME/.config}/bash_completion"
        if shopt -q progcomp && [ -r /opt/homebrew/Cellar/bash-completion@2/2.11/share/bash-completion/bash_completion ]; then
            # Source completion code.
            . /opt/homebrew/Cellar/bash-completion@2/2.11/share/bash-completion/bash_completion
        fi
    fi
```

**Comment by maxim-belkin** [comment]
> The latest version of `bash` provided by `brew` is `5.2.15` and in the script its checking for `4.2`

Bash versions 4+ are taken care of by the first check: `if [ "${BASH_VERSINFO[0]}" -gt 4 ]`.

So, I recommend that you start debugging from the end: tt's obvious that `. /opt/homebrew/.../bash_completion` command is not executed, so go backwards from there and find the condition that is not true in your shell:
```
shopt -q progcomp || echo "progcomp False"
[ -r /opt/homebrew/Cellar/bash-completion@2/2.11/share/bash-completion/bash_completion ] || echo "file not readable"
[ "x${BASH_VERSION-}" != x ] || echo "BASH_VERSION empty"
[ "x${PS1-}" != x ] || echo  "PS1 unset"
[ "x${BASH_COMPLETION_VERSINFO-}" = x ] || echo "BASH_COMPLETION_VERSINFO is not unset"
```

**Comment by maxim-belkin** [comment]
I was able to reproduce this in WSL2: in Ubuntu (WSL2) there is the following piece of beauty in the default `~/.bashrc` file:

```sh
  if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
      . /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
      . /etc/bash_completion
    fi
  fi
```

which provide a slightly older version of bash-completion@2. As a result, it sets `BASH_COMPLETION_VERSINFO` variable and, as a result of that, sourced Bash completions are ignored.

I suppose that something similar is happening in your case, @nrlquaker.

**Comment by nrlquaker** [comment]
@maxim-belkin I'm running latest macos Ventura 13.2.1. The issue starts when I've updated to the latest version from the previous (don't remember the exact version).
I don't have time to debug the bash script.
But from your script:
```
shopt -q progcomp || echo "progcomp False"
[ -r ${HOMEBREW_PREFIX:-$(brew --prefix)}/Cellar/bash-completion@2/2.11/share/bash-completion/bash_completion ] || echo "file not readable"
[ "x${BASH_VERSION-}" != x ] || echo "BASH_VERSION empty"
[ "x${PS1-}" != x ] || echo  "PS1 unset"
[ "x${BASH_COMPLETION_VERSINFO-}" = x ] || echo "BASH_COMPLETION_VERSINFO is not unset"
```
I'm getting `PS1 unset`

**Comment by maxim-belkin** [comment]
> I'm getting `PS1 unset`

Setting PS1 to something sensible should do the trick then.

**Comment by nrlquaker** [comment]
@maxim-belkin I got a script that changes PS1. But its below mentioned code.
And it will be nice if it will be mentioned in the doc.

**Comment by gromgit** [comment]
> @gromgit Its empty.
> 
> ```
> env | grep BASH_COMPLETION
> ```

Sorry, what's the output of `set | grep BASH_COMPLETION`?

> I don't see any mentioning about `bash_completion.d` in `bash_completion.sh` from `bash-completion@2`:

That's because the snippet I `grep`'d earlier is from the file that's searched and sourced _by_ `bash_completion.sh`:
> ```
>         if shopt -q progcomp && [ -r /opt/homebrew/Cellar/bash-completion@2/2.11/share/bash-completion/bash_completion ]; then
>             # Source completion code.
>             . /opt/homebrew/Cellar/bash-completion@2/2.11/share/bash-completion/bash_completion
>         fi
> ```

**Pull request closed without merging**
