### PR TITLE
Simplify `TapConfig`.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Only allow `Symbol`s for keys and booleans as values.

### CODE REVIEW

**Comment by Bo98** [comment]
This is public API - have we checked nothing else in anything is using it?

**Comment by reitermarkus** [comment]
> I agree in principle, though this is public API

How is this public?

**Review by Bo98 — APPROVED** [review]
Am OK with this then

**Review by MikeMcQuaid — APPROVED** [review]
Looks good, thanks again @reitermarkus! Please merge when you're around to handle any regressions.

**Pull request merged**
