### PR TITLE
Audit taps for duplicates in aliases/renames.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

`homebrew/core` currently contains some duplicates in `Aliases` and `formula_renames.json`.

### CODE REVIEW

**Review by ZhongRuoyu — APPROVED** [review]
Makes sense to me!

**Review by MikeMcQuaid — APPROVED** [review]
Good idea!

**Comment by reitermarkus** [comment]
@Homebrew/core, can you check which of these should be aliases vs. renames?

https://github.com/Homebrew/brew/actions/runs/7832118805/job/21370092345?pr=16622#step:4:18

**Comment by ZhongRuoyu** [comment]
> @Homebrew/core, can you check which of these should be aliases vs. renames?
> 
> https://github.com/Homebrew/brew/actions/runs/7832118805/job/21370092345?pr=16622#step:4:18

See Homebrew/homebrew-core#162194.

**Pull request merged**
