### PR TITLE
Fixed link to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by pkuczynski**

### CODE REVIEW

**Comment by zmwangx** [comment]
Please correct all four occurrences, thanks:

```
$ grep -rI --exclude-dir=Taps '\.github/CONTRIBUTING.md'
.github/PULL_REQUEST_TEMPLATE.md:- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/.github/CONTRIBUTING.md) document?
docs/FAQ.md:Read [CONTRIBUTING.md](/.github/CONTRIBUTING.md).
docs/Formula-Cookbook.md:Before submitting a new formula make sure you read over our [contribution guidelines](https://github.com/Homebrew/brew/blob/master/.github/CONTRIBUTING.md).
docs/README.md:Read [CONTRIBUTING.md](/.github/CONTRIBUTING.md).
README.md:We'd love you to contribute to Homebrew. First, please read our [Contribution Guide](https://github.com/Homebrew/brew/blob/master/.github/CONTRIBUTING.md) and [Code of Conduct](https://github.com/Homebrew/brew/blob/master/CODEOFCONDUCT.md#code-of-conduct).
```

**Comment by MikeMcQuaid** [comment]
Missed these, thanks. Yeh, if you could get all of them that'd be amazing, thanks.

**Comment by MikeMcQuaid** [comment]
Just grabbed them quickly myself but thanks for submitting a PR ✨

**Comment by pkuczynski** [comment]
Sure. Here it comes: https://github.com/Homebrew/brew/pull/1042

**Pull request closed without merging**
