### PR TITLE
Improve @-versioned formulae linking.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Re-applies https://github.com/Homebrew/brew/pull/9009
Reverts Homebrew/brew#9016

I'll push a fix to the issue @sjackman mentions in #9016.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> I'll push a fix to the issue @sjackman mentions in #9016.

Done in bd7969c2b

**Comment by sjackman** [comment]
Thanks, Mike!

**Comment by sjackman** [comment]
This PR appears to have reintroduced the same regression.
```console
$ brew --version
Homebrew 2.5.8-70-gcbb0b87
Homebrew/homebrew-core (git revision 1cc3d9; last commit 2020-11-04)
Homebrew/homebrew-cask (git revision 3381ef; last commit 2020-11-04)
$ brew audit seqan@3
brewsci/bio/seqan@3:
  * Formula has other versions so create a versioned alias:
      cd /usr/local/Homebrew/Library/Taps/brewsci/homebrew-bio/Aliases
      ln -s ../Formula/seqan@3.rb seqan@3@3
Error: 1 problem in 1 formula detected
```
See for example https://github.com/brewsci/homebrew-bio/pull/1189/checks?check_run_id=1351289870#step:4:80

**Comment by iMichka** [comment]
Same error here: https://github.com/Homebrew/homebrew-core/pull/64151

**Comment by MikeMcQuaid** [comment]
> Same error here: [Homebrew/homebrew-core#64151](https://github.com/Homebrew/homebrew-core/pull/64151)

That's not a false positive, that error is correct.

**Comment by MikeMcQuaid** [comment]
@sjackman Apologies, I did try to fix that but incorrectly. I reproduced it now and fixed it (with a change that I'd have thought was identical but ho hum Ruby 😁 https://github.com/Homebrew/brew/pull/9051)

**Comment by maxim-lobanov** [comment]
We have found small issue that could be caused by this change.
In [image-generation code](https://github.com/actions/virtual-environments/blob/main/images/macos/provision/core/gcc.sh#L4), we invoke the following commands:
```bash
brew install gcc@8
brew install gcc@9
```

Previously, they worked well and added two binaries in PATH: `gcc-8` and `gcc-9`. Now, only `gcc-9` is available.
Even if we do `brew link gcc@8` after installation, it unlinks gcc-9 due to this change.
I understand that it is probably expected behavior accordingly to this PR but previously, both formulas worked perfect side by side.
Is there any workaround or improvements to `gcc` formula to apply both of them?

**Comment by maxim-lobanov** [comment]
Related issue: https://github.com/Homebrew/brew/issues/9100

**Comment by sjackman** [comment]
I would like to be able to link both `gcc@8` and `gcc@9` so that both `gcc-8` and `gcc-9` are found in the `PATH`. These two formulae do not conflict with each other. Should an exception be made specifically for `gcc@…`, or do we want to reconsider this particular aspect of this change?

**Pull request merged**
