### PR TITLE
formula_cellar_checks: check for shim dir references

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

I can't realistically test everything, but I ran `brew list | xargs -n 1 brew audit --only=installed` and got:

```
gcc:
  * Files were found with references to the Homebrew shims directory.
    The offending files are:
      libexec/gcc/x86_64-apple-darwin18/9.3.0/install-tools/fixincl
Error: 1 problem in 1 formula detected
ilmbase:
  * Files were found with references to the Homebrew shims directory.
    The offending files are:
      share/ilmbase/IexMath/CMakeFiles/IexMath.dir/link.txt
      share/ilmbase/IexMath/CMakeFiles/IexMath.dir/build.make
      share/ilmbase/IexMath/CMakeFiles/IexMath.dir/flags.make
      share/ilmbase/IlmThread/CMakeFiles/IlmThread.dir/link.txt
      share/ilmbase/IlmThread/CMakeFiles/IlmThread.dir/build.make
      share/ilmbase/IlmThread/CMakeFiles/IlmThread.dir/flags.make
      share/ilmbase/Imath/CMakeFiles/Imath.dir/link.txt
      share/ilmbase/Imath/CMakeFiles/Imath.dir/build.make
      share/ilmbase/Imath/CMakeFiles/Imath.dir/flags.make
      share/ilmbase/ImathTest/CMakeFiles/ImathTest.dir/link.txt
      share/ilmbase/ImathTest/CMakeFiles/ImathTest.dir/build.make
      share/ilmbase/ImathTest/CMakeFiles/ImathTest.dir/flags.make
      share/ilmbase/IexTest/CMakeFiles/IexTest.dir/link.txt
      share/ilmbase/IexTest/CMakeFiles/IexTest.dir/build.make
      share/ilmbase/IexTest/CMakeFiles/IexTest.dir/flags.make
      share/ilmbase/Half/CMakeFiles/toFloat.dir/link.txt
      share/ilmbase/Half/CMakeFiles/toFloat.dir/build.make
      share/ilmbase/Half/CMakeFiles/toFloat.dir/flags.make
      share/ilmbase/Half/CMakeFiles/eLut.dir/link.txt
      share/ilmbase/Half/CMakeFiles/eLut.dir/build.make
      share/ilmbase/Half/CMakeFiles/eLut.dir/flags.make
      share/ilmbase/Half/CMakeFiles/Half.dir/link.txt
      share/ilmbase/Half/CMakeFiles/Half.dir/build.make
      share/ilmbase/Half/CMakeFiles/Half.dir/flags.make
      share/ilmbase/HalfTest/CMakeFiles/HalfTest.dir/link.txt
      share/ilmbase/HalfTest/CMakeFiles/HalfTest.dir/build.make
      share/ilmbase/HalfTest/CMakeFiles/HalfTest.dir/flags.make
      share/ilmbase/Iex/CMakeFiles/Iex.dir/link.txt
      share/ilmbase/Iex/CMakeFiles/Iex.dir/build.make
      share/ilmbase/Iex/CMakeFiles/Iex.dir/flags.make
Error: 1 problem in 1 formula detected
imagemagick:
  * Files were found with references to the Homebrew shims directory.
    The offending files are:
      bin/MagickCore-config
      bin/MagickWand-config
      bin/Magick++-config
Error: 1 problem in 1 formula detected
perl:
  * Files were found with references to the Homebrew shims directory.
    The offending files are:
      lib/perl5/5.30.2/darwin-thread-multi-2level/CORE/config.h
      lib/perl5/5.30.2/darwin-thread-multi-2level/Config_heavy.pl
Error: 1 problem in 1 formula detected
ruby:
  * Files were found with references to the Homebrew shims directory.
    The offending files are:
      lib/libruby.2.7.dylib
      lib/ruby/2.7.0/x86_64-darwin18/rbconfig.rb
Error: 1 problem in 1 formula detected
```

`gcc` (sed), `imagemagick` (pkg-config) and `perl` (sed) look like genuine problems.

`ruby` (clang): depends on what `MJIT_CC` is.

`ilmbase` (various) looks like build files that should not be installed in the first place.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
This makes sense to me a PR but my concern is: does this mean CI for `perl`, `ruby`, etc. will fail from now on? If so: I think it might be worth holding off on this before at least some of the big and popular packages are fixed (so we're not going to be seeing red CI on updates).

**Comment by Bo98** [comment]
* `imagemagick`: Homebrew/homebrew-core#53162
* `gcc`: Homebrew/homebrew-core#53185
* `perl`: Homebrew/homebrew-core#53186
* `ruby`: Homebrew/homebrew-core#53187
* `ilmbase`: Homebrew/homebrew-core#53188

**Comment by MikeMcQuaid** [comment]
Other ones on mine (`brew audit --only=installed $(brew list)`) `libusb`, `mysql@5.7`, `ruby@2.6`.

**Comment by Bo98** [comment]
ruby@2.6 is covered under the Ruby pull request. Earlier versions should be fine since they don't have JIT support.

I'll look at libusb and mysql@5.7.

**Comment by MikeMcQuaid** [comment]
Nice, thanks @Bo98 ❤️

**Comment by Bo98** [comment]
libusb: Homebrew/homebrew-core#53190

mysql@5.7 (and other versions likely) is a `INFO_BIN` file describing how MySQL was built. It's pretty harmless. I guess we could either whitelist it or delete it.

**Comment by MikeMcQuaid** [comment]
> mysql@5.7 (and other versions likely) is a `INFO_BIN` file describing how MySQL was built. It's pretty harmless. I guess we could either whitelist it or delete it.

👍 to just whitelist.

**Comment by Bo98** [comment]
All linked pull requests have been merged.

**Comment by MikeMcQuaid** [comment]
Thanks @Bo98!

**Pull request merged**
