### PR TITLE
Implement `brew cask help <command>`.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Needed to display the usage information being added in https://github.com/Homebrew/brew/pull/7427.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Would this also be picked up by `brew cask [command] --help`?

**Comment by reitermarkus** [comment]
@SMillerDev, now it should.

**Comment by vitorgalvao** [comment]
Does this close https://github.com/Homebrew/homebrew-cask/issues/78491?

**Comment by reitermarkus** [comment]
No, because 

> This should be done by using the CLI/Parser logic in Homebrew/brew.

**Pull request merged**
