### PR TITLE
rubocop: Fix remaining TODOs for triaging Ruby 3 cops

### PR DESCRIPTION
**Pull request by issyl0**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

- I finally got around to finishing off this set of TODOs: triaging which of the Ruby 3 related cops we want to enable.
- See commits for more details.

### CODE REVIEW

**Review by ZhongRuoyu — APPROVED** [review]

**Comment by issyl0** [comment]
OMG, maybe at some point I'll fix all the things. 😩

**Review by p-linnane — APPROVED** [review]
Awesome job!

**Comment by issyl0** [comment]
There are too many taps. 😅

**Comment by MikeMcQuaid** [comment]
Yay, thanks again @issyl0!

**Pull request merged**
