### PR TITLE
download_strategy: fix git submodule references

### PR DESCRIPTION
**Pull request by UniqMartin**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Some Git versions create absolute `gitdir:` pointers in a submodule's `.git` file, which can be problematic once the resource is staged and causes various Git operations for those submodules to fail. Work around this issue by fixing the submodule `.git` files after submodule update.

See Homebrew/homebrew-core#1520 for details and an affected formula.

Strictly speaking this is a Git bug and not a Homebrew bug, but since we have to deal with affected Git versions and clones created by them for the foreseeable future, this workaround seems warranted.

(This is a [known regression](http://thread.gmane.org/gmane.comp.version-control.git/290491) that was introduced in the Git 2.7 series and [has been fixed in Git 2.8.3](https://github.com/git/git/commit/f5e16b2a7ba0ed12e4674f111386643e16692fe9). This explains why the problem started with Xcode 7.3.1 that updated Git from 2.6.4 to 2.7.4.)

### CODE REVIEW

**Comment by DomT4** [comment]
Yeah, `sourcekitten` builds fine for me with the latest `git` from Homebrew. Maybe it's worth filing an rdar with Apple to see if they're aware of this; it's a nasty enough regression to merit a fix before El Cap stops being the current release of OS X, _hopefully_.

**Comment by UniqMartin** [comment]
> Maybe it's worth filing an rdar with Apple to see if they're aware of this; it's a nasty enough regression to merit a fix before El Cap stops being the current release of OS X, *hopefully**.

Xcode 7.3.1 is currently the only version affected by this and I think Apple is unlikely to cut a new release just to address this bug. They have also been pretty quick to adopt new Git versions in the recent past: Xcode 7.2(.1) had 2.5.4, Xcode 7.3 had 2.6.4, and Xcode 7.3.1 already has 2.7.4, so I think it's not completely unlikely the next Xcode release will have Git 2.8.3 or higher. But of course all of this is just an excuse not to file a rdar as I've never done this before. :wink:

It's only nasty if you have recursive submodules *and* dare to move your working copies around on disk.

**Comment by MikeMcQuaid** [comment]
Makes sense to me 👍. What's the performance like e.g. how long does this take on your machine on a random repository?

**Comment by UniqMartin** [comment]
> What's the performance like e.g. how long does this take on your machine on a random repository?

There's zero impact on repositories without submodules. For those that have submodules, the cost is approximately linear in the number of submodules and dominated by how quickly `git submodule foreach --recursive` is able to enumerate them (about 0.5s for the `sourcekitten` repository with 9 submodules). The time for this tends to be significantly less than the preceding recursive `git submodule sync` and the initialization of submodule repositories not previously cloned.

**Comment by MikeMcQuaid** [comment]
@UniqMartin Sounds good 👍

**Pull request merged**
