### PR TITLE
azure-pipelines.yml: Build and test Docker image

### PR DESCRIPTION
**Pull request by sjackman**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

### CODE REVIEW

**Comment by sjackman** [comment]
Moving `HOMEBREW_REPOSITORY` to `…/Homebrew` was need to prevent this `brew doctor` error:
```
Warning: You have multiple Cellars.
You should delete /home/linuxbrew/.linuxbrew/Homebrew/Cellar:
  rm -rf /home/linuxbrew/.linuxbrew/Homebrew/Cellar
```

**Comment by MikeMcQuaid** [comment]
@sjackman 

> Successful in 41m — Linux succeeded
> Successful in 11m — macOS succeeded

I'm a bit concerned about the massive increase in build time (23m to 41m). Anything we can do to help speed this up a bit? If not let's maybe block this on making `brew test-bot` run more tests on macOS rather than Linux.

**Comment by sjackman** [comment]
Yep. Running `brew test-bot` both outside the container and inside the container is redundant. We can run it only within the container.

```
Run brew test-bo 22m 37s
Build and test Docker image 18m 22s
```

**Comment by sjackman** [comment]
Removed the duplication. Ready for re-review.

**Comment by MikeMcQuaid** [comment]
@sjackman Oh, much nicer. A few things:

> ##[warning]No test result files matching brew-test-bot.xml were found.

Probably need to copy that out the docker container. Just for future-proofing: may also want to copy the coverage files too (see "Publish brew tests code coverage" on the macOS build and https://github.com/Homebrew/homebrew-test-bot/blob/master/cmd/brew-test-bot.rb#L1030-L1031 e.g. the `coverage` directory in the build root).

Also need to ensure that the `TF_BUILD` variable is passed through: https://github.com/Homebrew/homebrew-test-bot/blob/master/cmd/brew-test-bot.rb#L1575 along with other Azure Pipelines environment variables e.g. https://github.com/Homebrew/homebrew-test-bot/blob/master/cmd/brew-test-bot.rb#L407-L408 to ensure the correct code is being tested.

Also, in an ideal world if it's technically possible it'd be nice to split the "build the docker image" and "run test-bot inside the docker image" into two separate steps so their output can be differentiated.

**Comment by sjackman** [comment]
Good grief that was surprisingly difficult to get the environment variables exported through Docker and sudo to test-bot, and get the `brew-test-bot.xml` out of Docker back to Azure.

@MikeMcQuaid Ready for re-review.

**Comment by MikeMcQuaid** [comment]
Nice work here @sjackman! Pretty cool to see us actually building and testing the docker image here. I think we should consider making the Docker image "official" in a future version; I suspect it'll get widely used.

**Comment by sjackman** [comment]
For installing packages required by CI to test a package, when the versions provided by the host package manager (likely `apt-get`) are not new enough, using Linuxbrew is a good alternative to using Ubuntu PPAs (Personal Package Archives).

**Pull request merged**
