### PR TITLE
language/java: add support for OpenJDK

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

I've been meaning to do this for a while.

This modifies `Language::Java` to also search for the OpenJDK formulae. This thus fixes `Pathname#write_jar_script` to also work when depending on the OpenJDK formula.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Thanks again @Bo98!

**Comment by bayandin** [comment]
It looks like this PR doesn't work as expected; here are some related fails:
- https://github.com/Homebrew/homebrew-core/pull/56418
- https://github.com/Homebrew/homebrew-core/pull/56450

```
==> /usr/local/Cellar/bnd/5.1.1/bin/bnd resolve resolve -b launch.bndrun
/usr/local/Cellar/bnd/5.1.1/bin/bnd: line 2: /private/tmp/bnd-test-20200617-35412-1nvizr5/java  -jar /usr/local/Cellar/bnd/5.1.1/libexec/biz.aQute.bnd-5.1.1.jar: No such file or directory
/usr/local/Cellar/bnd/5.1.1/bin/bnd: line 2: exec: /private/tmp/bnd-test-20200617-35412-1nvizr5/java  -jar /usr/local/Cellar/bnd/5.1.1/libexec/biz.aQute.bnd-5.1.1.jar: cannot execute: No such file or directory
```

It tries to launch `java` as a binary in the current directory.

**Comment by Bo98** [comment]
I'm afraid I cannot reproduce the issue you describe. Do you have more info?

With this change:

```
#!/bin/bash
JAVA_HOME="$(/usr/libexec/java_home --version 1.8)" exec java  -jar /usr/local/Cellar/jenkins/2.241/libexec/jenkins.war "$@"
```


Without this change:

```
#!/bin/bash
JAVA_HOME="$(/usr/libexec/java_home --version 1.8)" exec java  -jar /usr/local/Cellar/jenkins/2.241/libexec/jenkins.war "$@"
```

**Comment by Bo98** [comment]
Ok I figured out what was happening - sorry for the breakage.

**Pull request merged**
