### PR TITLE
cleaner: remove *.tbd

### PR DESCRIPTION
**Pull request by AkihiroSuda**
For https://github.com/Homebrew/brew/pull/16355#issuecomment-1860642797

- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [X] Have you successfully run `brew style` with your changes locally?
- [X] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Needed by:
- https://github.com/Homebrew/homebrew-core/pull/157617

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@AkihiroSuda Do you have any examples beyond https://github.com/Homebrew/homebrew-core/pull/157617 for things that might need this? Thanks!

**Comment by AkihiroSuda** [comment]
> @AkihiroSuda Do you have any examples beyond [Homebrew/homebrew-core#157617](https://github.com/Homebrew/homebrew-core/pull/157617) for things that might need this? Thanks!

I don't know.

**Comment by Bo98** [comment]
Bit of a weird one given shipping both a .tbd and a .dylib seems pointless - Apple ship .tbd to avoid shipping .dylib in their SDKs.

It's not _wrong_ per se but instead rather meaningless.

It seems to be a new CMake feature. We could clean them like we do for `.la` files:

https://github.com/Homebrew/brew/blob/b72421e25807b72eac4ed041d9ae3ced22f9c285/Library/Homebrew/cleaner.rb#L7

https://github.com/Homebrew/brew/blob/b72421e25807b72eac4ed041d9ae3ced22f9c285/Library/Homebrew/cleaner.rb#L128

**Comment by MikeMcQuaid** [comment]
> It seems to be a new CMake feature. We could clean them like we do for `.la` files:

This seems like a good idea until we have a use for them 👍🏻

**Comment by AkihiroSuda** [comment]
I understand that `*.tbd` files are not expected to co-exist with `*.dylib`, but I fear that removing them may potentially break something that does not follow the standard

**Comment by carlocab** [comment]
> I fear that removing them may potentially break something that does not follow the standard

I'd rather report those to the relevant upstream project as a bug instead of preemptively working around them by always keeping the `*.tbd` files.

**Comment by Bo98** [comment]
Yeah it should be safe to treat them exactly as we do `.la` files.

For CMake, it happens if `ENABLE_EXPORTS ON` is set, but that also does other things like linkable executables so it's not quite as simple as turning it off (not that we can anyway without patching).

**Comment by AkihiroSuda** [comment]
Updated PR to remove `*.tbd`

**Review by MikeMcQuaid — APPROVED** [review]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @AkihiroSuda!

**Pull request merged**
