### PR TITLE
service: use default.target on Linux

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----
Should fix https://github.com/Homebrew/homebrew-services/issues/508

### CODE REVIEW

**Review by dawidd6 — APPROVED** [review]

**Comment by dawidd6** [comment]
I allowed myself to fix the tests to get this PR merged faster as the issue just hit me.

**Comment by dawidd6** [comment]
Tested locally, works alright but needs to first stop the service, reinstall a formula and start the service back up.

**Comment by dawidd6** [comment]
Those test failures seem to be unrelated?

**Comment by enernico** [comment]
I can confirm that this works perfectly fine for me, great job! :pinata:

**Pull request merged**
