### PR TITLE
Do not specify absolute paths to utilities

### PR DESCRIPTION
**Pull request by sjackman**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Specifying an absolute path to utilities is no longer needed, since environment filtering uses a default PATH.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
😍. You could also extend this to the various usages of `with_system_path`, I think? Feel free to 👎 for now and I'll merge as-is.

**Comment by sjackman** [comment]
I've removed `with_system_path`. There weren't many uses.

**Comment by MikeMcQuaid** [comment]
@sjackman Thanks again! This excites the pedant in me and will hopefully make a bunch of the Linux porting work easier.

**Comment by sjackman** [comment]
Thanks for merging, Mike! It does eliminate a number of the smaller, dispersed patches to remove `/usr/bin`.

**Pull request merged**
