### PR TITLE
Add HOMEBREW_ARCH environment variable

### PR DESCRIPTION
**Pull request by dalance**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

I want to use HOMEBREW_ARCH environment variable proposed at #4831.
This is because my home directory is shared by NFS through hosts with variety architectures.
Now I do `brew install` at an oldest host carefully, but this is inconvenience.

### CODE REVIEW

**Comment by dalance** [comment]
In my environment, I use the following hosts and share home directory by NFS.

* OS
  * CentOS7.6
* CPU
  * host1: Intel(R) Xeon(R) Gold 6134
  * host2: Intel(R) Xeon(R) Silver 4108
  * host3: Intel(R) Xeon(R) CPU E5-2620 v4
  * host4: Intel(R) Xeon(R) CPU E5-2695 v3
  * host5: Intel(R) Xeon(R) CPU           L5630
  * host6: AMD Ryzen Threadripper 1950X

For example, if I do `brew install python3` at host1,
`python3` command will abort at host3, host4, host5, host6 like below:

```
[1]    106302 illegal hardware instruction (core dumped)  python3
```

git, tmux, neovim become the same result.

If I do `brew install` at host5 (this is the oldest arch), all binaries work fine at all hosts.
Alternatively If I set `HOMEBREW_ARCH=nehalem` with this PR, work fine too.

**Comment by dalance** [comment]
I tried to move the change to ` Library/Homebrew/extend/os/linux/hardware/cpu.rb`.

**Comment by MikeMcQuaid** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @dalance!

**Comment by dalance** [comment]
Thanks!

**Pull request merged**
