### PR TITLE
README: add @chenrui333

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
Have contributed many changes in homebrew-core, want to join the homebrew team :)

**Comment by shortdawg896** [comment]
Sure

On Aug 23, 2019 4:06 PM, "chenrui" <notifications@github.com> wrote:

Have contributed many changes in homebrew-core, want to join the homebrew
team :)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Homebrew/brew/pull/6399?email_source=notifications&email_token=AMWGPGOSQK3OB6HD5O7G6GDQGA7OBA5CNFSM4IPC47HKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5BGMGQ#issuecomment-524445210>,
or mute the thread

**Comment by MikeMcQuaid** [comment]
@chenrui333 Welcome to the team! Please rebase this on `origin/master`, run `brew man`, commit the changes and let me know when it's ✅.

**Comment by chenrui333** [comment]
@MikeMcQuaid Just did:
- ` git rebase master`
- `brew man`
- forced update

**Comment by MikeMcQuaid** [comment]
@chenrui333 You need to also `git commit` those changes from `brew man`.

**Comment by chenrui333** [comment]
I just copied the `brew man` changes into the repo. Not sure if that works.

**Comment by EricFromCanada** [comment]
You need to also pull the latest changes from Homebrew/brew. Try:
```
cd `brew --repo`
git checkout -- docs/Manpage.md manpages/brew.1 manpages/brew-cask.1
git pull --rebase origin master
brew man
```
and commit/push those changes.

**Comment by chenrui333** [comment]
That seems much more clear, thanks @EricFromCanada !

**Comment by EricFromCanada** [comment]
I should also point out that the file you need to add your name to is `/README.md`. The `brew man` command reads this file to generate the Markdown and manpage files.

**Comment by chenrui333** [comment]
I see, 🤣 I am adding the `README.md` change now.

**Pull request merged**
