### PR TITLE
Make Python 3.9 our main Python version

### PR DESCRIPTION
**Pull request by fxcoudert**
This will allow testing of https://github.com/Homebrew/homebrew-core/pull/63346

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
👍🏻 I wonder if there's a way we could do this automatically based on the versions though. CC @Rylan12 for thoughts as you did similarly in another PR?

**Comment by fxcoudert** [comment]
Not sure why the macOS runner is failing, maybe the warning about broken linkage on subversion?

**Comment by SMillerDev** [comment]
I think the other solution was dependent on allowing only a single "normal" python formula, and that's what we're enforcing here. But maybe we can count the amount of non `keg_only` formula for python and make sure it's only one?

**Comment by MikeMcQuaid** [comment]
> But maybe we can count the amount of non `keg_only` formula for python and make sure it's only one?

Yeh, I was thinking about something like that 👍🏻

**Comment by MikeMcQuaid** [comment]
> Not sure why the macOS runner is failing, maybe the warning about broken linkage on subversion?

Yeh, that's why. Opened a PR in https://github.com/Homebrew/homebrew-core/pull/63349

**Comment by Rylan12** [comment]
In https://github.com/Homebrew/brew/pull/8959, I just checked to see which python formula was not keg_only and assumed that was the one to use. We might want to add an e.g. `get_main_python_version` method somewhere that will find this for us.

It's probably not a bad idea to have an audit that makes sure there's only one python keg_only formula in Homebrew/core.

**Comment by fxcoudert** [comment]
New subversion bottles merged in https://github.com/Homebrew/homebrew-core/pull/63348
Retesting

**Comment by fxcoudert** [comment]
Test failure due to timeout.

```
2020-10-23T15:56:04.5367910Z Failures:
2020-10-23T15:56:04.5368070Z 
2020-10-23T15:56:04.5368660Z   1) Cask::Cmd::Zap can zap and unlink multiple Casks at once
2020-10-23T15:56:04.5369860Z      Failure/Error: raise "Example exceeded maximum runtime of #{timeout} seconds."
2020-10-23T15:56:04.5370230Z 
2020-10-23T15:56:04.5370520Z      RuntimeError:
2020-10-23T15:56:04.5370930Z        Example exceeded maximum runtime of 120 seconds.
2020-10-23T15:56:04.5372420Z      # ./test/spec_helper.rb:200:in `rescue in block (2 levels) in <top (required)>'
2020-10-23T15:56:04.5373380Z      # ./test/spec_helper.rb:191:in `block (2 levels) in <top (required)>'
2020-10-23T15:56:04.5374370Z      # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
2020-10-23T15:56:04.5375440Z      # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
2020-10-23T15:56:04.5376470Z      # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
2020-10-23T15:56:04.5377670Z      # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
2020-10-23T15:56:04.5378800Z      # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
2020-10-23T15:56:04.5394020Z      # ./vendor/bundle/ruby/2.6.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
2020-10-23T15:56:04.5395030Z      # ------------------
2020-10-23T15:56:04.5395650Z      # --- Caused by: ---
2020-10-23T15:56:04.5395960Z      # Timeout::Error:
2020-10-23T15:56:04.5396270Z      #   execution expired
2020-10-23T15:56:04.5396990Z      #   ./system_command.rb:157:in `select'
```

**Comment by fxcoudert** [comment]
Running a third time, and now it's the linux runner that's bailing out:

```
Error: brew update didn't update master!
Start commit:        c4ae961efac4904aabdd7dc3cbe20dc4ed004869
Expected end commit: 7881a93c5b077ccf0a3b1d173fb899d5609ea5f5
Actual end commit:   8982dc3f7eeee13d189324f38b3b9d3e9124b38f
```

**Comment by fxcoudert** [comment]
I don't know how to get the history of CI, so here's a summary: so far I've run it 4 times, and saw the Linux failure 3 times and the macOS timeout once.

**Comment by MikeMcQuaid** [comment]
Closing in favour of https://github.com/Homebrew/brew/pull/8980

**Pull request closed without merging**
