### PR TITLE
Output annotations for `brew cask audit` (again).

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

This was previously done in the `homebrew/cask` CI workflow.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Could/is this done for `brew audit` and/or `brew style` too?

**Comment by reitermarkus** [comment]
It should already work for `brew style`.

**Comment by MikeMcQuaid** [comment]
@reitermarkus Would you be able to write up an issue describing what someone would need to do for this to work with `brew audit`?

**Comment by reitermarkus** [comment]
> Would you be able to write up an issue describing what someone would need to do for this to work with `brew audit`?

Too late. 😉 

https://github.com/Homebrew/brew/pull/8684

**Pull request merged**
