### PR TITLE
Dockerfile: set default `umask`

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

This makes sure that the system `umask` is the same as the one on macOS.

Fixes Homebrew/homebrew-core@155e3ab5a88fb373342db5af0bc42499c5124402.

### CODE REVIEW

**Review by dawidd6 — APPROVED** [review]

**Review by Bo98 — APPROVED** [review]
Sure.

Probably should still handle it better elsewhere but this seems the easiest to do for now.

**Comment by carlocab** [comment]
This didn't seem to change anything: https://github.com/Homebrew/homebrew-core/actions/runs/5151557652

Weird; I tried this out in a Docker container first...

**Comment by dawidd6** [comment]
Maybe this sed should also be applied to `/etc/pam.d/common-session-noninteractive`?

**Comment by carlocab** [comment]
#15516

**Pull request merged**
