### PR TITLE
Set gist-logs to create private gist (vs. public)

### PR DESCRIPTION
**Pull request by JBallin**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Gists don't need to be listed on a user's page because they provide the direct link in their issues.

['Create Gist' GitHub API docs](https://developer.github.com/v3/gists/#create-a-gist).

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
What are the downsides of it being public?

**Comment by JBallin** [comment]
Privacy and keeping my public gists clean. What's the downside of private?

**Comment by MikeMcQuaid** [comment]
@Homebrew/maintainers any thoughts on this?

> What's the downside of private?

It's a change from the status quo. The change needs justified rather than the current behaviour.

**Comment by SMillerDev** [comment]
If it doesn't change anything in the behavior I'm fine with it.

**Comment by javian** [comment]
One privacy issue I can see at the moment is that if you install in a non-default location and put the root directory inside your home directory you would potentially expose your username through any exposed paths. If you posted in an issue it would of course be visible there anyway but then it would be a more conscious act.

It would also not expose data for people that typed the command without knowing the consequences.

**Comment by woodruffw** [comment]
Does making the gists private by default mean that search engines won't index them? If so, I'm :+1: on the status quo -- I've fixed more than one problem in the past by going through someone else's logs after finding them on Google. Otherwise, I'm fine with this change.

**Comment by JBallin** [comment]
@woodruffw looks like private gists are NOT indexed. I suppose that is a downside.

They use Google's [`robots` meta tag](https://developers.google.com/search/reference/robots_meta_tag)
```
$ curl $PRIVATE_GIST_URL | grep robots
<meta name="robots" content="noindex, follow" />

$ curl $PUBLIC_GIST_URL | grep robots
```

Another option is an optional `--private` flag.

**Comment by MikeMcQuaid** [comment]
> Another option is a `--private` flag.

As long as this isn't the default and is documented: this seems like a better option to me.

**Comment by JBallin** [comment]
Sounds good! I can't complete this immediately, but will do it soon. Should I close the PR in the mean time so it's not in your queue?

**Comment by MikeMcQuaid** [comment]
No, it's fine to leave open 👍

**Comment by MikeMcQuaid** [comment]
Thanks again @JBallin!

**Pull request merged**
