### PR TITLE
rubocop: Add cop to check `depends_on` order and tests

### PR DESCRIPTION
**Pull request by GauthamGoli**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
This new cop orders `depends_on` in the following sequence

=> :build first
=> :run second
=> regular third
=> :recommended fourth
=> :optional fifth

and _within_ each category alphabetized.

Also, conditional dependency ordering is taken care of 
```ruby
depends_on "apple" if build.with? "foo" || build.with? "bar"
depends_on "foo" => :optional
depends_on "bar"
```
After auto correct
```ruby
depends_on "bar"
depends_on "foo" => :optional
depends_on "apple" if build.with? "foo" || build.with? "bar"
```

cc @ilovezfs / @MikeMcQuaid

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
I tested this on `wget` and it fixed the order as expected 👍. `brew style --fix wget` did not, however.

**Comment by GauthamGoli** [comment]
@MikeMcQuaid I think thats because this is a `FormulaAuditStrict` cop, which doesn't get executed for `brew style`

**Comment by ilovezfs** [comment]
Let's merge this as a new formula only audit, and start using it. Then if all goes well, and we've worked out any rough spots, we can consider upgrading it to --strict or even non-strict and mass re-ordering everything.

**Comment by GauthamGoli** [comment]
Updated. This cop is now a `--new-formula` audit.

**Comment by MikeMcQuaid** [comment]
Thanks again @GauthamGoli!

**Pull request merged**
