### PR TITLE
docs: fix poor visibility in syntax highlighting

### PR DESCRIPTION
**Pull request by jonchang**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Some syntax highlighting on docs.brew.sh are illegible due to low contrast.

Before:

image

After:

image

### CODE REVIEW

**Comment by scpeters** [comment]
Example is from this page:

* https://docs.brew.sh/Common-Issues.html

I agree that it's hard to read

**Comment by MikeMcQuaid** [comment]
@jonchang Can you submit a PR to update https://github.com/Homebrew/homebrew.github.io/blob/master/css/pygments.css first? Thanks!

**Comment by jonchang** [comment]
https://github.com/Homebrew/homebrew.github.io/pull/182

**Comment by MikeMcQuaid** [comment]
Thanks @jonchang!

**Pull request merged**
