### PR TITLE
vendor: delete outdated readme

### PR DESCRIPTION
**Pull request by SeekingMeaning**
- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
This file is very much outdated. We don't even use `backports` anymore.

**Comment by SeekingMeaning** [comment]
Whoops. Is it safe to assume that this is the new list of vendored dependencies? https://github.com/Homebrew/brew/tree/master/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems

**Comment by Bo98** [comment]
Yes. I don't really see any value of having the README anymore. It's not been updated since the move to Bundler.

**Comment by MikeMcQuaid** [comment]
Yeh, agreed, I forgot this was even here. 👍 to delete and thanks for surfacing this @SeekingMeaning!

**Comment by MikeMcQuaid** [comment]
Thanks again @SeekingMeaning!

**Pull request merged**
