### PR TITLE
service: ensure environment variables are strings

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Review by dawidd6 — DISMISSED** [review]

**Comment by Bo98** [comment]
Can you mention what issue this is solving? Not entirely sure what error this was causing before.

**Comment by SMillerDev** [comment]
The issue is represented in the test block. If you used a pathname in a variable it would render in the plist as "data" instead of the path as a string.

**Comment by Bo98** [comment]
Oh right, I see we do `StandardOutPath` etc string conversion earlier. That's what confused me - I thought it was dealing with Pathname find there.

**Comment by Bo98** [comment]
Would it make sense to make to do `@environment_variables = variables.transform_values(&:to_s)` on line 108 instead, for consistency? Doesn't really matter much though.

**Comment by SMillerDev** [comment]
I think we can

**Comment by SMillerDev** [comment]
`Typecheck` is not happy and I'm not sure why

**Comment by Bo98** [comment]
Seems to think it could be nil here but it can’t. Could make wrap it as `T.must(variables).transform_values(...`

**Comment by SMillerDev** [comment]
> Seems to think it could be nil here but it can’t. Could make wrap it as T.must(variables).transform_values(...

I think this class has equal parts Sorbet and normal code... Okay, I'll try. I have to rebase anyway

**Comment by SMillerDev** [comment]
Since it hash an empty hash as fallback I guess it simply can't be null

**Review by Bo98 — APPROVED** [review]

**Pull request merged**
