### PR TITLE
Formula: create on_arm, on_intel, and on_ppc blocks

### PR DESCRIPTION
**Pull request by unitof**
A work in progress, by someone new to Homebrew & Ruby. Feel free to advise.

Basically copying from https://github.com/Homebrew/brew/commit/8b85ef2e8851b32eaac3f3094c7a6044eceb20e3#diff-9c6058d1e7a8fd9f2d2678820156daf1524cb3fbaacc66d195998260fd6e2f60

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?
- [ ] Have you successfully run `brew man` locally and committed any changes?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
Hi. Thanks for the proposal.

We do not support PCC and ARM on Linux. Even minor pull requests are not being always accepted, because we need to maintain that code without CI.

If we want to go down that road one day: a fork of Homebrew needs to be done for PCC and/or ARM, and supported by a community. Like when Linuxbrew was created back then. After a few years and that community has grown enough, we will consider the backport of the changes to plain Homebrew.

All the tooling is there to achieve this.

I'll leave this open so other maintainers can give their thoughts.

**Comment by unitof** [comment]
Got it! That actually helps a lot: I only included `on_ppc` because I saw it defined so thoroughly elsewhere and assumed it was therefore supported. I'll cut that.

Where I could use advise is whether it's best to stick with `on_arm`/`on_intel` or is it better to have these blocks depend on specific architectures or vendors, like `on_arm64` or `on_applesilicon`. Would love input from package maintainers which is more useful, while balancing futureproofness.

And thanks for looking @imichka! I was [inspired](https://github.com/Homebrew/brew/issues/7857#issuecomment-735909066) to draft this by your `on_mac`/`on_intel` blocks.

**Comment by MikeMcQuaid** [comment]
Sorry, passing on this as I don't see the need for it. Homebrew/homebrew-core has only 12 references to `Hardware::CPU.arm?` and they are all in `def install` blocks where `if` statements are less problematic (in the DSL for `depends_on` they end up restricting your ability to query what's happening on a given platform e.g. when generating macOS dependencies on Linux). 

Sorry again!

**Comment by unitof** [comment]
All's good! The idea popped up in a [comment](https://github.com/Homebrew/brew/issues/7857#issuecomment-735909066) on #7857 and seemed useful to a few others, but I hear what you're saying.

**Pull request closed without merging**
