### PR TITLE
xcode: 8.3.2 is latest version

### PR DESCRIPTION
**Pull request by JCount**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
The Sierra CI will need to be updated accordingly.
Given the content of this PR: cc @MikeMcQuaid

### CODE REVIEW

**Comment by DomT4** [comment]
Is the Xcode document no longer getting updated regularly?

**Comment by DomT4** [comment]
[This one](https://github.com/Homebrew/brew/blob/master/docs/Xcode.md) to be more specific.

**Comment by JCount** [comment]
@DomT4 Thanks for pointing that out. I based this PR off of the one MikeMcQuaid did for the 8.3.1 bump, so I didn't even think to look around.

**Comment by JCount** [comment]
@DomT4 Care to take a look and see if I got everything?

**Comment by DomT4** [comment]
No worries, Homebrew has too many moving parts sometimes to remember where they all are 😅. I think you got everything looking at it now 👍.

**Comment by MikeMcQuaid** [comment]
> Is the Xcode document no longer getting updated regularly?

I'd like to see this replaced with autogenerated output somewhere. It's generally a bit of a pain to update it.

**Comment by JCount** [comment]
@MikeMcQuaid Yeah, bumping the Xcode version requires remembering to modify at least three separate files. Finding some way of centralizing all of that, and then simply pulling from that central store or using it to autogenerate/autoupdate the rest of the associated files seems like a much better approach.

**Pull request merged**
