### PR TITLE
Use more descriptive heredoc names.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

This also enables nested syntax-highlighting in TextMate and on GitHub.

### CODE REVIEW

**Comment by ilovezfs** [comment]
I kind of like that we standardized on EOS.

**Comment by ilovezfs** [comment]
And to be super explicit: please don't bring this approach over to https://github.com/Homebrew/homebrew-core. The simplification to a single heredoc delimiter has improved maintainability significantly.

**Comment by commitay** [comment]
> please don't bring this approach over to https://github.com/Homebrew/homebrew-core.

or the cask taps.

**Comment by MikeMcQuaid** [comment]
Thanks again @reitermarkus!

**Comment by MikeMcQuaid** [comment]
To be clear: I'd also be 👎 on this were it for no reason but:

> This also enables nested syntax-highlighting in TextMate and on GitHub.

Is a pretty good feature, really.

**Comment by reitermarkus** [comment]
> I'd also be 👎 on this were it for no reason but

Yeah, I wouldn't have done it for no reason. 😉 

And don't worry @ilovezfs and @commitay, I wasn't planning on bringing this into taps.

**Pull request merged**
