### PR TITLE
audit: check GitHub tags for prerelease status

### PR DESCRIPTION
**Pull request by dtrodrigues**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
For GitHub formulae based on a tag vs a release, see if there is a corresponding release and if so, check to see if it's a prerelease. 

```
$ brew audit --online cbmc
cbmc:
  * cbmc-5.12.6 is a GitHub prerelease
Error: 1 problem in 1 formula detected
```

### CODE REVIEW

**Comment by dtrodrigues** [comment]
The 5 affected formulae are
```
cbmc.rb
elm-format.rb
infrakit.rb
riff.rb
volta.rb
```
`telegram-cli` is also a GitHub prerelease based on a tag but is already in the allowlist and the one other formula on the allowlist is `gitless`.

I'll file an issue with the five above prior to merging this, but I'm wondering if we should contact the other two/get rid of the the allowlist for prerelease since Homebrew should be packaging/distributing stable software, and the GitHub prerelease tag implies that the tag is not ready for production:
>To notify users that the release is not ready for production and may be unstable, select **This is a pre-release**. 

https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository#creating-a-release

**Comment by dtrodrigues** [comment]
Previous discussion about prerelease: https://github.com/Homebrew/brew/issues/7177
Previous discussion about prerelease allowlist: https://github.com/Homebrew/brew/pull/7737

**Comment by dtrodrigues** [comment]
In the short term, it might make the most sense to allow the current prerelease formula versions to remain and then have a conversation with the upstream projects when somebody tries to update the formula, so I added the few existing prerelease formulae to the allowlist and also added a check to ensure the formula version matches the allowlist version.

**Comment by MikeMcQuaid** [comment]
> In the short term, it might make the most sense to allow the current prerelease formula versions to remain and then have a conversation with the upstream projects when somebody tries to update the formula

Agreed 👍🏻. Great work @dtrodrigues!

**Pull request merged**
