### PR TITLE
Remove `brew search --desc` in readme

### LINKED ISSUE #243: brew search --desc is invalid
`--desc` seems to be an invalid flag for brew search.

### PR DESCRIPTION
**Pull request by kaizensoze**
--desc flag is invalid.

resolves #243

### CODE REVIEW

**Comment by DomT4** [comment]
It's not invalid as such, the documentation is just a little unclear/misguided. You use `brew search --desc` with a keyword of what you're looking for, i.e. I want to find formula that provide some kind of `sql` solution so I run:

```
~> brew search --desc sql
apache-drill: Schema-free SQL query engine for Hadoop and NoSQL
apgdiff: Another PostgreSQL diff tool
automysqlbackup: Automate MySQL backups
citus: PostgreSQL-based distributed RDBMS
fastbit: Open-source data processing library in NoSQL spirit
freetds: Libraries to talk to Microsoft SQL Server and Sybase databases
gom: GObject wrapper around SQLite
```

**Comment by kaizensoze** [comment]
Would it be ok to change this PR to have it say the following?

3. Or use brew search --desc text|/text/ to browse packages from the command line.

In addition I can create a separate PR to add --desc to the help text for brew search. Are there any other flags missing from that text?

**Comment by apjanke** [comment]
> Would it be ok to change this PR to have it say ...

Yes; please! That text is confusing as is; I would have made the same mistake. Or closing this and opening a new PR to do so might be less work than revising this and editing the description and comment history on this one to still be cogent.

At this location, I'd do something simpler like "`brew search --desc <keyword>`"; don't worry too much about the full syntax with `|` and such, since this is a brief, informal message.

> In addition I can create a separate PR to add --desc to the help text for brew search

:+1: You could just include it in the same PR, since it's related. It would be nice to have this too, since `--desc` is intended for common use by end users, so `brew --help` should describe it.

...and while you're in there, this is what the current `brew --help search` says:

```
brew search, -S:
    Display all locally available formulae for brewing (including tapped ones).
    No online search is performed if called without arguments.

brew search, -S text|/text/:
    Perform a substring search of formula names for text. If text is
    surrounded with slashes, then it is interpreted as a regular expression.
    The search for text is extended online to some popular taps.
```

I dunno about you, but that "`brew search, -S`" format with the comma seems odd and hard to read to me, and isn't standard quasi-BNF syntax. And using "text" as the placeholder for both literal text and regex patterns is hard to read IMHO. Maybe it should be something more like:

```
brew (search | -S)
   ...
brew (search | -S) (text | /pattern/)
   ...
```

Or just drop the `-S` from the helptext entirely, since it makes the syntax description more complex, and I'll bet 80%+ of users are using the `search` form instead of `-S`. If nothing else, change all the helptext to say `brew search ...` and then just put a footnote at the bottom saying "`-S` may be used as a synonym for `search`". Something like this, with appropriate markup:

```
brew search
   ...
brew search (text | /pattern/)
   ...

The `-S` switch may be used as a synonym for the `search` subcommand.
```

**Comment by kaizensoze** [comment]
Ok I'll take a look.

**Pull request closed without merging**
