### PR TITLE
Further terminology in docs + link on README

### PR DESCRIPTION
**Pull request by mjbrender**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----
Addressing a few spots where I looked for terminology and did not find what I was looking for. Input based on a recent [podcast with Mike](https://changelog.com/podcast/223). Thanks for the inspiration @MikeMcQuaid - I would love to continue to help with my favorite macOS tool 👌.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Lovely, cheers @mjbrender! Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by mjbrender** [comment]
You made my freaking day @MikeMcQuaid 👌. Looking forward to helping where I can.

**Comment by tdsmith** [comment]
I just noticed this change! It's really great! Thanks for this :)

**Comment by mjbrender** [comment]
Thanks @tdsmith! So happy that you all welcome contribution from the community. I ❤️ Homebrew.

**Pull request merged**
