### PR TITLE
shims/super/cc: stop filtering `m64`

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

We no longer support 32-bit machines, so there is no reason to filter
this out any longer.

### CODE REVIEW

**Comment by Bo98** [comment]
What is the effect of this flag on arm64?

While we don't support 32-bit, we still have retained the underlying build system so that 32-bit Intel and PowerPC, and probably even 32-bit ARM, _are_ usable when built from source (if the formula itself works with it). Example: `Hardware::CPU` has 32-bit stuff. We've been quite happy to allow this in the past - we accepted a PowerPC64 pull request despite it being unlikely we'll ever officially support it.

I also can't really think of a reason why allowing the flag would be necessary.

**Comment by carlocab** [comment]
`-m64` is an x86_64/PowerPC option, so I am pretty sure this is a no-op on ARM64. At the very least, it appears to do nothing with Apple Clang/Homebrew GCC 11 on M1.

You are correct to point out that this is probably not necessary to get things to compile. However, `-m64` also turns off `-fno-pic` on Darwin ([Ref](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html#x86-Options)), which has memory usage benefits and is probably what you want for shared libraries. (It also turns off `-mdynamic-no-pic`, but that's PowerPC-only.)

I will note, however, that a project that passes `-m64` to the compiler when trying to build from source on a 32-bit machine probably doesn't work on 32-bit machines already. Filtering the `-m64` flag _might_ get it to compile (maybe), but who knows where else the project makes assumptions about running on a 64-bit machine?

**Comment by Bo98** [comment]
> You are correct to point out that this is probably not necessary to get things to compile. However, `-m64` also turns off `-fno-pic` on Darwin ([Ref](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html#x86-Options)), which has memory usage benefits and is probably what you want for shared libraries. (It also turns off `-mdynamic-no-pic`, but that's PowerPC-only.)

PIC _cannot_ be toggled on x86_64 and arm64 on macOS. It is always forced on, except for `-static` in Clang where it's forced off. This isn't anything to do with `-m64` specifically.

**Comment by carlocab** [comment]
> PIC _cannot_ be toggled in x86_64 and arm64 on macOS. It is always forced on, except for `-static` in Clang where it's forced off.

I've heard that, but I've never actually found any documentation to support it.

> You can make this argument for anything the shim strips.

I disagree -- this does not apply to the bulk of what the shim strips: `-O`, `-m{arch,cpu,tune}`, `-W` and friends. There are some flags for which it does apply: for those flags, I would also argue in favour of no longer stripping them if they are only necessary on systems that are far enough outside of the systems we support (e.g. 32-bit systems).

**Comment by Bo98** [comment]
> I've heard that, but I've never actually found any documentation to support it.

Documentation's generally quite poor. But I've found the relevant Clang source code:

https://github.com/llvm/llvm-project/blob/80d62993d0720bc36523e39e64cc36da6e445e64/clang/lib/Driver/ToolChains/Darwin.cpp#L2783-L2786

https://github.com/llvm/llvm-project/blob/2a581710c1942b265b271e230368b1596132f242/clang/lib/Driver/ToolChains/CommonArgs.cpp#L1123-L1127

https://github.com/llvm/llvm-project/blob/2a581710c1942b265b271e230368b1596132f242/clang/lib/Driver/ToolChains/CommonArgs.cpp#L1204-L1206

> `-m64` is an x86_64/PowerPC option, so I am pretty sure this is a no-op on ARM64.

Just checked this (on Linux).

In Clang: it did seem to toggle between arm64 and arm32.
In GCC: this is a hard error and will stop the compile from happening (but not macOS: https://github.com/iains/gcc-darwin-arm64/commit/36674367930488d0fc152daafe77b23d5dd11052)

> I disagree -- this does not apply to the bulk of what the shim strips: `-O`, `-m{arch,cpu,tune}`, `-W` and friends. There are some flags for which it does apply: for those flags, I would also argue in favour of no longer stripping them if they are only necessary on systems that are far enough outside of the systems we support (e.g. 32-bit systems).

If the argument's about trusting upstream's choice of `-m64` then that argument does apply to most flags.

If the argument's about the flag being too "old" or "unnecessary", I still don't see a massive benefit.

Pros:

* A few less characters.
* ???

Cons:

* Can break 32-bit support in some cases. (Though I agree this will be somewhat rare.)
* Can break arm64 support in GCC on Linux. (This will be less rare, particularly given the compiler differences between Clang and GCC.)

**Comment by carlocab** [comment]
Ok, fair enough. You've persuaded me.

**Comment by MikeMcQuaid** [comment]
> Ok, fair enough. You've persuaded me.

Love to see this. @carlocab and @Bo98 you are both great ❤️

**Pull request closed without merging**
