### PR TITLE
dev-cmd/contributions: CSV output of queried repos; shorter sentence

### PR DESCRIPTION
**Pull request by issyl0**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

- Part of https://github.com/Homebrew/brew/issues/13642.
- This gives users of this command a `--csv` option to pass to... you guessed it, generate a CSV that's `pbcopy`able elsewhere, for more granular breakdowns of where a person contributed.
- Inspiration was taken from the mockup in https://github.com/Homebrew/brew/issues/13642#issuecomment-1254535251 but without the extra dependency of the TerminalTable gem.
- Always print a condensed "total contributions" sentence.

Output:

```
$ brew contributions issyl0
The user issyl0 has made 1201 contributions in all time.

$ brew contributions issyl0 --csv
user,repo,commits,coauthorships,signoffs
issyl0,brew,331,13,0
issyl0,core,473,24,326
issyl0,cask,4,0,0
issyl0,aliases,0,0,0
issyl0,autoupdate,1,0,0
issyl0,bundle,14,2,0
issyl0,command-not-found,1,0,0
issyl0,test-bot,3,0,0
issyl0,services,9,0,0
issyl0,cask-drivers,0,0,0
issyl0,cask-fonts,0,0,0
issyl0,cask-versions,0,0,0
```

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
Nice work! What would you think about having a total column in the CSV? Seem excessive?

While you continue to work on this: let me know how/where/if you'd like feedback to make this be the single source of truth I can use to check maintainer contributions.

**Comment by issyl0** [comment]
> Nice work!

😍

> What would you think about having a total column in the CSV? Seem excessive?

Done.

> While you continue to work on this: let me know how/where/if you'd like feedback to make this be the single source of truth I can use to check maintainer contributions.

Yes please!

**Comment by MikeMcQuaid** [comment]
> > While you continue to work on this: let me know how/where/if you'd like feedback to make this be the single source of truth I can use to check maintainer contributions.
> 
> Yes please!

@issyl0 Some non-exclusive ideas:
- allow me to output for all maintainers (we've got some code to scrape these from the README)
- order the maintainers based on their total contributions
- allow filtering to just the core repos (brew, homebrew-core, homebrew-cask) with `--repositories=primary` or something
- include PR approvals
- allow ranking against all contributors in a repository
- count commit authors/commit committers separately
- if not already done: include merge commits for the person who did the merge

Some of this may already be done/possible!

**Comment by issyl0** [comment]
Thanks @MikeMcQuaid! I linked that comment to the "enhancements" issue so it doesn't get lost. I would like to work on some of those!

**Pull request merged**
