### PR TITLE
Fix `Tty.gray`.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Fixes `undefined method 'Tty.gray'`.

Sorry, this was overlooked in https://github.com/Homebrew/brew/pull/823.

--

Fixes https://github.com/Homebrew/brew/issues/1209.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Thanks Markus

**Comment by reitermarkus** [comment]
@ilovezfs, feel free to merge this once CI passes.

**Comment by ilovezfs** [comment]
@reitermarkus indeed. I used the "prepare for shutdown" in Jenkins to clear a path for it so that it went to the top of the queue.

**Comment by ilovezfs** [comment]
Merged! Thanks again, Markus

**Pull request merged**
