### PR TITLE
cleaner: rewrite node shebangs

### PR DESCRIPTION
**Pull request by branchvincent**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

---

Fixes https://github.com/Homebrew/homebrew-core/issues/176257
Closes #17539

This rewrites `node` shebangs during cleanup, as we do for `perl`

```console
$ brew install -s typescript && head -1 $(which tsc)
#!/opt/homebrew/opt/node/bin/node
```

Not sure if we need tests here? `rewrite_shebangs` doesn't have any yet, happy to try to add some

### CODE REVIEW

**Review by Bo98 — APPROVED** [review]
Cautiously approve but this will affect a ton of formulae so maybe worth holding until after the next Monday release (already got a lot of other big changes on `master` that's taken a while to stabilise).

We already have at least one formula that actually tries to undo all the Perl stuff here and that's not a very good sign as `Cleaner` should never break a formula: https://github.com/Homebrew/homebrew-core/commit/b551b404200121c3e766559112bf5d662b25113c. There is significantly less Perl formulae than Node formulae.

Ideally we'd have some way to roll this out more gradually.

**Comment by MikeMcQuaid** [comment]
> Cautiously approve but this will affect a ton of formulae so maybe worth holding until after the next Monday release (already got a lot of other big changes on `master` that's taken a while to stabilise).

Agreed 👍🏻

**Review by MikeMcQuaid — APPROVED** [review]
Approving but marking as draft until next release.

**Comment by branchvincent** [comment]
how do we feel about merging this now? I'm rebuilding node formulae for https://github.com/Homebrew/brew/pull/17867 and having this would help us catch any potential issues quickly

**Comment by Bo98** [comment]
There will likely be a follow up release tonight with https://github.com/Homebrew/brew/pull/17902 (if approved, else tomorrow).

**Comment by MikeMcQuaid** [comment]
Thanks @branchvincent, good to go now.

**Pull request merged**
