### PR TITLE
Extend the `livecheck` DSL to work for resources

### PR DESCRIPTION
**Pull request by mohammadzainabbas**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

This PR extends the `livecheck` DSL to work for resources as mentioned [here](https://github.com/Homebrew/gsoc/issues/49#issuecomment-1040520006).

---

As suggested by @nandahkrishna, I have verified `livecheck` DSL inside resource block by updating few resource blocks locally.

_For instance_: inside `Library/Taps/homebrew/homebrew-core/Formula/airshare.rb`, add the `livecheck` block inside the resource `aiohttp` like mentioned below:

```ruby
...
  resource "aiohttp" do
    url "https://files.pythonhosted.org/packages/5a/86/5f63de7a202550269a617a5d57859a2961f3396ecd1739a70b92224766bc/aiohttp-3.8.1.tar.gz"
    sha256 "fc5471e1a54de15ef71c1bc6ebe80d4dc681ea600e68bfd1cbce40427f0b7578"
    livecheck do
      url "https://brew.sh/foo-1.0.tar.gz"
      regex(/foo/)
    end
  end
...
```

and from interactive ruby-shell (`brew irb`), run and check the following outputs:

```ruby
:airshare.f.resources[0].livecheck.class
:airshare.f.resources[0].livecheck.url
:airshare.f.resources[0].livecheck.regex
```

and it works as expected.

```
=> Livecheck
=> "https://brew.sh/foo-1.0.tar.gz"
=> /foo/
```

---

Kindly, do let me know if I miss something or any further improvement that we can do here.

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
Makes sense to me! Nice work @mohammadzainabbas! Will get @nandahkrishna to 👍🏻 before we 🚢 this.

**Review by samford — COMMENTED** [review]
These `Resource` changes are what I was expecting to see here (i.e., they're in line with how we handle `livecheck` blocks in `Formula`). I didn't have any issues when I tested this manually by adding a `livecheck` block to a `resource` in a formula, loading the formula in `brew irb`, and calling `#livecheck` on the related resource object 👍

I've added some suggestions to the tests but I've only taken a quick glance at this. I'm running out the door at the moment but I'll take another pass at this when I'm available again this evening (EDT).

**Review by nandahkrishna — COMMENTED** [review]
Apologies for the late comment, but these changes seem fine to me (as we discussed in our meeting yesterday).

I've just taken a quick look at this and will get back to it later today, but apart from Sam's suggestions there's just one other trivial change I'd include in this PR:

The documentation and the `@formula_or_cask` variable name in `livecheck.rb` could be updated to reflect that `livecheck` would soon work for resources too.

https://github.com/Homebrew/brew/blob/17a7e71d909de4d09bc2cb479b1ccf975648fbd2/Library/Homebrew/livecheck.rb#L4
https://github.com/Homebrew/brew/blob/17a7e71d909de4d09bc2cb479b1ccf975648fbd2/Library/Homebrew/livecheck.rb#L14

In this case, we might want to use something like `package_or_resource` instead of `formula_or_cask`:
https://github.com/Homebrew/brew/blob/17a7e71d909de4d09bc2cb479b1ccf975648fbd2/Library/Homebrew/livecheck.rb#L20

**Comment by mohammadzainabbas** [comment]
Thank you everyone for the valuable feedback. I have updated tests and relevant documentation (as suggested by @samford and @nandahkrishna). Do take a look and let me know if any changes are required.

**Review by nandahkrishna — APPROVED** [review]
This looks good to me. I'll wait before merging to get some more feedback from others.

Thanks @mohammadzainabbas for your work on this! 🍻

**Review by samford — APPROVED** [review]
I noticed some issues in the test resource that I should have caught the first time around but overlooked because I was short on time. Since this is otherwise ready to merge, I simply pushed a commit to bring the values in line instead of creating multiple suggestions again. This should be good to merge once CI finishes (and passes).

**Review by Rylan12 — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Great work @mohammadzainabbas 🎉

**Pull request merged**
