### PR TITLE
bump-formula-pr: use livecheck to determine new version

### PR DESCRIPTION
**Pull request by SeekingMeaning**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?
- [x] Have you successfully run `brew man` locally and committed any changes?

-----

This allows for `brew bump-formula-pr <formula>` without any additional arguments

I also did a bit of general cleanup of `bump-formula-pr.rb`:

- Deleted `requested_spec` variable since its value is always `:stable`
- Deleted `hash_type` variable since its value is always `:sha256` (if the formula has a checksum)

### CODE REVIEW

**Comment by reitermarkus** [comment]
I think it would make more sense the other way around, i.e. call `bump-(cask|formula)-pr` automatically during `brew livecheck`.

**Comment by MikeMcQuaid** [comment]
> I think it would make more sense the other way around, i.e. call `bump-(cask|formula)-pr` automatically during `brew livecheck`.

I actually think neither should call the other. `brew bump` was created this summer as the beginnings of a tool that (already) checks what both do. I think it would be the perfect place for a "mass bumps based on livecheck/repology output" tool 👍🏻

**Comment by SeekingMeaning** [comment]
I'll try to look into `brew bump`—if I remember right, it's kinda slow/resource intensive, right? Perhaps we should add a flag to make Repology optional and then use Livecheck by default since it is more reliable

**Comment by MikeMcQuaid** [comment]
> I'll try to look into `brew bump`—if I remember right, it's kinda slow/resource intensive, right?

Only to run on everything (because it does a lot of network requests).

> Perhaps we should add a flag to make Repology optional and then use Livecheck by default since it is more reliable

If there's data to support that: fine with me.

**Comment by samford** [comment]
> I think it would make more sense the other way around, i.e. call `bump-(cask|formula)-pr` automatically during `brew livecheck`.

This has come up several times before and I've always asserted that livecheck should be separate from tools that use its data. Other commands/tools are free to consume livecheck's data but `brew livecheck` should only focus on identifying version information.

There are times where we can make small modifications to the data that livecheck captures (and surfaces in its output) to support other use cases but livecheck shouldn't be modified to do unrelated tasks (e.g., creating version bump PRs, checking open PRs, etc.).

---

> I'll try to look into `brew bump`—if I remember right, it's kinda slow/resource intensive, right?

@SeekingMeaning One reason `brew bump` is slow is because it obtains data from livecheck by running `brew livecheck` and parsing the output (see: [`utils/livecheck_formula.rb`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/livecheck_formula.rb)). This means the user has to pay the cost of starting up `brew` every time livecheck is used in `brew bump` (and this is evident if you watch a graph of CPU usage while running it).

Using methods from `livecheck/livecheck.rb` and consuming livecheck's data directly would allow us to avoid this and also to get rid of `utils/livecheck_formula.rb` (which isn't necessary on a technical level). At the moment `brew bump` is naively parsing livecheck's standard output (not even using the JSON output), so receiving livecheck's data directly would be an improvement.

This bothered me when I discovered it awhile back and I planned to eventually rework `brew bump` to address this issue. I won't have time anytime soon (I'm quite busy with livecheck), so feel free to work on it in the interim time if you're planning to dig into `bump`. Last I checked, there are plenty of other areas where `bump` can be improved but this is the most valuable issue to address at the moment.

We may need some internal changes in livecheck to support this use case, so I'll try to look into that today.

**Comment by MikeMcQuaid** [comment]
> This bothered me when I discovered it awhile back and I planned to eventually rework `brew bump` to address this issue. I won't have time anytime soon (I'm quite busy with livecheck), so feel free to work on it in the interim time if you're planning to dig into `bump`. Last I checked, there are plenty of other areas where `bump` can be improved but this is the most valuable issue to address at the moment.

Sounds like a great idea 👍🏻.

@samford would you be open even a minimal `help wanted` issue for this?

**Comment by nandahkrishna** [comment]
I'm currently working on a PR that would make `brew bump` use methods from the `Livecheck` module directly, rather than parse the command output. Should be out soon.

**Pull request closed without merging**
