### PR TITLE
Update invalid-depends-on-macos-conflicting-forms.rb

### PR DESCRIPTION
**Pull request by robertleeblairjr**
Fix for style check error.

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> Fix for style check error.

Where are you seeing this failure?

**Comment by robertleeblairjr** [comment]
> > Fix for style check error.
> 
> Where are you seeing this failure?

Attached a screenshot from Terminal. These three are the only files which had these errors. If you compare to others, they use single quotes and don't contain the comment.
Screen Shot 2020-06-27 at 11 02 00 AM

**Comment by Rylan12** [comment]
Looks like it's a RuboCop issue here: https://github.com/Homebrew/brew/blob/59f622d4baf0b417ccba5b69f4aa3bfeddde902e/Library/Homebrew/rubocops/cask/homepage_matches_url.rb#L135-L151

`extract_url` isn't handling the `stanza` correctly I think.

I'll look into it a little more soon.

**Comment by issyl0** [comment]
Thanks for the clarification, @robertleeblairjr!

My original thought when seeing the `brew cask style` command was that the test fixtures shouldn't be included, but that appears to be [a designed feature](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/cmd/style.rb#L60). So maybe this is fine?

**Comment by Rylan12** [comment]
@MikeMcQuaid this PR (as well as #7842 and #7843) reverts some of the formatting changes you made in #7716.

The specific file diffs are:
- [`Library/Homebrew/test/support/fixtures/cask/Casks/invalid/invalid-depends-on-macos-conflicting-forms.rb`](https://github.com/Homebrew/brew/pull/7716/files?file-filters%5B%5D=.rb#diff-b92802b6718516c1cc970719164c622d)
- [`Library/Homebrew/test/support/fixtures/cask/Casks/with-depends-on-macos-array.rb`](https://github.com/Homebrew/brew/pull/7716/files?file-filters%5B%5D=.rb#diff-cb7e3d26f4ff90218539f1c891d70519)
- [`Library/Homebrew/test/support/fixtures/cask/Casks/with-depends-on-macos-comparison.rb`](https://github.com/Homebrew/brew/pull/7716/files?file-filters%5B%5D=.rb#diff-0905604906a1b238d41d51518b9e8311)

Can you elaborate on the changes you made so we don't revert any necessary changes?

**Comment by robertleeblairjr** [comment]
YW @issyl0 I don't know enough about rubocop to speculate more than what the error messages gave and comparing to other cask stanzas. Since the couple of others used single quotes and these had double, then I thought maybe it was change with the latest version enforcing semantics.

**Comment by Rylan12** [comment]
@robertleeblairjr Sorry, I didn't explain my thoughts well in my previous comment.

I think your changes are correct. RuboCop requires double quotes string in homebrew-core but requires single-quoted strings for Casks, including the files you have made changes for. (I didn't realize this at first which was why I thought the problem was something else...)

I looked at the history of the files to see why this wasn't an issue before. In #7716, the files were changed from the single-quoted version to the current (double-quoted) version. Before we revert them back by accepting your changes, I just want to make sure that we aren't undoing any important changes that were made in #7716.

Hopefully, that makes sense.

**Comment by robertleeblairjr** [comment]
Thanks to everyone who's been so quick to look at this issue and to those that contributes so much of their valuable time to the Homebrew project. You're appreciated more than you may realize. Have a great day!

**Comment by MikeMcQuaid** [comment]
Thanks all and @robertleeblairjr. 

@robertleeblairjr Would you be able to roll the other PRs into this one? It's easier to discuss/merge them all together.

> Can you elaborate on the changes you made so we don't revert any necessary changes?

Yup. If you run `rubocop --auto-correct` on those files (which my editor did when I had to edit them for other reasons) then it will change these back to the Homebrew style.

I think what I'd like to see this PR to (in addition and I and others can help with this):

- Fix the `rubocop` rules for these files (which may involve moving them around on disk) so that `rubocop --auto-correct` styles them appropriately
- Add `brew cask style` to the GitHub Actions CI configuration for this repository (so we don't break casks style in future).

Ideally what I'd love @Homebrew/cask to come to some agreement with us on:

- Unify the Homebrew/brew, Homebrew/homebrew-core and Homebrew/homebrew-cask style more. Now that we are one project with a single repo sharing our package manager code and this style can be auto changed by RuboCop I don't think it's sensible to have such large differences (all single quotes vs. all double quotes) between the package manager, formulae and casks.

**Comment by vitorgalvao** [comment]
> Ideally what I'd love @Homebrew/cask to come to some agreement with us on

I’m on board with that.

> all single quotes vs. all double quotes

I’m a big fan of “single quotes unless interpolation is needed”, because it’s practical in addition to stylistic. We rely on interpolation *a lot* (huge net win, it’s why we can have the bot auto-merge with confidence) and looking at the quotes makes (my) review process faster and more accurate.

Every other rule I could probably take or leave.

**Comment by MikeMcQuaid** [comment]
> I’m a big fan of “single quotes unless interpolation is needed”, because it’s practical in addition to stylistic. We rely on interpolation _a lot_ (huge net win, it’s why we can have the bot auto-merge with confidence) and looking at the quotes makes (my) review process faster and more accurate.

Can you explain why "double quotes all the time" would make your life harder? Similarly: do you think it outweighs the benefit of having consistency otherwise between all repos? 

That said: I'm not wanting to die on this hill so if this is literally the only deviation: I'm fine with that and it's easily codifiable 👍

**Comment by vitorgalvao** [comment]
> Can you explain why "double quotes all the time" would make your life harder?

The way I’d put it is that “single quotes by default makes my life easier”, because it helps me spot mistakes and places for improvement. In practical terms, some stanzas frequently need interpolation (`url`) while other seldom do (`app`). Quick example:

```ruby
version '83.0'
sha256 'ff2d854c62ce3c9527970404550c66d605fe37a407694b811c5d4c040fdf3b16'

url 'https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/MicrosoftEdge-83.0.478.56.pkg'
```

By looking at the quotes of `url`, I can instantly determine that either:

1. There might be a version in there somewhere that isn’t being interpolated. In this case there is, and will even improve `version` by making it more specific.
2. The URL is unversioned, meaning `version` needs to be `:latest` and `shasum :no_check`.

I use these clues to varying degrees in different stanzas. It helps keep the whole cask in my head while making broad fixes.

> Similarly: do you think it outweighs the benefit of having consistency otherwise between all repos?

Not at all.

> That said: I'm not wanting to die on this hill

We’re also in agreement there.

> if this is literally the only deviation

Yep.

> I'm fine with that and it's easily codifiable

I think the `--fix` flag converts double quotes to single quotes when there’s no interpolation (don’t hold me to that, I’d have to check).

**Comment by Rylan12** [comment]
> Yup. If you run `rubocop --auto-correct` on those files (which my editor did when I had to edit them for other reasons) then it will change these back to the Homebrew style.

The lines requiring double quotes are in [`.rubocop.yml`](https://github.com/Homebrew/brew/blob/master/Library/.rubocop.yml). My guess is that your editor's rubocop configuration is set from this file. `brew cask style`, however, using [`.rubocop_cask.yml`](https://github.com/Homebrew/brew/blob/master/Library/.rubocop_cask.yml). My guess is that your editor is applying the normal rules (`.rubocop.yml`) everywhere even though some files should be using `.rubocop_cask.yml` instead.

Note that there is a shared rubocop config file ([`.rubocop_shared.yml`](https://github.com/Homebrew/brew/blob/master/Library/.rubocop_shared.yml)) that would be referenced regardless.

> - Fix the rubocop rules for these files (which may involve moving them around on disk) so that rubocop --auto-correct styles them appropriately

I don't think there's really anything to fix. Unless I'm misunderstanding what you're saying `rubocop` is working fine, the issue is that your editor doesn't know which files to check with which rubocop config.

> - Add brew cask style to the GitHub Actions CI configuration for this repository (so we don't break casks style in future).

Totally agree (was going to suggest it in this PR once the issue was clarified)

> I think the --fix flag converts double quotes to single quotes when there’s no interpolation (don’t hold me to that, I’d have to check).

Yes, it does, when you run with `brew cask style` (using `.rubocop_cask.yml`). Otherwise, it would change to double-quotes.

On the surface, I, personally, would rather see a unified rule here, but I understand @vitorgalvao's points about practicality in addition to style and differ to him as I don't work with cask at all.

What's more concerning to me is that some files in Homebrew/brew conform the the "normal" style and some to the "cask" style. Having two conflicting styles in the same project generally is a red flag for me.

That being said, maybe adding the `brew cask style` check in the CI is enough, as it will alert when there are style changes like these.

**Comment by MikeMcQuaid** [comment]
> My guess is that your editor is applying the normal rules (`.rubocop.yml`) everywhere even though some files should be using `.rubocop_cask.yml` instead.

It's not an issue with my editor but the fact that `.rubocop_cask.yml` isn't being used for these files.



> I don't think there's really anything to fix. Unless I'm misunderstanding what you're saying `rubocop` is working fine, the issue is that your editor doesn't know which files to check with which rubocop config.

There is. The `rubocop` configuration is not correct as these files have not been setup to be styled correctly with the current configuration.

**Comment by Rylan12** [comment]
Maybe we have a different view of what is "correct". I'm considering `brew cask style` and `brew style` to be "correct".

When run with no arguments passed, `brew cask style` runs its checks on the files in `Library/Homebrew/test/support/fixtures/cask/Casks/` and `Library/Homebrew/test/support/fixtures/third-party/Casks/`. This makes sense to me because these files are meant to simulate actual Casks for testing purposes.

I guess I just don't understand what exactly isn't configured correctly.

**Comment by MikeMcQuaid** [comment]
> Maybe we have a different view of what is "correct". I'm considering `brew cask style` and `brew style` to be "correct".

Yup. These are not the exclusive interface to style checks. The style checks are designed such that running `rubocop` on a given file (which is what an editor will do) should use the right configuration file and make the right changes. This is not the case here.

**Comment by MikeMcQuaid** [comment]
> Edit: do you mean that `brew style` should check those files using `.rubocop_cask.yml`? That way there is one command for all style checks on the main repo?

Either that or that they should be excluded altogether from style checks here.

CC @reitermarkus for any last thoughts before I go mass-changing everything except single quotes to match 😉.

**Comment by robertleeblairjr** [comment]
@MikeMcQuaid I would if I was sure of how and what you mean by "roll it into one". I checked some settings on GitHub for this PR and the others to determine if they have a merge or squash function and I'm not seeing it. My 'git foo' is definitely amateur. But, I can easily follow instructions if you have a reference. I'd love to know how to do this and the only knowledge I have of it is using a local repo to squash them and then pushing to this repo. Of course, feel free to merge the commits, if you have the ability.

**Comment by MikeMcQuaid** [comment]
> @MikeMcQuaid I would if I was sure of how and what you mean by "roll it into one". I checked some settings on GitHub for this PR and the others to determine if they have a merge or squash function and I'm not seeing it. My 'git foo' is definitely amateur.

If you can add (`git cherry-pick` the commits from the other branches into this branch, push and close the other PRs: that'd be great. We don't need squashed commits in this repo! Thanks.

**Comment by Rylan12** [comment]
> Yup. These are not the exclusive interface to style checks. The style checks are designed such that running `rubocop` on a given file (which is what an editor will do) should use the right configuration file and make the right changes. This is not the case here.

Okay, this makes sense. Maybe I just don't have my editor/`rubocop` set up correctly. However, it seems to me that the solution you're proposing won't solve everything. Combining styles is great, but if single-quotes are still used in some of the files, the same issue (where an editor automatically makes inconsistent style fixes to certain files) will happen.

I still don't think I understand exactly what you're trying to say/do, so I'll hold off until you make/propose changes, and then I'll take a look to try to understand.

**Comment by MikeMcQuaid** [comment]
> Combining styles is great, but if single-quotes are still used in some of the files, the same issue (where an editor automatically makes inconsistent style fixes to certain files) will happen.

Not if `rubocop` is configured appropriately.

> I still don't think I understand exactly what you're trying to say/do, so I'll hold off until you make/propose changes, and then I'll take a look to try to understand.

Thanks 👍

**Comment by MikeMcQuaid** [comment]
Closing in favour of https://github.com/Homebrew/brew/pull/7867. Thanks anyway!

**Pull request closed without merging**
