### PR TITLE
Mute trash sound.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Closes https://github.com/Homebrew/brew/issues/2974.

### CODE REVIEW

**Comment by DomT4** [comment]
Nice. Seems to work as expected locally 👍 🙇.

**Comment by ilovezfs** [comment]
I think a more straightforward solution here would be to remove the test.

**Comment by MikeMcQuaid** [comment]
Or mock the test sufficiently.

**Comment by MikeMcQuaid** [comment]
@reitermarkus Thoughts on mocking instead or making this an additional test flag we only pass in CI/`brew test-bot`?

**Comment by MikeMcQuaid** [comment]
@reitermarkus What's the status of this?

**Pull request closed without merging**
