### PR TITLE
dependency: add `until` bound to `uses_from_macos`

### PR DESCRIPTION
**Pull request by cho-m**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

I think we were discussing something like this back in Ventura due to missing `texinfo` and `groff`.

Interpreting `until` as inclusive of bound (Probably need to document whether inclusive/exclusive as can be ambiguous).

Probably need some tests/docs and will need to check if anything else is needed to support this.

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

**Comment by Bo98** [comment]
Except for build-time dependencies, this really doesn't work very well for when you upgrade macOS.

And in the case of build-time dependencies it's usually easier to depend it for all macOS as we don't really gain much from doing otherwise.

**Comment by cho-m** [comment]
> And in the case of build-time dependencies it's usually easier to depend it for all macOS as we don't really gain much from doing otherwise.

I guess this is also an option. Currently, we have been avoiding an increase in extra dependencies on older macOS (perhaps given that these are likely to end up outside our support and require source-builds).

---

> Do you have examples of where this would be used?

Mainly to replace multiple occurrences of:
```rb
  on_system :linux, macos: :ventura_or_newer do
    depends_on "texinfo" => :build
  end
```

**Comment by Bo98** [comment]
`texinfo` is light. `groff` is very heavy however so so I'm more sympathetic for that but in a lot of cases of `groff` I wonder if we could either switch to `man2html` (or its fork that FreeBSD uses https://invisible-island.net/scripts/man2html.html) or simply disable some of this PDF/HTML doc generation in some cases. There's also `mandoc` which shipped with macOS.

For example the `ledger` current release: we could use `man2html`, apply https://github.com/ledger/ledger/commit/14b90d8d952b40e0a474223e7f74a1e6505d5450 which allows macOS `mandoc`, or use `-DBUILD_WEB_DOCS=OFF`.

**Comment by Bo98** [comment]
I do recall some pain during Sonoma bottling due to `groff`'s dependency tree so there is benefits to be had on newer macOS too by avoiding it.

**Comment by Bo98** [comment]
Tried a few:

* https://github.com/Homebrew/homebrew-core/pull/158578
* https://github.com/Homebrew/homebrew-core/pull/158581
* https://github.com/Homebrew/homebrew-core/pull/158586
* https://github.com/Homebrew/homebrew-core/pull/158590
* https://github.com/Homebrew/homebrew-core/pull/158593
* https://github.com/Homebrew/homebrew-core/pull/158596
* https://github.com/Homebrew/homebrew-core/pull/158598

**Comment by cho-m** [comment]
I'm fine with handling `groff` and `texinfo` in the above manner. I don't think there are any other formulae currently impacted by Apple's removals. Can revisit if situation changes in future.

**Comment by MikeMcQuaid** [comment]
> Currently, we have been avoiding an increase in extra dependencies on older macOS (perhaps given that these are likely to end up outside our support and require source-builds).

Personally: I don't think it's worth the effort for stuff like this that adds effort for maintainers to try and make things better on already unsupported configurations.

**Pull request closed without merging**
