### PR TITLE
Remove usages of `Homebrew.args.verbose?` and `Homebrew.args.debug?`.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Remove some more usages of `Homebrew.args` for global flags.

### CODE REVIEW

**Comment by joshbranham** [comment]
Was this meant to remove the ability to use `downloader.shutup!` on a `GitHubGitDownloadStrategy`?

**Comment by MikeMcQuaid** [comment]
@joshbranham No. CC @reitermarkus FYI

**Comment by reitermarkus** [comment]
@joshbranham, can you point me to where you are using this?

**Comment by li-shahn** [comment]
Wanted to add a +1 to @joshbranham's comment, this broke my use of `downloader.shutup!` in `CurlDownloadStrategy`. I can't link to where I'm using it as it's an external command on an in-house Tap, but my tool fetches potentially dozens of items in one go and it's handy to be able to suppress the progress bar (etc.) on all those downloads; I have my own progress bar that shows the total progress for all [xxx] download/install operations.

**Comment by joshbranham** [comment]
We were essentially doing something like this:

```
def most_recent_version
    Formula.cache[:most_recent_version] = begin
      downloader.shutup! unless Homebrew.args.verbose?
      downloader.fetch
....
```

Which would hide the few checkouts occurring for the lookup

**Pull request merged**
