### PR TITLE
livecheck: Add `Json` strategy

### LINKED ISSUE #13992: JSON support as a livecheck strategy
### Provide a detailed description of the proposed feature

- Along with HTML, XHTML, XML and RSS as mentioned in [Fr] Xpath Support as strategy #13991 
- An option to parse JSON data.

### What is the motivation for the feature?

- Some services and websites offer version/changelog/release information as JSON
- This could be a hosted file or an API 
- Used instead of regex or additional to regex
- I see this being most useful for livechecks

### How will the feature be relevant to at least 90% of Homebrew users?

easier to update formula and casks

### What alternatives to the feature have been considered?

scripts

### PR DESCRIPTION
**Pull request by samford**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

This adds a generic `Json` strategy to livecheck that requires a `strategy` block to operate. This is primarily intended as a replacement for existing `strategy` blocks in formulae/casks that use `JSON#parse`, as it allows us to internalize/standardize that boilerplate while improving error-handling.

Additionally, future strategies that parse JSON data can use the `Json#find_versions` method instead of having to reinvent the wheel (similar to how we currently have a number of strategies that leverage `PageMatch#find_versions`).

Resolves #13992, as we reduced the scope of that issue to simply deal with adding a `Json` strategy (`Xml` will be added in a separate PR and we do not intend to add strategies for HTML/XHTML, due to our `nokogiri` policy).

-----

## Examples

When we simply need to grab the value of a field from the parsed JSON, it's as simple as:

```ruby
livecheck do
  url "https://www.example.com/example.json"
  strategy :json |json|
     json["version"]
  end
end
```

We may be able to simplify that scenario further in the future after I've added `options` support (forthcoming, after I work through these strategy additions).

In a more complex scenario, we may end up with something like this:

```ruby
livecheck do
  url "https://www.example.com/example.json"
  regex(/^v?(\d+(?:\.\d+)+)$/i)
  strategy :json do |json, regex|
    json["versions"].select { |item| item["version"]&.match?(regex) }
                    .map { |item| item["version"][regex, 1] }
  end
end
```

This approach tries to strike a balance between safety/error-avoidance and simplicity. This approach would gracefully handle the situation where one of these objects doesn't provide a `version` field but it would still error if there isn't a `versions` field. it's possible to structure this such that it will simply return `nil` if we don't have all the information we need in the expected structure but it felt a bit like overkill.

At the other end of the spectrum, it's possible to do something like `json["versions"].map { |item| item["version"][regex, 1] }` but it would fail with an ```undefined method `[]' for nil:NilClass``` error if any of the objects omits a `version` field. Upstream sources aren't always the best at providing highly-standardized data, so I prefer the aforementioned approach (i.e., any breakages require human intervention to fix and we don't want to spend our limited time dealing with avoidable errors).

-----

## Notes

One thing to note is that I set up `Json#find_versions` to also support `provided_content` like the `PageMatch` strategy. This is something that I will be rolling out to all the existing strategies in a later PR. It allows us to improve code coverage in the near-term but it's intended as part of a future caching implementation (so we don't have to re-fetch content for duplicate URLs in a run). [That should be the last bit of foundation required for caching and after that I can create a PR for a proper implementation.]

I have the vast majority of that work done (i.e., updating the strategies and related tests) and I think it just needs some finishing touches before I create a PR. That said, there are a few other PRs that I have to work through first but this is also in the pipeline.

### CODE REVIEW

**Comment by reitermarkus** [comment]
Does this do `json["version"]` by default, or is a block always needed?

**Comment by samford** [comment]
> Does this do `json["version"]` by default, or is a block always needed?

From what I've seen, JSON data is often too variable (across formulae/casks) to implement a reasonable strategy default, so it always requires a `strategy` block (though this is no worse than the status quo).

After I'm done with this and the XML strategy, I'll be creating a PR for the `options` feature that I've been talking about for ages (it's done but I'm working through these strategy PRs first). That feature basically lays the groundwork to make it possible to control the user agent, set curl args, make POST requests, etc. in a `livecheck` block (blockers for a small number of formulae/casks). One other thing that I want to accomplish with that feature is to be able to pass arguments to strategies to control the behavior in some situations.

Once that's possible, we could modify the `Json` strategy to add support for a terse syntax to handle this simple scenario (maybe something like, `strategy :json, field: "version"`). This is something that I've thought about and I considered explaining this particular point in the PR description but left it out for the sake of brevity. I kind of like the idea but it's something we can revisit after `options` are available.

**Comment by reitermarkus** [comment]
> From what I've seen, JSON data is often too variable

Yeah, it's definitely variable so may not be worth having a default. About 17/90 casks would use this default.

**Review by MikeMcQuaid — APPROVED** [review]
Looks great, nice work @samford!

**Pull request merged**
