### PR TITLE
python_virtualenv_constants: upgrade virtualenv to 20.0.26

### PR DESCRIPTION
**Pull request by lembacon**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Thanks @lembacon!

**Comment by Bo98** [comment]
While previous versions of `virtualenv` didn't have any dependencies, virtualenv 20.x does so this currently breaks CI on Catalina:

```
==> python3.8 -s /private/tmp/snakemake--homebrew-virtualenv-20200708-40521-1n4amgf/target/bin/virtualenv -p python3.8 /usr/local/Cellar/snakemake/5.20.0/libexec
Traceback (most recent call last):
  File "/private/tmp/snakemake--homebrew-virtualenv-20200708-40521-1n4amgf/target/bin/virtualenv", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3255, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3238, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3267, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'six<2,>=1.9.0' distribution was not found and is required by virtualenv
```

**Comment by vladimyr** [comment]
> While previous versions of `virtualenv` didn't have any dependencies, virtualenv 20.x does so this currently breaks CI on Catalina

It breaks install from source for any python formula using virtualenv ⚠️
Following dependencies are missing: https://github.com/pypa/virtualenv/blob/20.0.26/setup.cfg#L41-L48
```ini
install_requires =
    appdirs>=1.4.3,<2
    distlib>=0.3.1,<1
    filelock>=3.0.0,<4
    six>=1.9.0,<2   # keep it >=1.9.0 as it may cause problems on LTS platforms
    importlib-metadata>=0.12,<2;python_version<"3.8"
    importlib-resources>=1.0;python_version<"3.7"
    pathlib2>=2.3.3,<3;python_version < '3.4' and sys.platform != 'win32'
```

IMHO this should be reverted as soon as possible until the proper upgrade is made.

**Comment by MikeMcQuaid** [comment]
Thanks @Bo98 and @vladimyr.

@vladimyr Check your email! I replied to your one and haven't seen a reply yet.

**Pull request merged**
