### PR TITLE
cask: activate GPG verification on install

### PR DESCRIPTION
**Pull request by jawshooah**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

---

Following up on https://github.com/caskroom/homebrew-cask/pull/16090.

@Homebrew/cask @fanquake @ndr-qef

### CODE REVIEW

**Comment by zmwangx** [comment]
`Library/Homebrew/cask/test/support/binaries/gnupg-2.1.1.tar.bz2` and `Library/Homebrew/cask/test/support/binaries/gnupg-2.1.1_tampered.tar.bz2`: please, committing ~5MB files to the repo is not cool.

**Comment by jawshooah** [comment]
Yup, those are left over from when we had a bunch of similar sized fixtures. These commits are over a year old; haven't gotten around to cleaning them up yet. AFK right now, but will add the `do not merge` label when I get a chance.

**Comment by zmwangx** [comment]
Added.

**Comment by MikeMcQuaid** [comment]
@jawshooah Any news on this? If it's too stale might just be worth closing out.

**Comment by jawshooah** [comment]
Sadly no, no news, and likely none to come for a while. I agree we should just close this for now. We can re-open when I have time to clean this up later, or someone else can feel free to pick up where I left off whenever.

**Pull request closed without merging**
