### PR TITLE
Add HOMEBREW_CURL_RETRIES (#6142)

### PR DESCRIPTION
**Pull request by letmaik**
Fixes https://github.com/Homebrew/brew/issues/6142

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by letmaik** [comment]
@MikeMcQuaid Can you have a quick look at this draft PR before I tick off the other boxes and make it a real PR?

**Comment by MikeMcQuaid** [comment]
@letmaik Yup, looks good! Remember to run `brew man`.

**Comment by MikeMcQuaid** [comment]
Thanks so much for your brilliant first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @letmaik!

**Comment by letmaik** [comment]
Thanks! :)
With this variable all the bottle downloads and most (since most (all?) use http) source downloads can be made more robust in CI. The only missing thing now is to do the same for "brew update" which relies on git, and git unfortunately doesn't have a similar retry option as curl does.

**Comment by MikeMcQuaid** [comment]
> With this variable all the bottle downloads and most (since most (all?) use http) source downloads can be made more robust in CI. The only missing thing now is to do the same for "brew update" which relies on git, and git unfortunately doesn't have a similar retry option as curl does.

Good idea!

**Pull request merged**
