### PR TITLE
Convert echo to ohai

### PR DESCRIPTION
**Pull request by nexxai**
Using brew-native text formatting instead of plain old `echo`.

- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [X] Have you successfully run `brew style` with your changes locally?
- [X] Have you successfully run `brew typecheck` with your changes locally?
- [X] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by reitermarkus** [comment]
I don't think this should output to `stdout`, since this can potentially break output for some commands.

**Comment by nexxai** [comment]
It already did though; all this does is changes the formatting from plaintext to the blue arrows and yellow text so it meshes with the rest of the commands that run.

**Comment by carlocab** [comment]
> It already did though

Is this being printed to stdout despite the `>&2` redirection?

**Comment by MikeMcQuaid** [comment]
Passing on this, this is intentionally not printed to `stdout`, sorry.

**Pull request closed without merging**
