### PR TITLE
Move Cask core code to Homebrew

### PR DESCRIPTION
**Pull request by AnastasiaSulyagina**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Moving [Cask](https://github.com/caskroom/homebrew-cask) core code to Homebrew as part of [#14384](https://github.com/caskroom/homebrew-cask/issues/14384).

Change is splitted in 2 commits to be easier to review. Any advice on better splitting or anything else welcome.

cc @MikeMcQuaid @vitorgalvao @jawshooah @adidalal (bring other cask maintainers please)

### CODE REVIEW

**Comment by jawshooah** [comment]
Pinging @caskroom/maintainers for visibility.

**Comment by MikeMcQuaid** [comment]
CC @Homebrew/maintainers as this is a big one.

**Comment by MikeMcQuaid** [comment]
I've opened https://github.com/Homebrew/brew/issues/727 to fix the test failures here as they are in our code making assumptions about Cask code that we need to decide if they are valid.

**Comment by MikeMcQuaid** [comment]
Some of the cask-tests are failing: https://bot.brew.sh/job/Brew%20Pull%20Requests/1302/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/cask_tests/

**Comment by MikeMcQuaid** [comment]
You can probably remove all the "under Ruby 2.1" tests and may need some test fixtures to not assume Caskroom/homebrew-cask is tapped (although we could compromise that and just tap it before the test). It's probably worth doing these in a separate PR before merging this or the respective Cask PR.

**Comment by AnastasiaSulyagina** [comment]
Seems that cask tap's path for test-bot is not `HOMEBREW_LIBRARY.join("Taps", "caskroom", "homebrew-cask")`. Will take a look

**Comment by MikeMcQuaid** [comment]
> Seems that cask tap's path for test-bot is not HOMEBREW_LIBRARY.join("Taps", "caskroom", "homebrew-cask"). Will take a look

@AnastasiaSulyagina on the test-bot: it's not even tapped 😀. This is something we could address at a later point, though.

**Comment by MikeMcQuaid** [comment]
> This is something we could address at a later point, though.

Although let me know which you'd rather do.

**Comment by AnastasiaSulyagina** [comment]
I'd rather tap it before tests. 
Why to address it at later point and not now?

**Comment by MikeMcQuaid** [comment]
> I'd rather tap it before tests. 

:cool: I can open a PR for that.

> Why to address it at later point and not now?

Basically because at some point we're going to need to remove that reliance on having the tap tapped in favour of making tests create the Casks they expect and I figure that doesn't need to necessarily block this PR being merged.

**Comment by AnastasiaSulyagina** [comment]
>  I can open a PR for that.
That would be nice :)

> Basically because at some point we're going to need to remove that reliance on having the tap tapped in favour of making tests create the Casks they expect and I figure that doesn't need to necessarily block this PR being merged.

Thanks, got it.

**Comment by reitermarkus** [comment]
If possible, you might want to merge in the last two commits in https://github.com/caskroom/homebrew-cask/pull/23821. The only thing I'm missing is an elegant way to redefine `Tap::TAP_DIRECTORY` for our tests.

**Comment by MikeMcQuaid** [comment]
@reitermarkus I think you could merge that in for now as there's already conflicts there until there's a 👍 on holding off merging core PRs.

**Comment by reitermarkus** [comment]
Ok, merged the three remaining core PRs. Holding off now until this move is complete.

**Comment by DomT4** [comment]
Do we need stuff like the GitHub templates, CoC & other dotfiles from Cask here? Are they not remaining with the Cask tap?

**Comment by MikeMcQuaid** [comment]
> Do we need stuff like the GitHub templates, CoC & other dotfiles from Cask here? Are they not remaining with the Cask tap?

@DomT4 I'm in favour of moving basically everything for now and then removing them once they are over; it's too hard to review the diff for now.

**Comment by DomT4** [comment]
Cool. That was exactly my thought, that removing the unnecessary text files might make the diff actually reviewable, heh, but whether that's done in pre or post doesn't matter much.

**Comment by AnastasiaSulyagina** [comment]
@jawshooah, are these tests needed? If yes, why should directories be undeletable and how to fix it?
```
rspec ./spec/cask/macos_spec.rb:43 # OS::Mac says the user library directory is undeletable
rspec ./spec/cask/macos_spec.rb:31 # OS::Mac says the home directory is undeletable
```

**Comment by jawshooah** [comment]
Unrelatable directories include system and user directories that should never be included in `uninstall :delete` or `zap :delete`. Those tests ensure that, were a Cask author to mistakenly include, for example, `~/Library` in `uninstall :delete`, we will not actually delete that directory.

**Comment by AnastasiaSulyagina** [comment]
As I understood `/Users/brew/Jenkins/pr-brew/version/el_capitan/home/` is `Dir.home` for test-bot. In `macos.rb` [there is](https://github.com/AnastasiaSulyagina/brew/blob/move-cask/Library/Homebrew/cask/lib/hbc/macos.rb#L239) `~` string which actually should equal `Dir.home`. Am I wrong?

**Comment by reitermarkus** [comment]
This would mean we have need to call `sub(%r{^~(?=(/|$))}, Dir.home)` everywhere we expect to receive a relative path instead of (or in addition to) `expand_path`.

**Comment by AnastasiaSulyagina** [comment]
Hm. I thought that as it never appeared before and appeared now in tests only, I can just replace `~` with `Dir.home` in Undeletables list. If it's unacceptable I'll fix it

**Comment by AnastasiaSulyagina** [comment]
Why can build pass in travis-ci/pr and fail in default?

**Comment by MikeMcQuaid** [comment]
@AnastasiaSulyagina The filesystems may have different permissions.

**Comment by reitermarkus** [comment]
@AnastasiaSulyagina, could you rather cange https://github.com/AnastasiaSulyagina/brew/blob/move-cask/Library/Homebrew/cask/lib/hbc/macos.rb#L364 to                      `.map { |x| Pathname(x.sub(%r{^~(?=(/|$))}, Dir.home)).expand_path }` instead of changing the whole list, to keep it at little more readable?

**Comment by MikeMcQuaid** [comment]
Mentioned to @AnastasiaSulyagina in Slack: https://github.com/Homebrew/brew/blob/b39eba6c5f0f6f1b19e663df52bc72b9d8518886/Library/Homebrew/dev-cmd/test-bot.rb#L942-L943 is the issue; the test-bot overrides the `$HOME` variable to stop things being dumped in `~` and I'm guessing it's not getting expanded consistently as a result.

**Comment by reitermarkus** [comment]
@MikeMcQuaid, might be worth knowing what `File.expand_path` is using internally then to see if we can also override it globally in tests.

**Comment by reitermarkus** [comment]
Ok, seem's like it is using `$HOME` internally as well: https://github.com/ruby/ruby/blob/7a4aea47e281402a178b69b5f90d6ed330122e67/file.c#L3209

**Comment by AnastasiaSulyagina** [comment]
Rebased both PRs, fixed `macos.rb`

**Comment by reitermarkus** [comment]
I might have found the reason why some of the  `undeletable?` tests are still failing.

```
irb> File.identical?('does-not-exist', './does-not-exist')
=> false
irb> File.identical?('exists', './exists')
=> true
```

Seems like `File.identical?` doesn't work on nonexistent paths.

@AnastasiaSulyagina, could you try changing https://github.com/AnastasiaSulyagina/brew/blob/move-cask/Library/Homebrew/cask/lib/hbc/macos.rb#L369-L375 to the following?

```ruby
  def system_dir?(dir)
    SYSTEM_DIRS.include?(Pathname.new(dir).expand_path)
  end

  def undeletable?(dir)
    UNDELETABLE_DIRS.include?(Pathname.new(dir).expand_path)
  end
```

**Comment by AnastasiaSulyagina** [comment]
```
1) Hbc::SystemCommand with a very long STDERR output returns without deadlocking
     Failure/Error: wait(10).for {
       RSpec::Wait::TimeoutError
     # ./spec/cask/system_command_spec.rb:136:in `block (3 levels) in <top (required)>'
```
Is it somehow related to the PR?

**Comment by reitermarkus** [comment]
@AnastasiaSulyagina, could you bump https://github.com/AnastasiaSulyagina/brew/blob/move-cask/Library/Homebrew/cask/spec/cask/system_command_spec.rb#L136 to 15 seconds? I don't think there's actually a deadlock, as this only happens occasionally.

**Comment by reitermarkus** [comment]
Finally! :tada:

**Comment by MikeMcQuaid** [comment]
Merging this and https://github.com/caskroom/homebrew-cask/pull/23852 should follow soon afterwards 🎉. Great work, @AnastasiaSulyagina!

**Pull request merged**
