### PR TITLE
git_spec.rb: use HTTPS for Git remote test

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

It seems more realistic to make tests via HTTPS, because this is how Git is used in most cases anyway.

### CODE REVIEW

**Comment by vszakats** [comment]
Test failure seems unrelated:
```
Failures:
  1) brew home opens the homepage for a given Formula
     Failure/Error:
       expect { brew "home", "testball", "HOMEBREW_BROWSER" => "echo" }
         .to output("#{Formula["testball"].homepage}\n").to_stdout
         .and not_to_output.to_stderr
         .and be_a_success
       expected block to output "\n" to stdout, but output "https://example.com/testball\n"
     # ./test/cmd/home_spec.rb:12:in `block (2 levels) in <top (required)>'
     # ./test/support/helper/spec/shared_context/integration_test.rb:44:in `block (2 levels) in <top (required)>'
     # ./test/spec_helper.rb:96:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.0.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
```

**Comment by vszakats** [comment]
Force pushed for another CI run, this time another unrelated failure:
```
2.00s==> brew audit testbottest --online
Error: 1 problem in 1 formula
testbottest:
  * Incorrect file permissions (664): chmod 644 /home/travis/build/Homebrew/brew/Library/Taps/homebrew/homebrew-core/Formula/testbottest.rb
==> FAILED
brew.bottle.17
```

**Comment by vszakats** [comment]
Strange errors :(

**Comment by JCount** [comment]
Yeah, this is a known issue that is currently being worked on in https://github.com/Homebrew/homebrew-test-bot/pull/120, and should hopefully be fixed soon.

**Comment by vszakats** [comment]
Thanks for the fix! The macOS failure was already reported in #3113 and pending a fix.

**Comment by MikeMcQuaid** [comment]
Thanks for this @vszakats!

**Pull request merged**
