### PR TITLE
pr-pull: streamline mirroring and upload

### PR DESCRIPTION
**Pull request by jonchang**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

* Remove duplicated functionality in `brew pr-pull` and let `mirror` and `pr-upload` handle it instead.
* Fixes a bug where mirrored URLs were being uploaded but not published since `bintray.publish` needs the number of files published to confirm that everything was uploaded correctly. 
* Lets third-party taps use the same mirroring logic for their own Bintray repositories.

### CODE REVIEW

**Comment by srisuk2519** [comment]
เมื่อ อา. 21 มิ.ย. 2563 เวลา 18:36 Dawid Dziurla <notifications@github.com>
เขียนว่า:

**Comment by jonchang** [comment]
We bit this in https://github.com/Homebrew/homebrew-core/pull/56607. Going to merge this pull request once CI passes.

**Comment by jonchang** [comment]
Thanks for the review @dawidd6!

**Comment by MikeMcQuaid** [comment]
@jonchang Nice work!

**Pull request merged**
