### PR TITLE
workflows: run on `macos-13`

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Now that the `macos-13` runner image is available, let's switch to it so that we have the tests run on the latest macOS.

Alternatively, for some of the `tests` workflows, we may consider adding an additional `macos-13` matrix job instead of switching from `macos-12` to it.

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
actionlint failure is due to https://github.com/rhysd/actionlint/issues/296. As for the now-missing required macOS 12 checks: should they be migrated to macOS 13, or should we keep them in the matrices?

**Comment by MikeMcQuaid** [comment]
> As for the now-missing required macOS 12 checks: should they be migrated to macOS 13, or should we keep them in the matrices?

Migrated to 13.

**Review by MikeMcQuaid — APPROVED** [review]
Looks good once 💚

**Comment by carlocab** [comment]
A workaround for the `actionlint` failure would be to add it here:

https://github.com/Homebrew/brew/blob/c343e545c0dbb567ccae8e39130d8251ee28d688/.github/actionlint.yaml#L1-L4

**Comment by carlocab** [comment]
Looks like there are some required tests that still look for macOS 12.

**Review by carlocab — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks @ZhongRuoyu!

**Pull request merged**
