### PR TITLE
brew.1: correct documentation of install --keep-tmp

### PR DESCRIPTION
**Pull request by zmwangx**
Obvious copy/paste failure in acc9a7c.

### CODE REVIEW

**Comment by UniqMartin** [comment]
Thanks for the PR! The change will need to be made in `cmd/install.rb` though (there's a special documentation comment at the top). After you made the change there, please run `brew man` to regenerate the man page and its HTML version, then make sure all three changed files are added to the commit.

**Comment by apjanke** [comment]
Yup; :+1: once converted to fix `cmd/install.rb` too.

**Comment by zmwangx** [comment]
Thanks for the tip. Corrected.

**Comment by UniqMartin** [comment]
Merged. Thank you for this PR and another contribution to Homebrew, @zmwangx! :tada:

**Pull request merged**
