### PR TITLE
uses_from_macos: allow cpio

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
This list is for `provided_by_macos` rather than `shadowed_by_macos`. It could be added to the second list further down.

**Comment by iMichka** [comment]
I changed the formula to `provided_by_macos` in #57574, as this is what I initially wanted to do.

**Comment by Bo98** [comment]
I suppose it's close enough. macOS doesn't ship with GNU cpio - but rather the one from `libarchive`. The functionality is probably just about the same.

**Comment by iMichka** [comment]
I think there may be others in this list which have the same "issue", we did not go into so much detail. The list is more about: can we use it in "uses_from_macos" than "is is exactly the same tool".

**Comment by MikeMcQuaid** [comment]
> I suppose it's close enough. macOS doesn't ship with GNU cpio - but rather the one from `libarchive`. The functionality is probably just about the same.

We should allow `shadowed_by_macos` in this case, instead. I'd rather that our DSL usage is accurate rather than incorrect but allows us to use `uses_from_macos`.

**Comment by iMichka** [comment]
Ok I'll move this back to `shadowed_by_macos` then and move the entry to the second list later today.

**Comment by MikeMcQuaid** [comment]
Thanks ❤️

**Pull request merged**
