### PR TITLE
bin/brew: Preserve the LC_* localization variables

### PR DESCRIPTION
**Pull request by sjackman**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Can you explain why this is the case and how it is used?

**Comment by russel** [comment]
> Can you explain why this is the case and how it is used?

The file brew.sh needs to be executed with the LANG, LANGUAGE, and LC_* environment variables from the user environment, this is currently not the case as seen at https://discourse.brew.sh/t/brew-failing-to-handle-localisation/8234/21

**Comment by sjackman** [comment]
Sorry, of course. I should have given context. The origin of this PR is this discourse discussion https://discourse.brew.sh/t/brew-failing-to-handle-localisation/8234 and this stale issue https://github.com/Linuxbrew/brew/issues/568

Homebrew env filtering filters out the user's locale settings, the `LC_*` environment variables. This PR preserves these environment variables.

**Comment by sjackman** [comment]
Should `LANG` and/or `LANGUAGE` be preserved? See https://superuser.com/questions/392439/lang-and-language-environment-variable-in-debian-based-systems

**Comment by sjackman** [comment]
I've reread that stale issue, and we've already had this same debate/discussion before. See https://github.com/Linuxbrew/brew/issues/568#issuecomment-359166923
@MikeMcQuaid Does your opinion remain the same?

@russel Is your original issue fixed by PR https://github.com/Homebrew/brew/pull/8047, which changes the default locale on Linux to `C.UTF-8`? If so, I'll close this PR without merging.

**Comment by russel** [comment]
@sjackman  Is #8047 now in the current released system? I can only try it if it is unless there is an easy way of trying the merged system. Given the experiments so far, it seems that brew.sh is never going to be called with the user's locale set (unless something akin to this merge request is merged) so the default local is the always locale, not the default locale.

**Comment by sjackman** [comment]
> Is #8047 now in the current released system? I can only try it if it is unless there is an easy way of trying the merged system.

I've merged PR https://github.com/Homebrew/brew/pull/8047. You can test it out with `HOMEBREW_DEVELOPER=1 brew update`.

> Given the experiments so far, it seems that brew.sh is never going to be called with the user's locale set (unless something akin to this merge request is merged) so the default local is the always locale, not the default locale.

Correct.

**Comment by russel** [comment]
> I've merged PR #8047. You can test it out with `HOMEBREW_DEVELOPER=1 brew update`.

Is this a one way trip, a one-off trip, or a reversible state change trip? If either of the latter two, I'll certainly give it a go.

**Comment by sjackman** [comment]
> Is this a one way trip, a one-off trip, or a reversible state change trip? If either of the latter two, I'll certainly give it a go.

It's reversible with `cd $(brew --repo) && git reset --hard 2.4.8`

**Comment by russel** [comment]
I ran this:
```
|> brew update
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.sh: line 4: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
Already up-to-date.

|> HOMEBREW_DEVELOPER=1 brew update
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.sh: line 4: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Already up-to-date.

506 lynet:~ 
|> brew update
Already up-to-date.

|> HOMEBREW_DEVELOPER=1 brew update
Already up-to-date.
```
I checked the Git repo and it had been switched from stable to master. I can switch that back later.

**Comment by sjackman** [comment]
The warning `/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)` has gone away, so it looks as though your issue is resolved by PR #8047? If so, I'll close this PR without merging.

**Comment by russel** [comment]
@sjackman  Your choice, but I think documentation needs to make it clear to users that brew runs in C.UTF-8 no matter what the user's locale is.

**Comment by sjackman** [comment]
Homebrew is not currently localized, so I don't see much benefit to running it in a different locale. Do you have a use case in mind?

**Comment by russel** [comment]
Not really. It was just that if the brew command was worrying so much about locale in the script system, and was claiming to use the user's locale, then it should. If it is going to impose C.UTF-8 as the execution environment then that needs saying, and all the locale handling code stripped out so as not to have redundant code.

As it is, I am a happy bunny – no need to install irrelevant locales, and no messages telling me I am a bad person. :-)

Thanks for all your work on this.

**Comment by sjackman** [comment]
With `HOMEBREW_NO_ENV_FILTERING=1` Homebrew will use the user's locale if it's `UTF-8` and otherwise `C.UTF-8` on Linux and `en_US.UTF-8` on macOS. Without `HOMEBREW_NO_ENV_FILTERING` Homebrew will use `C.UTF-8` on Linux and `en_US.UTF-8` on macOS.

> Thanks for all your work on this.

👍

**Pull request closed without merging**
