### PR TITLE
bottle: add `--skip-relocation` flag to skip keg relocate

### PR DESCRIPTION
**Pull request by xu-cheng**
This flag is indented to be used in `homebrew/portable` to build vendor
ruby/git/curl.

### CODE REVIEW

**Comment by xu-cheng** [comment]
cc @MikeMcQuaid we may be able to tweak the existing system to build and upload vendor ruby.

**Comment by MikeMcQuaid** [comment]
Can you link to the PR where this flag is used? Thanks!

**Comment by MikeMcQuaid** [comment]
Sorry, misread the diff. 👍 from me. I do wonder if we could somehow skip this relocation automatically when its not required, though, and remove use of `install_name_tool` when we don't actually need it. Thoughts?

**Comment by UniqMartin** [comment]
> I do wonder if we could somehow skip this relocation automatically when its not required, though, and remove use of `install_name_tool` when we don't actually need it. Thoughts?

We cannot avoid it at the moment, because otherwise the `strings` invocation that checks for remaining mentions of the prefix (after the relocation with `install_name_tool`) will trigger for the unmodified load commands. Once we completely switch to `ruby-macho` it will be easier, as it could provide the offsets of the load commands so those could be filtered from the offsets returned by `strings`.

However, the situation where we can completely avoid `install_name_tool` are relatively rare, because it means that there are no dylibs at all (as all dylibs have a dylib ID that is an absolute path in the Homebrew prefix) and that no executables can reference other Homebrew dylibs (as that would mean dylib load commands that contain paths into the Homebrew prefix). Under these very specific conditions, we already don't invoke `install_name_tool` today (because `otool` won't yield paths that need to be adjusted).

**Comment by MikeMcQuaid** [comment]
> We cannot avoid it at the moment, because otherwise the strings invocation that checks for remaining mentions of the prefix (after the relocation with install_name_tool) will trigger for the unmodified load commands. Once we completely switch to ruby-macho it will be easier, as it could provide the offsets of the load commands so those could be filtered from the offsets returned by strings.

👍

**Comment by xu-cheng** [comment]
@MikeMcQuaid Since this PR is to explore using existing test-bot to build vendor Ruby/Git/Curl, there is no way automatically to check whether it's relocatable. Please note, formulae in `homebrew/portable` are very special, which need to be treated differently than normal formulae. 

To make this work, I have two questions need to be addressed. 
* How to setup a Leopard VM on bot.brew.sh?
* @mistydemeo Can Homebrew be used on Mac OS X 10.5 to build formulae or these changes need to be ported to Tigerbrew?

**Comment by MikeMcQuaid** [comment]
> How to setup a Leopard VM on bot.brew.sh?

Why do we need this? Have you tested if e.g. a build on 10.11 works on earlier versions of OS X e.g. 10.6/7?

**Comment by xu-cheng** [comment]
> Have you tested if e.g. a build on 10.11 works on earlier versions of OS X e.g. 10.6/7?

It won't work.

**Comment by UniqMartin** [comment]
>> Have you tested if e.g. a build on 10.11 works on earlier versions of OS X e.g. 10.6/7?
> 
> It won't work.

Sorry if I'm making you repeat things; it's quite possible you already elaborated on that. Why doesn't it work? Naively, I would assume that setting `MACOSX_DEPLOYMENT_TARGET` to `10.6` would be enough to produce a working binary. (Of course there can be all kinds of corner cases where a newer SDK doesn't sufficiently align with an older OS X release. Even Apple makes mistakes. Is that the case here?)

**Comment by xu-cheng** [comment]
@UniqMartin The reason is I have tried it and it doesn't work. As far as I can tell, making it work is extreme hard and may be broken in unexpected way. While a VM solution is much easier.
```
Vagrants-Mac-2:~ vagrant$ ./portable-ruby/2.0.0-p648/bin/ruby -v
Illegal instruction
```

**Comment by MikeMcQuaid** [comment]
> @UniqMartin The reason is I have tried it and it doesn't work. As far as I can tell, making it work is extreme hard and may be broken in unexpected way. While a VM solution is much easier.

Can you detail what platform you tried building and testing it on and if it was on physical hardware or a VM? If we're going to have Homebrew depend on the vendored Ruby work we need to up the quality of understanding and documentation so it's not just you that understands how and why this works the way it does. I don't think replies like "it doesn't work" really help with building that understanding among maintainers who want to learn more.

**Comment by xu-cheng** [comment]
I test it on 10.5 VM. Also, I don't think whether it's a VM or physical hardware matters. Because as a software, Homebrew should be oblivious to it.

The detail reasons are many. New SDK does't work and there is no way you can install old SDK to new machine. There is also ABI compatible issue as well. But overall, the only reason is Apple only supports some degree of backward compatibility but no forward compatibility. The latter one is a whole new story.

I admit there is a slight possibility to make vendor Ruby built on modern OS and work for old OS. But it is extremely hard, and quite possible to be broken in some places where tests will fail to catch. And building on a VM is the simplest and most robust solution. Since we can have a VM, I don't think we should waste our time on that road.

**Pull request closed without merging**
