### PR TITLE
dev-cmd: add add-license command

### PR DESCRIPTION
**Pull request by SeekingMeaning**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

This PR adds `brew add-license`, a command that adds a license to a formula if it does not have one already or changes the current license if run with `--force`. (I'm uncertain about the name `add-license`. What do you guys think about <code>update&#8209;license</code>?)

This is useful for Homebrew/homebrew-core#58225

Example usage:

```console
% brew add-license sendemail GPL-2.0+
[licenses-s 2fd6f1572a] sendemail: add license
 1 file changed, 1 insertion(+)

% brew add-license curl curl --force
[licenses-c d18f574745] curl: change license
 1 file changed, 1 insertion(+), 1 deletion(-)
```

`brew help add-license`:

```
Usage: brew add-license [options] formula license

Create a commit to add license to formula.

    -n, --dry-run                    Print what would be done rather than doing
                                     it.
        --no-audit                   Don't run brew audit before committing.
        --strict                     Run brew audit --strict before
                                     committing.
        --message                    Append message to the default commit
                                     message.
    -f, --force                      Override warnings and enable potentially
                                     unsafe operations.
    -q, --quiet                      Suppress any warnings.
    -v, --verbose                    Make some output more verbose.
    -d, --debug                      Display any debugging information.
    -h, --help                       Show this message.
``

### CODE REVIEW

**Comment by SMillerDev** [comment]
Wouldn't this be a one time use thing? We don't have a `update-homepage` either.

**Comment by SeekingMeaning** [comment]
True, although it'd be nice to have this in `master` while the work is still in progress

**Comment by SMillerDev** [comment]
I think this might be useful for 1% of homebrew users and I wouldn't want to take on the burden to support it with such a small set of users. @Homebrew/brew might think differently though.

**Comment by jonchang** [comment]
Yeah I think in this case this would work best in a tap that e.g. @SeekingMeaning runs. You can then loop in the other maintainers and contributors helping out with the licensing push and then just archive the tap when the licensing stuff finishes.

**Comment by MikeMcQuaid** [comment]
> Yeah I think in this case this would work best in a tap that e.g. @SeekingMeaning runs. You can then loop in the other maintainers and contributors helping out with the licensing push and then just archive the tap when the licensing stuff finishes.

Agreed 👍

**Pull request closed without merging**
