### PR TITLE
dev-cmd/bottle: fix positioning of bottle block in some cases

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Fixes the bottle commit breaking `brew style` when the license line or livecheck block is included.

### CODE REVIEW

**Comment by Rylan12** [comment]
Just curious, the `components_order` rubocop has a few additional components that precede the `bottle` block:

https://github.com/Homebrew/brew/blob/1b1e3b449ef77d5e13a198f49c97febb2c0d15b9/Library/Homebrew/rubocops/components_order.rb#L18-L33

Namely: `livecheck`, `stable`, `head`, `url` and `include`.

Should these be added here as well?

Also, can `sha1` be removed given that Homebrew has [removed sha1 support as of ~4 years ago](https://docs.brew.sh/Checksum_Deprecation)?

**Comment by Bo98** [comment]
`url` and `head` is already there.

I will test the others.

> Also, can sha1 be removed given that Homebrew has removed sha1 support as of ~4 years ago?

Probably.

**Comment by Bo98** [comment]
`stable do` was also already supported but not very well (no blank line after the `end`), I've tweaked it now.

Regex on code is kinda horrible to do, but doing anything else is a bigger task than I expected to do here.

**Comment by Bo98** [comment]
Yeah, that's an idea.

I'll merge as is to mitigate the impact it's currently having though.

**Pull request merged**
