### PR TITLE
tap.rb: clone large taps on slow networks

### PR DESCRIPTION
**Pull request by maxim-belkin**
Cloning large repos on slow networks may error out with weird Git errors, see #8550. 
Doing a shallow clone and then unshallowing the repo (is necessary) -- is less prone to these problems.

-----

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
We deliberately don't use shallow clones for anything that's going to be `brew update`d because it's slower for us and significantly more expensive for GitHub (so they've asked us not to). Sorry!

**Comment by maxim-belkin** [comment]
This PR splits `git clone` into `git clone --depth=1` + `git fetch --unshallow`, so in the end we end up with a full clone. This is merely to avoid erroring out on slow networks.

**Comment by MikeMcQuaid** [comment]
This does not speed things up. It's both slower and more expensive for GitHub and slower for us.

**Comment by gromgit** [comment]
Perhaps the two-step shallow/unshallow can be used as a fallback, if the primary full-clone step fails?

**Comment by MikeMcQuaid** [comment]
Users can do it manually if needed. It's not something I can agree to in good faith as it'll really piss off GitHub who provide us with a non-trivial amount of resources for free.

**Pull request closed without merging**
