### PR TITLE
audit: check patch sha matches when --online

### PR DESCRIPTION
**Pull request by alyssais**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

See Homebrew/homebrew-core#5353 for motivation.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
`brew fetch -s` may already do this. If so, I think this is already covered by the test-bot? If not: that'd be the best place to add it. Thanks for jumping on this anyway, though!

**Comment by alyssais** [comment]
I can't figure out what `-s` does, but `fetch` does seem to do this, so no point duplicating it here.

I think there is some value to having a command that would check this for all formulae like `brew audit` does though. This would let people find problems and fix them in bulk before they affected anyone. So a way to bulk fetch all formulae?

**Comment by MikeMcQuaid** [comment]
Sorry, `-s` is `--build-from-source`'s alias.

Could see an argument for a `brew fetch --force --all` but that's going to do all tarballs and patches too which I'm not sure will scale well.

**Comment by alyssais** [comment]
> which I'm not sure will scale well.

Good point. I do think it would be a good idea to have some way of identifying broken formulae because resources have changed, but I don't know how to go about this, so I'll close this.

**Pull request closed without merging**
