### PR TITLE
livecheck: add component order rubocop

### PR DESCRIPTION
**Pull request by nandahkrishna**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Adding a component order style check for Livecheck blocks, to ensure they're above the `bottle` block.

### CODE REVIEW

**Comment by nandahkrishna** [comment]
Sure. Some style fixes before that 😅

**Comment by nandahkrishna** [comment]
Checked the test I added by adding a `livecheck` block after bottle in `zzz.rb`, works as expected - errors out on `brew style`.

Would anything else be required, such as ordering of components within the block?

**Comment by MikeMcQuaid** [comment]
> Would anything else be required, such as ordering of components within the block?

No, that seems good for now! Eventually ordering with a block might be nice to add.

**Comment by MikeMcQuaid** [comment]
Thanks again @nandahkrishna!

**Pull request merged**
