### PR TITLE
Move Formatter and Locale specs.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Is this code shared between Homebrew and Homebrew Cask (and used in both)?

**Comment by reitermarkus** [comment]
At least `Formatter` is shared, but why does this matter? I thought we wanted to have `brew tests` also run Cask tests?

**Comment by MikeMcQuaid** [comment]
> At least Formatter is shared, but why does this matter? 

👍 on Formatter then.

> I thought we wanted to have brew tests also run Cask tests?

Yep, I think so but it should probably still live in e.g. `Library/Homebrew/test/cask/locale_spec.rb` if it's not shared just to make it more obvious.

**Comment by reitermarkus** [comment]
Ok, seems like `Locale` is used for the `os/mac` test.

**Comment by MikeMcQuaid** [comment]
> Yep, I think so but it should probably still live in e.g. Library/Homebrew/test/cask/locale_spec.rb if it's not shared just to make it more obvious.

Just to repeat myself: I'm cool with moving all these tests around but I think still maintaining a `test/cask` subdirectory probably makes sense (and it is better than `cask/test`). Thanks @reitermarkus !

**Comment by reitermarkus** [comment]
> I think still maintaining a `test/cask` subdirectory probably makes sense

Yes, these were the only ones that weren't actually in `test/cask`.

**Pull request merged**
