### PR TITLE
upgrade formulae using the same compilers as installed them

### PR DESCRIPTION
**Pull request by whitslack**
If a formula needs a non-default compiler to install, then most likely it will need the same non-default compiler to upgrade. This commit makes the `upgrade` command use the same compiler to upgrade each formula as was used to install the formula.

Function parameters are introduced to enable a future commit to implement a `--cc=` command-line option for `upgrade` to use a different compiler than that which was used for formula installation.

----

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

### CODE REVIEW

**Review by MikeMcQuaid — CHANGES_REQUESTED** [review]
I'm not sure this is the right change.

If a custom compiler is needed: `fails_with` should be used to indicate this in the formula and pick the right logic. The `--cc` flag is not intended for use for when another compiler is required but is an unsupported flag for testing with other compilers.

**Comment by whitslack** [comment]
> If a custom compiler is needed: `fails_with` should be used to indicate this in the formula and pick the right logic.

Can `fails_with` indicate a particular version of the system-default compiler? For example, the `freetype` formula fails to compile with Apple clang 10, but probably does compile fine with a newer version of Apple clang. How would that constraint be expressed with `fails_with`?

**Comment by gromgit** [comment]
You'd have to find the build number of the specific Clang that fails the build, then look at the examples here: https://docs.brew.sh/Formula-Cookbook#compiler-selection

**Comment by whitslack** [comment]
Thank you. Adding a `fails_with` block to the `freetype` formula solved my issue (and I opened https://github.com/Homebrew/homebrew-core/pull/125422 to contribute it).

**Pull request closed without merging**
