### PR TITLE
various tweaks (user agent, Google Analytics)

### PR DESCRIPTION
**Pull request by UniqMartin**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] ~~Have you written new tests for your changes?~~
- [x] Have you successfully ran `brew tests` with your changes locally?

----

Mostly a bunch of independent minor improvements; follow-up to Homebrew/legacy-homebrew#50462 and Homebrew/legacy-homebrew#50480. Unless obvious, additional detail is given in the respective commit message. Also contains one bug fix (`HOMEBREW_OS_VERSION` being treated improperly for the non-OS-X case).

cc @mikemcquaid

### CODE REVIEW

**Comment by mikemcquaid** [comment]
👍 

> Linuxbrew/0.9.9 (Linux; unknown Debian GNU/Linux 8.3 (jessie))

Would be good to handle that `unknown` if you tested that on an actual system.

**Comment by UniqMartin** [comment]
> Would be good to handle that `unknown` if you tested that on an actual system.

One way would be to move `HOMEBREW_PROCESSOR` into the `if`, i.e., use `uname -p` on OS X and `uname -m` on all other systems. Not sure how it will behave outside of Linux, but on the Debian system I tested this `uname -m` returns something sensible (`x86_64`). How does that sound?

**Comment by mikemcquaid** [comment]
> One way would be to move HOMEBREW_PROCESSOR into the if, i.e., use uname -p on OS X and uname -m on all other systems. Not sure how it will behave outside of Linux, but on the Debian system I tested this, uname -m returns something sensible (x86_64). How does that sound?

Sounds good 👍

**Comment by UniqMartin** [comment]
> Sounds good :+1:

Done.

**Comment by mikemcquaid** [comment]
🚢 !

**Pull request closed without merging**
