### PR TITLE
Handle tap migrations in `CaskLoader`.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
Makes sense to me! Some tests might be nice. Is this a companion to https://github.com/Homebrew/brew/pull/16595? Do either of those PRs require the other?

**Comment by reitermarkus** [comment]
> Is this a companion to https://github.com/Homebrew/brew/pull/16595? Do either of those PRs require the other?

Yes, but they don't require each other. This one follows the refactored logic from https://github.com/Homebrew/brew/pull/16595 though.

**Comment by aivus** [comment]
@reitermarkus started to getting lots of:

```
➜  ~ brew remove -v -d --cask vagrant
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading vagrant
Error: Invalid tap name 'vagrant/'
/usr/local/Homebrew/Library/Homebrew/tap.rb:48:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:460:in `tap_cask_token_type'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:502:in `block in for'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:495:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:495:in `for'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:455:in `load'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:159:in `block in load_formula_or_cask'
/usr/local/Homebrew/Library/Homebrew/api.rb:199:in `with_no_api_env_if_needed'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:118:in `load_formula_or_cask'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:83:in `block in to_formulae_and_casks'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:81:in `each'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:81:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:81:in `to_formulae_and_casks'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:317:in `to_kegs_to_casks'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:48:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:86:in `<main>'
➜  ~ 

```

**Comment by williammck** [comment]
Seeing the same issues as @aivus. Reverting to the commit prior to this merge (cd9c3fc8a813df3439a00ab304db3a40ff6cad48) allows formulae and casks to install again.

**Pull request merged**
