### PR TITLE
tests: clean up file system for all tests

### PR DESCRIPTION
**Pull request by alyssais**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

(No longer just integration tests.)

This was a big change, and I wanted to avoid removing any `ensure`/`teardown` code that would later end up needing to be added back in, so it's likely there'll be a few lines I could have removed but missed.

Similarly, I'm sure there are more directories that could be purged in teardown safely, but I decided to do an 80/20 and just copy the list from the integration tests for now.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Yes, so much deleted code! Any noticeable difference in speed?

**Comment by alyssais** [comment]
Looks like it averages to about four seconds per full (`--official-cmd-taps`) test suite run.

**Comment by alyssais** [comment]
(Where a full test suite run after this change takes 104 seconds)

**Comment by MikeMcQuaid** [comment]
So a 4% regression? Seems fine given the code complexity and (moreso) the better errors we'll get on failures.

**Pull request merged**
