### PR TITLE
Make `ignore_interrupts` thread-safe.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Make `ignore_interrupts` thread-safe to prevent race conditions when cancelling concurrent downloads.

### CODE REVIEW

**Review by Bo98 — COMMENTED** [review]
Is there any way to avoid locking for the entire duration of the yield? Some can be very long (e.g. `safe_fork`).

**Comment by reitermarkus** [comment]
No, there is no way to avoid it, but as far as I understand the code in `safe_fork`, the child will receive the interrupt and send it back to the parent via exit code 130, so the `ignore_interrupts` is only there to avoid the parent receiving the interrupt before the child.

**Comment by Bo98** [comment]
Doesn't this break the whole nesting level stuff? How can it ever have `$ignore_interrupts_nesting_level > 1` if the whole block is mutex locked?

**Comment by reitermarkus** [comment]
Right, I assumed the standard `Mutex` is reentrant. The question is, do we ever even call it nestedly?

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by Bo98** [comment]
Not sure, would need to audit existing usages, but it seems very easy for something to do `ignore_interrupts { system_command!("echo") }` (`system_command` has an `ignore_interrupts` internally).

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by reitermarkus** [comment]
Got rid of `ignore_interrupts` in in `SystemCommand` and `safe_fork`, all remaining usages only clean up files, so should be good.

**Review by Bo98 — APPROVED** [review]
Thanks, looks better!

No idea which places needed it or not, so I'll assume the removed ones weren't needed.

**Pull request merged**
