### PR TITLE
os/mac/diagnostic: output non-default Xcode prefix.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
This should help people find it when this is a fatal error (and they don't look at `brew config`).

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
```
2018-11-28T16:06:26.3139510Z   1) Cask::Quarantine by default quarantines Cask audits
2018-11-28T16:06:26.3141020Z      Failure/Error: Cask::Cmd::Audit.run("local-transmission", "--download")
2018-11-28T16:06:26.3141640Z 
2018-11-28T16:06:26.3142550Z      Cask::CaskError:
2018-11-28T16:06:26.3143740Z        audit failed for casks: local-transmission
2018-11-28T16:06:26.3144880Z      # ./cask/cmd/audit.rb:17:in `run'
2018-11-28T16:06:26.3146010Z      # ./cask/cmd/abstract_command.rb:34:in `run'
2018-11-28T16:06:26.3147190Z      # ./test/cask/quarantine_spec.rb:32:in `block (3 levels) in <top (required)>'
2018-11-28T16:06:26.3148320Z      # ./test/support/helper/spec/shared_context/homebrew_cask.rb:38:in `block (2 levels) in <top (required)>'
2018-11-28T16:06:26.3149380Z      # ./test/spec_helper.rb:137:in `block (2 levels) in <top (required)>'
2018-11-28T16:06:26.3150430Z      # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:123:in `block in run'
2018-11-28T16:06:26.3151490Z      # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `loop'
2018-11-28T16:06:26.3152510Z      # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `run'
2018-11-28T16:06:26.3153560Z      # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
2018-11-28T16:06:26.3154620Z      # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
2018-11-28T16:06:26.3155690Z      # ./vendor/bundle/ruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
2018-11-28T16:06:26.3156410Z 
2018-11-28T16:06:26.3156880Z   2) Cask::Quarantine when disabled does not quarantine Cask audits
2018-11-28T16:06:26.3157900Z      Failure/Error: Cask::Cmd::Audit.run("local-transmission", "--download", "--no-quarantine")
2018-11-28T16:06:26.3158380Z 
2018-11-28T16:06:26.3158820Z      Cask::CaskError:
2018-11-28T16:06:26.3159740Z        audit failed for casks: local-transmission
2018-11-28T16:06:26.3160700Z      # ./cask/cmd/audit.rb:17:in `run'
2018-11-28T16:06:26.3161720Z      # ./cask/cmd/abstract_command.rb:34:in `run'
2018-11-28T16:06:26.3162720Z      # ./test/cask/quarantine_spec.rb:145:in `block (3 levels) in <top (required)>'
2018-11-28T16:06:26.3163770Z      # ./test/support/helper/spec/shared_context/homebrew_cask.rb:38:in `block (2 levels) in <top (required)>'
2018-11-28T16:06:26.3164800Z      # ./test/spec_helper.rb:137:in `block (2 levels) in <top (required)>'
2018-11-28T16:06:26.3165840Z      # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:123:in `block in run'
2018-11-28T16:06:26.3166890Z      # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `loop'
2018-11-28T16:06:26.3167910Z      # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `run'
2018-11-28T16:06:26.3168950Z      # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
2018-11-28T16:06:26.3170010Z      # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
2018-11-28T16:06:26.3171070Z      # ./vendor/bundle/ruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
```

@Homebrew/cask could one of you take a look at this? It seems to be failing pretty consistently.

**Comment by claui** [comment]
It seems that the TLS certificate served by https://example.com/ has expired. 😱😛

**Comment by MikeMcQuaid** [comment]
@claui Ouch! Any chance of a PR to update the relevant casks?

**Comment by claui** [comment]
> Ouch! Any chance of a PR to update the relevant casks?

@MikeMcQuaid https://github.com/Homebrew/brew/pull/5359

**Pull request merged**
