### PR TITLE
rubocops/uses_from_macos: remove openlibm

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

This is not provided by macOS. See https://github.com/Homebrew/homebrew-core/pull/76528.

### CODE REVIEW

**Review by Rylan12 — APPROVED** [review]

**Comment by Rylan12** [comment]
Just a though that's not blocking (and is not related directly to these changes):

Right now, the `brew style` message for a formula not `PROVIDED_BY_MACOS_FORMULAE` and using `keg_only :provided_by_macos` is this:

```
Formulae that are `keg_only :provided_by_macos` should be added to the `PROVIDED_BY_MACOS_FORMULAE` list (in the Homebrew/brew repo)
```

I wonder if this is misleading and could cause formulae to be added to `PROVIDED_BY_MACOS_FORMULAE` when they shouldn't. It almost reads like it's encouraging the user to add the formula to the list when in reality it should probably read as "oh this formula probably shouldn't be using `keg_only :provided_by_macos`, if that makes sense.

How about:

```
Only formulae in the `PROVIDED_BY_MACOS_FORMULAE` list (in the Homebrew/brew repo) are allowed to specify `keg_only :provided_by_macos`
```

**Review by Ghostglass — APPROVED** [review]

**Review by Ghostglass — APPROVED** [review]
:octocat: Cool

**Review by Ghostglass — APPROVED** [review]
👍🏼

**Review by Ghostglass — APPROVED** [review]
👍🏼

**Comment by MikeMcQuaid** [comment]
> ```
> Only formulae in the `PROVIDED_BY_MACOS_FORMULAE` list (in the Homebrew/brew repo) are allowed to specify `keg_only :provided_by_macos`
> ```

👍🏻

**Review by MikeMcQuaid — APPROVED** [review]

**Pull request merged**
