### PR TITLE
fix: allow generate-formula-api to support renamed formulae

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----
It feels incredibly naive, but I think this should support formula renames in the API.

### CODE REVIEW

**Comment by reitermarkus** [comment]
Everything here looks reasonable, but I think this will only work for `brew install`, not `brew upgrade`. `brew install` would also not warn when using the old name.

On upgrade, we implicitly check `formula_renames.json` in `Formulary`. I don't see a way of doing the same with this naive approach. `Tap#formula_renames` should do the same when using the API, so I think the API JSON needs to have a `"formula_renames"` field.

**Comment by Bo98** [comment]
The HTML redirects is a good idea and that makes sense to do.

I however don't think the bit copying the JSON is a good idea. `brew` will not treat that as a rename and it may confuse API consumers as they'll now need to cross-check the `name` field to know if it's a real formula or not.

In terms of supporting renames in the install-from-api code in brew, I think the data is already there in terms of `oldnames`. Let me have a look and see what can be done there.

**Comment by Bo98** [comment]
> I however don't think the bit copying the JSON is a good idea. It may confuse API consumers as they'll now need to cross-check the `name` field to know if it's a real formula or not, and inflates the JSON by a fair bit. For the mega formula.json, it'll actually appear as two of the same entry as it's just a big array.

Thinking about it more actually: if it's just the direct JSON for individual formulae and not the formula.json file then it's probably ok

**Comment by MikeMcQuaid** [comment]
> The HTML redirects is a good idea and that makes sense to do.

I'm not opposed but I'm not strongly in favour either given we've not really had requests for this.

> I however don't think the bit copying the JSON is a good idea. It may confuse API consumers as they'll now need to cross-check the `name` field to know if it's a real formula or not, and inflates the JSON by a fair bit. For the mega formula.json, it'll actually appear as two of the same entry as it's just a big array.

Also agreed.

Now that https://github.com/Homebrew/brew/pull/15320 is implemented I think it'd be good to do the bare minimum required to get this data in place. I don't think we need to provide JSON or HTML files for the old names; no-one has asked for this really.

**Comment by SMillerDev** [comment]
It seems I misunderstood the problem with formula renames. What needs to be solved for the API? I thought it was discoverability but that doesn't seem to be the case.

**Comment by reitermarkus** [comment]
> What needs to be solved for the API?

Nothing anymore since https://github.com/Homebrew/brew/pull/15320 is merged.

We can keep the additional redirects added in this PR though.

**Pull request closed without merging**
