### PR TITLE
leaves: account for requirements

### PR DESCRIPTION
**Pull request by maxim-belkin**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

See https://github.com/Homebrew/brew/pull/3344#issuecomment-338296522

After:
```
$ brew leaves 
atk
fdupes
gdk-pixbuf
gnu-sed
hicolor-icon-theme
jpegoptim
p7zip
pango
pstree
pyenv
r
rbenv
tree
vim
```

Fixes https://github.com/Homebrew/brew/issues/3100
Closes https://github.com/Homebrew/brew/pull/3344

### CODE REVIEW

**Comment by maxim-belkin** [comment]
I don't think what was requested but it works 🙄

**Comment by MikeMcQuaid** [comment]
> I don't think this is what was requested but it works 🙄

Sorry I don't really understand this comment (and don't appreciate the 🙄).

**Comment by maxim-belkin** [comment]
this pr uses `f.runtime_dependency`, where f == formula, not tab of keg as you suggested in https://github.com/Homebrew/brew/pull/3344#issuecomment-338296522

> and don't appreciate the 🙄)

 ok :)

**Comment by MikeMcQuaid** [comment]
🎉 Great work here again @maxim-belkin and apologies for my earlier grumpiness.

**Pull request merged**
