### PR TITLE
Allow defining service run command per platform

### PR DESCRIPTION
**Pull request by dawidd6**
- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Closes: https://github.com/Homebrew/brew/issues/14352

Merge after: https://github.com/Homebrew/homebrew-services/pull/536

### CODE REVIEW

**Comment by dawidd6** [comment]
Gonna need some help here with the tests (if the implementation is alright). I can't get them to work :(

**Comment by jfoy** [comment]
`brew tests --changed --online` with your branch is passing locally for me. Was that all you needed?

**Comment by MikeMcQuaid** [comment]
@dawidd6 not sure what's going on with CI here, may want a rebase?

**Comment by dawidd6** [comment]
Some tests seem to be flaky recently. I've seen some issues related to Repology API in our scheduled autobump workflow in homebrew-core. Seems like the problems are present also here.

**Comment by MikeMcQuaid** [comment]
@dawidd6 Yeh, agreed. I've seen Repology and GitHub API related tests flaking a lot. Need to think about a better way of handling these. Thinking perhaps we have a non-required test suite that runs just the online tests.

**Pull request merged**
