### PR TITLE
xcode: expect 7.3.1 on 10.11

### PR DESCRIPTION
**Pull request by UniqMartin**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

cc @DomT4 because I'm not sure whether our CI is ready yet. (I suspect not quite.)

### CODE REVIEW

**Comment by DomT4** [comment]
Hasn't been updated on CI yet, no. Will fix that as soon as the CI queue finishes up. You need to update [this line](https://github.com/UniqMartin/brew/blob/xcode-7.3.1/Library/Homebrew/os/mac/xcode.rb#L175) as well :)

**Comment by UniqMartin** [comment]
> You need to update [this line](https://github.com/UniqMartin/brew/blob/xcode-7.3.1/Library/Homebrew/os/mac/xcode.rb#L175) as well :)

No, I don't. 😉 But thanks for the careful review! There's no new version of the CLT (yet?), thus its Clang version still matches the one from Xcode 7.3. If you have both Xcode and CLT installed, compare:

```
$ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang --version
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$ /Library/Developer/CommandLineTools/usr/bin/clang --version
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

(Sadly, this means CLT-only users are also stuck with an older unpatched Git version.)

**Comment by DomT4** [comment]
> There's no new version of the CLT (yet?)

There is, Apple just haven't pushed it to MAS for some reason. This happened last time but it was up within a few hours.

**Comment by UniqMartin** [comment]
> There is, Apple just haven't pushed it to MAS for some reason.

Strange. Definitely hasn't appeared in my MAS yet. Maybe they withheld it intentionally?

> ```
> Target: x86_64-apple-darwin15.5.0
> ```

You seem to be on the 10.11.5 Beta (I'm on 10.11.4). Could that be why you have it and I don't?

**Comment by DomT4** [comment]
> Maybe they withheld it intentionally?

Wouldn't think so. This happened last time so perhaps it's just the "new normal".

> Could that be why you have it and I don't?

I don't use MAS for Xcode because it blows for large downloads. I went and fetched it manually from Apple's "Additional Downloads" and noticed the CLT whilst I was there.

**Comment by UniqMartin** [comment]
> I don't use MAS for Xcode because it blows for large downloads.

Getting a bit off-topic, but it actually works fine (at least for me). The only issue is that because it uses a delta, it has to validate what is on your system and then applying the delta usually takes much longer than the actual download (which was only 200 MB for this update). Because the MAS UI is horrible, there's hardly any indication of what is going on, so it can often appear stuck … but it only requires patience.

**Comment by DomT4** [comment]
Updated the main El Cap CI. Will do the backup later today, but will be enough for this PR to pass CI. May wish to wait to see what the CLT situation is given what happened last time but up to you.

**Comment by UniqMartin** [comment]
> May wish to wait to see what the CLT situation is given what happened last time but up to you.

Updated as suggested by you now that Apple has graced me with not only one, but two CLT updates:

MAS CLT Weirdness

**Comment by mikemcquaid** [comment]
Updated all the machines.

**Comment by DomT4** [comment]
Thanks Mike! Did the main one last night but it took a while to finish installing so I went to 😴 after, heh.

**Comment by UniqMartin** [comment]
Thank you both!

**Pull request merged**
