### PR TITLE
Xcode 9.1 Updates.

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by DomT4** [comment]
🌮

**Comment by DomT4** [comment]
Oh, okay. I meant 👍 but I guess 🌮 will do too.

**Comment by ilovezfs** [comment]
CC @sjackman time to start bugging Circle CI again ;)

**Comment by sjackman** [comment]
No mention of 9.1 yet on CircleCI. Here's where it will be listed: https://circleci.com/docs/1.0/build-image-macos/#selecting-xcode-version-and-operating-system

**Comment by ilovezfs** [comment]
This says 9.1 is available: https://discuss.circleci.com/t/xcode-9-1-release-for-circleci-2-0/17891

**Comment by ilovezfs** [comment]
high_sierra_homebrew_1, high_sierra_homebrew_2, and high_sierra_homebrew_3 don't have 9.1, which is unfortunate, but since we're not using those very often right now I don't think that has to block this PR.

**Comment by DomT4** [comment]
Thanks @ilovezfs 🙇

**Pull request merged**
