### PR TITLE
cmd/bump: add --force option

### LINKED ISSUE #14336: brew bump is giving invalid suggestion
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.17-57-gea0b786
ORIGIN: https://github.com/Homebrew/brew
HEAD: ea0b7863883d355eb60b82e14155d8d6befc234e
Last commit: 29 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1926d1fefbc73f074f41df73ebf889260bf7e5a4
Core tap last commit: 52 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.AHMfiKLQ0p/org.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.85.0 => /usr/bin/curl
macOS: 13.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false
```

### The bug

```
$ brew bump --open-pr mpfr
==> mpfr
Current formula version:  4.1.0-p13
Latest livecheck version: 4.2.0
Latest Repology version:  4.2.0
Open pull requests:       none
Error: These pull requests may be duplicates:
mpfr 4.2.0 https://github.com/Homebrew/homebrew-core/pull/118066
Duplicate PRs should not be opened. Use --force to override this error.
```

1. That's weird, is a closed PR considered a duplicate?
2. OK, I will follow the suggestion:

```
$ brew bump --open-pr --force mpfr
Usage: brew bump [options] [formula|cask ...]

Display out-of-date brew formulae and the latest version available. If the
returned current and livecheck versions differ or when querying specific
formulae, also displays whether a pull request has been opened with the URL.

      --full-name                  Print formulae/casks with fully-qualified
                                   names.
      --no-pull-requests           Do not retrieve pull requests from GitHub.
      --formula, --formulae        Check only formulae.
      --cask, --casks              Check only casks.
      --open-pr                    Open a pull request for the new version if
                                   there are none already open.
      --limit                      Limit number of package results returned.
      --start-with                 Letter or word that the list of package
                                   results should alphabetically follow.
  -d, --debug                      Display any debugging information.
  -q, --quiet                      Make some output more quiet.
  -v, --verbose                    Make some output more verbose.
  -h, --help                       Show this message.
Error: invalid option: --force
```

So it suggested an invalid option.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew bump --open-pr --force mpfr
```

### PR DESCRIPTION
**Pull request by apainintheneck**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

This fixes #14336.

It adds `--force` as an option that gets passed along to `brew bump-cask-pr` and `brew bump-formula-pr`.

This was failing in [Github.check_for_duplicate_pull_requests](https://github.com/Homebrew/brew/blob/5babb49100ede5afbfafa2d1a8cfc4063a358708/Library/Homebrew/utils/github.rb#L505).

On thing to not is that the `--force` param carries some additional weight when used with `brew bump-formula-pr`. I decided not to add that to the help page for this command but I'd like to hear your thoughts on whether that's necessary.

```
  -f, --force                      Ignore duplicate open PRs. Remove all mirrors
                                   if --mirror was not specified.
```

I'm also not exactly sure how to best test this out without nuking existing PRs.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> This fixes #14336.

From that:

> @fxcoudert: That's weird, is a closed PR considered a duplicate?

It feels like that may the actual bug here?

**Comment by fxcoudert** [comment]
> It feels like that may the actual bug here?

- Suggesting to use `--force` and reject it: this is definitely a bug
- Considering a closed PR as duplicate: I would tend to consider it a bug, but I did not know what the intent was, and there may be use cases I do not have in mind

**Comment by MikeMcQuaid** [comment]
> * Suggesting to use `--force` and reject it: this is definitely a bug

Or alternatively: just don't print this message if not being run directly.

**Comment by apainintheneck** [comment]
I think that the `--force` flag should be added either way because not having it can cause unexpected behavior for the user.

But you're both right that there seems to be another bug that caused this that needs to be investigated a little first.

**Comment by apainintheneck** [comment]
Turns out there is code that checks for both open and closed PRs in `bump-formula-pr` (but not in `bump-cask-pr`) so this is expected behavior though it is a bit confusing. I guess the idea is that if you're opening a PR that is a duplicate of one that was closed you could maybe use the old one as a reference point or even reopen it in some cases.

https://github.com/Homebrew/brew/blob/5babb49100ede5afbfafa2d1a8cfc4063a358708/Library/Homebrew/dev-cmd/bump-formula-pr.rb#L441

Note: The check for closed PRs only happens when the exact formula and version is known.

I think the thing to do here is add the `--force` flag and then update the error message to include the PR status to make it clearer. Does that make sense?

### Before
```diff
$ brew bump --open-pr mpfr
...
Error: These pull requests may be duplicates:
...
```

### After
```sh
$ brew bump --open-pr mpfr
...
Error: These closed pull requests may be duplicates:
...
```

**Comment by apainintheneck** [comment]
We could also just pass the `--force` flag by default to `bump-cask-pr` and `bump-formula-pr` since we're already checking for open PRs in `brew bump`. I'd rather not pass a destructive flag by default though.

I wonder why the checking for closed PRs logic was never added to `bump-cask-pr`.

**Comment by apainintheneck** [comment]
Closing in favor of an approach where `brew bump` always exits when closed PRs exists and `brew bump-cask-pr` mimics the closed PR behavior that exists in `brew bump-formula-pr`.

**Pull request closed without merging**
