### PR TITLE
bin/brew: allow `GPG_TTY`

### LINKED ISSUE #3544: bump-formula-pr fails when attempting to sign commit
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew doctor 
Your system is ready to brew.
```
[brew-config](https://gist.github.com/jasonkarns/e864f763dc24e6291572d534a7a096e9)

To help us debug your issue please explain:
- What you were trying to do (and why)
attempting to bump a formula with bump-formula-pr
- What happened (include command output)
Error when it attempting to git-commit.
<details>
<summary><code>$ HOMEBREW_DEVELOPER=true brew bump-formula-pr --url=https://github.com/nodenv/node-build/archive/v2.6.20.tar.gz --sha256=af89b9eb0086324a78674d31e7d74e750d30ac8565b27058431b1b854b068b9a node-build</code></summary>
<pre><code>
Already up-to-date.
==> replace "https://github.com/nodenv/node-build/archive/v2.6.19.tar.gz" with "https://github.com/nodenv/node-build/archive/v2.6.20.tar.gz"
==> replace "ed4b5aa3e5d6c474f7e53e9a78b6080bb7e57497ff1d2c67ddbc2700d0c5c2d0" with "af89b9eb0086324a78674d31e7d74e750d30ac8565b27058431b1b854b068b9a"
M	Formula/node-build.rb
Switched to a new branch 'node-build-2.6.20'
error: gpg failed to sign the data
fatal: failed to write commit object
Error: Failure while executing: git commit --no-edit --verbose --message=node-build\ 2.6.20 -- /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node-build.rb
</code></pre>
</details>

- What you expected to happen
expected it to commit and open a PR
- Step-by-step reproduction instructions (by running `brew` commands)

My git configuration has `user.signingkey` set and `commit.gpgsign=true`.

Failed on: `HOMEBREW_DEVELOPER=true brew bump-formula-pr --url=https://github.com/nodenv/node-build/archive/v2.6.20.tar.gz --sha256=af89b9eb0086324a78674d31e7d74e750d30ac8565b27058431b1b854b068b9a node-build`

The commit succeeded when executed manually (by just re-running the exact command that was echoed in the failure output: `git commit --no-edit --verbose --message=node-build\ 2.6.20 -- /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node-build.rb`). So I'm presuming the issue is that the brew process is running under a different user so it doesn't have access to gpg-agent, thus it's unable to sign the commit. However, I'm not sure what the remedy should be here. (This isn't the first issue I've encountered with homebrew respecting the user's gitconfig, but then failing due to some configuration therein.)

Is there some configuration that other homebrew devs use? I assume I'm not the only one who has git configured to sign commits.

### PR DESCRIPTION
**Pull request by tuzi3040**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----
`GPG_TTY` is required for gpg-agent to identify which tty to prompt for the passphrase of user's GPG key.

While user's GPG key have passphrase set, `HOMEBREW_NO_ENV_FILTERING` is not set to `1`, and `commit.gpgsign` is `true`, `brew bump-(?:formula|cask)-pr` may fail.

This fix #3544.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> While user's GPG key have passphrase set, `HOMEBREW_NO_ENV_FILTERING` is not set to `1`, and `commit.gpgsign` is `true`, `brew bump-(?:formula|cask)-pr` may fail.

I have this set and it works for me. Can we try to figure out what differs in our configuration?

**Comment by tuzi3040** [comment]
I have neither gpg.conf nor gpg-agent.conf configured.
`GPG_TTY` is set by oh-my-zsh plugin `gpg-agent`, `HOMEBREW_NO_ENV_FILTERING` is not set.

`brew sh <<< 'echo $GPG_TTY 1>&2' 1>/dev/null` prints empty, but shows `$(tty)` with this change applied.

**Comment by MikeMcQuaid** [comment]
> I have neither gpg.conf nor gpg-agent.conf configured.

Any reason why not?

**Comment by tuzi3040** [comment]
> Any reason why not?

No reason actually. Since I only use gpg to sign git commits for now, there is just no need to configure gpg or gpg-agent.

**Comment by tuzi3040** [comment]
> I have this set and it works for me. Can we try to figure out what differs in our configuration?

BTW, what do you mean by `works`?
Does it pops a pinentry prompt or just successfully signed the commit?
This change is made so that a terminal-based pinentry prompt can be shown, when the corresponding passphrase of the gpg key used for signing is not cached.

**Comment by MikeMcQuaid** [comment]
> BTW, what do you mean by `works`?
> Does it pops a pinentry prompt or just successfully signed the commit?

Either/both.

> This change is made so that a terminal-based pinentry prompt can be shown, when the corresponding passphrase of the gpg key used for signing is not cached.

Ok. I'd suggest instead that code be added here: https://github.com/Homebrew/brew/blob/3ce31edb7122d66831c26a729a4e484df750f38e/Library/Homebrew/utils/git.rb#L123-L129

to do `ENV["GPG_TTY"] = ENV["HOMEBREW_GPG_TTY"]` and add the `GPG_TTY` to list this instead:

https://github.com/Homebrew/brew/blob/7466d371f5222e3d68c6748052024e255f290f5c/bin/brew#L78

**Comment by tuzi3040** [comment]
> Ok. I'd suggest instead that code be added here

Seems some `git commit` don't runs `Utils::Git.setup_gpg!` in advance, like `bump-(?:formula|cask)-pr` use [`GitHub.create_bump_pr`](https://github.com/Homebrew/brew/blob/2e6b6ab3a20da503ba2a22a37fdd6bd936d818ed/Library/Homebrew/utils/github.rb#L534), and [`bump-revision`](https://github.com/Homebrew/brew/blob/d53dab62c9de8fe7bc34c69fe8a44fb0b8fd32b6/Library/Homebrew/dev-cmd/bump-revision.rb#L74), which will also need `ENV["GPG_TTY"] = ENV["HOMEBREW_GPG_TTY"]`, or migrate to `Git.setup_gpg!`.

**Pull request closed without merging**
