### PR TITLE
Readme: tweak wording

### PR DESCRIPTION
**Pull request by bayandin**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----
This PR renames a section in README.md from `Who Are You?` to `Who We Are`.
The current wording confuses me a bit (because it's not clear whether "you" refers to a reader or an author).

If it's only me, I'm ok with keeping it as it is 🙂

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> The current wording confuses me a bit (because it's not clear whether "you" refers to a reader or an author).

I find the same thing with "we" as I assume it refers to the reader 🤣. Interested what others think, though.

**Comment by vitorgalvao** [comment]
I think of a piece of text as something an author is communicating, as opposed to something the reader is thinking. So “you” refers to the reader and “I” or “we” to the author(s).

Considering the PR template uses “you” to refer to the reader (every check starts with “Have you”), I can see how the “you” in the README can be confusing.

**Comment by issyl0** [comment]
I agree with this change.

**Comment by MikeMcQuaid** [comment]
Fine with me, thanks @bayandin!

**Pull request merged**
