### PR TITLE
brew cleanup --git-gc

### PR DESCRIPTION
**Pull request by stefansundin**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

I have been trying to free up some space on my Mac and I saw that my Homebrew .git directories were taking up a few hundred MB. I was hoping `git gc` would free up more space, so I was a little bit disappointed. But in any case I think it may be worth considering adding this to make it easier for users to do it themselves.

What I ran before I wrote this:

```
$ cd /usr/local/Homebrew
$ find . -name .git | xargs du -hs
1.1M  ./Library/Taps/heroku/homebrew-brew/.git
 74M  ./Library/Taps/homebrew/homebrew-core/.git
182M  ./Library/Taps/homebrew/homebrew-cask/.git
4.9M  ./Library/Taps/homebrew/homebrew-bundle/.git
1.5M  ./Library/Taps/homebrew/homebrew-services/.git
240M  ./Library/Taps/caskroom/homebrew-cask/.git
1.3M  ./Library/Taps/aws/homebrew-tap/.git
 50M  ./.git
$ find . -name .git | xargs -I % git -C % gc
$ find . -name .git | xargs du -hs
152K  ./Library/Taps/heroku/homebrew-brew/.git
 48M  ./Library/Taps/homebrew/homebrew-core/.git
173M  ./Library/Taps/homebrew/homebrew-cask/.git
1.4M  ./Library/Taps/homebrew/homebrew-bundle/.git
236K  ./Library/Taps/homebrew/homebrew-services/.git
237M  ./Library/Taps/caskroom/homebrew-cask/.git
300K  ./Library/Taps/aws/homebrew-tap/.git
 43M  ./.git
```

And now I would just need to run `brew cleanup --git-gc`.

If this functionality is desired and the code looks good, then I can try to add a test. Let me know what other changes you'd like to see. Thanks!

### CODE REVIEW

**Comment by reitermarkus** [comment]
You should run `brew untap caskroom/cask`.

**Comment by MikeMcQuaid** [comment]
How long does this take to run? As you point out: it's not a lot of space saving so unless it's (very) quick: I don't think it's worth it, sorry 😭

**Comment by dtrodrigues** [comment]
I ran the commands locally and while I wasn't timing it, it seemed to take quite some time (minutes not seconds) to finish and it only reduced my total size from something like 6xx MB to 5xx MB. If there was a bigger reduction or it was quicker, it might make sense but given the speed to space savings ratio, I don't think it's worth it.

**Comment by stefansundin** [comment]
> You should run `brew untap caskroom/cask`.

Thanks!

> How long does this take to run? As you point out: it's not a lot of space saving so unless it's (very) quick: I don't think it's worth it, sorry 😭

I agree it's not worth running often, which is why it should not be used by default or very often. I see now that I forgot to actually check `git_gc?`, but my intention was to only run this on demand. As for whether or not to include it, keep in mind that the bloat builds up over time and it depends on how often you have pulled new changes (and other factors), so while it only saved me a hundred MB or so (which is still pretty ok in my opinion), it may prove useful for others who have a more bloated repo.

But of course the choice is yours, so feel free to close this PR. Hopefully google will help people find the bash commands above if there are people looking for how to do this.

**Comment by MikeMcQuaid** [comment]
> that the bloat builds up over time

Kinda, Git will run `gc` itself when it determines it is needed on `git fetch` operations.



> But of course the choice is yours, so feel free to close this PR.

Thanks for understanding ❤️. Yeh, will pass on this for now. Thanks anyway!

**Pull request closed without merging**
