### PR TITLE
Cask Refactoring

### PR DESCRIPTION
**Pull request by reitermarkus**

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@reitermarkus 👍 Feel free to self-merge anything with Cask-only changes (not that this is) in future as soon as the "default" CI is 💚.

**Comment by reitermarkus** [comment]
@MikeMcQuaid, well it started out being cask-only, but of course I couldn't stop refactoring. :smile: 

> Feel free to self-merge anything with Cask-only changes

Will do, but I don't have commit access yet.

**Comment by MikeMcQuaid** [comment]
@reitermarkus You should do. On this repo we use the "Merge Pull Request" button for everything. Can you not click it? Feel free to try to merge this PR.

**Comment by reitermarkus** [comment]
No, it's greyed out. (”You're not authorized to merge this pull request.“)

**Comment by MikeMcQuaid** [comment]
@reitermarkus How about now?

**Comment by reitermarkus** [comment]
All green.

**Pull request merged**
