### PR TITLE
DependencyCollector: Add java_dep_if_needed [Linux]

### PR DESCRIPTION
**Pull request by sjackman**
Use the `openjdk` formula if it's installed.
Use the host's Java if it's sufficient.
Otherwise install the `openjdk` formula.

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

### CODE REVIEW

**Comment by sjackman** [comment]
This change is hopefully the last fix needed to transition `Brewsci/bio` to using Homebrew/brew rather than Linuxbrew/brew.

**Comment by MikeMcQuaid** [comment]
This looks a lot like `default_formula` written another way. Are you sure it's sensible to allow either `openjdk` or any satisfaction of the Java requirement?

**Comment by sjackman** [comment]
The `openjdk` keg is 170 MB, and many systems already have Java installed, so I was aiming to avoid installing it unnecessarily. `JavaRequirement` tests that the system-provided Java meets the required minimum version, so it seems sensible to me.

**Comment by jonchang** [comment]
Anecdotally, I haven't had any issues relying on system Java on Linux on even a CentOS install, which is usually a few versions behind.

**Comment by sjackman** [comment]
FWIW we've been using this patch in Linuxbrew/brew since 1.5.5 (2018-03-02).

**Comment by MikeMcQuaid** [comment]
I’m away at a conference but will get back to you further ASAP when given more review and thoughts. Thanks!

**Comment by MikeMcQuaid** [comment]
My objections still stand that I think having two paths for resolving Java is a bad idea but given it's Linux-only I don't care enough to block this being merged. :shipit:

**Comment by sjackman** [comment]
Objection noted. Thanks for merging, Mike. I'm going to try migrating Brewsci/bio to Homebrew/brew now.

**Pull request merged**
