### PR TITLE
Make `brew typecheck --update --suggest-typed` bump strictness further

### PR DESCRIPTION
**Pull request by issyl0**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

- Not only `false` to `true` but `true` to `strict`.
- Only humans every run this, but our goal is to increase the typechecking in our files to get to `strict` everywhere so let's make that easy to remember to do.
- Inspired by https://github.com/Homebrew/brew/pull/17410#issuecomment-2143960238.

### CODE REVIEW

**Review by apainintheneck — APPROVED** [review]
The change looks good and works for me locally.

My only nit is that the `brew type check --update --suggest-typed` exits with a non-zero exit code when there are files that can be bumped up a strictness level. It seems like it should still exit successfully since this is only a suggestion.

```
Error: Failure while executing; `bundle exec spoom srb bump --dry --from true --to strict --sorbet /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-0.5.11406/bin/srb\ tc` exited with 1.
```

**Comment by MikeMcQuaid** [comment]
Thanks @issyl0!

> My only nit is that the `brew type check --update --suggest-typed` exits with a non-zero exit code when there are files that can be bumped up a strictness level. It seems like it should still exit successfully since this is only a suggestion.

I think with `--update` supplied it should do the bumping for us automatically.

**Comment by apainintheneck** [comment]
Yeah, if that's possible, that would be great.

**Comment by issyl0** [comment]
Yeah, removing `--dry` should do it.

**Comment by MikeMcQuaid** [comment]
Ok, think this is working as expected then, thanks @issyl0!

**Pull request merged**
