### PR TITLE
pr-{publish,pull}: autosquash by default

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

This allows dispatching the publish workflow via the GitHub UI to have
the exact same behaviour as doing `brew pr-publish`.

Closes Homebrew/homebrew-core#94704.

### CODE REVIEW

**Comment by carlocab** [comment]
@dawidd6 you were right about #11734 after all!

**Review by dawidd6 — APPROVED** [review]

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by carlocab** [comment]
```
 1:3  error  'Adding Software to Homebrew'   Homebrew.Titles 
             should be in title case                         

✖ 1 error, 0 warnings and 0 suggestions in 58 files.
```
Is that not in title case?

**Comment by MikeMcQuaid** [comment]
@carlocab `Adding Software To Homebrew` maybe?

**Comment by carlocab** [comment]
Yea, "to" must be capitalised according to the AP style guide. Everyone else (AMA, APA, Bluebook, Chicago, MLA, NYT, and Wikipedia) do not capitalise "to".

**Comment by carlocab** [comment]
Yea, that checks out:

https://github.com/Homebrew/brew/blob/89ab131984d4bacd0f4d10d7cdf9ab8675206ad8/docs/vale-styles/Homebrew/Titles.yml#L6

**Review by Rylan12 — APPROVED** [review]
Looks good to me! Thanks!

**Pull request merged**
