### PR TITLE
feat: Add `brew doctor --ignore-warnings`

### PR DESCRIPTION
**Pull request by 9999years**
When `brew doctor` is run, `brew` exits with a non-zero status if any warnings or errors are encountered. However, this groups warnings and errors together, but (as the output notes) warnings can be innocuous:

> Please note that these warnings are just used to help the Homebrew
> maintainers with debugging if you file an issue. If everything you use
> Homebrew for is working fine: please don't worry or file an issue;
> just ignore this. Thanks!

The `--ignore-warnings` switch makes it possible for automated tools interacting with Homebrew to distinguish between warnings and hard errors.

```
$ brew doctor --ignore-warnings
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  graphql-playground
$ echo "$?"
0
```

Hard errors will still cause a non-zero exit status:

```
$ brew doctor --ignore-warnings
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: gettext files detected at a system prefix.
These files can cause compilation and link failures, especially if they
are compiled with improper architectures. Consider removing these files:
  /opt/homebrew/lib/libgettextlib.dylib
  /opt/homebrew/lib/libintl.dylib
  /opt/homebrew/include/libintl.h
Error: unknown or unsupported macOS version: :dunno
$ echo "$?"
1
```

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> The `--ignore-warnings` switch makes it possible for automated tools interacting with Homebrew to distinguish between warnings and hard errors.

There is no distinction in `brew doctor` made between warnings and errors. 

Automated tools should either avoid running `brew doctor` at all or ensure that all warnings are fixed if it's essential that it passes.



> Error: unknown or unsupported macOS version: :dunno

This is not a `brew doctor` warning, it's a random Homebrew warning that will trigger from many other commands.

**Comment by 9999years** [comment]
> This is not a `brew doctor` warning, it's a random Homebrew warning that will trigger from many other commands.

I understand that (although perhaps it _should_ be a `brew doctor` error). What command would you recommend I run to check for this error, if not `brew doctor`?

**Comment by MikeMcQuaid** [comment]
> What command would you recommend I run to check for this error, if not `brew doctor`?

How are you triggering this error? It seems like you're on an unknown macOS version?

**Comment by 9999years** [comment]
I maintain a developer environment bootstrapping tool which (among other things) installs Homebrew and then PostgreSQL with Homebrew. I'm working on a feature to upgrade the PostgreSQL installation. However, we only use Homebrew for PostgreSQL, so developers rarely update it on their own. As a result, we have a bunch of engineers running macOS Sonoma with versions of Homebrew too old to support macOS Sonoma.

I can solve this with `brew update`, but the tool tries to avoid doing unnecessary work, so I'd like to avoid it if possible. Therefore, I'd like to detect if the current version of macOS is supported by the current version of Homebrew.

Ideally, I'd also like to catch any other show-stopper errors with the Homebrew installation, and I was hoping I could use `brew doctor` for this purpose.

**Comment by 9999years** [comment]
BTW I appreciate you taking the time to talk this over! I would've included more context in the original PR description but I thought the feature was uncontroversial enough that it wasn't warranted.

**Comment by Bo98** [comment]
That error isn't an intentional from `brew doctor` - it's just you hitting a code path that is immediately aborting on an invalid macOS. If it was an intentional error it would have a proper message and wouldn't abort immediately. This is technically a bug so could be fixed if someone finds where it breaks.

You could try `brew doctor check_for_unsupported_macos`. It does however also check for old macOS that are semi-unsupported (i.e. Big Sur and earlier).

**Comment by MikeMcQuaid** [comment]
Sorry, passing on this PR but hopefully @Bo98's suggested workaround is useful.

**Comment by 9999years** [comment]
@Bo98 Thanks, `brew doctor check_for_unsupported_macos` works great for this!

**Pull request closed without merging**
