### PR TITLE
Recover system $TMPDIR for emacsclient

### PR DESCRIPTION
**Pull request by tshu-w**
Try to fix: https://github.com/Homebrew/brew/issues/17334,

I'm not sure if `Etc.systmpdir` is equal to `TMPDIR`, but it works for me.

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
Seems ok but might not work if someone sets a custom `TMPDIR`, so a full fix might be to store the original `TMPDIR` somewhere like we do for `PATH`.

**Comment by tshu-w** [comment]
> like we do for `PATH`.

Would you mind share the code about this?

**Comment by MikeMcQuaid** [comment]
> By the way, @MikeMcQuaid asks me to modify only the `Library/Homebrew/dev-cmd/edit.rb`, in which case I cannot save the original `TMPDIR`.

@tshu-w It's ok to have `TMPDIR` added to this list: https://github.com/Homebrew/brew/blob/7683b22b6196d8dc276c53a6441f0c5251dc7847/bin/brew#L185

this will set `HOMEBREW_TMPDIR` which you can then use `ENV["TMPDIR"] = ENV["HOMEBREW_TMPDIR"]` or similar to set back in `dev-cmd/edit.rb`

**Comment by tshu-w** [comment]
As suggested by @Bo98 @MikeMcQuaid, I open a new https://github.com/Homebrew/brew/pull/18260.

**Comment by MikeMcQuaid** [comment]
@tshu-w Thanks! For future reference: feel free to just push (force pushing if necessary) to existing PRs.

**Pull request closed without merging**
