### PR TITLE
Add PYTHONDONTWRITEBYTECODE to common_stage_test_env.

### LINKED ISSUE #14274: Speed up Python tests by not writing bytecode
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

`PYTHONDONTWRITEBYTECODE` is an environment variable that disables the writing of Python bytecode files when modules are loaded. By setting this environment variable during our CI runs, we can reduce the overall CI time with no loss of functionality.

When this value is set Python will not compile modules to bytecode and cache them at runtime. 

This should also not byte-compile all modules while installing dependencies ([i.e here](https://github.com/Homebrew/homebrew-core/actions/runs/3736404369/jobs/6340746247#step:6:16567))

```
   byte-compiling /opt/homebrew/Cellar/jupyterlab/3.5.2/libexec/lib/python3.10/site-packages/urllib3/filepost.py to filepost.cpython-310.pyc
    byte-compiling /opt/homebrew/Cellar/jupyterlab/3.5.2/libexec/lib/python3.10/site-packages/urllib3/fields.py to fields.cpython-310.pyc
    byte-compiling /opt/homebrew/Cellar/jupyterlab/3.5.2/libexec/lib/python3.10/site-packages/urllib3/util/queue.py to queue.cpython-310.pyc
    byte-compiling /opt/homebrew/Cellar/jupyterlab/3.5.2/libexec/lib/python3.10/site-packages/urllib3/util/ssltransport.py to ssltransport.cpython-310.pyc
    byte-compiling /opt/homebrew/Cellar/jupyterlab/3.5.2/libexec/lib/python3.10/site-packages/urllib3/util/proxy.py to proxy.cpython-310.pyc
    byte-compiling /opt/homebrew/Cellar/jupyterlab/3.5.2/libexec/lib/python3.10/site-packages/urllib3/util/wait.py to wait.cpython-310.pyc
    byte-compiling /opt/homebrew/Cellar/jupyterlab/3.5.2/libexec/lib/python3.10/site-packages/urllib3/util/request.py to request.cpython-310.pyc
    byte-compiling /opt/homebrew/Cellar/jupyterlab/3.5.2/libexec/lib/python3.10/site-packages/urllib3/util/timeout.py to timeout.cpython-310.pyc
    byte-compiling /opt/homebrew/Cellar/jupyterlab/3.5.2/libexec/lib/python3.10/site-packages/urllib3/util/__init__.py to __init__.cpython-310.pyc
    byte-compiling /opt/homebrew/Cellar/jupyterlab/3.5.2/libexec/lib/python3.10/site-packages/urllib3/util/response.py to response.cpython-310.pyc
```

### What is the motivation for the feature?

Our CI time is valuable, and changing python versions incurs a lot of CI time.

### How will the feature be relevant to at least 90% of Homebrew users?

Quicker builds in aggregate = faster releases?

### What alternatives to the feature have been considered?

Not doing this, which is fine?

### PR DESCRIPTION
**Pull request by orf**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Closes #14274

### CODE REVIEW

**Comment by Bo98** [comment]
> environment variables used at both build and test time

Do we actually want this at build time?

**Comment by orf** [comment]
I think it's sort of required: we build before testing, and bytecode is produced during the build.

This change means bytecode isn't compiled and written until the user first runs the tool.

**Comment by Bo98** [comment]
The notable difference being that pyc generated in the build stage will be shipped in the bottle if the pyc is from the formula itself being built.

**Comment by Bo98** [comment]
Actually nevermind: https://github.com/Homebrew/brew/blob/974984d1f52fe7b27f6d5bac6c683d0d9659ad33/Library/Homebrew/dev-cmd/bottle.rb#L390

This seems fine then.

**Review by Bo98 — APPROVED** [review]

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Makes sense, thanks again @orf!

**Pull request merged**
