### PR TITLE
Add shims/super/gcc-8 and shims/super/g++-8

### PR DESCRIPTION
**Pull request by sjackman**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

These shims are conspicuously missing.

### CODE REVIEW

**Comment by sjackman** [comment]
This missing `gcc-8` shim caused Superenv not to be used.
No superenv meant no `refurbish_args` to remove `cc -g`, which meant debugging symbols remained.
Debugging symbols caused the bottles of anything built with `gcc-8` to be detected as non-relocatable, when some may be `cellar :any`.

**Comment by sjackman** [comment]
Note that `refurbish_args` is only used by default with the `make` build system. Formulae built with build systems other than `make` may still have debugging symbols, and may be incorrectly detected as not being relocatable.

**Comment by sjackman** [comment]
Note that `shims/linux/super/gcc-8` from abac6dfaf8409695c367eef4c4722780c47362c5 `Add shims/linux/super`

**Comment by MikeMcQuaid** [comment]
Thanks again @sjackman!

**Comment by sjackman** [comment]
> Would be good to perhaps use the GCC regex or similar to produce a simple test for the existence of these files so it doesn’t bite us in future?

Merged without this change, but yes very good idea.

**Pull request merged**
