### PR TITLE
upgrade: unlink kegs of renamed formulae

### PR DESCRIPTION
**Pull request by alyssais**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

This is a solution to #1770.

Because this change refactors some alias-resolving logic, I re-ran all the test commands I used in #971 to make sure that behaviour was still correct.

This PR changes the way <kbd>brew upgrade</kbd> finds linked kegs to be unlinked. Instead of looking for the linked keg based on the current name of the formula, it loops through all linked kegs to find any that were installed with the formula under any name. For efficiency (to avoid iterating all linked kegs for every formula) the list of linked kegs is generated for all formulae to be uninstalled in the same iteration and stored in an instance variable.

While this fixes the problem in #1770, I can see kegs installed with previous names of formulae causing lots more problems in future, because a lot of the code in `Formula` assumes that kegs can be found on the filesystem based on the current name of the formula. So, I'm wondering if, instead of working around that in this one specific case, it might be worth changing `brew upgrade` to migrate any kegs of renamed formulae?

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> This PR changes the way brew uninstall finds linked kegs to be unlinked.

Can you elaborate a bit more on this; I'm not seeing any `uninstall` changes here?



> So, I'm wondering if, instead of working around that in this one specific case, it might be worth changing brew upgrade to migrate any kegs of renamed formulae?

`brew update` does migrate kegs of renamed formulae so I'm not entirely convinced this is an issue that can be exposed to users rather than e.g. developers who haven't setup a tap migration properly.

**Comment by alyssais** [comment]
> Can you elaborate a bit more on this; I'm not seeing any `uninstall` changes here?

Meant `upgrade`, sorry. I'll update the PR body.

**Comment by alyssais** [comment]
> `brew update` does migrate kegs of renamed formulae so I'm not entirely convinced this is an issue that can be exposed to users rather than e.g. developers who haven't setup a tap migration properly.

That seems reasonable. I did have to disable auto-update to test this.

**Comment by MikeMcQuaid** [comment]
I think there may be some rom for improvement here around this but will wait and see if there's a few more issues first.

**Comment by vladshablinsky** [comment]
I think it's not the best solution here, because what happens in `upgrade` for renamed formula is just ignoring the rename and install formula with new name as some other formula which has same binaries. No rename is detected here. Still, this is a solution, because what we do on migrations is unlinking old name, moving it to the new cellar and then linking, right?

I think this solution leaves us with `oldname` and `newname` installed, no additional links created and we can't even migrate `oldname` since `newname` already exist. Which btw won't be the case if we merge #2359.

**Pull request closed without merging**
