### PR TITLE
Use install(1) instead of mkdir(1) + chown(8)

### PR DESCRIPTION
**Pull request by rjc**
Two-step action can be reduced to a single step - fewer things to type, fewer mistakes to make :^)

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by rjc** [comment]
The 2nd commit replaces usage of the obsoleted whoami(1) utility with the id(1) one.

**Comment by MikeMcQuaid** [comment]
Would rather leave this as-is, sorry. It's easier to understand any individual failures when it's two steps. We've also not had any problems with this approach.

**Comment by rjc** [comment]
Understood. What about the 2nd commit - using utilities marked as *obsolete*?

**Comment by vitorgalvao** [comment]
@MikeMcQuaid I agree, but maybe changing the `whoami` to `id -un` makes sense. `man whoami` says in the description:

> The whoami utility has been obsoleted by the id(1) utility, and is equivalent to ``id -un''.

**Comment by MikeMcQuaid** [comment]
If it's changed consistently everywhere: we'll consider it. I don't personally see the need to change something that is working fine, though. I'd be interested whether that message still applies on e.g. 10.5 and in general whether it behaves identically in literally every situation on every OS. Regardless, I'm still not sure it's worth the change until it's actually fixing user issues.

As a personal preference I also find `whoami` infinitely more readable than `id -un` which doesn't even have the ability to do e.g. `id --effective-user-id --name` for readability.

**Comment by rjc** [comment]
id(1) is a [`POSIX`](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/id.html) utility - whoami(1) is **not**

Short, single-dash options, as specified by `POSIX`, are available on any `POSIX`-compliant OS - double-dash options are `GNU` extensions specific *mostly* to `Linux`.

And yes - `whoami` and `id -un` **are** equivalent - the latter construct is specifically for `whoami` backward-compatibility.

**Comment by MikeMcQuaid** [comment]
> id(1) is a [`POSIX`](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/id.html) utility - whoami(1) is **not**

This makes literally no difference to Homebrew which only targets macOS and Linux both of which provide `whoami`.

> Short, single-dash options, as specified by `POSIX`, are available on any `POSIX`-compliant OS - double-dash options are `GNU` extensions specific _mostly_ to `Linux`.

Many, many non-GNU tools provide double-dash options. They are significantly more readable which is why they are preferable. If no POSIX utilities ever provide them: that's a pretty strong argument _against_ us using them.

**Comment by MikeMcQuaid** [comment]
> So are you interested in `id`'s behaviour on every OS or just `macOS` and `Linux`? :^)

I should have elaborated "every OS we attempt to support" which is just macOS and Linux.

**Comment by vitorgalvao** [comment]
> apart from the fact that `whoami(1)` utility, which comes from `2BSD` BTW, has been deprecated for [_at least_ 25 years](https://www.freebsd.org/cgi/man.cgi?query=whoami)?

To me, that’s an argument to not stop using `whoami`. If it’s been deprecated for 25 years but it’s still here and working, will it ever be removed, really?

> > Many, many non-GNU tools provide double-dash options.
> 
> True... unfortunately.

You lost me there. Very few tools provide long-form options without a short-form equivalent, so what’s the problem?

> > They are significantly more readable which is why they are preferable.
> 
> Debatable. I prefer short, i.e. single-dash and single letter, options

Single letter options are fine when you’re writing commands interactively. When you’re typing a script, long-form options are better *every time* because they are clearer.

> quicker (less typing)

Which is irrelevant on a script. Comprehension (readability) later on is way more important.

> (long options are just asking for a typo!).

If you mistype a long-form option, you get an error. If you mistype a short-form option, you may activate a different option and screw up you work.

> At the end of the day, what are manual pages for, then!?

They’re definitely not for you to need to keep them open and reference multiple times when reading a single line of a script. With long-form options, you at least have a chance of understanding what is happening without needing to read the `man` pages.

Are you advocating that it’s fine for interfaces to be confusing as long as they have a manual? That literally gets people killed.

> > If no POSIX utilities ever provide them: that's a pretty strong argument _against_ us using them.
> 
> No sure if I understand correctly - strong argument **against** using `POSIX` utilities?

Yes. If being POSIX doesn’t offer any benefit over the alternative (in our use cases) but it does offer disadvantages (again, for our desired usage), there’s no point to using them.

**Comment by rjc** [comment]
@MikeMcQuaid 

> I should have elaborated "every OS we attempt to support" which is just macOS and Linux.

Then there's no issue here - they behave **exactly** the same way. That's one of the arguments **for** `POSIX` - portability!

**Comment by rjc** [comment]
@vitorgalvao 

> > No sure if I understand correctly - strong argument against using POSIX utilities?
>
> Yes. If being POSIX doesn’t offer any benefit over the alternative (in our use cases) but it does offer disadvantages (again, for our desired usage), there’s no point to using them.

You do know *what* `POSIX` is and *why* it is there, right?

**Comment by vitorgalvao** [comment]
> You do know _what_ `POSIX` is and _why_ it is there, right?

I also know what the statue of liberty is and why it’s there. It doesn’t mean it’s useful for the goals of the project.

> Then there's no issue here - they behave **exactly** the same way. That's one of the arguments **for** `POSIX` - portability!

Again, portability for portability’s sake means nothing. We don’t need that portability for the systems we act on. We are arguing that *in this case*, readability trumps portability (because we don’t need that portability and care about readability).

**Comment by rjc** [comment]
@vitorgalvao

> > apart from the fact that `whoami(1)` utility, which comes from `2BSD` BTW, has been deprecated for [_at least_ 25 years](https://www.freebsd.org/cgi/man.cgi?query=whoami)?
> 
> To me, that’s an argument to not stop using `whoami`. If it’s been deprecated for 25 years but it’s still here and working, will it ever be removed, really?

Utility has been deprecated - it even says so in the manual page -
`id(1)` is the replacement and is also portable (`POSIX`).

*- Nah, we're good - not changing*.

Do you see where I am going with this? Yes, that kind of approach
contributes to the above problem.

> > At the end of the day, what are manual pages for, then!?
> 
> They’re definitely not for you to need to keep them open and reference multiple times when reading a single line of a script. With long-form options, you at least have a chance of understanding what is happening without needing to read the `man` pages.
> 
> Are you advocating that it’s fine for interfaces to be confusing as long as they have a manual? That literally gets people killed.

I'm advocating for reading manual pages, lack of which I consider a bug.

**Comment by rjc** [comment]
On Fri, Nov 23, 2018 at 06:00:01PM GMT, Vítor Galvão wrote:
> > You do know _what_ `POSIX` is and _why_ it is there, right?
> 
> I also know what the statue of liberty is and why it’s there. It doesn’t mean it’s useful for the goals of the project.
> 
> > Then there's no issue here - they behave **exactly** the same way. That's one of the arguments **for** `POSIX` - portability!
> 
> Again, portability for portability’s sake means nothing. We don’t need that portability for the systems we act on. We are arguing that *in this case*, readability trumps portability (because we don’t need that portability and care about readability).

Well, you support two distinct Unix families - the *BSDs and Linux - so
portability *is* important to you, at least at some level.
Ironically, `POSIX` made the job much easier! ;^)

Anyway, this was the part that has clearly confused me.

Also, I should have spotted `set +o posix` earlier.

Thanks for clarifying.

/me shrugs

**Comment by rjc** [comment]
@vitorgalvao

> > apart from the fact that `whoami(1)` utility, which comes from `2BSD` BTW, has been deprecated for [_at least_ 25 years](https://www.freebsd.org/cgi/man.cgi?query=whoami)?
> 
> To me, that’s an argument to not stop using `whoami`. If it’s been deprecated for 25 years but it’s still here and working, will it ever be removed, really?

Utility has been deprecated - it even says so in the manual page -
`id(1)` is the replacement and is also portable (`POSIX`).

*- Nah, we're good - not changing*.

Do you see where I am going with this? Yes, that kind of approach
contributes to the above problem.

> > At the end of the day, what are manual pages for, then!?
> 
> They’re definitely not for you to need to keep them open and reference multiple times when reading a single line of a script. With long-form options, you at least have a chance of understanding what is happening without needing to read the `man` pages.
> 
> Are you advocating that it’s fine for interfaces to be confusing as long as they have a manual? That literally gets people killed.

I'm advocating for reading manual pages, lack of which I consider a bug.

**Comment by rjc** [comment]
> > You do know _what_ `POSIX` is and _why_ it is there, right?
> 
> I also know what the statue of liberty is and why it’s there. It doesn’t mean it’s useful for the goals of the project.
> 
> > Then there's no issue here - they behave **exactly** the same way. That's one of the arguments **for** `POSIX` - portability!
> 
> Again, portability for portability’s sake means nothing. We don’t need that portability for the systems we act on. We are arguing that *in this case*, readability trumps portability (because we don’t need that portability and care about readability).

Well, you support two distinct Unix families - the *BSDs and Linux - so
portability *is* important to you, at least at some level.
Ironically, `POSIX` made the job much easier! ;^)

Anyway, this was the part that has clearly confused me.

Also, I should have spotted `set +o posix` earlier.

Thanks for clarifying.

/me shrugs

**Comment by MikeMcQuaid** [comment]
Thanks for the conversation but let’s leave this one now.

**Pull request closed without merging**
