### PR TITLE
Try homebrew curl on unhandled SSL protocol.

### PR DESCRIPTION
**Pull request by jameshilliard**
Needed for some formulas like theora.

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [N/A] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> Needed for some formulas like theora.

@jameshilliard can you elaborate more on this? What does your `brew config` and `brew doctor` output?

**Comment by jameshilliard** [comment]
It's easy to reproduce, just try building theora from source like this:
```
brew install --build-from-source theora --debug
```

error log:
```
==> Starting build of theora
==> brew fetch --retry theora --build-bottle --force
==> FAILED
==> Downloading https://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.bz2
curl: (35) error:1400442E:SSL routines:CONNECT_CR_SRVR_HELLO:tlsv1 alert protocol version
==> Retrying download
==> Downloading https://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.bz2
curl: (35) error:1400442E:SSL routines:CONNECT_CR_SRVR_HELLO:tlsv1 alert protocol version
Error: Failed to download resource "theora"
Download failed: https://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.bz2
```

By running the built in osx curl in verbose mode you can see the protocol negotiation failure due to osx's curl apparently not supporting TLSv1.3 as appears to be required by the xiph server:
```
$ /usr/bin/curl -vvv https://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.bz2
*   Trying 140.211.166.31...
* TCP_NODELAY set
* Connected to downloads.xiph.org (140.211.166.31) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS alert, protocol version (582):
* error:1400442E:SSL routines:CONNECT_CR_SRVR_HELLO:tlsv1 alert protocol version
* Closing connection 0
curl: (35) error:1400442E:SSL routines:CONNECT_CR_SRVR_HELLO:tlsv1 alert protocol version
```

**Comment by nandahkrishna** [comment]
Just adding a note that we've seen macOS `curl`'s lack of TLS v1.3 support cause issues, as noted in https://github.com/Homebrew/homebrew-core/pull/78815 and https://github.com/Homebrew/homebrew-core/pull/78711 among others. I can reproduce this locally too, and I've attached my `brew config` and `brew doctor`.
```
➜ brew fetch --build-from-source theora
==> Downloading https://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.bz2
##O=#  #
curl: (35) error:1400442E:SSL routines:CONNECT_CR_SRVR_HELLO:tlsv1 alert protocol version
Error: Failed to download resource "theora"
Download failed: https://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.bz2
```
`brew config`:
```
➜ brew config
HOMEBREW_VERSION: 3.1.12-25-gd391331
ORIGIN: https://github.com/Homebrew/brew
HEAD: d3913310268a1877763a6b3e10382984f67e1fde
Last commit: 8 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 97affcb192c6a3ff24b3647419f5bc8334abb4af
Core tap last commit: 18 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BAT: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.h5vJH5v9BU/org.macosforge.xquartz:0
HOMEBREW_EDITOR: /usr/local/bin/nvim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.4-x86_64
CLT: 12.5.0.22.9
Xcode: 12.5
XQuartz: 2.7.11 => /opt/X11
```
`brew doctor`:
```
➜ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  dgraph
  proj@7
```

**Comment by MikeMcQuaid** [comment]
> By running the built in osx curl in verbose mode you can see the protocol negotiation failure due to osx's curl apparently not supporting TLSv1.3 as appears to be required by the xiph server:

Yup, reproduced, thanks for the instructions here.

I think we should handle this a different way, though. We need a way to indicate in formulae that Homebrew's `curl` is needed for downloading these sources e.g. `depends_on "curl" => :build` or even a new `depends_on "curl" => :fetch`.

**Comment by jameshilliard** [comment]
> I think we should handle this a different way, though. We need a way to indicate in formulae that Homebrew's `curl` is needed for downloading these sources e.g. `depends_on "curl" => :build` or even a new `depends_on "curl" => :fetch`.

Hmm, since this looks to be a more common issue than I expected it might get a bit annoying to deal with it that way as more download sites end up requiring TLSv1.3 or higher. I'm thinking we should maybe unconditionally use homebrew's curl when installed and install automatically if/when this error is encountered.

**Comment by MikeMcQuaid** [comment]
@jameshilliard I strongly disagree. If we get to the point it's needed for the majority of formulae: we could make it mandatory (when building from source). At the moment it's a small proportion of projects built from source (which is not the primary way of using Homebrew).

**Comment by jameshilliard** [comment]
> If we get to the point it's needed for the majority of formulae: we could make it mandatory (when building from source). At the moment it's a small proportion of projects built from source (which is not the primary way of using Homebrew).

Yeah, I mean that would also work, I'm just thinking using homebrew's curl by default when installed doesn't appear to have any downsides that I'm aware of as it should be newer than the built in. By the way is there a reason homebrew needs to use curl instead of just doing a download in the ruby code?

**Comment by MikeMcQuaid** [comment]
> I'm just thinking using homebrew's curl by default when installed doesn't appear to have any downsides that I'm aware of as it should be newer than the built in

It can be broken more easily in more ways.

> By the way is there a reason homebrew needs to use curl instead of just doing a download in the ruby code?

`curl` handles many more things than `open-api`.

**Comment by carlocab** [comment]
> I'm just thinking using homebrew's curl by default when installed doesn't appear to have any downsides that I'm aware of

Here's one downside that was once explained to me: having Homebrew `curl` installed creates risk of linkage with Homebrew's `libcurl` instead of the system one. We should avoid this when possible, as this can needlessly blow up a formula's dependency graph, and no one wants that.

**Comment by jameshilliard** [comment]
> > I'm just thinking using homebrew's curl by default when installed doesn't appear to have any downsides that I'm aware of
> 
> Here's one downside that was once explained to me: having Homebrew `curl` installed creates risk of linkage with Homebrew's `libcurl` instead of the system one. We should avoid this when possible, as this can needlessly blow up a formula's dependency graph, and no one wants that.

Couldn't we just have homebrew sanity check homebrew's curl and fallback to the built in version if it errors at all?

**Comment by MikeMcQuaid** [comment]
> Couldn't we just have homebrew sanity check homebrew's curl and fallback to the built in version if it errors at all?

Again: specifying this per formula is better than a "try something, fall back on errors".

**Pull request closed without merging**
