### PR TITLE
python_requirement: prefer Homebrew's Python

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

This avoids linkage to both system Python and Homebrew's python.

### CODE REVIEW

**Comment by DomT4** [comment]
Think this caused a problem with https://github.com/Homebrew/homebrew-core/pull/15941, FWIW.

**Comment by ilovezfs** [comment]
@DomT4 this is likely to cause all manner of problems but the MacVim bleeding needed to stop.

**Comment by ilovezfs** [comment]
@DomT4 you'll need to elaborate for me since I don't really see how this change impacts PYTHONPATH for python3.

**Comment by DomT4** [comment]
Oh, you are correct, sorry I misread the commit. I'll go hunting for the right breakage 🙈.

**Comment by ilovezfs** [comment]
@DomT4 what this _will_ totally as far as I know: you don't have `depends_on :python` listed as a dependency in a formula, with which you want to use system Python, in a multi-formula PR, but brew python happens to get installed along the way.

**Comment by DomT4** [comment]
Starting to wonder if my PR is an upstream thing, or a local thing, perhaps. Although I've checked my env for `PYTHON` stuff about 50 times, and there's nothing there. But I can checkout as far back as the `1.0.0` tag and still hit the problem:

```
==> python3 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/diffoscope/84/libexec/vendor --single-version-externally-managed --record=installed.txt
Failed to import the site module
Your PYTHONPATH points to a site-packages dir for Python 2.x but you are running Python 3.x!
     PYTHONPATH is currently: "/usr/local/Cellar/diffoscope/84/libexec/vendor/lib/python3.6/site-packages:/usr/local/lib/python2.7/site-packages"
     You should `unset PYTHONPATH` to fix this.
```

I managed to mislead myself by checking out `stable` and then it built fine, but I forgot I hadn't commented back out the `ENV.delete` initially, so 👏 👏  @ myself.

**Comment by DomT4** [comment]
Still fails with `HOMEBREW_ENV_FILTERING="1"` set as well, so presumably not local. Guess I'll move discussion over to the other PR since this seems completely unrelated then.

**Pull request merged**
