### PR TITLE
upgrade: check for already broken dependents

### PR DESCRIPTION
**Pull request by scpeters**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [X] Have you successfully run `brew style` with your changes locally?
- [X] Have you successfully run `brew tests` with your changes locally?

-----

After upgrading a formula, it currently [checks for broken dependents](https://github.com/Homebrew/brew/blob/12070b4c0fd0f41151c10ad2322168e7aa30fa9e/Library/Homebrew/upgrade.rb#L169-L181) after upgrading any outdated dependents. If there are no outdated dependents, [it exits early](https://github.com/Homebrew/brew/blob/12070b4c0fd0f41151c10ad2322168e7aa30fa9e/Library/Homebrew/upgrade.rb#L127-L130) and doesn't check for broken dependents. This adds an earlier check for already broken dependents so they can be fixed even if there are no outdated dependents. (sorry that's kind of a mouthful)

I duplicated the block that checks for broken dependents; let me know if it should have its own method instead.

I haven't profiled this, but I expect it will perform linkage checks for dependents more often.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> I duplicated the block that checks for broken dependents; let me know if it should have its own method instead.

Yes, I think this would be desirable.

> This adds an earlier check for already broken dependents so they can be fixed even if there are no outdated dependents.

So this fix, if I understand correctly, is to fix the case where they haven't been broken by this `brew upgrade` but may have done by e.g. a previous one or user action?

This behaviour (and possibly your previous PR) may also warrant being added to `cmd/install.rb` and `cmd/reinstall.rb` which also both perform some of these checks.

Just to call it out: it does seem potentially surprising that this would start reinstalling things that are unrelated to anything that's being upgraded. I think it's still probably the right move but might want to improve the messaging.

**Comment by scpeters** [comment]
> > I duplicated the block that checks for broken dependents; let me know if it should have its own method instead.
> 
> Yes, I think this would be desirable.

I moved the logic to a `check_broken_dependents` method in the same file in 24e7f55

> > This adds an earlier check for already broken dependents so they can be fixed even if there are no outdated dependents.
> 
> So this fix, if I understand correctly, is to fix the case where they haven't been broken by this `brew upgrade` but may have done by e.g. a previous one or user action?

That's correct

> This behaviour (and possibly your previous PR) may also warrant being added to `cmd/install.rb` and `cmd/reinstall.rb` which also both perform some of these checks.
> 
> Just to call it out: it does seem potentially surprising that this would start reinstalling things that are unrelated to anything that's being upgraded. I think it's still probably the right move but might want to improve the messaging.

Yes, if we make this change we should improve the messaging. Alternatively, we could put this behavior in a separate command `brew rebuild_broken_bottles` or `brew linkage --rebuild-broken-from-source`

**Comment by MikeMcQuaid** [comment]
Let's try this out for now and see how people react. Thanks again @scpeters 1

**Comment by scpeters** [comment]
thanks!

**Pull request merged**
