### PR TITLE
bump-formula-pr: gracefully handle unforkable repositories

### PR DESCRIPTION
**Pull request by alyssais**
Hello! 👋 It's been a while.

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

GitHub seems to be [discouraging](https://help.github.com/articles/allowing-people-to-fork-private-repositories-in-your-organization/) forking private repositories:

> By default, new organizations are configured to disallow the forking of private repositories.

bump-formula-pr tries to create its pull requests from a fork, so it can't be used for private taps set up in this way.

I've added a --no-fork option that will create PRs in the tap repo itself, rather than in a fork, to accommodate this use case.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
What about instead of being an option defaulting to not using a fork on private repositories?

**Comment by alyssais** [comment]
Works for me. Didn't want to change behaviour without discussing first. Would mean an extra API call to check the visibility before attempting to create the fork.

An alternative would be to try to fork the repo, and if we get the "Validation Fails" message from GitHub, assume forking is disabled and try to use the base repo instead.

Thoughts?

**Comment by MikeMcQuaid** [comment]
> An alternative would be to try to fork the repo, and if we get the "Validation Fails" message from GitHub, assume forking is disabled and try to use the base repo instead.

That seems good to me. Could do the API call then 👍

**Comment by MikeMcQuaid** [comment]
Nice work, thanks @alyssais!

**Pull request merged**
