### PR TITLE
Remove redirection for default prefixes

### PR DESCRIPTION
**Pull request by dduugg**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
This felt like unnecessary redirection to define a pair of constants

### CODE REVIEW

**Comment by Bo98** [comment]
This is so it gets overridden by https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/support/lib/default_prefix.rb.

Though I'm a little surprised this didn't fail any tests.

**Comment by dduugg** [comment]
ah, must be the magic that happens here? https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/spec_helper.rb#L36

I've removed the test file as well, but maybe we should improve the integration tests…

**Comment by Bo98** [comment]
Yeah I'm a bit suspicious - will check tonight.

**Comment by Bo98** [comment]
Hi sorry, I forgot to look at this.

Turns out `Homebrew.default_prefix?` is used very little - with one of the main usages disabled for integration tests anyway. So it's probably safe to remove given `HOMEBREW_PREFIX` itself is unchanged.

I'm not going to really be around until post-AGM now to be able to look any further but given tests pass this should be OK to merge.

**Comment by p-linnane** [comment]
Rebased to resolve hanging jobs with the new macOS 14 runner.

**Comment by MikeMcQuaid** [comment]
@dduugg what's the latest here?

**Comment by dduugg** [comment]
@Bo98 i'm going to click the button given "this should be OK to merge", but holler if you have any concerns.

**Comment by dduugg** [comment]
@Bo98 is this clear to go in?

**Review by Bo98 — APPROVED** [review]
Cautiously yeah. Seems weird to flip tests to be non-default-prefix but also seems to not break anything

**Pull request merged**
