### PR TITLE
Update to RuboCop 0.59.1.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@reitermarkus Can you hold off merging this until tomorrow? Want to cut a new tag tonight. Thanks!

**Comment by commitay** [comment]
Should this be fixed in `core` or disabled in the rubocop?

```console
$ brew style homebrew/core
== /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/cmd/brew-postgresql-upgrade-database.rb ==
C: 35:  1: rescue at 35, 0 is not aligned with begin at 29, 12.

4641 files inspected, 1 offense detected

```

**Comment by scpeters** [comment]
https://github.com/Homebrew/homebrew-core/blob/master/cmd/brew-postgresql-upgrade-database.rb#L29-L37

**Comment by reitermarkus** [comment]
Yeah, this should be disabled for now at least because this doesn't support the format where `rescue` is aligned with the first line. There is also a RuboCop issue for this somewhere.

**Pull request merged**
