### PR TITLE
formula_cellar_checks: .dylib and .framework are macOS-specific

### PR DESCRIPTION
**Pull request by maxim-belkin**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----
A follow-up to Homebrew/brew#4685: `.dylib` and `.framework` are macOS-specific, so moving them to `extend/os/mac/...`.

@sjackman

### CODE REVIEW

**Comment by sjackman** [comment]
```
==> brew man --fail-if-changed
==> Installing or updating 'ronn' gem
Successfully installed mustache-1.0.5
Building native extensions.  This could take a while...
Successfully installed rdiscount-2.2.0.1
Building native extensions.  This could take a while...
Successfully installed hpricot-0.8.6
Successfully installed ronn-0.7.3
4 gems installed
==> Tapping homebrew/bundle
Cloning into '/home/travis/build/Homebrew/brew/Library/Taps/homebrew/homebrew-bundle'...
Tapped 1 command (152 files, 549.6KB).
==> Tapping homebrew/services
Cloning into '/home/travis/build/Homebrew/brew/Library/Taps/homebrew/homebrew-services'...
Tapped 1 command (43 files, 198.5KB).
Writing markdown to /home/travis/build/Homebrew/brew/docs/Manpage.md
Writing man page to /home/travis/build/Homebrew/brew/manpages/brew.1
Writing man page to /home/travis/build/Homebrew/brew/manpages/brew-cask.1
==> FAILED
```
https://travis-ci.org/Homebrew/brew/jobs/419459474#L224

`brew man --fail-if-changed` is failing, which I'd guess is unrelated to this PR.
@maxim-belkin Once it's fixed in master, could you please rebase this PR onto master?

**Comment by maxim-belkin** [comment]
OK

```sh
$ cd $(brew --repo) && git checkout mac-libs
$ brew man --fail-if-changed
Writing markdown to /usr/local/Homebrew/docs/Manpage.md
Writing man page to /usr/local/Homebrew/manpages/brew.1
Writing man page to /usr/local/Homebrew/manpages/brew-cask.1
No changes to manpage output detected.
```

**Comment by MikeMcQuaid** [comment]
@sjackman That'll be the homebrew-bundle README update. Fixed in https://github.com/Homebrew/brew/pull/4747 and I'm rerunning this now.

**Comment by sjackman** [comment]
Merged. Thanks again, Maxim! 🏅

**Pull request merged**
