### PR TITLE
pathname: Use CI env variable rather than TRAVIS

### PR DESCRIPTION
**Pull request by sjackman**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Add `CIRCLECI`, `CIRCLE_*`, and `CI_*` to the white list.
See https://circleci.com/docs/2.0/env-vars/
and https://circleci.com/docs/1.0/environment-variables/

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Can you elaborate on why this is needed?

**Comment by MikeMcQuaid** [comment]
(To elaborate: Travis only is whitelisted because we use it for our Homebrew/brew CI).

**Comment by sjackman** [comment]
I feel that it's worth supporting external taps that wish to use CircleCI for CI. CircleCI may be used to build bottles for both macOS and Linux. `Homebrew/homebrew-test-bot` supports CircleCI.

**Comment by MikeMcQuaid** [comment]
@sjackman Circle CI is not unsupported as-is and none of these variables would be used in Homebrew internals. `brew test-bot` does not filter the environment. Can you be more specific about what the actual problem is you're trying to solve here?

**Comment by sjackman** [comment]
> `brew test-bot` does not filter the environment.

Ah, I didn't realize that. Thanks for the info. I suppose it's just for this one line then. Sorry that I hadn't included it in the original PR.

https://github.com/Homebrew/brew/pull/3627/files#diff-06540c12bb8e84922c0d329ed05b19bfR502

We run Linuxbrew/brew CI on both CircleCI and TravisCI. If it's not needed for Homebrew/brew though, then I'll close this PR.

**Comment by sjackman** [comment]
I suppose this PR could be useful for external taps running on CircleCI with
```
HOMEBREW_VERBOSE=1
HOMEBREW_VERBOSE_USING_DOTS=1
```
to avoid timeouts.

**Comment by MikeMcQuaid** [comment]
> Ah, I didn't realize that. Thanks for the info. I suppose it's just for this one line then. Sorry that I hadn't included it in the original PR.

Could that be `ENV["CI"]` or similar instead?

> We run Linuxbrew/brew CI on both CircleCI and TravisCI.

Why?

**Comment by sjackman** [comment]
> Could that be ENV["CI"] or similar instead?

Good idea. Works for me.

**Comment by sjackman** [comment]
>> We run Linuxbrew/brew CI on both CircleCI and TravisCI.

> Why?

We build bottles on CircleCI, so it's important that `brew tests` passes on both CircleCI and TravisCI. It's reasonably rare, but occasionally a test will pass on TravisCI but fail on CircleCI, due to differences in their configuration. For example, the version of `git` at `/usr/bin/git`. For example, `git clone` with `git` 1.8 outputs `Cloning into` to standard output, whereas recent versions of `git` output `Cloning into` to standard error. That difference causes a  `brew test` failure. If something like that slips through, every tap PR fails due to `brew tests` failing.

**Comment by sjackman** [comment]
TravisCI isn't actually using `git` 1.8. It's just an example of how a configuration difference of the host can cause `brew tests` to fail.

**Comment by MikeMcQuaid** [comment]
> That difference causes a brew test failure. If something like that slips through Linuxbrew/brew, every tap PR fails due to brew tests failing.

Tap PRs do not run `brew tests` so I'm still not sure I understand here.

**Comment by sjackman** [comment]
> Tap PRs do not run brew tests so I'm still not sure I understand here.

I got that wrong, sorry. Nonetheless, we run Linuxbrew/brew `test-bot` on CircleCI to ensure that `brew tests` passes on Ubuntu 16. TravisCI runs Ubuntu 14.

**Comment by MikeMcQuaid** [comment]
Thanks @sjackman!

**Comment by sjackman** [comment]
Thanks for merging, Mike!

**Pull request merged**
