### PR TITLE
Remove `CaskLoader::tap_paths`.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Remove the last usage of `CaskLoader::tap_paths`.

### CODE REVIEW

**Review by apainintheneck — APPROVED** [review]
Code looks good and I'm happy to get rid of this. I do think that at some point it would be nice to add some more tests for some of these new cask loaders but that's non-blocking.

**Comment by reitermarkus** [comment]
There are a bunch of new tests for the new rename logic, which also implicitly test the `FromDefaultNameLoader` and `FromNameLoader` by way of testing the warning messages for renames, which really is the main difference between them. Both subclass `FromTapLoader`, which also already has tests.

Probably the only one missing tests is `FromInstalledPathLoader`. That may still already be tested using some uninstall test, as that is really the only place where this loader is relevant.

**Comment by apainintheneck** [comment]
Good point. I wasn't looking at code coverage but instead at the tap loader tests directory so I didn't think of that.

**Comment by MikeMcQuaid** [comment]
Thanks @reitermarkus for PR and @apainintheneck for the review!

**Pull request merged**
