### PR TITLE
Fix reading HOMEBREW_LIVECHECK_WATCHLIST file

### PR DESCRIPTION
**Pull request by josh**
When setting a `HOMEBREW_LIVECHECK_WATCHLIST` environment variable, `livecheck` attempts to perform an IO read on a String when it probably expected a Pathname.

```
$ HOMEBREW_LIVECHECK_WATCHLIST="my_brew_livecheck_watchlist"  brew livecheck
Error: undefined method `read' for "my_brew_livecheck_watchlist":String
/usr/local/Homebrew/Library/Homebrew/dev-cmd/livecheck.rb:61:in `livecheck'
/usr/local/Homebrew/Library/Homebrew/brew.rb:113:in `<main>'
```

Looks like this may have been lost in the shuffle of moving livecheck into core.

https://github.com/Homebrew/homebrew-livecheck/blob/6b4a6e342a1a39c0179a1704cf5497cbe9054d8d/cmd/livecheck.rb#L99-L101

(BTW livecheck is ✨)

-----

CC: @MikeMcQuaid

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
Looks good! Thanks @josh, good to see you and hope you're well! ❤️

**Review by nandahkrishna — COMMENTED** [review]
I'm not able to add a suggestion in a line without changes, but we have:

```ruby
WATCHLIST_PATH = (
    ENV["HOMEBREW_LIVECHECK_WATCHLIST"] ||
    Pathname.new(Dir.home)/".brew_livecheck_watchlist"
  ).freeze
```

Might be good to change it to:

```ruby
WATCHLIST_PATH = (
    ENV["HOMEBREW_LIVECHECK_WATCHLIST"] ||
    "#{Dir.home}/.brew_livecheck_watchlist"
  ).freeze
```

Along with your current change, that is. What do you think @samford?

**Comment by josh** [comment]
@nandahkrishna 👍🏻  that seems like good idea. That way `WATCHLIST_PATH` is always of type `String` rather than `String | Pathname`.

**Comment by samford** [comment]
Good catch, Nanda. I agree that using a uniform type for `HOMEBREW_LIVECHECK_WATCHLIST` is a good idea.

I believe at one point I made that change while working on something else in livecheck but evidently I didn't commit (or stash) it.

**Review by nandahkrishna — APPROVED** [review]
Thanks @josh!

**Pull request merged**
