### PR TITLE
dev-cmd/bump: add `--tap=` flag

### PR DESCRIPTION
**Pull request by jck112**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Allow tap maintainers to run `brew bump --tap <user>/<repo>` to keep their formulae and casks up-to-date.

(Note: this is the same exact behavior as `brew livecheck --tap <user/<repo>`)

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
You should be able to do it with `brew bump <user>/<repo>/<formula>`, just like `brew install`.

**Comment by jck112** [comment]
> You should be able to do it with `brew bump <user>/<repo>/<formula>`, just like `brew install`.

Yes it works for individual formula and casks. However if you want to `bump` your entire tap repository then you have to either maintain a list of all your formula / casks or generate it with some kind of custom script.

**Comment by bevanjkay** [comment]
I appreciate you looking into this @jck112 - I'm running a subcommand to generate a list in my own tap's autobump workflow.

**Review by carlocab — APPROVED** [review]

**Comment by Bo98** [comment]
Am OK with this but am tempted to add an error `if args.tap.official?` so no one does `brew bump --tap=Homebrew/core`.

**Comment by jck112** [comment]
> This is a good idea but I am tempted to add an error `if tap.official?` so no one does `brew bump --tap=Homebrew/core`.

Added the check as well as a test. Let me know if want any tweaks to the error message.

**Review by ZhongRuoyu — APPROVED** [review]

**Review by MikeMcQuaid — APPROVED** [review]
Thanks so much for your first contribution to Homebrew/brew! Without people like you submitting PRs we couldn't run this project. You rock, @jck112!

**Pull request merged**
