### PR TITLE
ENV/super: don't set PKG_CONFIG

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

We'll have to think of another way to do this if build systems aren't able to pick our shim up.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
If it's first a shim first in the `PATH` and is set here: how are they even getting `/usr/local/bin/pkg-config`? It's not like it's `/usr/bin/pkg-config`? 

All this mess is starting to make me think `pkg-config` should go keg-only.

**Comment by Bo98** [comment]
I maybe misread something when I first added it. It seems CMake doesn't need it and I don't see anything autotools related that would require it.

**Comment by Bo98** [comment]
It's not exactly a deal breaker anyway if there is a build system out there that doesn't find it on the path. I think it's clear that setting `PKG_CONFIG` is going to break things more than it fixes (if it fixes anything).

**Comment by MikeMcQuaid** [comment]
Fine with me to remove, then 👍.

**Comment by ydnar** [comment]
@Bo98 how does one trigger Homebrew to re-bottle Go?

**Comment by Bo98** [comment]
I’ve already queued one here: Homebrew/homebrew-core#52828

**Comment by ydnar** [comment]
@Bo98 thank you! 👍

**Pull request merged**
