### PR TITLE
Replace some `include Kernel` usages with `requires_ancestor`

### PR DESCRIPTION
**Pull request by Bo98**
This didn't exist way back but does now.

For `Utils::Shebang::*` I have made it more stricter than necessary (`requires_ancestor { Formula }` rather than `Kernel`) purely because they are documented as a "Mixin module for Formula", though they don't actually need or use anything from `Formula`. I can make it `Kernel` if preferred.

### CODE REVIEW

**Comment by dduugg** [comment]
Just flagging that, AFAIK, all current usage of `requires_ancestor` is in rbi files, bc I didn't want the runtime to depend on an [experimental](https://sorbet.org/docs/requires-ancestor) sorbet feature.

That may have been overly cautious though, since we ship with `sorbet-runtime` bundled. (If so, we can probably ditch a few rbi files with a migration PR.)

**Comment by Bo98** [comment]
Hmm that's a fair point. Though AFAIK `requires_ancestor` is no-op at runtime anyway.

I don't really have a strong opinion either way.

**Comment by dduugg** [comment]
> Hmm that's a fair point. Though AFAIK `requires_ancestor` is no-op at runtime anyway.
> 
> I don't really have a strong opinion either way.

Yep (pending TODO): https://github.com/sorbet/sorbet/blob/bb6e8f4/gems/sorbet-runtime/lib/types/helpers.rb#L63-L64

It's probably fine, just seems like a decision we should explicitly opt into.

**Review by dduugg — APPROVED** [review]

**Review by carlocab — APPROVED** [review]

**Review by MikeMcQuaid — APPROVED** [review]
Very nice, thanks @Bo98!

**Pull request merged**
