### PR TITLE
bottle: add: improve regexp to recognize comments

### PR DESCRIPTION
**Pull request by zmwangx**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

This would have eliminated the need for Homebrew/homebrew-core#9000, for instance.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@zmwangx CI failed. Can you bump https://github.com/Homebrew/brew/blob/a5019d281ef0757adcc0f4157e7f15495da01cdf/Library/Homebrew/.rubocop_todo.yml#L66-L69 a bit. Thanks!

**Comment by zmwangx** [comment]
@MikeMcQuaid 

> Can you bump ... a bit

What about 363 => 400?

**Comment by MikeMcQuaid** [comment]
👍

**Comment by zmwangx** [comment]
Done.

**Comment by MikeMcQuaid** [comment]
Thanks again @zmwangx!

**Pull request merged**
