### PR TITLE
Add SubversionDownloadStrategy#source_modified_time

### PR DESCRIPTION
**Pull request by vladshablinsky**
- [x] Have you followed the guidelines in our Contributing document?
 - [x] Have you checked to ensure there aren't other open Pull Requests for the same change?
 - [x] Have you added an explanation of what your changes do and why you'd like us to include them?
 - [ ] Have you written new tests for your changes? Here's an example.
 - [x] Have you successfully ran brew tests with your changes locally?

## Description

Implement `SubversionDownloadStrategy#source_modified_time` from https://github.com/Homebrew/brew/issues/81

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Looks good to me 👍 @xu-cheng, any thoughts?

**Comment by xu-cheng** [comment]
LGTM. Sorry for late respond.

**Comment by UniqMartin** [comment]
Sorry for the late comment! I wonder to what extent https://github.com/Homebrew/brew/pull/171#issuecomment-215999975 is also applicable here and whether it would be a good idea to extract the information from `svn info --xml` instead …

**Comment by xu-cheng** [comment]
cc @vladshablinsky 

`svn info --xml` seems to be a better approach. You can parse XML using `REXML::XPath`.
e.g.
```ruby
require "rexml/document"
xml = REXML::Document.new(Utils.popen_read("svn", "info", "--xml", cached_location.to_s))
Time.parse REXML::XPath.first(xml, "//date/text()")

**Comment by vladshablinsky** [comment]
@xu-cheng I knew about this option and thought that `REXML` does pretty much the same things like regular expression matching. However it could be more flexible if `svn`'s log output changes in new versions, so I'll open a new PR.

@UniqMartin seems there is no way to change the date output format.

**Pull request merged**
