### PR TITLE
mac/xcode: update expected Clang on 10.13

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-----

Goodbye `-beta.app`, hello GM.

### CODE REVIEW

**Comment by ilovezfs** [comment]
:1st_place_medal: :m: :bowing_man:

**Comment by DomT4** [comment]
:heart:. Where's Homebrew at on a High Sierra CI, out of curiosity?

**Comment by ilovezfs** [comment]
I think it's at the pub slacking off.

**Comment by ilovezfs** [comment]
@DomT4 getting closer … 
screen shot 2017-09-14 at 7 43 29 am

**Comment by DomT4** [comment]
I'm surprised we don't have the High Sierra GM yet. Mid-to-late September for the first public release has been common over the last couple years. But certainly bottles would be a welcome addition 🙈.

**Pull request merged**
