### PR TITLE
diagnostic: check for stray stuff only on macos

### PR DESCRIPTION
**Pull request by dawidd6**
stuff:
- headers
- las
- pcs
- static libs
- dylibs

Those checks seem to be redundant on Linux.

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by mishz** [comment]
في جمعة، 17 أبريل، 2020 في 8:00 م، كتب Dawid Dziurla <
notifications@github.com>:

**Comment by Bo98** [comment]
I'd probably move `__check_stray_files` too unless you think it would be needed on Linux in the future.

**Comment by dawidd6** [comment]
This method does not seem to be very macos-specific, so I would leave it as is there.

**Comment by MikeMcQuaid** [comment]
Passing on this, sorry @dawidd6.

**Pull request closed without merging**
