### PR TITLE
ISSUE_TEMPLATE: tweak instructions.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Be clearer about what's expected and where to file things.

See also https://github.com/Homebrew/homebrew-core/pull/11972

### CODE REVIEW

**Comment by vitorgalvao** [comment]
“Please always follow these steps” followed by “Or propose a feature” is a bit weird. You already mention in bold all steps need to be followed.

How about “Report a bug” and “Or propose a feature”?

**Comment by MikeMcQuaid** [comment]
> “Please always follow these steps” followed by “Or propose a feature” is a bit weird. You already mention in bold all steps need to be followed.

Yeh, I get that but: repetition is sadly necessary. Will think next time we tweak this, though.

**Comment by vitorgalvao** [comment]
> repetition is sadly necessary.

That it is. Tweaking the issue and PR templates is a never-ending struggle to me as well.

**Comment by monouser7dig** [comment]
> That it is. Tweaking the issue and PR templates is a never-ending struggle to me as well.

FWIW I think you're doing a pretty good job, just discovered more documentation about home-brew and especially the behind the scenes stuff seems very well thought out. As well as all these small changes/ checks on those changes that happen daily.

**Comment by MikeMcQuaid** [comment]
@monouser7dig Thanks for the kind words ❤️

**Pull request merged**
