### PR TITLE
`brew bump`: do not call repology by default

### PR DESCRIPTION
**Pull request by Moisan**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

This is a follow up of https://github.com/Homebrew/brew/issues/17021 : by running `brew bump` without other argument, the command would still query repology on all formulae then hide the repology information in the output. I spotted that due to some formulae having matching formula version and livecheck version without any mention that they were up to date. There was an extra comparison with the repology version.

This PR adds the `--eval-all` flag to make this behaviour explicit. It also stops calling repology by default.

### CODE REVIEW

**Comment by Rylan12** [comment]
Now, this check seems irrelevant and I think it can be removed:

https://github.com/Homebrew/brew/blob/988c44ce20fda08e579616734b95657387f76efd/Library/Homebrew/dev-cmd/bump.rb#L93-L97

And potentially we have no need for `handle_api_response` anymore?

**Review by MikeMcQuaid — COMMENTED** [review]
Makes sense to me, thanks @Moisan!

Please answer/address @Rylan12's comment first.

**Comment by Moisan** [comment]
After discussion with @nandahkrishna , I removed the `handle_api_response` which was first listing all formulae available on repology.

**Review by nandahkrishna — APPROVED** [review]
This is great, thanks!

**Pull request merged**
