### PR TITLE
include  patchelf.rb and its deps in Gemfile.lock

### PR DESCRIPTION
**Pull request by rmNULL**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Includes patchelf.rb and its deps in Gemfile.lock .

Request @ 
https://github.com/Homebrew/brew/pull/7996#issuecomment-657922970

cc @jonchang @MikeMcQuaid @sjackman @woodruffw

### CODE REVIEW

**Comment by rmNULL** [comment]
1 of the test is failing.

> anyone actually using the functionality will have the right gems installed on demand.
This seems to be the case according to the test on my host, 

reporting back soon after tests on docker ...

**Comment by jonchang** [comment]
Gemfile needs to be updated to remove the conditional dependency based on HOMEBREW_PATCHELF_RB, as I laid out in the other issue.

**Comment by rmNULL** [comment]
>This will result in the same Gemfile.lock issue people are seeing with HOMEBREW_DEVELOPER happening for all non-HOMEBREW_DEVELOPERs. That doesn't seem to be a solution as it will affect/annoy more people.

sorry, can you expand on this ?

**Comment by rmNULL** [comment]
> Gemfile needs to be updated to remove the conditional dependency based on HOMEBREW_PATCHELF_RB, as I laid out in the other issue.

@jonchang . 
Why is that a requirement? 
we only wish on devs.

**Comment by MikeMcQuaid** [comment]
> We still wish only to force it on devs

We can't really do that without the current problems. Let's remove the conditional `Gemfile``if ENV["HOMEBREW_PATCHELF_RB"]` and install it unconditionally in `Gemfile.lock`.

**Comment by sjackman** [comment]
Currently having `HOMEBREW_DEVELOPER=1` set gives you a dirty `Gemfile.lock`. If you change the `Gemfile.lock` without also changing the `Gemfile` to remove the conditional, you’ll get a dirty `Gemfile.lock` when you do _not_ have `HOMEBREW_DEVELOPER=1` set, that is, for all non-developer users. We want to update the `Gemfile.lock` as your PR 8034 does but also remove the conditional from `Gemfile`. I believe we also want to vendor the `patchelf.rb` gem and its dependencies, and remove the logic to install this gem.

The feature would continue to be enabled only when `HOMEBREW_DEVELOPER=1` is set, but the gem would be installed for everyone.

**Comment by sjackman** [comment]
@MikeMcQuaid At what point is `patchelf.rb` vendored into Homebrew/brew? In this PR, or in a subsequent PR?

**Comment by MikeMcQuaid** [comment]
> @MikeMcQuaid At what point is `patchelf.rb` vendored into Homebrew/brew? In this PR, or in a subsequent PR?

@sjackman I'd think when we're at the point that `patchelf.rb` is enabled for everyone and we remove the `HOMEBREW_PATCHELF_RB` variable.

**Pull request merged**
